#include "exgine/android_audio.hpp"
#include "exgine/android.hpp"
#include "exgine/mobile.hpp"
#include "exgine/showcase.hpp"
#include <android/asset_manager.h>
#include <android/input.h>
#include <android/log.h>
#include <android_native_app_glue.h>
#include <algorithm>
#include <cstdint>
#include <ctime>
#include <memory>
#include <string>
namespace {
constexpr const char* kTag="EXGINE_FIRST_LIGHT";
std::uint64_t monotonic_time_ns(){timespec v{};if(clock_gettime(CLOCK_MONOTONIC,&v)!=0)return 0;return static_cast<std::uint64_t>(v.tv_sec)*1000000000ull+static_cast<std::uint64_t>(v.tv_nsec);}
bool load_asset(AAssetManager*m,std::string_view path,std::string&out){if(!m)return false;AAsset*a=AAssetManager_open(m,std::string(path).c_str(),AASSET_MODE_BUFFER);if(!a)return false;const auto n=static_cast<std::size_t>(AAsset_getLength64(a));out.resize(n);const auto got=AAsset_read(a,out.data(),n);AAsset_close(a);return got>=0&&static_cast<std::size_t>(got)==n;}
struct AppState{exgine::AndroidEglPresenter presenter;exgine::MobileRuntimeBridge mobile;exgine::AndroidAudioBackend audio;std::unique_ptr<exgine::ShowcaseGame> game;double previous_time=0;bool started=false;};
exgine::MobileInputEvent touch(exgine::MobileInputType t,const AInputEvent*e,std::size_t i){exgine::MobileInputEvent v;v.type=t;v.timestamp_ns=monotonic_time_ns();v.touch.pointer_id=AMotionEvent_getPointerId(e,i);v.touch.x=AMotionEvent_getX(e,i);v.touch.y=AMotionEvent_getY(e,i);v.touch.pressure=AMotionEvent_getPressure(e,i);return v;}
int32_t handle_input(android_app*app,AInputEvent*input){auto*s=static_cast<AppState*>(app->userData);if(!s||!input)return 0;if(AInputEvent_getType(input)==AINPUT_EVENT_TYPE_KEY){const int a=AKeyEvent_getAction(input);if(a!=AKEY_EVENT_ACTION_DOWN&&a!=AKEY_EVENT_ACTION_UP)return 0;exgine::MobileInputEvent v;v.type=a==AKEY_EVENT_ACTION_DOWN?exgine::MobileInputType::KeyDown:exgine::MobileInputType::KeyUp;v.timestamp_ns=monotonic_time_ns();v.key_code=AKeyEvent_getKeyCode(input);v.meta_state=static_cast<std::uint32_t>(AKeyEvent_getMetaState(input));return s->mobile.push_input(v)?1:0;}if(AInputEvent_getType(input)!=AINPUT_EVENT_TYPE_MOTION||(AMotionEvent_getSource(input)&AINPUT_SOURCE_CLASS_POINTER)==0)return 0;const int32_t action=AMotionEvent_getAction(input),type=action&AMOTION_EVENT_ACTION_MASK;const std::size_t idx=static_cast<std::size_t>((action&AMOTION_EVENT_ACTION_POINTER_INDEX_MASK)>>AMOTION_EVENT_ACTION_POINTER_INDEX_SHIFT),count=AMotionEvent_getPointerCount(input);if(type==AMOTION_EVENT_ACTION_DOWN||type==AMOTION_EVENT_ACTION_POINTER_DOWN||type==AMOTION_EVENT_ACTION_UP||type==AMOTION_EVENT_ACTION_POINTER_UP){if(idx>=count)return 0;return s->mobile.push_input(touch((type==AMOTION_EVENT_ACTION_UP||type==AMOTION_EVENT_ACTION_POINTER_UP)?exgine::MobileInputType::TouchUp:exgine::MobileInputType::TouchDown,input,idx))?1:0;}if(type==AMOTION_EVENT_ACTION_MOVE||type==AMOTION_EVENT_ACTION_CANCEL){bool ok=false;const auto et=type==AMOTION_EVENT_ACTION_MOVE?exgine::MobileInputType::TouchMove:exgine::MobileInputType::TouchCancel;for(std::size_t i=0;i<count;++i)ok=s->mobile.push_input(touch(et,input,i))||ok;return ok?1:0;}return 0;}
void handle_cmd(android_app*app,int32_t cmd){auto*s=static_cast<AppState*>(app->userData);if(!s)return;switch(cmd){case APP_CMD_START:s->mobile.on_start();break;case APP_CMD_RESUME:s->mobile.on_resume();break;case APP_CMD_PAUSE:s->mobile.on_pause();break;case APP_CMD_STOP:s->mobile.on_stop();s->audio.stop();s->started=false;break;case APP_CMD_INIT_WINDOW:if(app->window&&s->presenter.attach(app->window))s->mobile.on_surface_available();break;case APP_CMD_TERM_WINDOW:s->mobile.on_surface_lost();s->presenter.detach();break;case APP_CMD_WINDOW_RESIZED:case APP_CMD_CONTENT_RECT_CHANGED:(void)s->presenter.resize();break;default:break;}}
}
void android_main(android_app*app){app_dummy();AppState state;AAssetManager*assets=app->activity?app->activity->assetManager:nullptr;state.game=std::make_unique<exgine::ShowcaseGame>([assets](std::string_view p,std::string&o){return load_asset(assets,p,o);});std::string manifest;if(!load_asset(assets,"first_3d_game/project.exg",manifest)||!state.game->open(manifest)){__android_log_print(ANDROID_LOG_ERROR,kTag,"First Light project startup failed");return;}if(!state.audio.start())__android_log_print(ANDROID_LOG_WARN,kTag,"AAudio unavailable; continuing without backend output");app->userData=&state;app->onAppCmd=handle_cmd;app->onInputEvent=handle_input;for(;;){int ident=0,events=0;android_poll_source*source=nullptr;while((ident=ALooper_pollOnce(state.mobile.renderable()?0:-1,nullptr,&events,reinterpret_cast<void**>(&source)))>=0){if(source)source->process(app,source);if(app->destroyRequested){state.mobile.on_destroy();state.mobile.on_surface_lost();state.audio.stop();state.presenter.detach();return;}}if(!state.mobile.renderable()||!state.presenter.ready())continue;const double now=static_cast<double>(monotonic_time_ns())/1000000000.0;const double dt=state.previous_time>0?std::clamp(now-state.previous_time,0.0,.05):1.0/60.0;state.previous_time=now;const auto timing=state.mobile.begin_frame(now);if(timing.state==exgine::MobileFrameState::Paused)continue;if(!state.started)state.started=state.game->start();if(!state.started)continue;if(state.game->update(dt)){const auto mix=state.game->audio().mix(static_cast<float>(dt));if(!mix.empty())state.audio.set_mix(exgine::SpatialAudioProcessor::process(state.game->audio().listener(),{mix.front().clip,mix.front().position,mix.front().gain,mix.front().pitch,mix.front().max_distance,mix.front().looping},.1f));(void)state.game->present(state.presenter);}}
}
