#include "exgine/ast.hpp"
#include "exgine/building.hpp"
#include "exgine/character.hpp"
#include "exgine/compiler.hpp"
#include "exgine/diagnostic.hpp"
#include "exgine/engine.hpp"
#include "exgine/geometry.hpp"
#include "exgine/ir.hpp"
#include "exgine/lexer.hpp"
#include "exgine/lighting.hpp"
#include "exgine/material.hpp"
#include "exgine/physics.hpp"
#include "exgine/render.hpp"
#include "exgine/resources.hpp"
#include "exgine/runtime.hpp"
#include "exgine/scene.hpp"
#include "exgine/shaders.hpp"
#include "exgine/source.hpp"
#include "exgine/texture.hpp"
#include "exgine/token.hpp"
#include "exgine/version.hpp"
#include "exgine/vehicle.hpp"
#include "exgine/world.hpp"
#include <cassert>
#include <cmath>
#include <cstdint>
#include <string>
namespace {
const exgine::SourceText valid_source(R"( game "Green World" { world { terrain { type = procedural height = 20 } building "house" { floors = 2 enabled = true } vehicle "car" { type = "sports_car" } } })");
void test_version(){assert(exgine::version_string=="0.1.0");}
void test_diagnostics(){exgine::DiagnosticBag d;d.note("parser note",{4,2,5});d.warning("unused property",{10,3,2});d.error("invalid value",{20,4,1});assert(d.has_errors()&&d.all().size()==3);}
void test_ir(){exgine::IR game;game.add_property("terrain",std::string{"procedural"});auto& b=game.add_child(exgine::NodeKind::Building,"house");b.properties.push_back({"floors",std::int64_t{2}});assert(std::get<std::int64_t>(game.root.children[0].find_property("floors")->value)==2);assert(exgine::NodeKind::NPC!=exgine::NodeKind::Player);}
void test_world_determinism(){exgine::TerrainConfig c;c.amplitude=80;c.seed=1337;c.chunk_size=32;exgine::ProceduralWorld a(c),b(c);assert(std::isfinite(a.sample_height(32.0f,64.0f))&&a.sample_height(32.0f,64.0f)==b.sample_height(32.0f,64.0f));const auto ca=a.generate_chunk({0,0}),cb=b.generate_chunk({0,0});assert(ca.valid()&&cb.valid()&&ca.terrain.vertices.size()==cb.terrain.vertices.size()&&ca.terrain.indices==cb.terrain.indices);assert(ca.vegetation.size()==cb.vegetation.size());}
void test_biomes_water_and_streaming(){exgine::TerrainConfig c;c.amplitude=70;c.seed=99;c.chunk_size=24;c.resolution=16;c.vegetation_density=32;exgine::ProceduralWorld w(c);const auto b=w.sample_biome(100,200);assert(b.moisture>=0&&b.moisture<=1&&b.temperature>=0&&b.temperature<=1&&b.slope>=0&&b.slope<=1);assert(w.sample_water_depth(0,0)>=0);exgine::WorldStreamer s(w);s.update({0,0,0},2);assert(s.loaded_count()>0&&s.find({0,0})!=nullptr);const auto loaded=s.loaded_count();s.update({c.chunk_size*10,0,0},1);assert(s.loaded_count()!=loaded&&s.find({10,0})!=nullptr);s.clear();assert(s.loaded_count()==0);}
void test_scene_graph(){exgine::SceneGraph scene;assert(scene.root()!=exgine::invalid_scene_node&&scene.size()==1);const auto parent=scene.create(scene.root());const auto child=scene.create(parent);assert(parent!=0&&child!=0&&scene.size()==3);assert(scene.set_local_transform(parent,{{10,2,3},{0,0,0},{2,2,2}}));assert(scene.set_local_transform(child,{{1,4,5},{0.1f,0.2f,0.3f},{1,2,1}}));assert(!scene.set_parent(parent,child));scene.update_world_transforms();const auto* p=scene.get(parent);const auto* c=scene.get(child);assert(p&&c&&p->world.position.x==10&&c->world.position.x==12&&c->world.position.y==10&&c->world.position.z==13&&c->world.scale.y==4);assert(scene.destroy(parent)&&scene.size()==1);}
void test_lighting(){exgine::LightingWorld lights;assert(lights.main_camera().valid());exgine::Camera bad=lights.main_camera();bad.far_plane=.01f;assert(!lights.set_main_camera(bad));exgine::Camera camera=lights.main_camera();camera.vertical_fov_degrees=70;camera.far_plane=2000;assert(lights.set_main_camera(camera));exgine::Light directional;directional.type=exgine::LightType::Directional;directional.direction={-1,-2,-1};directional.range=0;const auto sun=lights.create_light(directional);assert(sun!=0&&lights.get_light(sun)!=nullptr);exgine::Light point;point.type=exgine::LightType::Point;point.range=25;point.intensity=20;const auto point_id=lights.create_light(point);assert(point_id!=0&&lights.active_lights().size()==2);assert(lights.destroy_light(sun)&&lights.light_count()==1);assert(lights.destroy_light(point_id)&&lights.light_count()==0);}
void test_language_pipeline(){exgine::DiagnosticBag d;const auto tokens=exgine::Lexer(valid_source).tokenize(d);assert(!d.has_errors()&&tokens.front().kind==exgine::TokenKind::Game);const auto r=exgine::Compiler{}.compile(valid_source);assert(r.succeeded()&&r.ir.has_value());assert(r.ir->root.kind==exgine::NodeKind::World&&r.ir->root.children.size()==3);assert(r.ir->root.children[1].name=="house");}
void test_runtime(){const auto c=exgine::Compiler{}.compile(valid_source);assert(c.succeeded());exgine::Runtime r;assert(r.load(*c.ir));assert(r.state().entities.size()==4&&r.world()!=nullptr&&r.world_streamer()!=nullptr);assert(r.scene().size()==5);const auto world_entity=r.state().entities.get(r.state().world_entity);assert(world_entity&&world_entity->scene_node!=exgine::invalid_scene_node);const auto id=r.state().world_entity+1;assert(r.attach_geometry(id,exgine::MeshAssembly{{{"house_mesh",exgine::make_box({{8,3,8}}),"concrete",{},{1,1,1}}}}));assert(r.set_main_camera(exgine::Camera{}));exgine::Light sun;sun.type=exgine::LightType::Directional;sun.direction={-1,-1,0};assert(r.create_light(sun)!=0);assert(r.lighting().light_count()==1);assert(r.stream_world({0,0,0},1));assert(r.world_streamer()->loaded_count()>0);r.update(.5);r.update(.25);assert(r.state().tick==2&&r.state().elapsed_seconds==.75);r.reset();assert(r.state().entities.size()==0&&r.world()==nullptr&&r.scene().size()==1&&r.lighting().light_count()==0);}
void test_geometry(){const auto b=exgine::make_box({{2,3,4}});const auto s=exgine::make_sphere({1,16,8});const auto c=exgine::make_cylinder({.5f,2,16});const auto k=exgine::make_capsule();assert(b.valid()&&s.valid()&&c.valid()&&k.valid()&&b.vertices.size()==24&&s.vertices.size()==16*9);}
void test_characters(){exgine::CharacterDefinition n;n.type=exgine::CharacterType::NPC;n.appearance.seed=42;n.appearance.watch=true;n.appearance.backpack=true;const auto a=exgine::generate_character(n),b=exgine::generate_character(n);assert(a.valid()&&b.valid()&&a.parts.size()==10&&a.parts[0].mesh.vertices.size()==b.parts[0].mesh.vertices.size());n.appearance.seed=43;assert(exgine::generate_character(n).parts[0].position.x!=a.parts[0].position.x);}
void test_materials(){auto steel=exgine::make_real_world_material("steel",42);assert(steel.valid()&&steel.metallic>.9f);exgine::MaterialLibrary lib;assert(lib.define(steel)&&lib.find("steel")!=nullptr);assert(!lib.define(exgine::Material{}));auto bad=steel;bad.roughness=2;assert(!lib.define(bad));}
void test_textures(){exgine::TextureGenerationSettings s;s.width=16;s.height=12;s.noise.seed=123;s.noise.type=exgine::NoiseType::Fbm;auto t=exgine::generate_noise_texture(s,1);assert(t.valid()&&t.data.size()==16u*12u);assert(exgine::sample_noise(.2f,.7f,s.noise)==exgine::sample_noise(.2f,.7f,s.noise));auto m=exgine::make_real_world_material("wood",7);auto set=exgine::generate_material_textures(m,s);assert(set.valid()&&set.base_color->width==16&&set.base_color->channels==3);}
void test_resources_and_runtime_materials(){const auto c=exgine::Compiler{}.compile(valid_source);assert(c.succeeded());exgine::Runtime r;assert(r.load(*c.ir));auto m=exgine::make_real_world_material("concrete",99);assert(r.define_material(m));assert(r.material("concrete")!=nullptr);assert(r.material_resource("concrete")!=nullptr);assert(r.material_resource("concrete")->textures->valid());const auto key=exgine::material_generation_key(m,{});auto resource=exgine::build_material_resource(m,{});assert(resource&&resource->generation_key==key);}
void test_render(){const auto c=exgine::Compiler{}.compile(valid_source);assert(c.succeeded());exgine::Runtime r;assert(r.load(*c.ir));auto m=exgine::make_real_world_material("concrete",11);assert(r.define_material(m));const auto id=r.state().world_entity+1;auto* e=r.state().entities.get(id);assert(e&&e->scene_node!=exgine::invalid_scene_node);assert(r.scene().set_local_transform(e->scene_node,{{0,0,-5},{0,0,0},{1,1,1}}));r.update(0);assert(r.attach_geometry(id,exgine::MeshAssembly{{{"house",exgine::make_box({{2,2,2}}),"concrete",{}, {1,1,1}}}}));exgine::Light sun;sun.type=exgine::LightType::Directional;sun.direction={-1,-1,-1};assert(r.create_light(sun)!=0);exgine::RenderConfig no_cull;no_cull.frustum_culling=false;exgine::Renderer renderer(no_cull);exgine::RenderFrame frame;assert(renderer.build_frame(r,frame)&&frame.valid()&&frame.draws.size()==1&&frame.lights.size()==1);const auto result=renderer.submit(frame);assert(result.success&&result.stats.submitted_draws==1&&renderer.next_frame_id()==2);assert(r.scene().set_local_transform(e->scene_node,{{0,0,100},{0,0,0},{1,1,1}}));r.update(0);exgine::RenderConfig cull;exgine::Renderer culler(cull);assert(culler.build_frame(r,frame)&&frame.draws.empty());assert(culler.config().frustum_culling);auto invalid=frame;invalid.config.max_lights=0;assert(!culler.validate(invalid));}
void test_shaders(){const auto p=exgine::make_pbr_shader(),u=exgine::make_unlit_shader();assert(p.valid()&&u.valid()&&p.vertex_source.find("u_view_projection")!=std::string::npos&&p.fragment_source.find("u_lights[256]")!=std::string::npos);exgine::ShaderLibrary lib;assert(lib.size()==2&&lib.find("pbr")&&lib.find("unlit"));}
void test_buildings(){exgine::BuildingConfig cfg;cfg.seed=4242;cfg.floors=3;cfg.rooms_per_floor=4;cfg.furniture_density=3;const auto a=exgine::generate_building(cfg),b=exgine::generate_building(cfg);assert(a.valid()&&b.valid()&&a.seed==b.seed&&a.rooms.size()==12&&a.rooms.size()==b.rooms.size()&&a.geometry.parts.size()==b.geometry.parts.size()&&a.collision.size()==b.collision.size());for(const auto& room:a.rooms){assert(room.min.x>=-cfg.width*.5f&&room.max.x<=cfg.width*.5f);assert(room.min.z>=-cfg.depth*.5f&&room.max.z<=cfg.depth*.5f);assert(room.max.y-room.min.y==cfg.floor_height);}const auto* room=exgine::find_building_room(a,a.rooms.front().center);assert(room&&room->id==a.rooms.front().id);const auto* door=static_cast<const exgine::BuildingOpening*>(nullptr);for(const auto& opening:a.openings)if(opening.type==exgine::BuildingOpeningType::Door){door=&opening;break;}assert(door&&door->valid());const auto before=exgine::active_building_collision(a).size();auto mutable_building=a;assert(exgine::set_building_door_open(mutable_building,door->id,true));const auto after=exgine::active_building_collision(mutable_building).size();assert(after<before);assert(!exgine::set_building_door_open(mutable_building,0,true));cfg.seed=4243;const auto different=exgine::generate_building(cfg);assert(different.valid()&&different.rooms.front().id!=a.rooms.front().id);}
void test_runtime_buildings(){const auto c=exgine::Compiler{}.compile(valid_source);assert(c.succeeded());exgine::Runtime r;assert(r.load(*c.ir));auto small=exgine::TextureGenerationSettings{};small.width=8;small.height=8;assert(r.define_material(exgine::make_real_world_material("concrete",1),small));assert(r.define_material(exgine::make_real_world_material("wood",2),small));assert(r.define_material(exgine::make_real_world_material("glass",3),small));const auto id=r.state().world_entity+2;exgine::BuildingConfig cfg;cfg.seed=7;cfg.floors=2;cfg.rooms_per_floor=2;cfg.furniture_density=2;const auto generated=exgine::generate_building(cfg);assert(generated.valid());assert(r.generate_building(id,cfg));const auto* b=r.building(id);assert(b&&b->valid());const auto* e=r.state().entities.get(id);assert(e&&e->geometry&&e->geometry->valid());const auto initial=r.building_collision(id).size();const auto* door=static_cast<const exgine::BuildingOpening*>(nullptr);for(const auto& opening:b->openings)if(opening.type==exgine::BuildingOpeningType::Door){door=&opening;break;}assert(door);assert(r.set_building_door(id,door->id,true));assert(r.building_collision(id).size()<initial);r.scene().set_local_transform(e->scene_node,{{0,0,-8},{0,0,0},{1,1,1}});r.update(0);exgine::RenderConfig render_cfg;render_cfg.frustum_culling=false;exgine::Renderer renderer(render_cfg);exgine::RenderFrame frame;assert(renderer.build_frame(r,frame)&&!frame.draws.empty());r.reset();assert(r.building(id)==nullptr);}
void test_physics_contract(){exgine::PhysicsAabb a{{-1,-2,-3},{1,2,3}};assert(a.valid());exgine::PhysicsAabb bad{{1,0,0},{-1,0,0}};assert(!bad.valid());exgine::PhysicsShape box;assert(box.valid());assert(box.local_bounds().valid());exgine::PhysicsWorldSettings settings;assert(settings.valid());}
void test_vehicles(){const auto types={exgine::VehicleType::Car,exgine::VehicleType::SUV,exgine::VehicleType::SportsCar,exgine::VehicleType::Pickup,exgine::VehicleType::Truck,exgine::VehicleType::Bus,exgine::VehicleType::Motorcycle,exgine::VehicleType::Construction,exgine::VehicleType::Emergency,exgine::VehicleType::Boat,exgine::VehicleType::Aircraft};for(const auto type:types){auto cfg=exgine::make_vehicle_config(type);cfg.seed=0;const auto a=exgine::generate_vehicle(cfg),b=exgine::generate_vehicle(cfg);assert(a.valid()&&b.valid());assert(a.config.length==cfg.length&&a.config.width==cfg.width&&a.config.height==cfg.height);assert(a.geometry.parts.size()==b.geometry.parts.size());assert(a.wheels.size()==b.wheels.size());assert(a.physics_attachments.size()==b.physics_attachments.size());for(const auto& w:a.wheels){assert(w.position.x>=-cfg.width*.5f-w.width&&w.position.x<=cfg.width*.5f+w.width);assert(w.position.z>=-cfg.length*.5f-w.radius&&w.position.z<=cfg.length*.5f+w.radius);}if(!a.doors.empty()){auto v=a;const auto id=a.doors.front().id;assert(exgine::find_vehicle_door(v,id)!=nullptr&&exgine::set_vehicle_door_open(v,id,true)&&exgine::find_vehicle_door(v,id)->open);}const auto changed_cfg=exgine::make_vehicle_config(type);auto changed=changed_cfg;changed.length=changed_cfg.length*1.25f;const auto larger=exgine::generate_vehicle(changed);assert(larger.valid()&&larger.config.length==changed.length);}}
void test_runtime_vehicles(){const auto c=exgine::Compiler{}.compile(valid_source);assert(c.succeeded());exgine::Runtime r;assert(r.load(*c.ir));auto small=exgine::TextureGenerationSettings{};small.width=8;small.height=8;assert(r.define_material(exgine::make_real_world_material("steel",1),small));assert(r.define_material(exgine::make_real_world_material("glass",2),small));assert(r.define_material(exgine::make_real_world_material("rubber",3),small));assert(r.define_material(exgine::make_real_world_material("aluminium",4),small));const auto id=r.state().world_entity+3;auto cfg=exgine::make_vehicle_config(exgine::VehicleType::SportsCar);cfg.seed=99;assert(r.generate_vehicle(id,cfg));const auto* v=r.vehicle(id);assert(v&&v->valid()&&v->config.length==cfg.length);const auto* e=r.state().entities.get(id);assert(e&&e->geometry&&e->geometry->valid());assert(!r.vehicle_collision(id).empty());r.scene().set_local_transform(e->scene_node,{{0,0,-10},{0,0,0},{1,1,1}});r.update(0);exgine::RenderConfig rc;rc.frustum_culling=false;exgine::Renderer renderer(rc);exgine::RenderFrame frame;assert(renderer.build_frame(r,frame)&&frame.draws.size()==v->geometry.parts.size());r.reset();assert(r.vehicle(id)==nullptr);}
void test_engine(){exgine::Engine e;assert(e.load(valid_source));e.update(1.0/60.0);assert(e.runtime().state().tick==1);assert(!e.load(exgine::SourceText("game \"Broken\" { world { terrain_height = 0 } }")));assert(e.runtime().state().entities.size()==0&&e.diagnostics().has_errors());}
}
int main(){test_version();test_diagnostics();test_ir();test_world_determinism();test_biomes_water_and_streaming();test_scene_graph();test_lighting();test_language_pipeline();test_runtime();test_geometry();test_characters();test_materials();test_textures();test_resources_and_runtime_materials();test_render();test_shaders();test_buildings();test_runtime_buildings();test_physics_contract();test_vehicles();test_runtime_vehicles();test_engine();return 0;}
