#include "exgine/exanimation.hpp"
#include "exgine/exanimation_catalog.hpp"
#include "exgine/exsound.hpp"
#include "exgine/exsound_catalog.hpp"
#include "exgine/runtime.hpp"
#include <cassert>
int main(){
 using namespace exgine;
 ExSound audio(48000);
 auto s=audio.synthesize_recipe(SoundClass<1000>::recipe()); assert(s.valid()&&s.channels==2&&s.sample_rate==48000);
 auto voice=audio.synthesize_speech(speech("Hello, this is a procedural conversation generated by ExSound.")); assert(voice.valid());
 auto event=audio.synthesize_event({SoundEvent::Impact,SoundMaterial::Metal,0.8f,4.0f,3.0f,2.0f,0.2f,0.1f,77}); assert(event.valid());
 auto sk=make_humanoid_skeleton(); assert(sk.valid());
 auto pose=make_bind_pose(sk); ExAnimation anim(sk); MotionState motion; motion.speed=3.5f; motion.sprinting=true; auto clip=anim.locomotion(motion,1000); assert(clip.valid(sk)); anim.evaluate(motion,.37f,pose); assert(pose.valid_for(sk));
 auto generated=AnimationClass<1000>::graph(sk); assert(generated.valid(sk));
 Runtime runtime; auto generated2=runtime.generate_sound({SoundEvent::Explosion,SoundMaterial::Generic,1,0,2,10,0.3f,0.2f,9}); assert(generated2.valid());
 return 0;
}
