#include "exgine/gameplay.hpp"
#include "exgine/runtime.hpp"
#include <cassert>
#include <cmath>
namespace {
using namespace exgine;
void test_controller(){PhysicsWorld physics;GameplayWorld world;world.bind_physics(&physics);CharacterDefinition d;d.type=CharacterType::Player;auto id=world.create_character(d,{0,2,0});assert(id);auto*c=world.character(id);assert(c&&c->valid());CharacterControllerInput in;in.move_z=1;in.run=true;assert(world.update_character(id,in,1.0f/60.0f));auto p=c->controller.transform(physics);assert(p&&p->position.z>0);assert(c->controller.state.movement==CharacterMovementState::Run);}
void test_inventory_items_and_consumption(){PhysicsWorld physics;GameplayWorld world;world.bind_physics(&physics);auto id=world.create_character({},{});assert(id);ItemDefinition food;food.id=10;food.name="Apple";food.type=ItemType::Food;food.nutrition=20;food.hydration=5;food.max_stack=8;assert(world.define_item(food));auto*c=world.character(id);assert(c->inventory.add(10,3,food.max_stack));assert(c->inventory.count(10)==3);c->vitals.hunger=30;c->vitals.thirst=20;assert(world.consume(id,10));assert(c->inventory.count(10)==2);assert(c->vitals.hunger==10&&c->vitals.thirst==15);assert(world.set_equipped_item(id,10));}
void test_damage_recovery(){PhysicsWorld physics;GameplayWorld world;world.bind_physics(&physics);auto a=world.create_character({},{}),b=world.create_character({},{});assert(a&&b);CombatResult r;assert(world.damage({a,b,DamageType::Slash,35,{},{}} ,&r));assert(r.hit&&!r.killed&&world.character(b)->vitals.health==65);assert(world.damage({a,b,DamageType::Blunt,100,{},{}} ,&r));assert(r.killed&&!world.character(b)->vitals.alive());assert(world.recover(b,25));assert(world.character(b)->vitals.health==25&&!world.character(b)->unconscious);}
void test_interaction_schedule_and_time(){PhysicsWorld physics;GameplayWorldSettings s;s.seconds_per_game_minute=0.1f;GameplayWorld world(s);world.bind_physics(&physics);auto id=world.create_character({},{});assert(id);ItemDefinition item;item.id=20;item.name="Tool";item.max_stack=1;assert(world.define_item(item));auto iid=world.add_interaction({0,InteractionType::Pickup,{0,0,0},2,0,20,true});assert(iid);assert(world.interact(id,iid,InteractionType::Pickup));assert(world.character(id)->inventory.count(20)==1);assert(!world.interact(id,iid,InteractionType::Pickup));CharacterDefinition npc;npc.type=CharacterType::NPC;auto n=world.create_character(npc,{});NPCSchedule schedule;schedule.entries.push_back({0,30,ScheduleAction::Work,{5,0,5},42});assert(world.set_schedule(n,schedule));world.update(1.0f);assert(world.game_minute()==10);auto ns=world.npc_state(n);assert(ns&&ns->activity==ActivityType::Work&&ns->target_entity==42);}
void test_runtime_integration(){IR ir;ir.root.kind=NodeKind::World;ir.root.name="world";ir.root.children.push_back(Node{NodeKind::Terrain,"terrain",{}, {}});ir.root.children.push_back(Node{NodeKind::Player,"player",{}, {}});Runtime runtime;assert(runtime.load(ir));auto id=runtime.create_character({},{});assert(id&&runtime.gameplay()&&runtime.physics());CharacterControllerInput input;input.move_x=1;assert(runtime.update_character(id,input,1.0f/60.0f));runtime.update(1.0/60.0);assert(runtime.gameplay()->character(id));assert(runtime.state().tick==1);runtime.reset();assert(runtime.gameplay()==nullptr);}
}
int main(){test_controller();test_inventory_items_and_consumption();test_damage_recovery();test_interaction_schedule_and_time();test_runtime_integration();return 0;}
