#include "exgine/gpu.hpp"
#include "exgine/shaders.hpp"
#include <cassert>
#include <cstdint>
#include <iostream>
#include <memory>
#include <utility>
using namespace exgine;
namespace {
std::uint32_t next_id=1; int draws=0; int uploads=0; int deletes=0; int texture_uploads=0; int mipmaps=0;
void Clear(GlUInt){} void ClearColor(GlFloat,GlFloat,GlFloat,GlFloat){} void Viewport(GlInt,GlInt,GlInt,GlInt){} void Enable(GlEnum){} void Disable(GlEnum){} void DepthFunc(GlEnum){} void BlendFunc(GlEnum,GlEnum){}
GlUInt CreateShader(GlEnum){return next_id++;} void ShaderSource(GlUInt,GlInt,const char*const*,const GlInt*){} void CompileShader(GlUInt){} void GetShaderiv(GlUInt,GlEnum,GlInt*v){*v=1;} void GetShaderInfoLog(GlUInt,GlInt,GlInt*w,char*){if(w)*w=0;} void DeleteShader(GlUInt){}
GlUInt CreateProgram(){return next_id++;} void AttachShader(GlUInt,GlUInt){} void LinkProgram(GlUInt){} void GetProgramiv(GlUInt,GlEnum,GlInt*v){*v=1;} void GetProgramInfoLog(GlUInt,GlInt,GlInt*w,char*){if(w)*w=0;} void UseProgram(GlUInt){} void DeleteProgram(GlUInt){}
GlInt GetUniformLocation(GlUInt,const char*){return 1;} void UniformMatrix4fv(GlInt,GlInt,GlBool,const GlFloat*){} void Uniform3f(GlInt,GlFloat,GlFloat,GlFloat){} void Uniform4f(GlInt,GlFloat,GlFloat,GlFloat,GlFloat){} void Uniform1f(GlInt,GlFloat){} void Uniform1i(GlInt,GlInt){}
void GenBuffers(GlInt n,GlUInt*v){for(int i=0;i<n;++i)v[i]=next_id++;} void BindBuffer(GlEnum,GlUInt){} void BufferData(GlEnum,GlSize,const void*,GlEnum){++uploads;} void DeleteBuffers(GlInt,const GlUInt*){++deletes;} void BindBufferBase(GlEnum,GlUInt,GlUInt){}
void GenVertexArrays(GlInt n,GlUInt*v){for(int i=0;i<n;++i)v[i]=next_id++;} void BindVertexArray(GlUInt){} void DeleteVertexArrays(GlInt,const GlUInt*){++deletes;} void EnableVertexAttribArray(GlUInt){} void VertexAttribPointer(GlUInt,GlInt,GlEnum,GlBool,GlInt,const void*){} void DrawElements(GlEnum,GlInt,GlEnum,const void*){++draws;}
void GenTextures(GlInt n,GlUInt*v){for(int i=0;i<n;++i)v[i]=next_id++;} void BindTexture(GlEnum,GlUInt){} void TexParameteri(GlEnum,GlEnum,GlInt){} void TexImage2D(GlEnum,GlInt,GlInt,GlInt,GlInt,GlInt,GlEnum,GlEnum,const void*){++texture_uploads;} void GenerateMipmap(GlEnum){++mipmaps;} void ActiveTexture(GlEnum){} void DeleteTextures(GlInt,const GlUInt*){++deletes;}
OpenGLESApi fake(){OpenGLESApi a;a.Clear=Clear;a.ClearColor=ClearColor;a.Viewport=Viewport;a.Enable=Enable;a.Disable=Disable;a.DepthFunc=DepthFunc;a.BlendFunc=BlendFunc;a.CreateShader=CreateShader;a.ShaderSource=ShaderSource;a.CompileShader=CompileShader;a.GetShaderiv=GetShaderiv;a.GetShaderInfoLog=GetShaderInfoLog;a.DeleteShader=DeleteShader;a.CreateProgram=CreateProgram;a.AttachShader=AttachShader;a.LinkProgram=LinkProgram;a.GetProgramiv=GetProgramiv;a.GetProgramInfoLog=GetProgramInfoLog;a.UseProgram=UseProgram;a.DeleteProgram=DeleteProgram;a.GetUniformLocation=GetUniformLocation;a.UniformMatrix4fv=UniformMatrix4fv;a.Uniform3f=Uniform3f;a.Uniform4f=Uniform4f;a.Uniform1f=Uniform1f;a.Uniform1i=Uniform1i;a.GenBuffers=GenBuffers;a.BindBuffer=BindBuffer;a.BufferData=BufferData;a.DeleteBuffers=DeleteBuffers;a.BindBufferBase=BindBufferBase;a.GenVertexArrays=GenVertexArrays;a.BindVertexArray=BindVertexArray;a.DeleteVertexArrays=DeleteVertexArrays;a.EnableVertexAttribArray=EnableVertexAttribArray;a.VertexAttribPointer=VertexAttribPointer;a.DrawElements=DrawElements;a.GenTextures=GenTextures;a.BindTexture=BindTexture;a.TexParameteri=TexParameteri;a.TexImage2D=TexImage2D;a.GenerateMipmap=GenerateMipmap;a.ActiveTexture=ActiveTexture;a.DeleteTextures=DeleteTextures;return a;}
std::shared_ptr<Texture2D> tex(float r,float g,float b,float a=1){auto t=std::make_shared<Texture2D>();t->width=t->height=1;t->channels=4;t->format=TextureFormat::RGBA32F;t->data={r,g,b,a};return t;}
RenderFrame frame(){RenderFrame f;f.frame_id=1;f.config.backend=RenderBackend::OpenGLES;f.config.width=640;f.config.height=360;f.camera=Camera{};f.view_projection=Mat4::identity();MeshPart p;p.name="triangle";p.material_slot="m";p.mesh.vertices={{{0,0,0},{0,0,1},{0,0}},{{1,0,0},{0,0,1},{1,0}},{{0,1,0},{0,0,1},{0,1}}};p.mesh.indices={0,1,2};auto g=std::make_shared<MeshAssembly>();g->parts.push_back(std::move(p));RenderDrawCall d;d.entity_id=1;d.scene_node=1;d.geometry=g;d.material.material=make_real_world_material("steel");d.material.textures=std::make_shared<TextureSet>();d.material.textures->base_color=tex(.6f,.6f,.65f);d.material.textures->roughness=tex(.4f,.4f,.4f);d.material.textures->metallic=tex(.7f,.7f,.7f);d.material.textures->normal=tex(.5f,.5f,1);d.material.textures->ambient_occlusion=tex(1,1,1);d.material.textures->emission=tex(0,0,0);d.material.textures->opacity=tex(1,1,1);d.material.textures->height=tex(.5f,.5f,.5f);d.model=Mat4::identity();d.world_bounds=mesh_bounds(g->parts[0].mesh);f.draws.push_back(std::move(d));return f;}
}
int main(){OpenGLESApi empty;assert(!empty.complete());auto api=fake();assert(api.complete());OpenGLESRenderer gpu(api);auto f=frame();assert(f.valid());auto r=gpu.submit(f);assert(r.success&&r.draw_calls==1&&r.triangles==1&&draws==1);assert(gpu.cached_mesh_count()==1);assert(gpu.cached_texture_count()==7);assert(texture_uploads==7&&mipmaps==7);r=gpu.submit(f);assert(r.success&&r.draw_calls==1&&r.triangles==1&&draws==2);assert(gpu.cached_mesh_count()==1&&gpu.cached_texture_count()==7);assert(uploads==2&&texture_uploads==7);gpu.release();assert(deletes>=10);assert(make_mobile_pbr_shader().valid());assert(make_mobile_textured_pbr_shader().valid());std::cout<<"Phase 15 GPU backend tests passed\n";}
