#include "exgine/performance.hpp"
#include <cassert>
#include <cmath>
#include <iostream>
using namespace exgine;
static void test_profiles(){for(auto tier:{PerformanceTier::Ultra,PerformanceTier::High,PerformanceTier::Medium,PerformanceTier::Low,PerformanceTier::BatterySaver}){auto p=make_mobile_profile(tier,2560,1440);assert(p.valid());assert(p.render_width<=1920&&p.render_height<=1080);assert(p.render_scale>=.5f&&p.render_scale<=1.0f);assert(p.world_prefetch_radius>=p.world_active_radius);assert(p.max_loaded_chunks>0);}DevicePerformanceLimits l;l.max_target_fps=60;l.max_dynamic_lights=32;l.max_texture_budget_mb=128;l.max_geometry_budget_mb=128;PerformanceController c(make_mobile_profile(PerformanceTier::High),l);assert(c.profile().valid());assert(c.profile().target_fps<=60&&c.profile().max_dynamic_lights<=32&&c.profile().texture_budget_mb<=128);}
static void test_budgets_and_adaptation(){PerformanceController c(make_mobile_profile(PerformanceTier::High));assert(c.frame_budget().valid());PerformanceTelemetry bad;bad.cpu_frame_ms=30;bad.gpu_frame_ms=30;bad.streaming_ms=5;bad.physics_ms=10;bad.thermal=ThermalState::Nominal;PerformanceDecision d{};for(int i=0;i<8;++i)d=c.update(bad);assert(d.valid());assert(d.quality_changed||d.tier!=PerformanceTier::High||d.render_scale<1.0f);assert(c.profile().tier!=PerformanceTier::High||c.profile().render_scale<1.0f);bad.thermal=ThermalState::Critical;d=c.update(bad);assert(d.throttle_simulation);}
static void test_invalid_input_and_recovery(){PerformanceController c(make_mobile_profile(PerformanceTier::Medium));auto before=c.profile().tier;PerformanceTelemetry invalid;invalid.cpu_frame_ms=std::nanf("");auto d=c.update(invalid);assert(d.valid()&&d.tier==before);PerformanceTelemetry good;good.cpu_frame_ms=2;good.gpu_frame_ms=2;good.streaming_ms=.1f;good.physics_ms=1;for(int i=0;i<120;++i)c.update(good);assert(c.profile().tier!=PerformanceTier::Medium||c.profile().render_scale>=.70f);c.reset();assert(c.profile().valid());}
int main(){test_profiles();test_budgets_and_adaptation();test_invalid_input_and_recovery();std::cout<<"Phase 13 performance tests passed\n";}
