#pragma once
#include "exgine/character.hpp"
#include "exgine/physics.hpp"
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>
namespace exgine {
enum class CharacterMovementState:uint8_t{Idle,Walk,Run,Crouch,Jump,Fall,Climb,Swim,Dead}; enum class CharacterPosture:uint8_t{Standing,Crouching,Sitting}; enum class DamageType:uint8_t{Physical,Blunt,Slash,Pierce,Projectile,Fire,Fall,Drowning}; enum class ItemType:uint8_t{Generic,Food,Drink,Clothing,Equipment,MeleeWeapon,RangedWeapon,Medical,Quest}; enum class InteractionType:uint8_t{Use,Pickup,Drop,Open,Close,Sit,EnterVehicle,ExitVehicle,Talk,Attack}; enum class ActivityType:uint8_t{Idle,Eat,Sleep,Work,Socialize,Shop,Travel,Rest}; enum class ScheduleAction:uint8_t{Idle,MoveTo,Work,Eat,Sleep,Socialize,Shop,Rest};
using CharacterId=uint64_t; using ItemId=uint64_t; using InteractionId=uint64_t; inline constexpr CharacterId invalid_character=0; inline constexpr ItemId invalid_item=0; inline constexpr InteractionId invalid_interaction=0;
struct CharacterControllerConfig{float radius=.34f,standing_height=1.8f,crouching_height=1.1f,walk_speed=2,run_speed=5.5f,crouch_speed=1.1f,acceleration=24,braking=30,jump_speed=5.2f,gravity_scale=1,step_height=.35f,slope_limit_degrees=48,climb_speed=1.6f,swim_speed=2.5f; PhysicsLayer layer=1U; PhysicsMask mask=0xffffffffU; bool valid()const noexcept;};
struct CharacterControllerInput{float move_x=0,move_z=0;bool run=false,crouch=false,jump=false,climb=false,swim=false;bool valid()const noexcept;};
struct CharacterControllerState{CharacterMovementState movement=CharacterMovementState::Idle;CharacterPosture posture=CharacterPosture::Standing;Vec3 velocity{};Vec3 ground_normal{0,1,0};bool grounded=false,climbing=false,swimming=false;bool valid()const noexcept;};
struct CharacterController{CharacterControllerConfig config{};CharacterControllerState state{};PhysicsBodyId body=0;PhysicsColliderId collider=0;void reset()noexcept;bool valid()const noexcept;bool create(PhysicsWorld&,Vec3);bool destroy(PhysicsWorld&)noexcept;bool update(PhysicsWorld&,CharacterControllerInput,float)noexcept;std::optional<PhysicsTransform> transform(const PhysicsWorld&)const noexcept;};
struct ItemDefinition{ItemId id=0;std::string name;ItemType type=ItemType::Generic;float mass=.1f,value=0,nutrition=0,hydration=0,damage=0,range=1.5f;uint32_t max_stack=1;bool valid()const noexcept;};
struct InventorySlot{ItemId item=0;uint32_t quantity=0;}; class Inventory{public:explicit Inventory(uint32_t capacity=32);uint32_t capacity()const noexcept;const std::vector<InventorySlot>&slots()const noexcept;bool add(ItemId,uint32_t=1,uint32_t=1);bool remove(ItemId,uint32_t=1);uint32_t count(ItemId)const noexcept;void clear()noexcept;private:uint32_t capacity_;std::vector<InventorySlot>slots_;};
struct CharacterVitals{float health=100,max_health=100,stamina=100,max_stamina=100,hunger=0,thirst=0,fatigue=0,oxygen=100;bool valid()const noexcept;bool alive()const noexcept;}; struct DamageEvent{CharacterId source=0,target=0;DamageType type=DamageType::Physical;float amount=0;Vec3 point{},normal{};}; struct CombatResult{bool hit=false,killed=false;float damage=0;};
struct CharacterInstance{CharacterId id=0;CharacterType type=CharacterType::NPC;CharacterDefinition definition{};CharacterController controller{};CharacterVitals vitals{};Inventory inventory{};ItemId equipped_item=0;CharacterPosture posture=CharacterPosture::Standing;bool unconscious=false,recovering=false;float recovery_time=0;bool valid()const noexcept;};
struct InteractionTarget{InteractionId id=0;InteractionType type=InteractionType::Use;Vec3 position{};float radius=1.5f;uint64_t target_entity=0;ItemId item=0;bool enabled=true;bool valid()const noexcept;};
struct ScheduleEntry{uint16_t start_minute=0,end_minute=0;ScheduleAction action=ScheduleAction::Idle;Vec3 target{};uint64_t target_entity=0;bool valid()const noexcept;}; struct NPCSchedule{std::vector<ScheduleEntry>entries;bool valid()const noexcept;}; struct NPCState{ActivityType activity=ActivityType::Idle;size_t schedule_index=0;Vec3 target{};uint64_t target_entity=0;}; struct GameplayWorldSettings{float time_scale=1,seconds_per_game_minute=1;bool deterministic=true;bool valid()const noexcept;};
class GameplayWorld{public:explicit GameplayWorld(GameplayWorldSettings={});~GameplayWorld();GameplayWorld(GameplayWorld&&)noexcept;GameplayWorld&operator=(GameplayWorld&&)noexcept;GameplayWorld(const GameplayWorld&)=delete;GameplayWorld&operator=(const GameplayWorld&)=delete;const GameplayWorldSettings&settings()const noexcept;CharacterId create_character(CharacterDefinition={},Vec3={});bool destroy_character(CharacterId)noexcept;CharacterInstance*character(CharacterId)noexcept;const CharacterInstance*character(CharacterId)const noexcept;std::vector<CharacterId>character_ids()const;bool update_character(CharacterId,CharacterControllerInput,float)noexcept;bool damage(const DamageEvent&,CombatResult*=nullptr)noexcept;bool recover(CharacterId,float)noexcept;bool set_equipped_item(CharacterId,ItemId)noexcept;bool consume(CharacterId,ItemId)noexcept;bool define_item(ItemDefinition);const ItemDefinition*item(ItemId)const noexcept;bool remove_item_definition(ItemId)noexcept;InteractionId add_interaction(InteractionTarget);bool remove_interaction(InteractionId)noexcept;const InteractionTarget*interaction(InteractionId)const noexcept;bool interact(CharacterId,InteractionId,InteractionType)noexcept;bool set_schedule(CharacterId,NPCSchedule);const NPCSchedule*schedule(CharacterId)const noexcept;const NPCState*npc_state(CharacterId)const noexcept;void update(float)noexcept;void clear()noexcept;uint64_t game_minute()const noexcept;const std::vector<DamageEvent>&damage_events()const noexcept;void bind_physics(PhysicsWorld*)noexcept;PhysicsWorld*physics()noexcept;private:struct Impl;std::unique_ptr<Impl>impl_;};
}