#pragma once
#include "exgine/render.hpp"
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>
namespace exgine {
struct RenderPipelinePlan;
using GlEnum=std::uint32_t; using GlInt=std::int32_t; using GlUInt=std::uint32_t; using GlSize=std::ptrdiff_t; using GlFloat=float; using GlBool=std::uint8_t;
using PFNGLCLEARPROC=void(*)(GlUInt); using PFNGLCLEARCOLORPROC=void(*)(GlFloat,GlFloat,GlFloat,GlFloat); using PFNGLVIEWPORTPROC=void(*)(GlInt,GlInt,GlInt,GlInt); using PFNGLENABLEPROC=void(*)(GlEnum); using PFNGLDISABLEPROC=void(*)(GlEnum); using PFNGLDEPTHFUNCPROC=void(*)(GlEnum); using PFNGLBLENDFUNCPROC=void(*)(GlEnum,GlEnum); using PFNGLCLEARDEPTHFPROC=void(*)(GlFloat);
using PFNGLCREATESHADERPROC=GlUInt(*)(GlEnum); using PFNGLSHADERSOURCEPROC=void(*)(GlUInt,GlInt,const char* const*,const GlInt*); using PFNGLCOMPILESHADERPROC=void(*)(GlUInt); using PFNGLGETSHADERIVPROC=void(*)(GlUInt,GlEnum,GlInt*); using PFNGLGETSHADERINFOLOGPROC=void(*)(GlUInt,GlInt,GlInt*,char*); using PFNGLDELETESHADERPROC=void(*)(GlUInt);
using PFNGLCREATEPROGRAMPROC=GlUInt(*)(); using PFNGLATTACHSHADERPROC=void(*)(GlUInt,GlUInt); using PFNGLLINKPROGRAMPROC=void(*)(GlUInt); using PFNGLGETPROGRAMIVPROC=void(*)(GlUInt,GlEnum,GlInt*); using PFNGLGETPROGRAMINFOLOGPROC=void(*)(GlUInt,GlInt*,GlInt*,char*); using PFNGLUSEPROGRAMPROC=void(*)(GlUInt); using PFNGLDELETEPROGRAMPROC=void(*)(GlUInt); using PFNGLGETUNIFORMLOCATIONPROC=GlInt(*)(GlUInt,const char*);
using PFNGLUNIFORMMATRIX4FVPROC=void(*)(GlInt,GlInt,GlBool,const GlFloat*); using PFNGLUNIFORM3FPROC=void(*)(GlInt,GlFloat,GlFloat,GlFloat); using PFNGLUNIFORM4FPROC=void(*)(GlInt,GlFloat,GlFloat,GlFloat,GlFloat); using PFNGLUNIFORM1FPROC=void(*)(GlInt,GlFloat); using PFNGLUNIFORM1IPROC=void(*)(GlInt,GlInt);
using PFNGLGENBUFFERSPROC=void(*)(GlInt,GlUInt*); using PFNGLBINDBUFFERPROC=void(*)(GlEnum,GlUInt); using PFNGLBUFFERDATAPROC=void(*)(GlEnum,GlSize,const void*,GlEnum); using PFNGLDELETEBUFFERSPROC=void(*)(GlInt,const GlUInt*); using PFNGLBINDBUFFERBASEPROC=void(*)(GlEnum,GlUInt,GlUInt);
using PFNGLGENVERTEXARRAYSPROC=void(*)(GlInt,GlUInt*); using PFNGLBINDVERTEXARRAYPROC=void(*)(GlUInt); using PFNGLDELETEVERTEXARRAYPROC=void(*)(GlInt,const GlUInt*); using PFNGLENABLEVERTEXATTRIBARRAYPROC=void(*)(GlUInt); using PFNGLVERTEXATTRIBPOINTERPROC=void(*)(GlUInt,GlInt,GlEnum,GlBool,GlInt,const void*); using PFNGLVERTEXATTRIBDIVISORPROC=void(*)(GlUInt,GlUInt); using PFNGLDRAWELEMENTSPROC=void(*)(GlEnum,GlInt,GlEnum,const void*); using PFNGLDRAWARRAYSPROC=void(*)(GlEnum,GlInt,GlInt); using PFNGLDRAWELEMENTSINSTANCEDPROC=void(*)(GlEnum,GlInt,GlEnum,const void*,GlInt);
using PFNGLGENTEXTURESPROC=void(*)(GlInt,GlUInt*); using PFNGLBINDTEXTUREPROC=void(*)(GlEnum,GlUInt); using PFNGLTEXPARAMETERIPROC=void(*)(GlEnum,GlEnum,GlInt); using PFNGLTEXIMAGE2DPROC=void(*)(GlEnum,GlInt,GlInt,GlInt,GlInt,GlInt,GlEnum,GlEnum,const void*); using PFNGLGENERATEMIPMAPPROC=void(*)(GlEnum); using PFNGLACTIVETEXTUREPROC=void(*)(GlEnum); using PFNGLDELETETEXTURESPROC=void(*)(GlInt,const GlUInt*);
using PFNGLGENFRAMEBUFFERSPROC=void(*)(GlInt,GlUInt*); using PFNGLBINDFRAMEBUFFERPROC=void(*)(GlEnum,GlUInt); using PFNGLDELETEFRAMEBUFFERSPROC=void(*)(GlInt,const GlUInt*); using PFNGLFRAMEBUFFERTEXTURE2DPROC=void(*)(GlEnum,GlEnum,GlEnum,GlUInt,GlInt); using PFNGLCHECKFRAMEBUFFERSTATUSPROC=GlEnum(*)(GlEnum); using PFNGLGENRENDERBUFFERSPROC=void(*)(GlInt,GlUInt*); using PFNGLBINDRENDERBUFFERPROC=void(*)(GlEnum,GlUInt); using PFNGLDELETERENDERBUFFERPROC=void(*)(GlInt,const GlUInt*); using PFNGLRENDERBUFFERSTORAGEPROC=void(*)(GlEnum,GlEnum,GlInt,GlInt); using PFNGLFRAMEBUFFERRENDERBUFFERPROC=void(*)(GlEnum,GlEnum,GlEnum,GlUInt);
struct OpenGLESApi { PFNGLCLEARPROC Clear=nullptr; PFNGLCLEARCOLORPROC ClearColor=nullptr; PFNGLVIEWPORTPROC Viewport=nullptr; PFNGLENABLEPROC Enable=nullptr; PFNGLDISABLEPROC Disable=nullptr; PFNGLDEPTHFUNCPROC DepthFunc=nullptr; PFNGLBLENDFUNCPROC BlendFunc=nullptr; PFNGLCLEARDEPTHFPROC ClearDepthf=nullptr; PFNGLCREATESHADERPROC CreateShader=nullptr; PFNGLSHADERSOURCEPROC ShaderSource=nullptr; PFNGLCOMPILESHADERPROC CompileShader=nullptr; PFNGLGETSHADERIVPROC GetShaderiv=nullptr; PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog=nullptr; PFNGLDELETESHADERPROC DeleteShader=nullptr; PFNGLCREATEPROGRAMPROC CreateProgram=nullptr; PFNGLATTACHSHADERPROC AttachShader=nullptr; PFNGLLINKPROGRAMPROC LinkProgram=nullptr; PFNGLGETPROGRAMIVPROC GetProgramiv=nullptr; PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog=nullptr; PFNGLUSEPROGRAMPROC UseProgram=nullptr; PFNGLDELETEPROGRAMPROC DeleteProgram=nullptr; PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation=nullptr; PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv=nullptr; PFNGLUNIFORM3FPROC Uniform3f=nullptr; PFNGLUNIFORM4FPROC Uniform4f=nullptr; PFNGLUNIFORM1FPROC Uniform1f=nullptr; PFNGLUNIFORM1IPROC Uniform1i=nullptr; PFNGLGENBUFFERSPROC GenBuffers=nullptr; PFNGLBINDBUFFERPROC BindBuffer=nullptr; PFNGLBUFFERDATAPROC BufferData=nullptr; PFNGLDELETEBUFFERSPROC DeleteBuffers=nullptr; PFNGLBINDBUFFERBASEPROC BindBufferBase=nullptr; PFNGLGENVERTEXARRAYSPROC GenVertexArrays=nullptr; PFNGLBINDVERTEXARRAYPROC BindVertexArray=nullptr; PFNGLDELETEVERTEXARRAYPROC DeleteVertexArrays=nullptr; PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray=nullptr; PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer=nullptr; PFNGLVERTEXATTRIBDIVISORPROC VertexAttribDivisor=nullptr; PFNGLDRAWELEMENTSPROC DrawElements=nullptr; PFNGLDRAWARRAYSPROC DrawArrays=nullptr; PFNGLDRAWELEMENTSINSTANCEDPROC DrawElementsInstanced=nullptr; PFNGLGENTEXTURESPROC GenTextures=nullptr; PFNGLBINDTEXTUREPROC BindTexture=nullptr; PFNGLTEXPARAMETERIPROC TexParameteri=nullptr; PFNGLTEXIMAGE2DPROC TexImage2D=nullptr; PFNGLGENERATEMIPMAPPROC GenerateMipmap=nullptr; PFNGLACTIVETEXTUREPROC ActiveTexture=nullptr; PFNGLDELETETEXTURESPROC DeleteTextures=nullptr; PFNGLGENFRAMEBUFFERSPROC GenFramebuffers=nullptr; PFNGLBINDFRAMEBUFFERPROC BindFramebuffer=nullptr; PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers=nullptr; PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D=nullptr; PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus=nullptr; PFNGLGENRENDERBUFFERSPROC GenRenderbuffers=nullptr; PFNGLBINDRENDERBUFFERPROC BindRenderbuffer=nullptr; PFNGLDELETERENDERBUFFERPROC DeleteRenderbuffers=nullptr; PFNGLRENDERBUFFERSTORAGEPROC RenderbufferStorage=nullptr; PFNGLFRAMEBUFFERRENDERBUFFERPROC FramebufferRenderbuffer=nullptr; [[nodiscard]] bool complete() const noexcept; [[nodiscard]] bool advanced_complete() const noexcept; };
struct GpuSubmitResult { bool success=false; std::size_t draw_calls=0; std::size_t triangles=0; std::size_t animated_draw_calls=0; std::string error; };
struct GpuCachedMesh { GlUInt vao=0; GlUInt vertex_buffer=0; GlUInt index_buffer=0; std::size_t index_count=0; std::size_t vertex_count=0; bool animated=false; std::uint64_t last_used_frame=0; [[nodiscard]] bool valid() const noexcept{return vao!=0&&vertex_buffer!=0&&index_buffer!=0&&index_count>0;} };
struct GpuCachedTexture { GlUInt handle=0; std::uint32_t width=0,height=0; std::uint64_t source_key=0; [[nodiscard]] bool valid() const noexcept{return handle!=0&&width>0&&height>0;} };
class OpenGLESRenderer { public: explicit OpenGLESRenderer(OpenGLESApi api) noexcept:api_(api){} ~OpenGLESRenderer(); OpenGLESRenderer(const OpenGLESRenderer&)=delete; OpenGLESRenderer& operator=(const OpenGLESRenderer&)=delete; [[nodiscard]] bool ready()const noexcept; [[nodiscard]] bool texture_ready()const noexcept; [[nodiscard]] bool prepare(std::string& error); [[nodiscard]] GpuSubmitResult submit(const RenderFrame&); [[nodiscard]] GpuSubmitResult submit_advanced(const RenderFrame&); void release()noexcept; [[nodiscard]] std::size_t cached_mesh_count()const noexcept{return meshes_.size();} [[nodiscard]] std::size_t cached_texture_count()const noexcept{return textures_.size();} [[nodiscard]] GlUInt mobile_program()const noexcept{return program_;} [[nodiscard]] GlUInt mobile_skinned_program()const noexcept{return skinned_program_;} [[nodiscard]] GlUInt mobile_textured_program()const noexcept{return textured_program_;} [[nodiscard]] GlUInt mobile_skinned_textured_program()const noexcept{return skinned_textured_program_;} [[nodiscard]] const OpenGLESApi& api()const noexcept{return api_;} private: OpenGLESApi api_{}; GlUInt program_=0,skinned_program_=0,textured_program_=0,skinned_textured_program_=0; GlInt u_vp_=-1,u_model_=-1,u_camera_=-1,u_ambient_=-1,u_base_=-1,u_rough_=-1,u_metal_=-1,u_emission_=-1,u_opacity_=-1,u_light_dir_=-1,u_light_color_=-1,u_light_intensity_=-1; GlInt tu_vp_=-1,tu_model_=-1,tu_camera_=-1,tu_ambient_=-1,tu_base_=-1,tu_metal_=-1,tu_emission_=-1,tu_light_dir_=-1,tu_light_color_=-1,tu_light_intensity_=-1; GlInt t_base_=-1,t_rough_=-1,t_metal_=-1,t_normal_=-1,t_ao_=-1,t_emission_=-1,t_opacity_=-1,t_use_=-1; GlInt s_vp_=-1,s_model_=-1,s_camera_=-1,s_ambient_=-1,s_base_=-1,s_metal_=-1,s_emission_=-1,s_light_dir_=-1,s_light_color_=-1,s_light_intensity_=-1,s_bones_=-1,s_bone_count_=-1; GlInt stu_vp_=-1,stu_model_=-1,stu_camera_=-1,stu_ambient_=-1,stu_base_=-1,stu_metal_=-1,stu_emission_=-1,stu_light_dir_=-1,stu_light_color_=-1,stu_light_intensity_=-1,stu_bones_=-1,stu_bone_count_=-1; GlInt st_base_=-1,st_rough_=-1,st_metal_=-1,st_normal_=-1,st_ao_=-1,st_emission_=-1,st_opacity_=-1,st_use_=-1; std::unordered_map<std::uint64_t,GpuCachedMesh> meshes_; std::unordered_map<std::uint64_t,GpuCachedTexture> textures_; [[nodiscard]] bool ensure_programs(std::string&); [[nodiscard]] bool compile_shader(GlEnum,const char*,GlUInt&,std::string&); [[nodiscard]] bool link_program(const char*,GlUInt,const char*,GlUInt&,std::string&); [[nodiscard]] bool ensure_mesh(const RenderDrawCall&,std::uint64_t,GpuCachedMesh*&,std::string&); [[nodiscard]] bool ensure_texture(const std::shared_ptr<const Texture2D>&,std::uint64_t,GpuCachedTexture*&,std::string&); void release_meshes()noexcept; void release_textures()noexcept; };
GpuSubmitResult render_world_systems(OpenGLESApi&, const RenderFrame&, const RenderPipelinePlan&);
}