#include "exgine/aaa.hpp"
#include <algorithm>
#include <cmath>
#include <limits>

namespace exgine {
namespace { float clamp01(float x) noexcept { return std::clamp(x,0.0f,1.0f); } float len(Vec3 v) noexcept { return std::sqrt(v.x*v.x+v.y*v.y+v.z*v.z); } Vec3 norm(Vec3 v) noexcept { const float l=len(v); return l>1e-6f?Vec3{v.x/l,v.y/l,v.z/l}:Vec3{0,1,0}; } }

IrradianceProbeGrid::IrradianceProbeGrid(std::uint32_t nx,std::uint32_t ny,std::uint32_t nz,float spacing):nx_(std::max(1u,nx)),ny_(std::max(1u,ny)),nz_(std::max(1u,nz)),spacing_(std::max(.1f,spacing)){}
bool IrradianceProbeGrid::generate(Vec3 origin,const HighQualityLighting& lighting){ probes_.clear(); probes_.reserve(static_cast<std::size_t>(nx_)*ny_*nz_); const Vec3 sun=norm(lighting.sun_direction); for(std::uint32_t z=0;z<nz_;++z) for(std::uint32_t y=0;y<ny_;++y) for(std::uint32_t x=0;x<nx_;++x){ const float ndl=std::max(0.0f,-sun.y); const float base=lighting.ambient_intensity+lighting.sun_intensity*ndl*0.08f; probes_.push_back({{origin.x+x*spacing_,origin.y+y*spacing_,origin.z+z*spacing_},{base*lighting.sun_color.r,base*lighting.sun_color.g,base*lighting.sun_color.b},spacing_*1.5f}); } return !probes_.empty(); }
Color3 IrradianceProbeGrid::sample(Vec3 position) const noexcept { if(probes_.empty()) return {}; const IrradianceProbe* best=&probes_.front(); float best_d=std::numeric_limits<float>::max(); for(const auto& p:probes_){ const float dx=p.position.x-position.x,dy=p.position.y-position.y,dz=p.position.z-position.z; const float d=dx*dx+dy*dy+dz*dz; if(d<best_d){best_d=d;best=&p;} } return best->irradiance; }

ReflectionHit trace_reflection_plane(const ReflectionQuery& q,Vec3 pp,Vec3 pn) noexcept { const Vec3 n=norm(pn); const float denom=q.direction.x*n.x+q.direction.y*n.y+q.direction.z*n.z; if(std::abs(denom)<1e-6f||q.max_distance<=0) return {}; const Vec3 d{pp.x-q.origin.x,pp.y-q.origin.y,pp.z-q.origin.z}; const float t=(d.x*n.x+d.y*n.y+d.z*n.z)/denom; if(t<0||t>q.max_distance) return {}; return {true,t,n}; }
float fog_transmittance(const VolumetricFog& fog,float distance,float height) noexcept { const float h=std::max(0.0f,height); const float density=std::max(0.0f,fog.density)*std::exp(-std::max(0.0f,fog.height_falloff)*h); return std::exp(-density*std::max(0.0f,distance)*std::max(0.0f,fog.extinction)); }
HdrColor aces_tonemap(HdrColor c,float exposure) noexcept { const float e=std::pow(2.0f,exposure); auto f=[](float x){ const float a=2.51f,b=.03f,c=2.43f,d=.59f,ee=.14f; return std::clamp((x*(a*x+b))/(x*(c*x+d)+ee),0.0f,1.0f); }; return {f(c.r*e),f(c.g*e),f(c.b*e)}; }
TerrainMaterialWeights blend_terrain(float height,float slope,float moisture,float snow_line,float rock_line) noexcept { const float snow=clamp01((height-snow_line)/std::max(1.0f, snow_line*.25f)); const float rock=clamp01((slope-.35f)/.45f); const float sand=clamp01((moisture-.05f)*4.0f)*clamp01((snow_line-height)/std::max(1.0f,snow_line)); const float mud=clamp01(moisture*.8f)*(1.0f-rock); const float grass=clamp01(1.0f-snow-rock-sand-mud); const float total=std::max(1e-6f,grass+sand+rock+snow+mud); return {grass/total,sand/total,rock/total,snow/total,mud/total}; }
TireForce combined_slip_force(const CombinedSlipInput& in) noexcept { const float load=std::max(0.0f,in.normal_load),mu=std::max(0.0f,in.mu); const float sr=std::clamp(in.slip_ratio,-1.0f,1.0f), sa=in.slip_angle; const float magnitude=load*mu; const float lx=sr/(1.0f+std::abs(sr)); const float ly=std::tan(sa); const float denom=std::sqrt(1.0f+lx*lx+ly*ly); return {magnitude*lx/denom,-magnitude*ly/denom}; }
IkResult solve_ground_foot(Vec3 hip,Vec3 target,float leg_length,float ground_y) noexcept { const float L=std::max(.05f,leg_length); Vec3 horizontal{target.x-hip.x,0,target.z-hip.z}; const float h=len(horizontal); const float y=ground_y; const float dy=y-hip.y; const float d=std::sqrt(h*h+dy*dy); if(d>L*2.0f) return {}; float scale=d>1e-5f?std::min(1.0f,L/d):1.0f; Vec3 foot{hip.x+(target.x-hip.x)*scale,hip.y+dy*scale,hip.z+(target.z-hip.z)*scale}; foot.y=y; return {true,foot}; }
void UtilityAiSelector::add(AiActionScore action){ if(action.action.empty()) return; actions_.push_back(std::move(action)); }
std::string UtilityAiSelector::choose() const { if(actions_.empty()) return {}; const auto it=std::max_element(actions_.begin(),actions_.end(),[](const auto&a,const auto&b){return a.score<b.score;}); return it->action; }
AcousticPath evaluate_acoustics(Vec3 listener,Vec3 source,float absorption) noexcept { const Vec3 d{source.x-listener.x,source.y-listener.y,source.z-listener.z}; const float distance=len(d); const float a=clamp01(absorption); return {distance,std::min(1.0f,a*std::min(1.0f,distance/30.0f)),a*std::min(1.0f,distance/50.0f)}; }
}
