#include "exgine/animation.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
namespace exgine { namespace { constexpr float pi=3.14159265358979323846f; float c01(float x){return std::clamp(x,0.0f,1.0f);} Vec3 add(Vec3 a,Vec3 b){return {a.x+b.x,a.y+b.y,a.z+b.z};} Vec3 mul(Vec3 a,float s){return {a.x*s,a.y*s,a.z*s};} float qdot(Quat a,Quat b){return a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w;} Quat qneg(Quat q){return {-q.x,-q.y,-q.z,-q.w};} Quat axis(Vec3 a,float angle){float s=std::sin(angle*.5f);return normalize({a.x*s,a.y*s,a.z*s,std::cos(angle*.5f)});} }
Quat Quat::identity() noexcept{return {};} Quat normalize(Quat q) noexcept{float n=std::sqrt(qdot(q,q));if(!std::isfinite(n)||n<1e-8f)return {};return {q.x/n,q.y/n,q.z/n,q.w/n};} Quat multiply(Quat a,Quat b) noexcept{return normalize({a.w*b.x+a.x*b.w+a.y*b.z-a.z*b.y,a.w*b.y-a.x*b.z+a.y*b.w+a.z*b.x,a.w*b.z+a.x*b.y-a.y*b.x+a.z*b.w,a.w*b.w-a.x*b.x-a.y*b.y-a.z*b.z});} Quat slerp(Quat a,Quat b,float t) noexcept{t=c01(t);a=normalize(a);b=normalize(b);float d=qdot(a,b);if(d<0){b=qneg(b);d=-d;}if(d>.9995f)return normalize({a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,a.z+(b.z-a.z)*t,a.w+(b.w-a.w)*t});float th=std::acos(std::clamp(d,-1.0f,1.0f)),s=std::sin(th);float u=std::sin((1-t)*th)/s,v=std::sin(t*th)/s;return normalize({a.x*u+b.x*v,a.y*u+b.y*v,a.z*u+b.z*v,a.w*u+b.w*v});}
AnimTransform interpolate(AnimTransform a,AnimTransform b,float t) noexcept{t=c01(t);return {{a.translation.x+(b.translation.x-a.translation.x)*t,a.translation.y+(b.translation.y-a.translation.y)*t,a.translation.z+(b.translation.z-a.translation.z)*t},slerp(a.rotation,b.rotation,t),{a.scale.x+(b.scale.x-a.scale.x)*t,a.scale.y+(b.scale.y-a.scale.y)*t,a.scale.z+(b.scale.z-a.scale.z)*t}};}
bool Skeleton::valid() const noexcept{if(bones.empty())return false;for(std::size_t i=0;i<bones.size();++i)if(bones[i].id!=i+1||bones[i].name.empty()||bones[i].parent>=bones[i].id)return false;return true;} BoneId Skeleton::find_bone(std::string_view n) const noexcept{for(const auto&b:bones)if(b.name==n)return b.id;return 0;} bool SkeletonPose::valid_for(const Skeleton&s)const noexcept{return s.valid()&&local.size()==s.bones.size()&&model.size()==s.bones.size();}
SkeletonPose make_bind_pose(const Skeleton&s){SkeletonPose p;p.local.reserve(s.bones.size());for(const auto&b:s.bones)p.local.push_back(b.local);p.model.resize(s.bones.size());update_pose(s,p);return p;} void update_pose(const Skeleton&s,SkeletonPose&p) noexcept{if(!p.valid_for(s))return;for(std::size_t i=0;i<s.bones.size();++i){auto pid=s.bones[i].parent;if(pid==0)p.model[i]=p.local[i];else{const auto&par=p.model[pid-1];auto cur=p.local[i];p.model[i].translation=add(par.translation,cur.translation);p.model[i].rotation=multiply(par.rotation,cur.rotation);p.model[i].scale={par.scale.x*cur.scale.x,par.scale.y*cur.scale.y,par.scale.z*cur.scale.z};}}}
bool SkinWeight::valid(const Skeleton&s)const noexcept{float sum=0;for(std::size_t i=0;i<4;++i){if(weights[i]<0||!std::isfinite(weights[i]))return false;if(weights[i]>0){if(bones[i]==0||bones[i]>s.bones.size())return false;sum+=weights[i];}}return sum>0&&sum<=1.001f;} bool SkinnedMesh::valid(const Skeleton&s)const noexcept{if(vertices.empty()||indices.empty()||indices.size()%3)return false;for(auto i:indices)if(i>=vertices.size())return false;for(const auto&v:vertices)if(!v.skin.valid(s))return false;return true;}
Vec3 qrotate(Quat q,Vec3 v){return add(v,mul(cross({q.x,q.y,q.z},v),2*q.w));} // intentionally replaced below by full formula
Vec3 qrot(Quat q,Vec3 v){Vec3 u{q.x,q.y,q.z};float s=q.w;float ud=u.x*v.x+u.y*v.y+u.z*v.z;float uu=u.x*u.x+u.y*u.y+u.z*u.z;Vec3 uxv{u.y*v.z-u.z*v.y,u.z*v.x-u.x*v.z,u.x*v.y-u.y*v.x};return {2*ud*u.x+(s*s-uu)*v.x+2*s*uxv.x,2*ud*u.y+(s*s-uu)*v.y+2*s*uxv.y,2*ud*u.z+(s*s-uu)*v.z+2*s*uxv.z};}
std::vector<Vertex> skin_mesh(const SkinnedMesh&m,const SkeletonPose&p){std::vector<Vertex>o;if(p.model.empty())return o;o.reserve(m.vertices.size());for(const auto&v:m.vertices){Vec3 pos{},norm{};float wsum=0;for(std::size_t j=0;j<4;++j)if(v.skin.weights[j]>0&&v.skin.bones[j]>0&&v.skin.bones[j]<=p.model.size()){const auto&t=p.model[v.skin.bones[j]-1];pos=add(pos,mul(add(t.translation,{t.scale.x*v.position.x,t.scale.y*v.position.y,t.scale.z*v.position.z}),v.skin.weights[j]));norm=add(norm,mul(qrot(t.rotation,v.normal),v.skin.weights[j]));wsum+=v.skin.weights[j];}if(wsum>0&&wsum<1){pos=add(pos,mul(v.position,1-wsum));norm=add(norm,mul(v.normal,1-wsum));}float n=std::sqrt(norm.x*norm.x+norm.y*norm.y+norm.z*norm.z);if(n>1e-8f)norm=mul(norm,1/n);o.push_back({pos,norm,v.uv});}return o;}
bool AnimationClip::valid(const Skeleton&s)const noexcept{if(id==0||name.empty()||!std::isfinite(duration)||duration<0||!s.valid())return false;for(const auto&t:tracks){if(t.bone==0||t.bone>s.bones.size()||t.keys.empty())return false;float last=-std::numeric_limits<float>::infinity();for(const auto&k:t.keys){if(!std::isfinite(k.time)||k.time<0||k.time>duration||k.time<last)return false;last=k.time;}}return true;}
bool AnimationLibrary::define(AnimationClip c){if(c.id==0)return false;clips_[c.id]=std::move(c);return true;} bool AnimationLibrary::erase(AnimationClipId i)noexcept{return clips_.erase(i)>0;} const AnimationClip*AnimationLibrary::find(AnimationClipId i)const noexcept{auto i2=clips_.find(i);return i2==clips_.end()?nullptr:&i2->second;} const AnimationClip*AnimationLibrary::find(std::string_view n)const noexcept{for(const auto&[id,c]:clips_)if(c.name==n)return &c;return nullptr;} void AnimationLibrary::clear()noexcept{clips_.clear();} std::size_t AnimationLibrary::size()const noexcept{return clips_.size();}
AnimationController::AnimationController(const Skeleton&s):skeleton_(&s),pose_(make_bind_pose(s)){} bool AnimationController::play(AnimationClipId id,float blend)noexcept{if(!skeleton_||!skeleton_->valid()||id==0)return false;if(player_.clip==id&&player_.playing)return true;previous_=player_.clip;previous_time_=player_.time;player_.clip=id;player_.next_clip=0;player_.time=0;player_.playing=true;player_.blend_duration=std::max(0.0f,blend);player_.blend_time=0;return true;} void AnimationController::stop()noexcept{player_.playing=false;player_.clip=player_.next_clip=0;player_.time=player_.blend_time=0;previous_=0;} void AnimationController::sample(const AnimationClip*c,float time,SkeletonPose&p)const noexcept{if(!c||!p.valid_for(*skeleton_))return;p.local=make_bind_pose(*skeleton_).local;float t=c->duration>0?std::fmod(std::max(0.0f,time),c->duration):0;for(const auto&tr:c->tracks){auto&d=p.local[tr.bone-1];if(tr.keys.size()==1){d=tr.keys[0].transform;continue;}if(t<=tr.keys.front().time){d=tr.keys.front().transform;continue;}if(t>=tr.keys.back().time){d=tr.keys.back().transform;continue;}for(std::size_t i=1;i<tr.keys.size();++i)if(t<=tr.keys[i].time){const auto&a=tr.keys[i-1],&b=tr.keys[i];d=interpolate(a.transform,b.transform,(t-a.time)/(b.time-a.time));break;}}update_pose(*skeleton_,p);}
void AnimationController::update(float dt,const AnimationLibrary&lib)noexcept{if(!player_.playing||!std::isfinite(dt)||dt<0)return;auto*c=lib.find(player_.clip);if(!c||!c->valid(*skeleton_)){stop();return;}float old_time=player_.time;player_.time+=dt*player_.playback_rate;if(c->duration>0){if(player_.looping||c->looping)player_.time=std::fmod(std::max(0.0f,player_.time),c->duration);else if(player_.time>=c->duration){player_.time=c->duration;player_.playing=false;}}sample(c,player_.time,pose_);if(previous_&&player_.blend_duration>0&&player_.blend_time<player_.blend_duration){auto*old=lib.find(previous_);if(old&&old->valid(*skeleton_)){SkeletonPose a=make_bind_pose(*skeleton_);sample(old,old_time,a);float w=c01(player_.blend_time/player_.blend_duration);for(std::size_t i=0;i<pose_.local.size();++i)pose_.local[i]=interpolate(a.local[i],pose_.local[i],w);update_pose(*skeleton_,pose_);}player_.blend_time+=dt;}else previous_=0;}
const SkeletonPose&AnimationController::pose()const noexcept{return pose_;} const AnimationPlayer&AnimationController::player()const noexcept{return player_;}
Skeleton make_humanoid_skeleton(){Skeleton s;s.name="humanoid";auto add=[&](const char*n,BoneId p){s.bones.push_back({static_cast<BoneId>(s.bones.size()+1),n,p,{}});};add("root",0);add("spine",1);add("chest",2);add("neck",3);add("head",4);add("upper_arm_l",3);add("lower_arm_l",6);add("hand_l",7);add("upper_arm_r",3);add("lower_arm_r",9);add("hand_r",10);add("upper_leg_l",1);add("lower_leg_l",12);add("foot_l",13);add("upper_leg_r",1);add("lower_leg_r",15);add("foot_r",16);return s;}
AnimationClip simple_clip(const Skeleton&s,AnimationClipId id,const char*n,float dur,float amp){AnimationClip c{id,n,dur,true,{}};for(const auto&b:s.bones)if(b.name=="root"||b.name.find("leg")!=std::string::npos){BoneTrack t;t.bone=b.id;for(int i=0;i<9;++i){float x=dur*i/8,a=std::sin(x/dur*2*pi)*amp;AnimTransform tr=b.local;if(b.name.find("leg")!=std::string::npos)tr.rotation=axis({1,0,0},a);if(b.name=="root")tr.translation.y=a*.15f;t.keys.push_back({x,tr});}c.tracks.push_back(std::move(t));}return c;} AnimationClip make_idle_clip(const Skeleton&s,AnimationClipId id){return simple_clip(s,id,"idle",2,.04f);} AnimationClip make_walk_clip(const Skeleton&s,AnimationClipId id){return simple_clip(s,id,"walk",1,.55f);} AnimationClip make_run_clip(const Skeleton&s,AnimationClipId id){return simple_clip(s,id,"run",.65f,.9f);} AnimationClip make_jump_clip(const Skeleton&s,AnimationClipId id){AnimationClip c{id,"jump",.9f,false,{}};BoneTrack t;t.bone=s.find_bone("root");t.keys={{0,{}},{.3f,{{0,.7f,0},{},{1,1,1}}},{.6f,{{0,.2f,0},{},{1,1,1}}},{.9f,{}}};c.tracks.push_back(std::move(t));return c;}
}
