#include "exgine/building.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace exgine {
namespace {
std::uint64_t mix64(std::uint64_t v) noexcept { v += 0x9e3779b97f4a7c15ULL; v=(v^(v>>30U))*0xbf58476d1ce4e5b9ULL; v=(v^(v>>27U))*0x94d049bb133111ebULL; return v^(v>>31U); }
float unit(std::uint64_t v) noexcept { return static_cast<float>(mix64(v)>>40U)/static_cast<float>(1U<<24U); }
bool finite(float v) noexcept { return std::isfinite(v); }
bool finite(Vec3 v) noexcept { return finite(v.x)&&finite(v.y)&&finite(v.z); }
std::uint64_t stable_id(std::uint64_t seed,std::uint64_t domain,std::uint64_t index) noexcept { return mix64(seed^mix64(domain)^mix64(index))|1ULL; }

void add_box(MeshAssembly& a,std::string name,Vec3 size,const std::string& material,Vec3 position){ if(size.x<=0||size.y<=0||size.z<=0||material.empty())return; MeshPart p{std::move(name),make_box({size}),material,position,{1,1,1},{0,0,0}};if(p.mesh.valid())a.parts.push_back(std::move(p)); }
struct Gap { float center=0; float width=0; };
void add_x_wall(MeshAssembly&a,std::vector<BuildingCollisionVolume>&c,const std::string&m,std::string name,float z,float y,float length,float thickness,float height,std::vector<Gap> gaps,std::uint64_t&next){std::sort(gaps.begin(),gaps.end(),[](const Gap&a,const Gap&b){return a.center<b.center;});float cursor=-length*.5f;for(std::size_t i=0;i<gaps.size();++i){const auto&g=gaps[i];const float left=std::clamp(g.center-g.width*.5f,-length*.5f,length*.5f),right=std::clamp(g.center+g.width*.5f,-length*.5f,length*.5f);if(left>cursor+1e-4f){const float w=left-cursor;const Vec3 p{(cursor+left)*.5f,y,z};add_box(a,name+"_"+std::to_string(i),{w,height,thickness},m,p);c.push_back({next++,{p.x-w*.5f,p.y-height*.5f,p.z-thickness*.5f},{p.x+w*.5f,p.y+height*.5f,p.z+thickness*.5f},0});}cursor=std::max(cursor,right);}if(cursor<length*.5f-1e-4f){const float w=length*.5f-cursor;const Vec3 p{(cursor+length*.5f)*.5f,y,z};add_box(a,name+"_end",{w,height,thickness},m,p);c.push_back({next++,{p.x-w*.5f,p.y-height*.5f,p.z-thickness*.5f},{p.x+w*.5f,p.y+height*.5f,p.z+thickness*.5f},0});}}
void add_z_wall(MeshAssembly&a,std::vector<BuildingCollisionVolume>&c,const std::string&m,std::string name,float x,float y,float length,float thickness,float height,std::vector<Gap> gaps,std::uint64_t&next){std::sort(gaps.begin(),gaps.end(),[](const Gap&a,const Gap&b){return a.center<b.center;});float cursor=-length*.5f;for(std::size_t i=0;i<gaps.size();++i){const auto&g=gaps[i];const float left=std::clamp(g.center-g.width*.5f,-length*.5f,length*.5f),right=std::clamp(g.center+g.width*.5f,-length*.5f,length*.5f);if(left>cursor+1e-4f){const float w=left-cursor;const Vec3 p{x,y,(cursor+left)*.5f};add_box(a,name+"_"+std::to_string(i),{thickness,height,w},m,p);c.push_back({next++,{p.x-thickness*.5f,p.y-height*.5f,p.z-w*.5f},{p.x+thickness*.5f,p.y+height*.5f,p.z+w*.5f},0});}cursor=std::max(cursor,right);}if(cursor<length*.5f-1e-4f){const float w=length*.5f-cursor;const Vec3 p{x,y,(cursor+length*.5f)*.5f};add_box(a,name+"_end",{thickness,height,w},m,p);c.push_back({next++,{p.x-thickness*.5f,p.y-height*.5f,p.z-w*.5f},{p.x+thickness*.5f,p.y+height*.5f,p.z+w*.5f},0});}}

BuildingConfig normalize(BuildingConfig c){c.width=finite(c.width)?std::max(c.width,4.0f):4.0f;c.depth=finite(c.depth)?std::max(c.depth,4.0f):4.0f;c.floors=std::clamp(c.floors,1U,64U);c.floor_height=finite(c.floor_height)?std::max(c.floor_height,2.4f):2.4f;c.wall_thickness=finite(c.wall_thickness)?std::clamp(c.wall_thickness,.05f,.6f):.2f;c.floor_thickness=finite(c.floor_thickness)?std::clamp(c.floor_thickness,.05f,.5f):.18f;c.rooms_per_floor=std::clamp(c.rooms_per_floor,1U,64U);c.door_width=finite(c.door_width)?std::clamp(c.door_width,.6f,std::min(1.6f,c.width*.25f)):.95f;c.door_height=finite(c.door_height)?std::clamp(c.door_height,1.8f,c.floor_height-.2f):std::min(2.15f,c.floor_height-.2f);c.window_width=finite(c.window_width)?std::clamp(c.window_width,.5f,c.width*.35f):1.25f;c.window_height=finite(c.window_height)?std::clamp(c.window_height,.6f,c.floor_height*.5f):1.15f;c.windows_per_wall=std::clamp(c.windows_per_wall,0U,8U);c.stair_width=finite(c.stair_width)?std::clamp(c.stair_width,.7f,std::min(c.width,c.depth)*.45f):1.1f;c.furniture_density=std::clamp(c.furniture_density,0U,5U);return c;}

struct RowLayout { std::uint32_t count=0; float min_z=0; float max_z=0; };
std::vector<RowLayout> make_rows(std::uint32_t rooms,float depth){const std::uint32_t rows=std::max(1U,std::min(rooms,static_cast<std::uint32_t>(std::floor(std::sqrt(static_cast<float>(rooms))))));const std::uint32_t base=rooms/rows,remainder=rooms%rows;std::vector<RowLayout> result;result.reserve(rows);float z=-depth*.5f;for(std::uint32_t r=0;r<rows;++r){const float h=depth/static_cast<float>(rows);result.push_back({base+(r<remainder?1U:0U),z,z+h});z+=h;}return result;}

void add_furniture(BuildingDefinition& b,const BuildingConfig& c,const BuildingRoom& room,std::uint32_t count,std::uint64_t seed,std::uint64_t&next){if(count==0||room.max.x-room.min.x<2.5f||room.max.z-room.min.z<2.5f)return;const float jx=(unit(seed^0x11ULL)-.5f)*(room.max.x-room.min.x)*.12f;const float jz=(unit(seed^0x17ULL)-.5f)*(room.max.z-room.min.z)*.12f;auto pos=[&](float x,float y,float z){return Vec3{x,y,z};};const auto cx=room.center.x+jx,cz=room.center.z+jz;if(count>=1){const Vec3 p=pos(cx,.28f+room.min.y,room.max.z-.62f);b.furniture.push_back({next++,BuildingFurnitureType::Bed,room.id,p,{1.65f,.5f,.88f},0});add_box(b.geometry,"bed_"+std::to_string(next),{1.65f,.5f,.88f},c.furniture_material,p);add_box(b.geometry,"pillow_"+std::to_string(next),{.85f,.14f,.34f},c.furniture_material,{p.x,p.y+.32f,p.z-.18f});}
if(count>=2){const Vec3 p=pos(room.min.x+(room.max.x-room.min.x)*.23f,room.min.y+.52f,cz);b.furniture.push_back({next++,BuildingFurnitureType::Desk,room.id,p,{1.1f,.10f,.55f},0});add_box(b.geometry,"desk_"+std::to_string(next),{1.1f,.10f,.55f},c.furniture_material,p);}
if(count>=3){const Vec3 p=pos(room.min.x+(room.max.x-room.min.x)*.23f,room.min.y+.45f,cz+.52f);b.furniture.push_back({next++,BuildingFurnitureType::Chair,room.id,p,{.46f,.9f,.46f},0});add_box(b.geometry,"chair_"+std::to_string(next),{.46f,.9f,.46f},c.furniture_material,p);}
if(count>=4){const Vec3 p=pos(cx,room.min.y+.42f,room.min.z+(room.max.z-room.min.z)*.28f);b.furniture.push_back({next++,BuildingFurnitureType::Table,room.id,p,{1.0f,.08f,.65f},0});add_box(b.geometry,"table_"+std::to_string(next),{1.0f,.08f,.65f},c.furniture_material,p);}
if(count>=5){const Vec3 p=pos(room.min.x+.65f,room.min.y+.52f,room.max.z-.95f);b.furniture.push_back({next++,BuildingFurnitureType::Cabinet,room.id,p,{.6f,1.2f,.45f},0});add_box(b.geometry,"cabinet_"+std::to_string(next),{.6f,1.2f,.45f},c.furniture_material,p);}}

void add_windows(BuildingDefinition& b,const BuildingConfig& c,std::uint32_t floor,float base,std::uint64_t&next_opening,std::uint64_t&next_interactable){if(c.windows_per_wall==0)return;const float inner_w=c.width-2*c.wall_thickness,inner_d=c.depth-2*c.wall_thickness,top=base+c.floor_height*.64f;const std::uint32_t count=c.windows_per_wall;for(std::uint32_t i=0;i<count;++i){const float t=(static_cast<float>(i)+.5f)/static_cast<float>(count);const float x=-inner_w*.5f+t*inner_w;const float z=-inner_d*.5f+t*inner_d;const Vec3 south{x,top,-c.depth*.5f+c.wall_thickness*.5f};const auto id=next_opening++;add_box(b.geometry,"window_south_"+std::to_string(id),{c.window_width,c.window_height,c.wall_thickness*.5f},c.glass_material,south);b.openings.push_back({id,BuildingOpeningType::Window,floor,BuildingWallAxis::X,south,{c.window_width,c.window_height,c.wall_thickness},false,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Window,id,{south.x,south.y,south.z+c.wall_thickness},true});const Vec3 north{x,top,c.depth*.5f-c.wall_thickness*.5f};const auto id2=next_opening++;add_box(b.geometry,"window_north_"+std::to_string(id2),{c.window_width,c.window_height,c.wall_thickness*.5f},c.glass_material,north);b.openings.push_back({id2,BuildingOpeningType::Window,floor,BuildingWallAxis::X,north,{c.window_width,c.window_height,c.wall_thickness},false,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Window,id2,{north.x,north.y,north.z-c.wall_thickness},true});const Vec3 west{-c.width*.5f+c.wall_thickness*.5f,top,z};const auto id3=next_opening++;add_box(b.geometry,"window_west_"+std::to_string(id3),{c.wall_thickness*.5f,c.window_height,c.window_width},c.glass_material,west);b.openings.push_back({id3,BuildingOpeningType::Window,floor,BuildingWallAxis::Z,west,{c.wall_thickness,c.window_height,c.window_width},false,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Window,id3,{west.x+c.wall_thickness,west.y,west.z},true});const Vec3 east{c.width*.5f-c.wall_thickness*.5f,top,z};const auto id4=next_opening++;add_box(b.geometry,"window_east_"+std::to_string(id4),{c.wall_thickness*.5f,c.window_height,c.window_width},c.glass_material,east);b.openings.push_back({id4,BuildingOpeningType::Window,floor,BuildingWallAxis::Z,east,{c.wall_thickness,c.window_height,c.window_width},false,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Window,id4,{east.x-c.wall_thickness,east.y,east.z},true});}}
}

bool BuildingRoom::contains(float x,float y,float z) const noexcept { return x>=min.x&&x<=max.x&&y>=min.y&&y<=max.y&&z>=min.z&&z<=max.z; }
bool BuildingOpening::valid() const noexcept { return id!=0&&finite(position)&&finite(size)&&size.x>0&&size.y>0&&size.z>0; }
bool BuildingInteractable::valid() const noexcept { return id!=0&&target_id!=0&&finite(position)&&(type!=BuildingInteractableType::LightSwitch||target_id==id); }
bool BuildingFurniture::valid() const noexcept { return id!=0&&room_id!=0&&finite(position)&&finite(size)&&size.x>0&&size.y>0&&size.z>0&&finite(rotation); }
bool BuildingCollisionVolume::valid() const noexcept { return id!=0&&finite(min)&&finite(max)&&min.x<=max.x&&min.y<=max.y&&min.z<=max.z; }
bool BuildingDefinition::valid() const noexcept { if(!geometry.valid()||rooms.empty()||config.width<=0||config.depth<=0||config.floors==0)return false;for(std::size_t i=0;i<rooms.size();++i){const auto&r=rooms[i];if(!r.id||r.name.empty()||!finite(r.min)||!finite(r.max)||r.min.x>=r.max.x||r.min.y>r.max.y||r.min.z>=r.max.z)return false;for(std::size_t j=i+1;j<rooms.size();++j)if(r.id==rooms[j].id)return false;}for(std::size_t i=0;i<openings.size();++i){if(!openings[i].valid())return false;for(std::size_t j=i+1;j<openings.size();++j)if(openings[i].id==openings[j].id)return false;}for(const auto&i:interactables){if(!i.valid())return false;if(i.type!=BuildingInteractableType::LightSwitch&&!std::any_of(openings.begin(),openings.end(),[&](const auto&o){return o.id==i.target_id;}))return false;}for(const auto&f:furniture)if(!f.valid()||!std::any_of(rooms.begin(),rooms.end(),[&](const auto&r){return r.id==f.room_id;}))return false;for(std::size_t i=0;i<collision.size();++i){if(!collision[i].valid())return false;for(std::size_t j=i+1;j<collision.size();++j)if(collision[i].id==collision[j].id)return false;if(collision[i].door_id&&!std::any_of(openings.begin(),openings.end(),[&](const auto&o){return o.id==collision[i].door_id&&o.type==BuildingOpeningType::Door;}))return false;}return true; }

BuildingDefinition generate_building(const BuildingConfig& input){const auto c=normalize(input);BuildingDefinition b;b.seed=c.seed;b.config=c;std::uint64_t next_collision=1,next_opening=1,next_interactable=1,next_furniture=1;const float inner_w=c.width-2*c.wall_thickness,inner_d=c.depth-2*c.wall_thickness;if(inner_w<=0||inner_d<=0)return b;const auto rows=make_rows(c.rooms_per_floor,inner_d);for(std::uint32_t floor=0;floor<c.floors;++floor){const float base=floor*c.floor_height,mid=base+c.floor_height*.5f;add_box(b.geometry,"floor_"+std::to_string(floor),{c.width,c.floor_thickness,c.depth},c.floor_material,{0,base+c.floor_thickness*.5f,0});b.collision.push_back({next_collision++,{-c.width*.5f,base,-c.depth*.5f},{c.width*.5f,base+c.floor_thickness,c.depth*.5f},0});if(floor+1==c.floors)add_box(b.geometry,"roof",{c.width,c.floor_thickness,c.depth},c.floor_material,{0,base+c.floor_height-c.floor_thickness*.5f,0});
        std::vector<std::vector<float>> row_boundaries(rows.size());std::uint32_t room_index=0;for(std::uint32_t row=0;row<rows.size();++row){const auto count=rows[row].count;const float w=inner_w/static_cast<float>(count);for(std::uint32_t col=0;col<count;++col){const float min_x=-inner_w*.5f+col*w,max_x=min_x+w;const float min_z=rows[row].min_z,max_z=rows[row].max_z;const auto rid=stable_id(c.seed,0x1000ULL,(static_cast<std::uint64_t>(floor)<<32U)|room_index);BuildingRoom room{rid,floor,"room_"+std::to_string(floor)+"_"+std::to_string(room_index),{min_x,base,min_z},{max_x,base+c.floor_height,max_z},{(min_x+max_x)*.5f,mid,(min_z+max_z)*.5f}};b.rooms.push_back(room);add_furniture(b,c,room,c.furniture_density,stable_id(c.seed,0x2000ULL,(static_cast<std::uint64_t>(floor)<<32U)|room_index),next_furniture);const auto light_id=next_interactable++;b.interactables.push_back({light_id,BuildingInteractableType::LightSwitch,light_id,{room.min.x+.16f,base+1.2f,room.center.z},true});++room_index;}
            for(std::uint32_t col=1;col<count;++col){const float x=-inner_w*.5f+col*(inner_w/static_cast<float>(count));const float local_center=rows[row].min_z+rows[row].max_z;const float door_center=rows[row].min_z+(rows[row].max_z-rows[row].min_z)*(.5f+.12f*(unit(stable_id(c.seed,0x3000ULL,(static_cast<std::uint64_t>(floor)<<24U)|(static_cast<std::uint64_t>(row)<<12U)|col))-.5f));add_z_wall(b.geometry,b.collision,c.wall_material,"partition_x"+std::to_string(floor)+"_"+std::to_string(row)+"_"+std::to_string(col),x,mid,rows[row].max_z-rows[row].min_z,c.wall_thickness,c.floor_height,{{door_center-local_center*.5f,c.door_width}},next_collision);const auto did=next_opening++;const Vec3 p{x,base+c.door_height*.5f,door_center};add_box(b.geometry,"door_"+std::to_string(did),{c.wall_thickness*.8f,c.door_height,c.door_width},c.door_material,p);b.openings.push_back({did,BuildingOpeningType::Door,floor,BuildingWallAxis::Z,p,{c.wall_thickness,c.door_height,c.door_width},false,false});b.interactables.push_back({next_interactable++,BuildingInteractableType::Door,did,{x,base+1,door_center},true});b.collision.push_back({next_collision++,{x-c.wall_thickness*.45f,base,door_center-c.door_width*.5f},{x+c.wall_thickness*.45f,base+c.door_height,door_center+c.door_width*.5f},did});}
        }
        for(std::size_t row=1;row<rows.size();++row){std::vector<Gap> gaps;float span_count=rows[row-1].count+rows[row].count;for(std::uint32_t k=0;k<rows[row].count;++k){const float x=-inner_w*.5f+(static_cast<float>(k)+.5f)*(inner_w/static_cast<float>(rows[row].count));gaps.push_back({x,c.door_width});}const float z=rows[row].min_z;add_x_wall(b.geometry,b.collision,c.wall_material,"partition_z"+std::to_string(floor)+"_"+std::to_string(row),z,mid,inner_w,c.wall_thickness,c.floor_height,gaps,next_collision);(void)span_count;}
        const auto entrance=floor==0?std::vector<Gap>{{0,c.door_width}}:std::vector<Gap>{};add_x_wall(b.geometry,b.collision,c.wall_material,"south_"+std::to_string(floor),-c.depth*.5f+c.wall_thickness*.5f,mid,inner_w,c.wall_thickness,c.floor_height,entrance,next_collision);add_x_wall(b.geometry,b.collision,c.wall_material,"north_"+std::to_string(floor),c.depth*.5f-c.wall_thickness*.5f,mid,inner_w,c.wall_thickness,c.floor_height,{},next_collision);add_z_wall(b.geometry,b.collision,c.wall_material,"west_"+std::to_string(floor),-c.width*.5f+c.wall_thickness*.5f,mid,inner_d,c.wall_thickness,c.floor_height,{},next_collision);add_z_wall(b.geometry,b.collision,c.wall_material,"east_"+std::to_string(floor),c.width*.5f-c.wall_thickness*.5f,mid,inner_d,c.wall_thickness,c.floor_height,{},next_collision);
        if(floor==0){const auto did=next_opening++;const Vec3 p{0,base+c.door_height*.5f,-c.depth*.5f+c.wall_thickness*.5f};add_box(b.geometry,"entrance_door",{c.door_width,c.door_height,c.wall_thickness*.8f},c.door_material,p);b.openings.push_back({did,BuildingOpeningType::Door,0,BuildingWallAxis::X,p,{c.door_width,c.door_height,c.wall_thickness},false,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Door,did,{0,base+1,-c.depth*.5f+c.wall_thickness},true});b.collision.push_back({next_collision++,{p.x-c.door_width*.5f,p.y-c.door_height*.5f,p.z-c.wall_thickness*.45f},{p.x+c.door_width*.5f,p.y+c.door_height*.5f,p.z+c.wall_thickness*.45f},did});}
        add_windows(b,c,floor,base,next_opening,next_interactable);
        if(floor+1<c.floors){const float stair_run=std::clamp(c.floor_height*1.4f,.3f,inner_d*.45f);const std::uint32_t steps=std::max(4U,static_cast<std::uint32_t>(std::ceil(c.floor_height/.22f)));const float depth=stair_run/static_cast<float>(steps);for(std::uint32_t s=0;s<steps;++s){const float h=c.floor_height*(static_cast<float>(s+1)/static_cast<float>(steps));const float z=inner_d*.22f+s*depth;const Vec3 p{inner_w*.18f,h*.5f+base,z};add_box(b.geometry,"stair_"+std::to_string(floor)+"_"+std::to_string(s),{c.stair_width,h,depth},c.floor_material,p);b.collision.push_back({next_collision++,{p.x-c.stair_width*.5f,base,p.z-depth*.5f},{p.x+c.stair_width*.5f,base+h,p.z+depth*.5f},0});}}
    }
    return b; }

bool set_building_door_open(BuildingDefinition& b,std::uint64_t id,bool open) noexcept { for(auto&d:b.openings)if(d.id==id&&d.type==BuildingOpeningType::Door){d.open=open;return true;}return false; }
const BuildingOpening* find_building_door(const BuildingDefinition&b,std::uint64_t id) noexcept { for(const auto&d:b.openings)if(d.id==id&&d.type==BuildingOpeningType::Door)return &d;return nullptr; }
std::vector<BuildingCollisionVolume> active_building_collision(const BuildingDefinition&b){std::vector<BuildingCollisionVolume> out;out.reserve(b.collision.size());for(const auto&c:b.collision){if(c.door_id){const auto*d=find_building_door(b,c.door_id);if(d&&d->open)continue;}out.push_back(c);}return out;}
const BuildingRoom* find_building_room(const BuildingDefinition&b,Vec3 position) noexcept {for(const auto&r:b.rooms)if(r.contains(position.x,position.y,position.z))return &r;return nullptr;}

} // namespace exgine
