#include "exgine/building.hpp"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <limits>
#include <string>
#include <utility>
#include <vector>
namespace exgine { namespace {
std::uint64_t mix64(std::uint64_t value) noexcept { value += 0x9e3779b97f4a7c15ULL; value = (value ^ (value >> 30U)) * 0xbf58476d1ce4e5b9ULL; value = (value ^ (value >> 27U)) * 0x94d049bb133111ebULL; return value ^ (value >> 31U); }
float unit(std::uint64_t value) noexcept { return static_cast<float>(mix64(value) >> 40U) / static_cast<float>(1U << 24U); }
bool finite(float value) noexcept { return std::isfinite(value); }
bool finite3(Vec3 value) noexcept { return finite(value.x) && finite(value.y) && finite(value.z); }
void add_box(MeshAssembly& assembly, std::string name, Vec3 size, const std::string& material, Vec3 position) { if (size.x <= 0.0f || size.y <= 0.0f || size.z <= 0.0f || material.empty()) return; MeshPart part{std::move(name), make_box({size}), material, position, {1.0f,1.0f,1.0f}}; if (part.mesh.valid()) assembly.parts.push_back(std::move(part)); }
struct Gap { float center=0.0f; float width=0.0f; };
void add_x_wall(MeshAssembly& a,std::vector<BuildingCollisionVolume>& c,const std::string& m,const std::string& p,float z,float y,float len,float th,float h,std::vector<Gap> gaps,std::uint64_t& next){std::sort(gaps.begin(),gaps.end(),[](const auto&x,const auto&y){return x.center<y.center;});const float left=-len*.5f,right=len*.5f;float cur=left;for(const auto&g:gaps){const float s=std::clamp(g.center-g.width*.5f,left,right),e=std::clamp(g.center+g.width*.5f,left,right);if(s>cur+1e-4f){const float w=s-cur;const Vec3 q{(cur+s)*.5f,y,z};add_box(a,p+"_segment",{w,h,th},m,q);c.push_back({next++,{q.x-w*.5f,y-h*.5f,z-th*.5f},{q.x+w*.5f,y+h*.5f,z+th*.5f},0});}cur=std::max(cur,e);}if(cur<right-1e-4f){const float w=right-cur;const Vec3 q{(cur+right)*.5f,y,z};add_box(a,p+"_segment",{w,h,th},m,q);c.push_back({next++,{q.x-w*.5f,y-h*.5f,z-th*.5f},{q.x+w*.5f,y+h*.5f,z+th*.5f},0});}}
void add_z_wall(MeshAssembly& a,std::vector<BuildingCollisionVolume>& c,const std::string& m,const std::string& p,float x,float y,float len,float th,float h,std::vector<Gap> gaps,std::uint64_t& next){std::sort(gaps.begin(),gaps.end(),[](const auto&x,const auto&y){return x.center<y.center;});const float near=-len*.5f,far=len*.5f;float cur=near;for(const auto&g:gaps){const float s=std::clamp(g.center-g.width*.5f,near,far),e=std::clamp(g.center+g.width*.5f,near,far);if(s>cur+1e-4f){const float w=s-cur;const Vec3 q{x,y,(cur+s)*.5f};add_box(a,p+"_segment",{th,h,w},m,q);c.push_back({next++,{x-th*.5f,y-h*.5f,q.z-w*.5f},{x+th*.5f,y+h*.5f,q.z+w*.5f},0});}cur=std::max(cur,e);}if(cur<far-1e-4f){const float w=far-cur;const Vec3 q{x,y,(cur+far)*.5f};add_box(a,p+"_segment",{th,h,w},m,q);c.push_back({next++,{x-th*.5f,y-h*.5f,q.z-w*.5f},{x+th*.5f,y+h*.5f,q.z+w*.5f},0});}}
std::uint32_t grid_columns(std::uint32_t rooms) noexcept { return std::max(1U, static_cast<std::uint32_t>(std::ceil(std::sqrt(static_cast<float>(rooms))))); }
}
bool BuildingRoom::contains(float x,float y,float z)const noexcept{return x>=min.x&&x<=max.x&&y>=min.y&&y<=max.y&&z>=min.z&&z<=max.z;}
bool BuildingOpening::valid()const noexcept{return id!=0&&finite3(position)&&finite3(size)&&size.x>0&&size.y>0&&size.z>0;}
bool BuildingInteractable::valid()const noexcept{return id!=0&&target_id!=0&&finite3(position)&&(type!=BuildingInteractableType::LightSwitch||target_id==id);}
bool BuildingFurniture::valid()const noexcept{return id!=0&&room_id!=0&&finite3(position)&&finite3(size)&&size.x>0&&size.y>0&&size.z>0&&finite(rotation);}
bool BuildingCollisionVolume::valid()const noexcept{return id!=0&&finite3(min)&&finite3(max)&&min.x<=max.x&&min.y<=max.y&&min.z<=max.z;}
bool BuildingDefinition::valid()const noexcept{
 if(seed==0||!geometry.valid()||rooms.empty())return false;
 for(std::size_t i=0;i<rooms.size();++i){const auto&r=rooms[i];if(r.id==0||r.name.empty()||!finite3(r.min)||!finite3(r.max)||r.min.x>=r.max.x||r.min.y>r.max.y||r.min.z>=r.max.z)return false;for(std::size_t j=i+1;j<rooms.size();++j)if(r.id==rooms[j].id)return false;}
 for(std::size_t i=0;i<openings.size();++i){if(!openings[i].valid())return false;for(std::size_t j=i+1;j<openings.size();++j)if(openings[i].id==openings[j].id)return false;}
 for(std::size_t i=0;i<interactables.size();++i){if(!interactables[i].valid())return false;for(std::size_t j=i+1;j<interactables.size();++j)if(interactables[i].id==interactables[j].id)return false;if(interactables[i].type!=BuildingInteractableType::LightSwitch&&!std::any_of(openings.begin(),openings.end(),[&](const BuildingOpening&o){return o.id==interactables[i].target_id;}))return false;}
 for(const auto&f:furniture){if(!f.valid()||!std::any_of(rooms.begin(),rooms.end(),[&](const BuildingRoom&r){return r.id==f.room_id;}))return false;}
 for(std::size_t i=0;i<collision.size();++i){if(!collision[i].valid())return false;for(std::size_t j=i+1;j<collision.size();++j)if(collision[i].id==collision[j].id)return false;if(collision[i].door_id&&!std::any_of(openings.begin(),openings.end(),[&](const BuildingOpening&o){return o.id==collision[i].door_id&&o.type==BuildingOpeningType::Door;}))return false;}
 return true;
}
BuildingDefinition generate_building(const BuildingConfig& input){
 BuildingConfig c=input;c.width=std::max(c.width,4.0f);c.depth=std::max(c.depth,4.0f);c.floors=std::clamp(c.floors,1U,32U);c.floor_height=std::max(c.floor_height,2.4f);c.wall_thickness=std::clamp(c.wall_thickness,.05f,.6f);c.floor_thickness=std::clamp(c.floor_thickness,.05f,.5f);c.rooms_per_floor=std::clamp(c.rooms_per_floor,1U,16U);c.door_width=std::clamp(c.door_width,.6f,std::min(1.6f,c.width*.25f));c.door_height=std::clamp(c.door_height,1.8f,c.floor_height-.2f);c.window_width=std::clamp(c.window_width,.5f,c.width*.35f);c.window_height=std::clamp(c.window_height,.6f,c.floor_height*.5f);c.windows_per_wall=std::clamp(c.windows_per_wall,0U,6U);c.stair_width=std::clamp(c.stair_width,.7f,std::min(c.width,c.depth)*.45f);c.furniture_density=std::clamp(c.furniture_density,0U,5U);
 BuildingDefinition b;b.seed=c.seed?c.seed:1;b.config=c;std::uint64_t next_collision=1,next_opening=1,next_interactable=1,next_furniture=1;const auto seed=mix64(b.seed);const auto columns=grid_columns(c.rooms_per_floor);const auto rows=static_cast<std::uint32_t>(std::ceil(static_cast<float>(c.rooms_per_floor)/static_cast<float>(columns)));const float inner_width=c.width-2*c.wall_thickness,inner_depth=c.depth-2*c.wall_thickness,room_width=inner_width/static_cast<float>(columns),room_depth=inner_depth/static_cast<float>(rows);
 for(std::uint32_t floor=0;floor<c.floors;++floor){const float base=static_cast<float>(floor)*c.floor_height,mid=base+c.floor_height*.5f;add_box(b.geometry,"floor_"+std::to_string(floor),{c.width,c.floor_thickness,c.depth},c.floor_material,{0,base+c.floor_thickness*.5f,0});b.collision.push_back({next_collision++,{-c.width*.5f,base,-c.depth*.5f},{c.width*.5f,base+c.floor_thickness,c.depth*.5f},0});if(floor+1==c.floors)add_box(b.geometry,"roof",{c.width,c.floor_thickness,c.depth},c.floor_material,{0,base+c.floor_height-c.floor_thickness*.5f,0});
  for(std::uint32_t ri=0;ri<c.rooms_per_floor;++ri){const auto row=ri/columns,col=ri%columns;const float min_x=-inner_width*.5f+static_cast<float>(col)*room_width,max_x=min_x+room_width,min_z=-inner_depth*.5f+static_cast<float>(row)*room_depth,max_z=min_z+room_depth;const auto room_id=mix64(seed^(static_cast<std::uint64_t>(floor)<<32U)^ri);BuildingRoom room{room_id,floor,"room_"+std::to_string(floor)+"_"+std::to_string(ri),{min_x,base,min_z},{max_x,base+c.floor_height,max_z},{(min_x+max_x)*.5f,mid,(min_z+max_z)*.5f}};b.rooms.push_back(room);if(c.furniture_density&&room_width>2.4f&&room_depth>2.4f){const float jx=(unit(room_id^0x11ULL)-.5f)*room_width*.1f,jz=(unit(room_id^0x17ULL)-.5f)*room_depth*.1f;const auto count=std::min(c.furniture_density,3U);if(count>=1)b.furniture.push_back({next_furniture++,BuildingFurnitureType::Bed,room_id,{room.center.x+jx,base+.28f,room.max.z-.75f},{1.7f,.5f,.9f},0});if(count>=2)b.furniture.push_back({next_furniture++,BuildingFurnitureType::Desk,room_id,{room.center.x-room_width*.22f,base+.55f,room.center.z+jz},{1.1f,.12f,.55f},0});if(count>=3)b.furniture.push_back({next_furniture++,BuildingFurnitureType::Chair,room_id,{room.center.x-room_width*.22f,base+.45f,room.center.z+.55f},{.45f,.9f,.45f},0});}b.interactables.push_back({next_interactable++,BuildingInteractableType::LightSwitch,next_interactable-1,{room.min.x+.15f,base+1.2f,room.center.z},true});}
  for(std::uint32_t col=1;col<columns;++col)for(std::uint32_t row=0;row<rows;++row){const auto left_room=row*columns+col-1;if(left_room+1>=c.rooms_per_floor)continue;const float x=-inner_width*.5f+static_cast<float>(col)*room_width,z0=-inner_depth*.5f+static_cast<float>(row)*room_depth,z1=z0+room_depth,center=z0+room_depth*(.3f+unit(seed^floor^(static_cast<std::uint64_t>(col)<<8U)^row)*.4f);add_z_wall(b.geometry,b.collision,c.wall_material,"partition_x",x,mid,room_depth,c.wall_thickness,c.floor_height,{{center-(z0+z1)*.5f,c.door_width}},next_collision);const auto door=next_opening++;add_box(b.geometry,"door_"+std::to_string(door),{c.wall_thickness*.8f,c.door_height,c.door_width},c.door_material,{x,base+c.door_height*.5f,center});b.openings.push_back({door,BuildingOpeningType::Door,floor,BuildingWallAxis::Z,{x,base+c.door_height*.5f,center},{c.wall_thickness,c.door_height,c.door_width},false,false});b.interactables.push_back({next_interactable++,BuildingInteractableType::Door,door,{x,base+1,center},true});b.collision.push_back({next_collision++,{x-c.wall_thickness*.45f,base,center-c.door_width*.5f},{x+c.wall_thickness*.45f,base+c.door_height,center+c.door_width*.5f},door});}
  for(std::uint32_t row=1;row<rows;++row)for(std::uint32_t col=0;col<columns;++col){const auto lower=(row-1)*columns+col;if(lower+columns>=c.rooms_per_floor)continue;const float z=-inner_depth*.5f+static_cast<float>(row)*room_depth,x0=-inner_width*.5f+static_cast<float>(col)*room_width,x1=x0+room_width,center=x0+room_width*(.3f+unit(seed^row^(static_cast<std::uint64_t>(col)<<8U)^floor)*.4f);add_x_wall(b.geometry,b.collision,c.wall_material,"partition_z",z,mid,room_width,c.wall_thickness,c.floor_height,{{center-(x0+x1)*.5f,c.door_width}},next_collision);const auto door=next_opening++;add_box(b.geometry,"door_"+std::to_string(door),{c.door_width,c.door_height,c.wall_thickness*.8f},c.door_material,{center,base+c.door_height*.5f,z});b.openings.push_back({door,BuildingOpeningType::Door,floor,BuildingWallAxis::X,{center,base+c.door_height*.5f,z},{c.door_width,c.door_height,c.wall_thickness},false,false});b.interactables.push_back({next_interactable++,BuildingInteractableType::Door,door,{center,base+1,z},true});b.collision.push_back({next_collision++,{center-c.door_width*.5f,base,z-c.wall_thickness*.45f},{center+c.door_width*.5f,base+c.door_height,z+c.wall_thickness*.45f},door});}
  const std::vector<Gap> entrance=floor==0?std::vector<Gap>{{0,c.door_width}}:std::vector<Gap>{};add_x_wall(b.geometry,b.collision,c.wall_material,"south",-c.depth*.5f+c.wall_thickness*.5f,mid,c.width-2*c.wall_thickness,c.wall_thickness,c.floor_height,entrance,next_collision);add_x_wall(b.geometry,b.collision,c.wall_material,"north",c.depth*.5f-c.wall_thickness*.5f,mid,c.width-2*c.wall_thickness,c.wall_thickness,c.floor_height,{},next_collision);add_z_wall(b.geometry,b.collision,c.wall_material,"west",-c.width*.5f+c.wall_thickness*.5f,mid,c.depth-2*c.wall_thickness,c.wall_thickness,c.floor_height,{},next_collision);add_z_wall(b.geometry,b.collision,c.wall_material,"east",c.width*.5f-c.wall_thickness*.5f,mid,c.depth-2*c.wall_thickness,c.wall_thickness,c.floor_height,{},next_collision);
  if(floor==0){const auto door=next_opening++;const Vec3 p{0,c.door_height*.5f,-c.depth*.5f+c.wall_thickness*.5f};add_box(b.geometry,"door_"+std::to_string(door),{c.door_width,c.door_height,c.wall_thickness*.8f},c.door_material,p);b.openings.push_back({door,BuildingOpeningType::Door,0,BuildingWallAxis::X,p,{c.door_width,c.door_height,c.wall_thickness},false,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Door,door,{0,1,-c.depth*.5f},true});b.collision.push_back({next_collision++,{-c.door_width*.5f,0,-c.depth*.5f},{c.door_width*.5f,c.door_height,-c.depth*.5f+c.wall_thickness},door});}
  for(std::uint32_t w=0;w<c.windows_per_wall;++w){const float t=(w+1.f)/(c.windows_per_wall+1.f),x=-inner_width*.5f+t*inner_width,wy=base+c.floor_height*.55f;const Vec3 north{x,wy,c.depth*.5f-c.wall_thickness*.7f},south{x,wy,-c.depth*.5f+c.wall_thickness*.7f};add_box(b.geometry,"window_n_"+std::to_string(w),{c.window_width,c.window_height,.04f},c.glass_material,north);add_box(b.geometry,"window_s_"+std::to_string(w),{c.window_width,c.window_height,.04f},c.glass_material,south);const auto wn=next_opening++,ws=next_opening++;b.openings.push_back({wn,BuildingOpeningType::Window,floor,BuildingWallAxis::X,north,{c.window_width,c.window_height,.04f},false,true});b.openings.push_back({ws,BuildingOpeningType::Window,floor,BuildingWallAxis::X,south,{c.window_width,c.window_height,.04f},false,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Window,wn,north,true});b.interactables.push_back({next_interactable++,BuildingInteractableType::Window,ws,south,true});}
 }
 if(c.floors>1){const auto steps=std::max(10U,static_cast<std::uint32_t>(std::ceil(c.floor_height/.2f)));for(std::uint32_t floor=0;floor+1<c.floors;++floor)for(std::uint32_t step=0;step<steps;++step){const float t=(step+1.f)/steps,z=c.depth*.10f+(t-.5f)*c.stair_width*2.2f,x=c.width*.27f,y=floor*c.floor_height+.1f+t*(c.floor_height-.2f)*.5f;add_box(b.geometry,"stair_"+std::to_string(floor)+"_"+std::to_string(step),{c.stair_width,.2f,c.stair_width*.48f},c.floor_material,{x,y,z});b.collision.push_back({next_collision++,{x-c.stair_width*.5f,floor*c.floor_height,z-c.stair_width*.24f},{x+c.stair_width*.5f,floor*c.floor_height+c.floor_height*t,z+c.stair_width*.24f},0});}}
 for(const auto&f:b.furniture){if(f.type==BuildingFurnitureType::Bed){add_box(b.geometry,"bed_"+std::to_string(f.id),f.size,c.furniture_material,f.position);add_box(b.geometry,"pillow_"+std::to_string(f.id),{f.size.x*.35f,f.size.y*.2f,f.size.z*.45f},c.furniture_material,{f.position.x,f.position.y+f.size.y*.58f,f.position.z+f.size.z*.2f});}else add_box(b.geometry,"furniture_"+std::to_string(f.id),f.size,c.furniture_material,f.position);}
 add_box(b.geometry,"foundation",{c.width,.3f,c.depth},c.wall_material,{0,-.15f,0});b.collision.push_back({next_collision++,{-c.width*.5f,-.3f,-c.depth*.5f},{c.width*.5f,0,c.depth*.5f},0});return b;
}
bool set_building_door_open(BuildingDefinition&b,std::uint64_t id,bool open)noexcept{for(auto&o:b.openings)if(o.id==id&&o.type==BuildingOpeningType::Door){o.open=open;return true;}return false;}
const BuildingOpening* find_building_door(const BuildingDefinition&b,std::uint64_t id)noexcept{for(const auto&o:b.openings)if(o.id==id&&o.type==BuildingOpeningType::Door)return &o;return nullptr;}
std::vector<BuildingCollisionVolume> active_building_collision(const BuildingDefinition&b){std::vector<BuildingCollisionVolume> out;out.reserve(b.collision.size());for(const auto&v:b.collision){if(v.door_id){const auto*d=find_building_door(b,v.door_id);if(d&&d->open)continue;}out.push_back(v);}return out;}
const BuildingRoom* find_building_room(const BuildingDefinition&b,Vec3 p)noexcept{for(const auto&r:b.rooms)if(r.contains(p.x,p.y,p.z))return &r;return nullptr;}
} // namespace exgine
