#include "exgine/building.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <utility>
namespace exgine { namespace {
std::uint64_t mix64(std::uint64_t x) noexcept{x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30U))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27U))*0x94d049bb133111ebULL;return x^(x>>31U);}
float unit(std::uint64_t x) noexcept{return static_cast<float>(mix64(x)>>40U)/static_cast<float>(1U<<24U);}
bool finite(float x) noexcept{return std::isfinite(x);} bool finite3(Vec3 v) noexcept{return finite(v.x)&&finite(v.y)&&finite(v.z);}
void add_box(MeshAssembly& g,std::string name,Vec3 size,const std::string& material,Vec3 position){if(size.x>0&&size.y>0&&size.z>0&&!material.empty())g.parts.push_back({std::move(name),make_box({size}),material,position,{1,1,1}});}
struct Gap{float center=0,width=0;};
void wall_x(MeshAssembly&g,std::vector<BuildingCollisionVolume>&c,const std::string&m,std::string p,float z,float y,float len,float th,float h,std::vector<Gap> gaps,std::uint64_t& id){std::sort(gaps.begin(),gaps.end(),[](const auto&a,const auto&b){return a.center<b.center;});float cur=-len*.5f;for(const auto&gap:gaps){float s=std::clamp(gap.center-gap.width*.5f,-len*.5f,len*.5f),e=std::clamp(gap.center+gap.width*.5f,-len*.5f,len*.5f);if(s>cur+1e-4f){float w=s-cur;Vec3 q{(cur+s)*.5f,y,z};add_box(g,p+"_segment",{w,h,th},m,q);c.push_back({id++,{q.x-w*.5f,y-h*.5f,z-th*.5f},{q.x+w*.5f,y+h*.5f,z+th*.5f},0});}cur=std::max(cur,e);}if(cur<len*.5f-1e-4f){float w=len*.5f-cur;Vec3 q{(cur+len*.5f)*.5f,y,z};add_box(g,p+"_segment",{w,h,th},m,q);c.push_back({id++,{q.x-w*.5f,y-h*.5f,z-th*.5f},{q.x+w*.5f,y+h*.5f,z+th*.5f},0});}}
void wall_z(MeshAssembly&g,std::vector<BuildingCollisionVolume>&c,const std::string&m,std::string p,float x,float y,float len,float th,float h,std::vector<Gap> gaps,std::uint64_t& id){std::sort(gaps.begin(),gaps.end(),[](const auto&a,const auto&b){return a.center<b.center;});float cur=-len*.5f;for(const auto&gap:gaps){float s=std::clamp(gap.center-gap.width*.5f,-len*.5f,len*.5f),e=std::clamp(gap.center+gap.width*.5f,-len*.5f,len*.5f);if(s>cur+1e-4f){float w=s-cur;Vec3 q{x,y,(cur+s)*.5f};add_box(g,p+"_segment",{th,h,w},m,q);c.push_back({id++,{x-th*.5f,y-h*.5f,q.z-w*.5f},{x+th*.5f,y+h*.5f,q.z+w*.5f},0});}cur=std::max(cur,e);}if(cur<len*.5f-1e-4f){float w=len*.5f-cur;Vec3 q{x,y,(cur+len*.5f)*.5f};add_box(g,p+"_segment",{th,h,w},m,q);c.push_back({id++,{x-th*.5f,y-h*.5f,q.z-w*.5f},{x+th*.5f,y+h*.5f,q.z+w*.5f},0});}}
std::uint32_t columns(std::uint32_t n)noexcept{return std::max(1U,static_cast<std::uint32_t>(std::ceil(std::sqrt(static_cast<float>(n)))));}
void add_furniture(BuildingDefinition&b,const BuildingFurniture&f){add_box(b.geometry,"furniture_"+std::to_string(f.id),f.size,b.config.furniture_material,f.position);if(f.type==BuildingFurnitureType::Bed)add_box(b.geometry,"pillow_"+std::to_string(f.id),{f.size.x*.35f,f.size.y*.2f,f.size.z*.45f},b.config.furniture_material,{f.position.x,f.position.y+f.size.y*.58f,f.position.z+f.size.z*.2f});}
}
bool BuildingRoom::contains(float x,float y,float z)const noexcept{return x>=min.x&&x<=max.x&&y>=min.y&&y<=max.y&&z>=min.z&&z<=max.z;}
bool BuildingOpening::valid()const noexcept{return id!=0&&finite3(position)&&finite3(size)&&size.x>0&&size.y>0&&size.z>0;}
bool BuildingInteractable::valid()const noexcept{return id!=0&&target_id!=0&&finite3(position);}
bool BuildingFurniture::valid()const noexcept{return id!=0&&room_id!=0&&finite3(position)&&finite3(size)&&size.x>0&&size.y>0&&size.z>0&&finite(rotation);}
bool BuildingCollisionVolume::valid()const noexcept{return id!=0&&finite3(min)&&finite3(max)&&min.x<=max.x&&min.y<=max.y&&min.z<=max.z;}
bool BuildingDefinition::valid()const noexcept{if(seed==0||!geometry.valid()||rooms.empty())return false;for(const auto&r:rooms)if(r.id==0||r.name.empty()||!finite3(r.min)||!finite3(r.max)||r.min.x>=r.max.x||r.min.z>=r.max.z)return false;for(const auto&o:openings)if(!o.valid())return false;for(const auto&i:interactables)if(!i.valid())return false;for(const auto&f:furniture)if(!f.valid())return false;for(const auto&v:collision)if(!v.valid())return false;return true;}
BuildingDefinition generate_building(const BuildingConfig&input){BuildingConfig c=input;c.width=std::max(c.width,4.f);c.depth=std::max(c.depth,4.f);c.floors=std::clamp(c.floors,1U,32U);c.floor_height=std::max(c.floor_height,2.4f);c.wall_thickness=std::clamp(c.wall_thickness,.05f,.6f);c.floor_thickness=std::clamp(c.floor_thickness,.05f,.5f);c.rooms_per_floor=std::clamp(c.rooms_per_floor,1U,16U);c.door_width=std::clamp(c.door_width,.6f,std::min(1.6f,c.width*.25f));c.door_height=std::clamp(c.door_height,1.8f,c.floor_height-.2f);c.window_width=std::clamp(c.window_width,.5f,c.width*.35f);c.window_height=std::clamp(c.window_height,.6f,c.floor_height*.5f);c.windows_per_wall=std::clamp(c.windows_per_wall,0U,6U);c.stair_width=std::clamp(c.stair_width,.7f,std::min(c.width,c.depth)*.45f);c.furniture_density=std::clamp(c.furniture_density,0U,5U);BuildingDefinition o;o.seed=c.seed?c.seed:1;o.config=c;std::uint64_t cid=1,iid=1,fid=1;const auto nc=columns(c.rooms_per_floor),nr=static_cast<std::uint32_t>(std::ceil(static_cast<float>(c.rooms_per_floor)/nc));const float iw=c.width-2*c.wall_thickness,id=c.depth-2*c.wall_thickness,rw=iw/nc,rd=id/nr,bs=mix64(o.seed);
for(std::uint32_t fl=0;fl<c.floors;++fl){float base=fl*c.floor_height;add_box(o.geometry,"floor_"+std::to_string(fl),{c.width,c.floor_thickness,c.depth},c.floor_material,{0,base+c.floor_thickness*.5f,0});if(fl+1==c.floors)add_box(o.geometry,"roof",{c.width,c.floor_thickness,c.depth},c.floor_material,{0,base+c.floor_height-c.floor_thickness*.5f,0});for(std::uint32_t ri=0;ri<c.rooms_per_floor;++ri){auto row=ri/nc,col=ri%nc;float minx=-iw*.5f+col*rw,maxx=minx+rw,minz=-id*.5f+row*rd,maxz=minz+rd;auto rid=mix64(bs^(static_cast<std::uint64_t>(fl)<<32U)^ri);o.rooms.push_back({rid,fl,"room_"+std::to_string(fl)+"_"+std::to_string(ri),{minx,base,minz},{maxx,base+c.floor_height,maxz},{(minx+maxx)*.5f,base+c.floor_height*.5f,(minz+maxz)*.5f}});for(std::uint32_t k=0;k<std::min(c.furniture_density,3U);++k){auto t=k==0?BuildingFurnitureType::Bed:(k==1?BuildingFurnitureType::Desk:BuildingFurnitureType::Chair);Vec3 p=o.rooms.back().center;if(k==0){p.z=maxz-.75f;p.y=base+.28f;}else if(k==1){p.x-=rw*.22f;p.y=base+.55f;}else{p.x-=rw*.22f;p.z+=.55f;p.y=base+.45f;}o.furniture.push_back({fid++,t,rid,p,k==0?Vec3{1.7f,.5f,.9f}:(k==1?Vec3{1.1f,.12f,.55f}:Vec3{.45f,.9f,.45f}),0});}}
for(std::uint32_t col=1;col<nc;++col)for(std::uint32_t row=0;row<nr;++row){auto left=row*nc+col-1;if(left+1>=c.rooms_per_floor)continue;float x=-iw*.5f+col*rw,z0=-id*.5f+row*rd,z1=z0+rd,dc=z0+rd*(.35f+unit(bs^fl^(static_cast<std::uint64_t>(col)<<8U)^row)*.3f);wall_z(o.geometry,o.collision,c.wall_material,"partition_x",x,base+c.floor_height*.5f,z1-z0,c.wall_thickness,c.floor_height,{{dc-(z0+z1)*.5f,c.door_width}},cid);auto did=mix64(bs^0xD001ULL^fl^(static_cast<std::uint64_t>(col)<<16U)^row);o.openings.push_back({did,BuildingOpeningType::Door,fl,BuildingWallAxis::Z,{x,base+c.door_height*.5f,dc},{c.wall_thickness,c.door_height,c.door_width},false,false});o.interactables.push_back({iid++,BuildingInteractableType::Door,did,{x,base+1,dc},true});o.collision.push_back({cid++,{x-c.wall_thickness*.5f,base,dc-c.door_width*.5f},{x+c.wall_thickness*.5f,base+c.floor_height,dc+c.door_width*.5f},did});}
for(std::uint32_t row=1;row<nr;++row)for(std::uint32_t col=0;col<nc;++col){auto lower=(row-1)*nc+col;if(lower+nc>=c.rooms_per_floor)continue;float z=-id*.5f+row*rd,x0=-iw*.5f+col*rw,x1=x0+rw,dc=x0+rw*(.35f+unit(bs^row^(static_cast<std::uint64_t>(col)<<8U)^fl)*.3f);wall_x(o.geometry,o.collision,c.wall_material,"partition_z",z,base+c.floor_height*.5f,x1-x0,c.wall_thickness,c.floor_height,{{dc-(x0+x1)*.5f,c.door_width}},cid);auto did=mix64(bs^0xD00EULL^fl^(static_cast<std::uint64_t>(row)<<16U)^col);o.openings.push_back({did,BuildingOpeningType::Door,fl,BuildingWallAxis::X,{dc,base+c.door_height*.5f,z},{c.door_width,c.door_height,c.wall_thickness},false,false});o.interactables.push_back({iid++,BuildingInteractableType::Door,did,{dc,base+1,z},true});o.collision.push_back({cid++,{dc-c.door_width*.5f,base,z-c.wall_thickness*.5f},{dc+c.door_width*.5f,base+c.floor_height,z+c.wall_thickness*.5f},did});}
wall_x(o.geometry,o.collision,c.wall_material,"south",-c.depth*.5f+c.wall_thickness*.5f,base+c.floor_height*.5f,c.width-2*c.wall_thickness,c.wall_thickness,c.floor_height,fl==0?std::vector<Gap>{{0,c.door_width}}:std::vector<Gap>{},cid);wall_x(o.geometry,o.collision,c.wall_material,"north",c.depth*.5f-c.wall_thickness*.5f,base+c.floor_height*.5f,c.width-2*c.wall_thickness,c.wall_thickness,c.floor_height,{},cid);wall_z(o.geometry,o.collision,c.wall_material,"west",-c.width*.5f+c.wall_thickness*.5f,base+c.floor_height*.5f,c.depth-2*c.wall_thickness,c.wall_thickness,c.floor_height,{},cid);wall_z(o.geometry,o.collision,c.wall_material,"east",c.width*.5f-c.wall_thickness*.5f,base+c.floor_height*.5f,c.depth-2*c.wall_thickness,c.wall_thickness,c.floor_height,{},cid);if(fl==0){auto did=mix64(bs^0xE17EULL);o.openings.push_back({did,BuildingOpeningType::Door,0,BuildingWallAxis::X,{0,c.door_height*.5f,-c.depth*.5f+c.wall_thickness*.5f},{c.door_width,c.door_height,c.wall_thickness},false,true});o.interactables.push_back({iid++,BuildingInteractableType::Door,did,{0,1,-c.depth*.5f},true});o.collision.push_back({cid++,{-c.door_width*.5f,0,-c.depth*.5f},{c.door_width*.5f,c.floor_height,-c.depth*.5f+c.wall_thickness},did});}if(c.windows_per_wall)for(std::uint32_t w=0;w<c.windows_per_wall;++w){float t=(w+1.f)/(c.windows_per_wall+1.f),x=-iw*.5f+t*iw,y=base+c.floor_height*.55f;Vec3 pn{x,y,c.depth*.5f-c.wall_thickness*1.1f},ps{x,y,-c.depth*.5f+c.wall_thickness*1.1f};add_box(o.geometry,"window_n",{c.window_width,c.window_height,.04f},c.glass_material,pn);add_box(o.geometry,"window_s",{c.window_width,c.window_height,.04f},c.glass_material,ps);auto wn=mix64(bs^0x1000ULL^fl^(static_cast<std::uint64_t>(w)<<16U)),ws=mix64(bs^0x2000ULL^fl^(static_cast<std::uint64_t>(w)<<16U));o.openings.push_back({wn,BuildingOpeningType::Window,fl,BuildingWallAxis::X,pn,{c.window_width,c.window_height,.04f},false,true});o.openings.push_back({ws,BuildingOpeningType::Window,fl,BuildingWallAxis::X,ps,{c.window_width,c.window_height,.04f},false,true});o.interactables.push_back({iid++,BuildingInteractableType::Window,wn,pn,true});o.interactables.push_back({iid++,BuildingInteractableType::Window,ws,ps,true});}}
if(c.floors>1){auto steps=std::max(10U,static_cast<std::uint32_t>(std::ceil(c.floor_height/.2f)));for(std::uint32_t fl=0;fl+1<c.floors;++fl)for(std::uint32_t s=0;s<steps;++s){float t=(s+1.f)/steps,y=fl*c.floor_height+.1f+t*(c.floor_height-.2f)*.5f,z=.18f+(t-.5f)*c.stair_width*2.2f,x=c.width*.27f;add_box(o.geometry,"stair_"+std::to_string(fl)+"_"+std::to_string(s),{c.stair_width,.2f,c.stair_width*.48f},c.floor_material,{x,y,z});o.collision.push_back({cid++,{x-c.stair_width*.5f,fl*c.floor_height,z-c.stair_width*.24f},{x+c.stair_width*.5f,fl*c.floor_height+c.floor_height*t,z+c.stair_width*.24f},0});}}for(const auto&f:o.furniture)add_furniture(o,f);add_box(o.geometry,"foundation",{c.width,.3f,c.depth},c.wall_material,{0,-.15f,0});o.collision.push_back({cid++,{-c.width*.5f,-.3f,-c.depth*.5f},{c.width*.5f,0,c.depth*.5f},0});return o;}
bool set_building_door_open(BuildingDefinition&b,std::uint64_t id,bool open) noexcept{for(auto&o:b.openings)if(o.id==id&&o.type==BuildingOpeningType::Door){o.open=open;return true;}return false;}
const BuildingOpening* find_building_door(const BuildingDefinition&b,std::uint64_t id)noexcept{for(const auto&o:b.openings)if(o.id==id&&o.type==BuildingOpeningType::Door)return &o;return nullptr;}
std::vector<BuildingCollisionVolume> active_building_collision(const BuildingDefinition&b){std::vector<BuildingCollisionVolume> out;out.reserve(b.collision.size());for(const auto&v:b.collision){if(v.door_id){const auto*d=find_building_door(b,v.door_id);if(d&&d->open)continue;}out.push_back(v);}return out;}
const BuildingRoom* find_building_room(const BuildingDefinition&b,Vec3 p)noexcept{for(const auto&r:b.rooms)if(r.contains(p.x,p.y,p.z))return &r;return nullptr;}
} // namespace exgine
