#include "exgine/editor.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <type_traits>
#include <unordered_set>

namespace exgine {
namespace {
constexpr std::size_t kMaxHistory=128;
bool finite(float v){return std::isfinite(v);} bool valid_transform(const SceneTransform&t){return finite(t.position.x)&&finite(t.position.y)&&finite(t.position.z)&&finite(t.rotation.x)&&finite(t.rotation.y)&&finite(t.rotation.z)&&finite(t.scale.x)&&finite(t.scale.y)&&finite(t.scale.z);}
std::string kind_name(NodeKind k){switch(k){case NodeKind::World:return "world";case NodeKind::Terrain:return "terrain";case NodeKind::Vegetation:return "vegetation";case NodeKind::Building:return "building";case NodeKind::Vehicle:return "vehicle";case NodeKind::Player:return "player";case NodeKind::NPC:return "npc";case NodeKind::Bridge:return "bridge";case NodeKind::Prop:return "prop";case NodeKind::Property:return "property";}return "property";}
const char* asset_name(EditorAssetType t){switch(t){case EditorAssetType::Mesh:return "mesh";case EditorAssetType::Texture:return "texture";case EditorAssetType::Material:return "material";case EditorAssetType::Audio:return "audio";case EditorAssetType::Script:return "script";case EditorAssetType::Scene:return "scene";}return "mesh";}
bool parse_kind(const std::string&s,NodeKind&out){for(NodeKind k:{NodeKind::World,NodeKind::Terrain,NodeKind::Vegetation,NodeKind::Building,NodeKind::Vehicle,NodeKind::Player,NodeKind::NPC,NodeKind::Bridge,NodeKind::Prop,NodeKind::Property})if(kind_name(k)==s){out=k;return true;}return false;}
bool parse_asset_type(const std::string&s,EditorAssetType&out){for(EditorAssetType t:{EditorAssetType::Mesh,EditorAssetType::Texture,EditorAssetType::Material,EditorAssetType::Audio,EditorAssetType::Script,EditorAssetType::Scene})if(asset_name(t)==s){out=t;return true;}return false;}
void write_property(std::ostream&o,const Property&p){o<<"property "<<std::quoted(p.name)<<' ';std::visit([&](const auto&v){using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::string>)o<<"s "<<std::quoted(v);else if constexpr(std::is_same_v<T,bool>)o<<"b "<<(v?1:0);else if constexpr(std::is_same_v<T,std::int64_t>)o<<"i "<<v;else o<<"d "<<std::setprecision(17)<<v;},p.value);o<<'\n';}
bool read_property(std::istream&in,Property&p){std::string type;if(!(in>>std::quoted(p.name)>>type))return false;if(type=="s"){std::string v;if(!(in>>std::quoted(v)))return false;p.value=v;return true;}if(type=="b"){int v{};if(!(in>>v))return false;p.value=v!=0;return true;}if(type=="i"){std::int64_t v{};if(!(in>>v))return false;p.value=v;return true;}if(type=="d"){double v{};if(!(in>>v))return false;p.value=v;return true;}return false;}
}
bool EditorAsset::valid()const noexcept{return id!=0&&!name.empty()&&!source.empty();}
bool EditorNode::valid()const noexcept{return id!=0&&!name.empty()&&valid_transform(transform);}
bool EditorProject::valid()const noexcept{if(name.empty()||root_id==0||next_node_id==0||next_asset_id==0)return false;std::unordered_set<std::uint64_t>ids;for(const auto&n:nodes)if(!n.valid()||!ids.insert(n.id).second)return false;if(!ids.contains(root_id))return false;for(const auto&n:nodes)if(n.parent!=0&&!ids.contains(n.parent))return false;std::unordered_set<std::uint64_t>aids;for(const auto&a:assets)if(!a.valid()||!aids.insert(a.id).second)return false;return true;}
bool EditorViewport::valid()const noexcept{return camera.valid()&&finite(grid_size)&&grid_size>0.0F;}
EditorSession::EditorSession(){EditorNode root;root.id=project_.next_node_id++;root.kind=NodeKind::World;root.name="World";project_.root_id=root.id;project_.nodes.push_back(root);}
EditorNode*EditorSession::find(std::uint64_t id)noexcept{for(auto&n:project_.nodes)if(n.id==id)return &n;return nullptr;} const EditorNode*EditorSession::find(std::uint64_t id)const noexcept{for(const auto&n:project_.nodes)if(n.id==id)return &n;return nullptr;}
bool EditorSession::would_cycle(std::uint64_t id,std::uint64_t parent)const noexcept{std::size_t guard=project_.nodes.size()+1;while(parent&&guard--){if(parent==id)return true;const auto*n=find(parent);if(!n)return false;parent=n->parent;}return guard==0;}
bool EditorSession::mutate(EditorProject next,std::uint64_t selected){if(!next.valid())return false;undo_.push_back({project_,std::move(next),selected_id_,selected});if(undo_.size()>kMaxHistory)undo_.erase(undo_.begin());project_=undo_.back().after;selected_id_=selected;redo_.clear();dirty_=true;return true;}
std::uint64_t EditorSession::create_node(NodeKind kind,std::string name,std::uint64_t parent){if(name.empty())return 0;if(!parent)parent=project_.root_id;if(!find(parent))return 0;EditorProject next=project_;EditorNode n;n.id=next.next_node_id++;n.kind=kind;n.name=std::move(name);n.parent=parent;next.nodes.push_back(n);return mutate(std::move(next),n.id)?n.id:0;}
bool EditorSession::destroy_node(std::uint64_t id)noexcept{if(id==project_.root_id||!find(id))return false;EditorProject next=project_;std::unordered_set<std::uint64_t>rem{id};bool changed=true;while(changed){changed=false;for(const auto&n:next.nodes)if(rem.contains(n.parent)&&rem.insert(n.id).second)changed=true;}next.nodes.erase(std::remove_if(next.nodes.begin(),next.nodes.end(),[&](const EditorNode&n){return rem.contains(n.id);}),next.nodes.end());return mutate(std::move(next),rem.contains(selected_id_)?0:selected_id_);}
bool EditorSession::set_parent(std::uint64_t id,std::uint64_t parent)noexcept{if(id==project_.root_id||!find(id))return false;if(!parent)parent=project_.root_id;if(!find(parent)||would_cycle(id,parent))return false;EditorProject next=project_;for(auto&n:next.nodes)if(n.id==id)n.parent=parent;return mutate(std::move(next),selected_id_);}
bool EditorSession::set_transform(std::uint64_t id,SceneTransform t)noexcept{if(!find(id)||!valid_transform(t))return false;EditorProject next=project_;for(auto&n:next.nodes)if(n.id==id)n.transform=t;return mutate(std::move(next),selected_id_);}
bool EditorSession::rename_node(std::uint64_t id,std::string name){if(!find(id)||name.empty())return false;EditorProject next=project_;for(auto&n:next.nodes)if(n.id==id)n.name=name;return mutate(std::move(next),selected_id_);}
bool EditorSession::set_active(std::uint64_t id,bool active)noexcept{if(!find(id))return false;EditorProject next=project_;for(auto&n:next.nodes)if(n.id==id)n.active=active;return mutate(std::move(next),selected_id_);}
bool EditorSession::set_property(std::uint64_t id,Property p){if(!find(id)||p.name.empty())return false;EditorProject next=project_;for(auto&n:next.nodes)if(n.id==id){auto it=std::find_if(n.properties.begin(),n.properties.end(),[&](const Property&x){return x.name==p.name;});if(it==n.properties.end())n.properties.push_back(p);else *it=p;}return mutate(std::move(next),selected_id_);}
bool EditorSession::remove_property(std::uint64_t id,std::string_view name)noexcept{if(!find(id)||name.empty())return false;EditorProject next=project_;for(auto&n:next.nodes)if(n.id==id){auto old=n.properties.size();n.properties.erase(std::remove_if(n.properties.begin(),n.properties.end(),[&](const Property&p){return p.name==name;}),n.properties.end());if(old==n.properties.size())return false;}return mutate(std::move(next),selected_id_);}
bool EditorSession::add_asset(EditorAssetType type,std::string name,std::string source,std::uint64_t*id){if(name.empty()||source.empty())return false;EditorProject next=project_;EditorAsset a{next.next_asset_id++,type,std::move(name),std::move(source)};if(id)*id=a.id;next.assets.push_back(a);return mutate(std::move(next),selected_id_);}
bool EditorSession::remove_asset(std::uint64_t id)noexcept{EditorProject next=project_;auto old=next.assets.size();next.assets.erase(std::remove_if(next.assets.begin(),next.assets.end(),[&](const EditorAsset&a){return a.id==id;}),next.assets.end());if(old==next.assets.size())return false;return mutate(std::move(next),selected_id_);}
bool EditorSession::select(std::uint64_t id)noexcept{if(id&&!find(id))return false;selected_id_=id;return true;}
bool EditorSession::undo()noexcept{if(undo_.empty())return false;auto h=std::move(undo_.back());undo_.pop_back();project_=h.before;selected_id_=h.selected_before;redo_.push_back(std::move(h));dirty_=true;return true;} bool EditorSession::redo()noexcept{if(redo_.empty())return false;auto h=std::move(redo_.back());redo_.pop_back();project_=h.after;selected_id_=h.selected_after;undo_.push_back(std::move(h));dirty_=true;return true;} void EditorSession::clear_history()noexcept{undo_.clear();redo_.clear();}
std::string EditorSession::quote(std::string_view s){std::ostringstream o;o<<std::quoted(std::string(s));return o.str();}
void EditorSession::append_source_node(const EditorProject&p,const EditorNode&n,std::string&out,int depth){std::string ind(static_cast<std::size_t>(depth)*4,' ');out+=ind+kind_name(n.kind)+" "+quote(n.name)+" {\n";out+=ind+"    active = "+std::string(n.active?"true":"false")+"\n";out+=ind+"    position_x = "+std::to_string(n.transform.position.x)+"\n";out+=ind+"    position_y = "+std::to_string(n.transform.position.y)+"\n";out+=ind+"    position_z = "+std::to_string(n.transform.position.z)+"\n";for(const auto&pty:n.properties){out+=ind+"    "+quote(pty.name)+" = ";std::visit([&](const auto&v){using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::string>)out+=quote(v);else if constexpr(std::is_same_v<T,bool>)out+=(v?"true":"false");else out+=std::to_string(v);},pty.value);out+='\n';}for(const auto&child:p.nodes)if(child.parent==n.id)append_source_node(p,child,out,depth+1);out+=ind+"}\n";}
std::string EditorSession::emit_source()const{std::string out="// Generated by EXGINE Editor\nworld "+quote(project_.name)+" {\n";for(const auto&n:project_.nodes)if(n.parent==project_.root_id)append_source_node(project_,n,out,1);out+="}\n";return out;}
bool EditorSession::save(std::string_view path)const{if(path.empty()||!project_.valid()||!viewport_.valid())return false;std::ofstream out{std::string(path),std::ios::trunc};if(!out)return false;out<<"EXGINE_EDITOR "<<EditorProject::format_version<<'\n';out<<"project "<<quote(project_.name)<<' '<<quote(project_.startup_scene)<<'\n';out<<"root "<<project_.root_id<<' '<<project_.next_node_id<<' '<<project_.next_asset_id<<'\n';auto&c=viewport_.camera;out<<std::setprecision(9)<<"viewport "<<c.position.x<<' '<<c.position.y<<' '<<c.position.z<<' '<<c.rotation.x<<' '<<c.rotation.y<<' '<<c.rotation.z<<' '<<(viewport_.grid_visible?1:0)<<' '<<(viewport_.gizmos_visible?1:0)<<' '<<(viewport_.wireframe?1:0)<<' '<<viewport_.grid_size<<'\n';for(const auto&n:project_.nodes){out<<"node "<<n.id<<' '<<kind_name(n.kind)<<' '<<n.parent<<' '<<(n.active?1:0)<<' '<<quote(n.name)<<' '<<n.transform.position.x<<' '<<n.transform.position.y<<' '<<n.transform.position.z<<' '<<n.transform.rotation.x<<' '<<n.transform.rotation.y<<' '<<n.transform.rotation.z<<' '<<n.transform.scale.x<<' '<<n.transform.scale.y<<' '<<n.transform.scale.z<<'\n';for(const auto&p:n.properties)write_property(out,p);out<<"endnode\n";}for(const auto&a:project_.assets)out<<"asset "<<a.id<<' '<<asset_name(a.type)<<' '<<quote(a.name)<<' '<<quote(a.source)<<'\n';out<<"end\n";return static_cast<bool>(out);}
bool EditorSession::load(std::string_view path){if(path.empty())return false;std::ifstream in{std::string(path)};if(!in)return false;EditorProject next;EditorViewport view;std::string token;if(!(in>>token)||token!="EXGINE_EDITOR")return false;std::uint32_t version{};if(!(in>>version)||version!=EditorProject::format_version)return false;if(!(in>>token)||token!="project"||!(in>>std::quoted(next.name)>>std::quoted(next.startup_scene)))return false;if(!(in>>token)||token!="root"||!(in>>next.root_id>>next.next_node_id>>next.next_asset_id))return false;if(!(in>>token)||token!="viewport")return false;int grid{},gizmos{},wire{};auto&c=view.camera;if(!(in>>c.position.x>>c.position.y>>c.position.z>>c.rotation.x>>c.rotation.y>>c.rotation.z>>grid>>gizmos>>wire>>view.grid_size))return false;view.grid_visible=grid!=0;view.gizmos_visible=gizmos!=0;view.wireframe=wire!=0;while(in>>token){if(token=="node"){EditorNode n;std::string kind;int active{};if(!(in>>n.id>>kind>>n.parent>>active>>std::quoted(n.name)>>n.transform.position.x>>n.transform.position.y>>n.transform.position.z>>n.transform.rotation.x>>n.transform.rotation.y>>n.transform.rotation.z>>n.transform.scale.x>>n.transform.scale.y>>n.transform.scale.z)||!parse_kind(kind,n.kind))return false;n.active=active!=0;while(in>>token&&token!="endnode"){if(token!="property")return false;Property p;if(!read_property(in,p))return false;n.properties.push_back(std::move(p));}if(token!="endnode")return false;next.nodes.push_back(std::move(n));}else if(token=="asset"){EditorAsset a;std::string type;if(!(in>>a.id>>type>>std::quoted(a.name)>>std::quoted(a.source))||!parse_asset_type(type,a.type))return false;next.assets.push_back(std::move(a));}else if(token=="end")break;else return false;}if(!next.valid()||!view.valid())return false;project_=std::move(next);viewport_=view;selected_id_=0;clear_history();dirty_=false;return preview();}
bool EditorSession::preview(){IR ir;ir.root.name=project_.name;for(const auto&n:project_.nodes)if(n.id!=project_.root_id&&n.parent==project_.root_id){auto&child=ir.add_child(n.kind,n.name);child.properties=n.properties;}return runtime_.load(ir);}
}
