#include "exgine/exanimation.hpp"
#include <algorithm>
#include <cmath>
#include <unordered_map>
namespace exgine { namespace {
constexpr float PI=3.14159265358979323846f;
Quat qx(float a)noexcept{float s=std::sin(a*.5f);return normalize({s,0,0,std::cos(a*.5f)});} Quat qy(float a)noexcept{float s=std::sin(a*.5f);return normalize({0,s,0,std::cos(a*.5f)});} Quat qz(float a)noexcept{float s=std::sin(a*.5f);return normalize({0,0,s,std::cos(a*.5f)});} 
float rnd(std::uint32_t&s){s^=s<<13;s^=s>>17;s^=s<<5;return float(s&0xffffu)/32767.5f-1;}
AnimTransform idt(){return {{0,0,0},Quat::identity(),{1,1,1}};} AnimTransform plus(AnimTransform a,const AnimTransform&b,float k=1){a.translation.x+=b.translation.x*k;a.translation.y+=b.translation.y*k;a.translation.z+=b.translation.z*k;a.rotation=multiply(a.rotation,b.rotation);return a;}
}
bool MotionGraph::valid(const Skeleton&s)const noexcept{if(nodes.empty()||output==0||duration<=0||!s.valid()||!node(output))return false;for(const auto&n:nodes)if(n.bone>s.bones.size()&&n.bone!=invalid_bone)return false;return true;}
MotionNode* MotionGraph::node(std::uint32_t x)noexcept{for(auto&n:nodes)if(n.id==x)return &n;return nullptr;} const MotionNode* MotionGraph::node(std::uint32_t x)const noexcept{for(const auto&n:nodes)if(n.id==x)return &n;return nullptr;}
std::uint32_t MotionGraph::add(MotionNode n){if(n.id==0){n.id=1;for(const auto&x:nodes)n.id=std::max(n.id,x.id+1);}if(node(n.id))n.id=std::uint32_t(nodes.size()+1);nodes.push_back(std::move(n));if(!output)output=nodes.back().id;return nodes.back().id;}
MotionGraph make_motion_graph(std::string_view name,std::uint32_t seed){MotionGraph g;g.name=std::string(name);g.seed=seed?seed:1;MotionNode n;n.id=1;n.type=MotionNodeType::Constant;n.p[6]=n.p[7]=1;g.nodes.push_back(n);g.output=1;return g;}
void ExAnimation::apply_bone(SkeletonPose&p,BoneId id,const AnimTransform&d)const noexcept{if(!skeleton_||id==invalid_bone||id>p.local.size()||!p.valid_for(*skeleton_))return;auto&t=p.local[id-1];t.translation.x+=d.translation.x;t.translation.y+=d.translation.y;t.translation.z+=d.translation.z;t.rotation=multiply(t.rotation,d.rotation);t.scale.x*=d.scale.x;t.scale.y*=d.scale.y;t.scale.z*=d.scale.z;}
void ExAnimation::evaluate(const MotionGraph&g,float time,const MotionState&,SkeletonPose&p)const noexcept{if(!skeleton_||!g.valid(*skeleton_)||!p.valid_for(*skeleton_)||!std::isfinite(time))return;std::unordered_map<std::uint32_t,AnimTransform>v;float t=g.looping?std::fmod(std::max(0.0f,time),g.duration):std::clamp(time,0.0f,g.duration);std::uint32_t seed=g.seed?g.seed:1;for(const auto&n:g.nodes){AnimTransform x=idt(),a=n.inputs.empty()?idt():v[n.inputs[0]],b=n.inputs.size()>1?v[n.inputs[1]]:idt();float phase=2*PI*t*std::max(.001f,n.p[0]);switch(n.type){case MotionNodeType::Constant: x.translation={n.p[0],n.p[1],n.p[2]};x.rotation=multiply(qx(n.p[3]),multiply(qy(n.p[4]),qz(n.p[5])));x.scale={n.p[6]==0?1:n.p[6],n.p[7]==0?1:n.p[7],1};break;case MotionNodeType::Oscillator:{float w=std::sin(phase+n.p[2]);x.translation={w*n.p[3],std::cos(phase+n.p[2])*n.p[4],w*n.p[5]};x.rotation=multiply(qx(w*n.p[6]),qy(w*n.p[7]));break;}case MotionNodeType::Noise:{std::uint32_t s=seed+n.seed+std::uint32_t(t*std::max(.1f,n.p[0]));x.translation={rnd(s)*n.p[1],rnd(s)*n.p[2],rnd(s)*n.p[3]};x.rotation=qy(rnd(s)*n.p[4]);break;}case MotionNodeType::Curve:{float u=std::clamp(t/g.duration,0.0f,1.0f),y=n.p[1]*u+n.p[0]*(1-u);y=std::pow(std::max(0.0f,y),std::max(.01f,n.p[2]));x.translation={y*n.p[3],y*n.p[4],y*n.p[5]};x.rotation=qy(y*n.p[6]);break;}case MotionNodeType::Transform:x.translation={n.p[0],n.p[1],n.p[2]};x.rotation=multiply(qx(n.p[3]),multiply(qy(n.p[4]),qz(n.p[5])));x.scale={n.p[6]==0?1:n.p[6],n.p[7]==0?1:n.p[7],1};x=plus(a,x);break;case MotionNodeType::Additive:x=plus(a,b,n.p[0]==0?1:n.p[0]);break;case MotionNodeType::Blend:x=interpolate(a,b,std::clamp(n.p[0],0.0f,1.0f));break;case MotionNodeType::Multiply:x=a;x.translation.x*=n.p[0];x.translation.y*=n.p[0];x.translation.z*=n.p[0];break;case MotionNodeType::Spring:x=plus(idt(),a,1-std::exp(-std::max(.01f,n.p[0])*t));break;case MotionNodeType::Damping:x=plus(idt(),a,std::exp(-std::max(0.0f,n.p[0])*t));break;case MotionNodeType::LookAt:case MotionNodeType::Aim:if(n.bone&&n.target_bone&&n.bone<=skeleton_->bones.size()&&n.target_bone<=skeleton_->bones.size()){auto a0=skeleton_->bones[n.bone-1].local.translation,b0=skeleton_->bones[n.target_bone-1].local.translation;x.rotation=qy(std::atan2(b0.x-a0.x,b0.z-a0.z)*(n.p[0]==0?1:n.p[0]));}break;case MotionNodeType::IK2Bone:if(n.bone&&n.secondary_bone&&n.target_bone&&n.target_bone<=skeleton_->bones.size()){auto a0=skeleton_->bones[n.bone-1].local.translation,t0=skeleton_->bones[n.target_bone-1].local.translation;float d=std::sqrt((t0.x-a0.x)*(t0.x-a0.x)+(t0.y-a0.y)*(t0.y-a0.y));x.rotation=qz(std::atan2(t0.y-a0.y,t0.x-a0.x)*std::clamp(d,0.0f,1.0f));}break;case MotionNodeType::TimeWarp:x=plus(a,idt(),std::sin(t*n.p[0]));break;case MotionNodeType::Mirror:x=a;x.translation.x=-x.translation.x;break;case MotionNodeType::Retarget:x=a;break;}v[n.id]=x;if(n.bone)apply_bone(p,n.bone,x);}update_pose(*skeleton_,p);}
void ExAnimation::evaluate(const MotionState&s,float time,SkeletonPose&p)const noexcept{if(!skeleton_)return;MotionGraph g=motion_catalog(s.sprinting?2:1,*skeleton_);for(auto&n:g.nodes)if(n.type==MotionNodeType::Oscillator){n.p[0]=std::max(.5f,.8f+s.speed*.28f);n.p[1]=s.sprinting?.7f:.42f;n.p[3]=0;n.p[4]=s.grounded?(s.sprinting?.06f:.025f):0;n.p[6]=n.p[1]*(s.sprinting?1.25f:1);n.p[7]=n.p[6];}evaluate(g,time,s,p);}
AnimationClip ExAnimation::generate(const MotionGraph&g,AnimationClipId id)const{AnimationClip c;c.id=id;c.name=g.name;c.duration=g.duration;c.looping=g.looping;if(!skeleton_||!g.valid(*skeleton_))return c;int samples=std::max(2,std::min(180,int(std::ceil(g.duration*60))));for(const auto&b:skeleton_->bones){BoneTrack tr;tr.bone=b.id;for(int i=0;i<samples;++i){float t=g.duration*float(i)/float(samples-1);auto p=make_bind_pose(*skeleton_);evaluate(g,t,MotionState{},p);tr.keys.push_back({t,p.local[b.id-1]});}c.tracks.push_back(std::move(tr));}return c;}
AnimationClip ExAnimation::generate(const ProceduralMotion&m,AnimationClipId id)const{if(!m.graph.nodes.empty())return generate(m.graph,id);MotionGraph g=motion_catalog(1,*skeleton_);g.name=m.name;g.duration=m.duration;g.looping=m.looping;return generate(g,id);}
AnimationClip ExAnimation::locomotion(const MotionState&s,AnimationClipId id)const{return generate(motion_catalog(s.sprinting?2:1,*skeleton_),id);} AnimationClip ExAnimation::action(std::string_view n,AnimationClipId id)const{std::uint32_t h=2166136261u;for(char c:n)h=(h^std::uint8_t(c))*16777619u;return generate(motion_catalog(h,*skeleton_),id);}
MotionGraph motion_catalog(std::uint32_t id,const Skeleton&s){MotionGraph g=make_motion_graph("procedural.motion."+std::to_string(id),id*747796405u+2891336453u);g.duration=.2f+float(id%180)/60;g.looping=id%11!=0;g.nodes.clear();std::uint32_t count=1+id%7;for(std::uint32_t i=0;i<count;++i){MotionNode n;n.id=i+1;n.seed=g.seed+i*2654435761u;n.type=static_cast<MotionNodeType>((id+i*17)%16);if(n.type==MotionNodeType::Constant||n.type==MotionNodeType::Transform||n.type==MotionNodeType::Oscillator||n.type==MotionNodeType::Noise||n.type==MotionNodeType::Curve)if(!s.bones.empty())n.bone=s.bones[(id+i*31)%s.bones.size()].id;n.p[0]=.5f+float((id+i*13)%300)/100;n.p[1]=.02f+float((id+i*17)%100)/100;n.p[2]=float((id+i*19)%100)/100;n.p[3]=float((id+i*23)%100)/100;n.p[4]=float((id+i*29)%100)/200;n.p[5]=float((id+i*31)%100)/200;n.p[6]=float((id+i*37)%100)/150;n.p[7]=float((id+i*41)%100)/150;if(i)n.inputs.push_back(i);g.nodes.push_back(n);}g.output=g.nodes.back().id;return g;} MotionGraph catalog_animation(std::uint32_t id,const Skeleton&s){return motion_catalog(id,s);}
void AnimationStateMachine::add(AnimationState s){if(!s.name.empty())states_.push_back(std::move(s));} bool AnimationStateMachine::set(std::string_view n,const AnimationLibrary&l)noexcept{for(const auto&s:states_)if(s.name==n&&l.find(s.clip)){if(!controller_.play(s.clip,s.blend))return false;current_=s.name;return true;}return false;} void AnimationStateMachine::update(float dt,const MotionState&m,const AnimationLibrary&l)noexcept{for(const auto&s:states_)if(m.speed>=s.minimum_speed&&m.speed<s.maximum_speed){if(current_!=s.name)set(s.name,l);break;}controller_.update(dt,l);}
}