#include "exgine/exg_package.hpp"
#include <algorithm>
#include <cstring>
#include <limits>
namespace exgine { namespace {
constexpr std::uint32_t MAGIC=0x4b505845u; constexpr std::uint16_t VERSION=2; constexpr std::size_t HEADER=16,ENTRY=24;
void p16(std::vector<std::byte>&o,std::uint16_t v){o.push_back(std::byte(v));o.push_back(std::byte(v>>8));} void p32(std::vector<std::byte>&o,std::uint32_t v){for(int i=0;i<4;i++)o.push_back(std::byte(v>>(8*i)));} void p64(std::vector<std::byte>&o,std::uint64_t v){for(int i=0;i<8;i++)o.push_back(std::byte(v>>(8*i)));}
std::uint16_t g16(std::span<const std::byte>s,std::size_t p){return std::uint16_t(std::to_integer<unsigned>(s[p]))|std::uint16_t(std::to_integer<unsigned>(s[p+1])<<8);} std::uint32_t g32(std::span<const std::byte>s,std::size_t p){std::uint32_t v=0;for(int i=0;i<4;i++)v|=std::uint32_t(std::to_integer<unsigned>(s[p+i]))<<(8*i);return v;} std::uint64_t g64(std::span<const std::byte>s,std::size_t p){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(std::to_integer<unsigned>(s[p+i]))<<(8*i);return v;} void ext(std::vector<std::byte>&o,std::size_t n){while(n>=255){o.push_back(std::byte{255});n-=255;}o.push_back(std::byte(n));}
std::vector<std::byte>lz4(std::span<const std::byte>s,bool hc){std::vector<std::byte>o;if(s.empty())return o;constexpr std::size_t HS=65536;std::vector<std::int32_t>head(HS,-1),prev(hc?s.size():0,-1);auto hash=[&](std::size_t p){std::uint32_t x=0;std::memcpy(&x,s.data()+p,4);return(x*2654435761u)>>16;};std::size_t a=0,p=0;while(p+4<=s.size()){auto h=hash(p);int c=head[h],tries=hc?64:1;std::size_t bl=0,bp=0;while(c>=0&&tries--){auto q=std::size_t(c);if(p>q&&p-q<=65535&&std::memcmp(s.data()+q,s.data()+p,4)==0){std::size_t n=4;while(p+n<s.size()&&q+n<s.size()&&s[q+n]==s[p+n]&&n<65539)++n;if(n>bl){bl=n;bp=q;if(n>=512)break;}}if(!hc)break;c=prev[q];}if(hc)prev[p]=head[h];head[h]=std::int32_t(p);if(bl<4){++p;continue;}std::size_t lit=p-a,tp=o.size();o.push_back(std::byte{0});std::uint8_t t=std::uint8_t(std::min<std::size_t>(15,lit)<<4);if(lit>=15)ext(o,lit-15);o.insert(o.end(),s.begin()+std::ptrdiff_t(a),s.begin()+std::ptrdiff_t(p));o.push_back(std::byte(bp));o.push_back(std::byte(bp>>8));std::size_t ml=bl-4;t|=std::uint8_t(std::min<std::size_t>(15,ml));if(ml>=15)ext(o,ml-15);o[tp]=std::byte(t);p+=bl;a=p;if(hc)for(std::size_t q=p-bl+1;q<p&&q+4<=s.size();++q){auto hh=hash(q);prev[q]=head[hh];head[hh]=std::int32_t(q);}}std::size_t lit=s.size()-a;o.push_back(std::byte(std::min<std::size_t>(15,lit)<<4));if(lit>=15)ext(o,lit-15);o.insert(o.end(),s.begin()+std::ptrdiff_t(a),s.end());return o;}
bool dlz4(std::span<const std::byte>s,std::size_t expected,std::vector<std::byte>&o){o.clear();o.reserve(expected);std::size_t p=0;while(p<s.size()){auto t=std::to_integer<std::uint8_t>(s[p++]);std::size_t l=t>>4;if(l==15){std::uint8_t x=255;while(x==255){if(p>=s.size())return false;x=std::to_integer<std::uint8_t>(s[p++]);l+=x;}}if(p+l>s.size()||o.size()+l>expected)return false;o.insert(o.end(),s.begin()+std::ptrdiff_t(p),s.begin()+std::ptrdiff_t(p+l));p+=l;if(p==s.size())break;if(p+2>s.size())return false;std::size_t off=std::to_integer<unsigned>(s[p])|(std::to_integer<unsigned>(s[p+1])<<8);p+=2;if(!off||off>o.size())return false;std::size_t m=t&15;if(m==15){std::uint8_t x=255;while(x==255){if(p>=s.size())return false;x=std::to_integer<std::uint8_t>(s[p++]);m+=x;}}m+=4;if(o.size()+m>expected)return false;for(std::size_t i=0;i<m;i++)o.push_back(o[o.size()-off]);}return o.size()==expected;}
}
std::uint32_t exg_crc32(std::span<const std::byte>d)noexcept{std::uint32_t c=~0u;for(auto b:d){c^=std::to_integer<unsigned char>(b);for(int i=0;i<8;i++)c=(c>>1)^(0xedb88320u&-(c&1));}return ~c;}
bool build_exg_package(std::span<const std::byte>payload,const ExgPackageBuildOptions&o,ExgPackage&out,std::string&err)noexcept{out={};if(o.block_size<4096){err="EXPK block size below 4096";return false;}if(payload.empty()){err="EXPK cannot package empty payload";return false;}if(payload.size()>std::numeric_limits<std::uint32_t>::max()){err="EXPK payload exceeds 4 GiB";return false;}std::vector<std::vector<std::byte>>data;std::vector<ExgPackageBlock>idx;for(std::size_t p=0;p<payload.size();p+=o.block_size){auto n=std::min(o.block_size,payload.size()-p);auto s=payload.subspan(p,n);auto h=lz4(s,true),f=lz4(s,false);std::vector<std::byte>enc(s.begin(),s.end());ExgCodec c=ExgCodec::Raw;if(h.size()<enc.size()){enc=std::move(h);c=ExgCodec::Lz4HighCompression;}else if(f.size()<enc.size()){enc=std::move(f);c=ExgCodec::Lz4;}idx.push_back({0,std::uint32_t(enc.size()),std::uint32_t(n),c,exg_crc32(s)});data.push_back(std::move(enc));}std::uint64_t off=HEADER+std::uint64_t(idx.size())*ENTRY;out.bytes.reserve(std::size_t(off)+payload.size());p32(out.bytes,MAGIC);p16(out.bytes,VERSION);p16(out.bytes,0);p32(out.bytes,std::uint32_t(idx.size()));p32(out.bytes,0);for(auto&e:idx){e.offset=off;p64(out.bytes,e.offset);p32(out.bytes,e.compressed_size);p32(out.bytes,e.decoded_size);out.bytes.push_back(std::byte(std::uint8_t(e.codec)));out.bytes.push_back(std::byte{0});p16(out.bytes,0);p32(out.bytes,e.checksum);off+=e.compressed_size;}for(auto&b:data)out.bytes.insert(out.bytes.end(),b.begin(),b.end());out.blocks=std::move(idx);return true;}
bool open_exg_package(std::span<const std::byte>p,ExgPackage&out,std::string&err)noexcept{out={};if(p.size()<HEADER||g32(p,0)!=MAGIC||g16(p,4)!=VERSION){err="invalid EXPK header";return false;}auto n=g32(p,8);auto base=HEADER+std::uint64_t(n)*ENTRY;if(!n||base>p.size()){err="invalid EXPK index";return false;}out.bytes.assign(p.begin(),p.end());out.blocks.reserve(n);for(std::uint32_t i=0;i<n;i++){auto q=HEADER+std::size_t(i)*ENTRY;ExgPackageBlock e{g64(p,q),g32(p,q+8),g32(p,q+12),ExgCodec(std::to_integer<unsigned char>(p[q+16])),g32(p,q+20)};if(e.offset<base||e.compressed_size==0||e.decoded_size==0||e.offset+e.compressed_size>p.size()){err="invalid EXPK block";out={};return false;}out.blocks.push_back(e);}return true;}
bool decode_exg_block(std::span<const std::byte>p,const ExgPackageBlock&e,std::vector<std::byte>&out,std::string&err)noexcept{if(e.offset+e.compressed_size>p.size()){err="EXPK block out of range";return false;}auto s=p.subspan(std::size_t(e.offset),e.compressed_size);bool ok=false;if(e.codec==ExgCodec::Raw){out.assign(s.begin(),s.end());ok=out.size()==e.decoded_size;}else if(e.codec==ExgCodec::Lz4||e.codec==ExgCodec::Lz4HighCompression)ok=dlz4(s,e.decoded_size,out);else{err="unsupported EXPK codec";return false;}if(!ok||exg_crc32(out)!=e.checksum){out.clear();err="EXPK checksum/decode failure";return false;}return true;}
ExgPackageStream::ExgPackageStream(ExgPackage p):package_(std::move(p)),worker_(&ExgPackageStream::run,this){} ExgPackageStream::~ExgPackageStream(){{std::lock_guard<std::mutex>l(mutex_);stop_=true;}condition_.notify_one();if(worker_.joinable())worker_.join();}
bool ExgPackageStream::request(std::uint64_t id,DecodeCallback cb){if(id>=package_.blocks.size()||!cb)return false;{std::lock_guard<std::mutex>l(mutex_);jobs_.push({id,std::move(cb)});}condition_.notify_one();return true;}
void ExgPackageStream::run(){for(;;){Job j;{std::unique_lock<std::mutex>l(mutex_);condition_.wait(l,[&]{return stop_||!jobs_.empty();});if(stop_&&jobs_.empty())return;j=std::move(jobs_.front());jobs_.pop();}Completed c;c.block_id=j.block_id;c.callback=std::move(j.callback);decode_exg_block(package_.bytes,package_.blocks[std::size_t(j.block_id)],c.data,c.error);{std::lock_guard<std::mutex>l(mutex_);completed_.push(std::move(c));}}}
std::size_t ExgPackageStream::pump(std::size_t max){std::size_t n=0;while(n<max){Completed c;{std::lock_guard<std::mutex>l(mutex_);if(completed_.empty())break;c=std::move(completed_.front());completed_.pop();}if(c.callback)c.callback(c.block_id,c.data,c.error);++n;}return n;}
std::size_t ExgPackageStream::pending()const noexcept{std::lock_guard<std::mutex>l(mutex_);return jobs_.size()+completed_.size();}
bool ExgGpuResidencyStreamer::submit_mesh_block(ExgPackageStream&s,std::uint64_t asset,std::uint32_t gen,std::uint64_t block,std::uint64_t frame,std::function<bool(std::span<const std::byte>,Mesh&,std::string&)>decode){if(!gpu_.request(asset,1.0f,gen))return false;return s.request(block,[this,asset,gen,frame,decode=std::move(decode)](std::uint64_t,std::span<const std::byte>d,std::string&e)->bool{Mesh m;if(!e.empty()||!decode(d,m,e)){gpu_.mark_decoded(asset,gen,0);return false;}if(!gpu_.mark_decoded(asset,gen,d.size()))return false;std::string upload_error;if(!gpu_.make_resident(asset,m,frame,upload_error)){e=upload_error;return false;}return true;});}
std::size_t ExgGpuResidencyStreamer::pump(ExgPackageStream&s,std::uint64_t frame,std::size_t max){(void)frame;return s.pump(max);}
}