#include "exgine/exsound.hpp"
#include <algorithm>
#include <cmath>
#include <cctype>
namespace exgine { namespace {
constexpr float PI=3.14159265358979323846f;
float c01(float x){return std::clamp(x,0.0f,1.0f);} 
float noise(std::uint32_t& s){s^=s<<13;s^=s>>17;s^=s<<5;return(float(s&0x00ffffffu)/8388607.5f)-1.0f;}
float osc(SoundWave w,float p,std::uint32_t& s){p-=std::floor(p);switch(w){case SoundWave::Sine:return std::sin(2*PI*p);case SoundWave::Triangle:return 4*std::fabs(p-.5f)-1;case SoundWave::Saw:return 2*p-1;case SoundWave::Square:return p<.5f?1:-1;case SoundWave::Noise:return noise(s);case SoundWave::Impulse:return p<.01f?1:0;case SoundWave::FM:return std::sin(2*PI*p+std::sin(10*PI*p)*2);case SoundWave::Pluck:return std::sin(2*PI*p)*std::exp(-4*p);case SoundWave::Formant:return .6f*std::sin(2*PI*p)+.25f*std::sin(4*PI*p)+.15f*std::sin(14*PI*p);}return 0;}
float env(float t,float d,const SoundEnvelope&e){float a=std::max(.0001f,e.attack),dc=std::max(.0001f,e.decay),r=std::max(.0001f,e.release);if(t<a)return t/a;if(t<a+dc)return 1-(1-c01(e.sustain))*(t-a)/dc;if(t>=std::max(a+dc,d-r))return c01(e.sustain)*std::max(0.0f,(d-t)/r);return c01(e.sustain);}
float mat(SoundMaterial m){switch(m){case SoundMaterial::Metal:return 1600;case SoundMaterial::Glass:return 2600;case SoundMaterial::Stone:return 700;case SoundMaterial::Wood:return 420;case SoundMaterial::Ceramic:return 2100;case SoundMaterial::Rubber:return 180;case SoundMaterial::Plastic:return 900;case SoundMaterial::Ice:return 1900;case SoundMaterial::Concrete:return 520;case SoundMaterial::Water:return 900;default:return 500;}}
SoundLayer generated_layer(std::uint32_t id,std::uint32_t seed){SoundLayer l;l.wave=static_cast<SoundWave>(id%9);l.frequency=35+float((id*2654435761u+seed)%1900u);l.frequency_end=l.frequency*(.15f+.8f*float((id>>3)%100)/100);l.gain=.15f+.7f*float((id*37u)%100)/100;l.noise=float((id*17u)%80)/100;l.resonance=float((id*11u)%100)/100;l.distortion=float((id*7u)%35)/100;l.envelope.attack=.001f+.02f*float(id%20)/20;l.envelope.decay=.02f+.4f*float((id/7)%100)/100;l.envelope.sustain=.2f+.7f*float((id/13)%100)/100;l.envelope.release=.03f+.5f*float((id/19)%100)/100;return l;}
}
bool ProceduralSound::valid()const noexcept{return duration>0&&std::isfinite(duration)&&std::isfinite(gain)&&std::isfinite(pan)&&std::isfinite(frequency)&&std::isfinite(frequency_end);}
bool SoundSample::valid()const noexcept{return sample_rate>0&&channels>0&&!pcm.empty()&&pcm.size()%channels==0;}
SoundRecipe SoundRecipe::catalog(std::uint32_t id){SoundRecipe r;r.catalog_id=id;r.family="procedural."+std::to_string(id);r.seed=id*747796405u+2891336453u;r.duration=.08f+float(id%900)/500.0f;r.gain=.2f+.65f*float((id*17u)%100)/100;r.pan=(float(id%201)-100)/100;r.reverb=float((id/3)%70)/100;for(std::size_t i=0;i<1+id%6;++i)r.layers.push_back(generated_layer(id+std::uint32_t(i*7919),r.seed));return r;}
ProceduralSound SoundRecipe::build()const{ProceduralSound s;s.name=family;s.duration=duration;s.gain=gain;s.pan=pan;s.reverb=reverb;s.seed=seed;s.layers=layers;if(!layers.empty()){s.wave=layers[0].wave;s.frequency=layers[0].frequency;s.frequency_end=layers[0].frequency_end;s.noise=layers[0].noise;s.resonance=layers[0].resonance;s.distortion=layers[0].distortion;s.envelope=layers[0].envelope;}return s;}
SoundSample ExSound::synthesize(const ProceduralSound&s)const{SoundSample out;out.sample_rate=sample_rate_;out.channels=2;if(!s.valid())return out;const auto frames=std::size_t(std::ceil(s.duration*sample_rate_));out.pcm.assign(frames*2,0);std::uint32_t st=s.seed?s.seed:1;for(std::size_t i=0;i<frames;++i){float t=float(i)/sample_rate_,u=c01(t/s.duration),x=0;auto emit=[&](const SoundLayer&l){float f=l.frequency+(l.frequency_end-l.frequency)*u,q=osc(l.wave,t*f,st);q=q*(1-c01(l.noise))+noise(st)*c01(l.noise);if(l.distortion>0)q=std::tanh(q*(1+10*l.distortion));return q*env(t,s.duration,l.envelope)*l.gain;};if(s.layers.empty()){SoundLayer l;l.wave=s.wave;l.frequency=s.frequency;l.frequency_end=s.frequency_end;l.gain=1;l.noise=s.noise;l.resonance=s.resonance;l.distortion=s.distortion;l.envelope=s.envelope;x=emit(l);}else for(const auto&l:s.layers)x+=emit(l);x*=s.gain;float pan=std::clamp(s.pan,-1.0f,1.0f),L=std::sqrt(.5f*(1-pan)),R=std::sqrt(.5f*(1+pan));out.pcm[i*2]=std::clamp(x*L,-1.0f,1.0f);out.pcm[i*2+1]=std::clamp(x*R,-1.0f,1.0f);}return out;}
SoundSample ExSound::synthesize_recipe(const SoundRecipe&r)const{return synthesize(r.build());}
ProceduralSound ExSound::event(const SoundEventParams&p)const{auto s=SoundRecipe::catalog((std::uint32_t(p.event)*97u+std::uint32_t(p.material)*31u+std::uint32_t(std::fabs(p.variation)*1000))%1000000u).build();float i=c01(p.intensity);s.duration*=.45f+.8f*i;s.gain*=(.35f+.65f*i)*std::sqrt(std::max(.05f,p.mass));s.reverb=c01(p.room);s.seed=p.seed;s.gain*=1/(1+std::max(0.0f,p.distance)*.04f);for(auto&l:s.layers)l.frequency*=std::max(.2f,mat(p.material)/600);if(p.event==SoundEvent::Vehicle){s.wave=SoundWave::Saw;s.frequency=25+std::max(0.0f,p.speed)*2;s.frequency_end=s.frequency*1.2f;}return s;}
SoundSample ExSound::synthesize_event(const SoundEventParams&p)const{return synthesize(event(p));}
SoundSample ExSound::synthesize_speech(const SpeechRequest&r)const{SoundSample out;out.sample_rate=sample_rate_;out.channels=2;if(r.text.empty())return out;const auto&v=r.voice;float rate=std::clamp(v.speed,.25f,3.0f);std::size_t chars=r.text.size(),frames=std::size_t(std::max(.08f,float(chars)*.055f/rate)*sample_rate_);out.pcm.assign(frames*2,0);std::uint32_t st=v.seed?v.seed:1;float phase=0;for(std::size_t i=0;i<frames;++i){float t=float(i)/sample_rate_,pos=t/(float(frames)/sample_rate_)*float(chars),local=pos-std::floor(pos);std::size_t ci=std::min(chars-1,std::size_t(pos));unsigned char ch=static_cast<unsigned char>(std::tolower(static_cast<unsigned char>(r.text[ci])));float f=120*v.pitch;switch(ch){case'a':f=800;break;case'e':f=530;break;case'i':f=390;break;case'o':f=500;break;case'u':f=350;break;case' ':f=0;break;default:f=130+float(ch%17)*9;break;}float pulse=local<.12f?local/.12f:(local>.88f?(1-local)/.12f:1),x=f?std::sin(2*PI*phase)+.35f*std::sin(4*PI*phase)+.12f*noise(st)*v.breath:0;phase+=f/sample_rate_;if(v.quality==VoiceQuality::Robotic)x=std::copysign(std::sqrt(std::fabs(x)),x);if(v.quality==VoiceQuality::Harsh)x=std::tanh(2.4f*x);if(v.quality==VoiceQuality::Whisper)x*=.25f; x*=pulse*r.gain;float pan=std::clamp(r.pan,-1.0f,1.0f);out.pcm[i*2]=x*std::sqrt(.5f*(1-pan));out.pcm[i*2+1]=x*std::sqrt(.5f*(1+pan));}return out;}
ProceduralSound footstep(SoundMaterial m,float f,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Footstep;p.material=m;p.intensity=c01(f);p.seed=seed;return ExSound{}.event(p);}
ProceduralSound impact(SoundMaterial m,float f,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Impact;p.material=m;p.intensity=c01(f);p.seed=seed;return ExSound{}.event(p);}
ProceduralSound explosion(float f,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Explosion;p.intensity=c01(f);p.seed=seed;return ExSound{}.event(p);}
ProceduralSound ui_click(std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::UI;p.seed=seed;return ExSound{}.event(p);}
ProceduralSound vehicle_engine(float rpm,float load,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Vehicle;p.intensity=c01(load);p.speed=rpm;p.seed=seed;return ExSound{}.event(p);}
SpeechRequest speech(std::string_view text,const VoiceProfile&v){SpeechRequest r;r.text=text;r.voice=v;return r;}
} // namespace exgine
