#include "exgine/exsound.hpp"
#include <algorithm>
#include <cmath>
#include <cctype>
#include <limits>
#include <unordered_map>

namespace exgine { namespace {
constexpr float PI=3.14159265358979323846f;
float clamp01(float x){return std::clamp(x,0.0f,1.0f);} 
float noise(std::uint32_t& s){s^=s<<13;s^=s>>17;s^=s<<5;return (float(s&0x00ffffffu)/8388607.5f)-1.0f;}
float wave(SoundWave w,float phase,std::uint32_t& seed){phase-=std::floor(phase);switch(w){case SoundWave::Sine:return std::sin(2*PI*phase);case SoundWave::Triangle:return 1.0f-4.0f*std::fabs(phase-.5f);case SoundWave::Saw:return 2*phase-1;case SoundWave::Square:return phase<.5f?1:-1;case SoundWave::Noise:return noise(seed);case SoundWave::Impulse:return phase<.01f?1:0;case SoundWave::FM:return std::sin(2*PI*phase+1.7f*std::sin(2*PI*7*phase));case SoundWave::Pluck:return std::sin(2*PI*phase)*std::exp(-5*phase);case SoundWave::Formant:return .58f*std::sin(2*PI*phase)+.28f*std::sin(4*PI*phase)+.14f*std::sin(14*PI*phase);}return 0;}
float envelope(float t,float d,const SoundEnvelope&e){float a=std::max(.0001f,e.attack),dc=std::max(.0001f,e.decay),r=std::max(.0001f,e.release);if(t<a)return t/a;if(t<a+dc)return 1-(1-clamp01(e.sustain))*(t-a)/dc;if(t>=std::max(a+dc,d-r))return clamp01(e.sustain)*std::max(0.0f,(d-t)/r);return clamp01(e.sustain);}
float read(const std::unordered_map<std::uint32_t,std::vector<float>>&v,std::uint32_t id,std::size_t i){auto it=v.find(id);return it!=v.end()&&i<it->second.size()?it->second[i]:0.0f;}
SoundNode node(std::uint32_t id,SoundNodeType type){SoundNode n;n.id=id;n.type=type;return n;}
}

bool SoundGraph::valid() const noexcept {if(nodes.empty()||output==0||duration<=0||!std::isfinite(duration)||!std::isfinite(gain)||!std::isfinite(pan))return false;for(const auto&n:nodes)if(n.id==0)return false;return node(output)!=nullptr;}
SoundNode* SoundGraph::node(std::uint32_t id) noexcept{for(auto&n:nodes)if(n.id==id)return &n;return nullptr;}
const SoundNode* SoundGraph::node(std::uint32_t id) const noexcept{for(const auto&n:nodes)if(n.id==id)return &n;return nullptr;}
std::uint32_t SoundGraph::add(SoundNode n){if(n.id==0){n.id=1;for(const auto&x:nodes)n.id=std::max(n.id,x.id+1);}if(node(n.id))n.id=static_cast<std::uint32_t>(nodes.size()+1);nodes.push_back(std::move(n));if(output==0)output=nodes.back().id;return nodes.back().id;}

bool ProceduralSound::valid() const noexcept{return duration>0&&std::isfinite(duration)&&std::isfinite(gain)&&std::isfinite(pan)&&std::isfinite(frequency)&&std::isfinite(frequency_end);}
SoundGraph ProceduralSound::graph() const {SoundGraph g;g.name=name;g.duration=duration;g.gain=gain;g.pan=pan;g.seed=seed;std::uint32_t next=1;auto add=[&](SoundNode n){n.id=next++;g.nodes.push_back(std::move(n));return g.nodes.back().id;};std::vector<std::uint32_t> layers;for(const auto&l:layers){(void)l;}if(layers.empty()){SoundNode o=node(next++,SoundNodeType::Oscillator);o.p[0]=static_cast<float>(static_cast<int>(wave));o.p[1]=frequency;o.p[2]=frequency_end;o.p[3]=noise;o.p[4]=gain;o.p[5]=distortion;o.p[6]=resonance;o.seed=seed;auto id=o.id;g.nodes.push_back(std::move(o));g.output=id;}return g;}

SoundSample ExSound::render(const SoundGraph& g) const {SoundSample out;out.sample_rate=sample_rate_;out.channels=2;if(!g.valid())return out;const std::size_t frames=std::max<std::size_t>(1,std::size_t(std::ceil(g.duration*sample_rate_)));out.pcm.assign(frames*2,0);std::unordered_map<std::uint32_t,std::vector<float>> values;for(const auto&n:g.nodes)values[n.id].assign(frames,0);std::uint32_t global_seed=g.seed?g.seed:1;
 for(const auto&n:g.nodes){auto&dst=values[n.id];for(std::size_t i=0;i<frames;++i){float t=float(i)/sample_rate_,u=clamp01(t/g.duration),a=n.inputs.size()>0?read(values,n.inputs[0],i):0,b=n.inputs.size()>1?read(values,n.inputs[1],i):0,c=n.inputs.size()>2?read(values,n.inputs[2],i):0;switch(n.type){case SoundNodeType::Constant:dst[i]=n.p[0];break;case SoundNodeType::Oscillator:{float f=n.p[1]+(n.p[2]-n.p[1])*u;auto w=static_cast<SoundWave>(std::clamp(int(n.p[0]),0,8));float x=wave(w,t*f,global_seed);x=x*(1-clamp01(n.p[3]))+noise(global_seed)*clamp01(n.p[3]);dst[i]=x*n.p[4];break;}case SoundNodeType::Noise:dst[i]=noise(global_seed)*n.p[0];break;case SoundNodeType::Impulse:dst[i]=(t*n.p[0]-std::floor(t*n.p[0]))<n.p[1]?n.p[2]:0;break;case SoundNodeType::Envelope:{SoundEnvelope e{std::max(.0001f,n.p[0]),std::max(.0001f,n.p[1]),n.p[2],std::max(.0001f,n.p[3])};dst[i]=envelope(t,g.duration,e);break;}case SoundNodeType::Gain:dst[i]=a*n.p[0];break;case SoundNodeType::Add:dst[i]=a+b;break;case SoundNodeType::Multiply:dst[i]=a*b;break;case SoundNodeType::Mix:dst[i]=a*(1-clamp01(n.p[0]))+b*clamp01(n.p[0]);break;case SoundNodeType::Filter:{float alpha=std::clamp(n.p[0],.0001f,1.0f);float prev=i?dst[i-1]:0;float lp=prev+alpha*(a-prev);if(static_cast<int>(n.p[1])==0)dst[i]=lp;else if(static_cast<int>(n.p[1])==1)dst[i]=a-lp;else dst[i]=a-lp-prev;break;}case SoundNodeType::Resonator:{float q=std::max(.001f,n.p[1]),freq=std::max(1.0f,n.p[0]);float k=2*std::sin(PI*freq/sample_rate_);float prev=i?dst[i-1]:0;dst[i]=a+k*(a-prev)*q*.01f;break;}case SoundNodeType::Delay:{std::size_t d=std::min<std::size_t>(frames-1,std::size_t(std::max(0.0f,n.p[0])*sample_rate_));dst[i]=a+(i>d?values.at(n.id)[i-d]*n.p[1]:0);break;}case SoundNodeType::Reverb:{std::size_t d=std::min<std::size_t>(frames-1,std::size_t(std::max(.001f,n.p[0])*sample_rate_));dst[i]=a+(i>d?values.at(n.id)[i-d]*n.p[1]:0);if(i>d*2)dst[i]+=values.at(n.id)[i-d*2]*n.p[1]*.5f;break;}case SoundNodeType::Distortion:dst[i]=std::tanh(a*(1+std::max(0.0f,n.p[0])*20));break;case SoundNodeType::Pan:dst[i]=a;break;case SoundNodeType::Wavetable:dst[i]=wave(static_cast<SoundWave>(std::clamp(int(n.p[0]),0,8)),t*std::max(1.0f,n.p[1]),global_seed);break;case SoundNodeType::FM:dst[i]=std::sin(2*PI*t*n.p[0]+n.p[2]*std::sin(2*PI*t*n.p[1]));break;case SoundNodeType::Formant:{float f=std::max(20.0f,n.p[0]);dst[i]=.55f*std::sin(2*PI*f*t)+.3f*std::sin(2*PI*f*2*t)+.15f*std::sin(2*PI*f*3*t);break;}case SoundNodeType::Granular:{float rate=std::max(.1f,n.p[0]),grain=std::fmod(t*rate,1.0f);dst[i]=a*(1-std::fabs(2*grain-1));break;}case SoundNodeType::Sequencer:{int steps=std::max(1,int(n.p[0]));int k=std::min(steps-1,int(u*steps));dst[i]=n.p[1+k%7];break;}}}}
 float pan=std::clamp(g.pan,-1.0f,1.0f),L=std::sqrt(.5f*(1-pan)),R=std::sqrt(.5f*(1+pan));auto it=values.find(g.output);if(it==values.end())return out;for(std::size_t i=0;i<frames;++i){float x=std::clamp(it->second[i]*g.gain,-1.0f,1.0f);out.pcm[i*2]=x*L;out.pcm[i*2+1]=x*R;}return out;}

SoundSample ExSound::synthesize(const ProceduralSound&s)const{return render(s.graph());}

SoundGraph make_sound_graph(std::string_view name,std::uint32_t seed){SoundGraph g;g.name=std::string(name);g.seed=seed?seed:1;g.duration=.5f;SoundNode o=node(1,SoundNodeType::Oscillator);o.p[0]=0;o.p[1]=220;o.p[2]=220;o.p[3]=0;o.p[4]=.5f;o.seed=g.seed;g.nodes.push_back(o);g.output=1;return g;}
SoundGraph sound_catalog(std::uint32_t id){SoundGraph g=make_sound_graph("procedural.sound."+std::to_string(id),id*747796405u+2891336453u);g.duration=.08f+float(id%900)/500.0f;g.gain=.25f+.7f*float((id*17u)%100)/100;g.pan=(float(id%201)-100)/100;g.nodes.clear();std::uint32_t seed=g.seed;for(std::uint32_t i=0;i<1+id%8;++i){SoundNode n=node(i+1,static_cast<SoundNodeType>(1+(id+i*13)%19));n.seed=seed+i*2654435761u;n.p[0]=float((id*37u+i*11u)%9);n.p[1]=30+float((id*97u+i*53u)%1800);n.p[2]=n.p[1]*(.2f+.8f*float((id+i)%100)/100);n.p[3]=float((id+i*7u)%100)/100;n.p[4]=.1f+.8f*float((id+i*17u)%100)/100;n.p[5]=.01f+.2f*float((id+i*23u)%100)/100;if(i) n.inputs.push_back(i);g.nodes.push_back(n);}g.output=g.nodes.back().id;return g;}
SoundRecipe catalog(std::uint32_t id){return sound_catalog(id);}

SoundGraph ExSound::event(const SoundEventParams&p)const{SoundGraph g=sound_catalog((std::uint32_t(p.event)*104729u+std::uint32_t(p.material)*7919u+std::uint32_t(std::fabs(p.variation)*1000)+p.seed)%1000000u);float intensity=clamp01(p.intensity);g.duration*=.35f+.9f*intensity;g.gain*=.25f+.75f*intensity;g.gain*=1.0f/(1.0f+.04f*std::max(0.0f,p.distance));g.pan=std::clamp(p.variation,-1.0f,1.0f);for(auto&n:g.nodes){n.seed^=p.seed;n.p[1]*=.5f+.8f*std::sqrt(std::max(.01f,p.mass));n.p[5]+=clamp01(p.room)*.1f;}return g;}
SoundSample ExSound::synthesize_event(const SoundEventParams&p)const{return render(event(p));}
SoundSample ExSound::synthesize_recipe(const SoundRecipe&r)const{return render(r);}

SoundSample ExSound::synthesize_speech(const SpeechRequest&r)const{SoundSample out;out.sample_rate=sample_rate_;out.channels=2;if(r.text.empty())return out;const auto&v=r.voice;float rate=std::clamp(v.speed,.25f,3.0f),char_time=.045f/rate;std::size_t frames=std::size_t(std::max(.08f,char_time*float(r.text.size()))*sample_rate_);out.pcm.assign(frames*2,0);std::uint32_t st=v.seed?v.seed:1;float phase=0;for(std::size_t i=0;i<frames;++i){float t=float(i)/sample_rate_,position=t/char_time,local=position-std::floor(position);std::size_t ci=std::min(r.text.size()-1,std::size_t(position));unsigned char ch=static_cast<unsigned char>(std::tolower(static_cast<unsigned char>(r.text[ci])));float f=120*v.pitch;switch(ch){case'a':f=800*v.voice.formant_shift;break;case'e':f=530*v.voice.formant_shift;break;case'i':f=390*v.voice.formant_shift;break;case'o':f=500*v.voice.formant_shift;break;case'u':f=350*v.voice.formant_shift;break;case' ':f=0;break;default:f=(100+float(ch%23)*8)*v.pitch;break;}float pulse=local<.1f?local/.1f:(local>.9f?(1-local)/.1f:1);float x=f?std::sin(2*PI*phase)+.3f*std::sin(4*PI*phase)+v.breath*.08f*noise(st):0;phase+=f/sample_rate_;if(v.quality==VoiceQuality::Robotic)x=std::copysign(std::sqrt(std::fabs(x)),x);if(v.quality==VoiceQuality::Harsh)x=std::tanh(2.5f*x);if(v.quality==VoiceQuality::Whisper)x*=.2f;x*=pulse*r.gain;float pan=std::clamp(r.pan,-1.0f,1.0f);out.pcm[i*2]=x*std::sqrt(.5f*(1-pan));out.pcm[i*2+1]=x*std::sqrt(.5f*(1+pan));}return out;}

ProceduralSound footstep(SoundMaterial m,float f,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Footstep;p.material=m;p.intensity=f;p.seed=seed;auto g=ExSound{}.event(p);ProceduralSound s;s.name=g.name;s.duration=g.duration;s.gain=g.gain;s.pan=g.pan;s.seed=g.seed;s.wave=SoundWave::Noise;s.frequency=120;s.frequency_end=40;s.layers={};return s;}
ProceduralSound impact(SoundMaterial m,float f,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Impact;p.material=m;p.intensity=f;p.seed=seed;auto g=ExSound{}.event(p);ProceduralSound s;s.name=g.name;s.duration=g.duration;s.gain=g.gain;s.pan=g.pan;s.seed=g.seed;s.frequency=80;s.frequency_end=30;return s;}
ProceduralSound explosion(float f,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Explosion;p.intensity=f;p.seed=seed;auto g=ExSound{}.event(p);ProceduralSound s;s.name=g.name;s.duration=g.duration;s.gain=g.gain;s.pan=g.pan;s.seed=g.seed;s.wave=SoundWave::Noise;s.frequency=45;s.frequency_end=20;return s;}
ProceduralSound ui_click(std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::UI;p.seed=seed;auto g=ExSound{}.event(p);ProceduralSound s;s.name=g.name;s.duration=g.duration;s.gain=g.gain;s.seed=g.seed;s.wave=SoundWave::Sine;s.frequency=1000;s.frequency_end=1400;return s;}
ProceduralSound vehicle_engine(float rpm,float load,std::uint32_t seed){SoundEventParams p;p.event=SoundEvent::Vehicle;p.speed=rpm;p.intensity=load;p.seed=seed;auto g=ExSound{}.event(p);ProceduralSound s;s.name=g.name;s.duration=g.duration;s.gain=g.gain;s.seed=g.seed;s.wave=SoundWave::Saw;s.frequency=std::max(20.0f,rpm);s.frequency_end=s.frequency*1.05f;return s;}
SpeechRequest speech(std::string_view text,const VoiceProfile&v){SpeechRequest r;r.text=text;r.voice=v;return r;}

} // namespace exgine
