#include "exgine/gameplay.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <unordered_map>
namespace exgine { namespace {
constexpr float E=1e-5f;
bool fin(float x){return std::isfinite(x);}
bool fin(Vec3 v){return fin(v.x)&&fin(v.y)&&fin(v.z);}
float len(Vec3 v){return std::sqrt(std::max(0.0f,v.x*v.x+v.y*v.y+v.z*v.z));}
Vec3 add(Vec3 a,Vec3 b){return {a.x+b.x,a.y+b.y,a.z+b.z};} Vec3 mul(Vec3 a,float s){return {a.x*s,a.y*s,a.z*s};}
Vec3 clampv(Vec3 v,float m){float l=len(v);return l>m&&l>E?mul(v,m/l):v;}
float approach(float a,float b,float d){return a<b?std::min(a+d,b):std::max(a-d,b);}
ActivityType activity(ScheduleAction a){switch(a){case ScheduleAction::Eat:return ActivityType::Eat;case ScheduleAction::Sleep:return ActivityType::Sleep;case ScheduleAction::Work:return ActivityType::Work;case ScheduleAction::Socialize:return ActivityType::Socialize;case ScheduleAction::Shop:return ActivityType::Shop;case ScheduleAction::MoveTo:return ActivityType::Travel;case ScheduleAction::Rest:return ActivityType::Rest;default:return ActivityType::Idle;}}
}
bool CharacterControllerConfig::valid()const noexcept{return fin(radius)&&radius>0&&fin(standing_height)&&standing_height>radius*2&&fin(crouching_height)&&crouching_height>radius*2&&crouching_height<=standing_height&&fin(walk_speed)&&walk_speed>=0&&fin(run_speed)&&run_speed>=walk_speed&&fin(crouch_speed)&&crouch_speed>=0&&fin(acceleration)&&acceleration>0&&fin(braking)&&braking>0&&fin(jump_speed)&&jump_speed>=0&&fin(gravity_scale)&&gravity_scale>=0&&fin(step_height)&&step_height>=0&&fin(slope_limit_degrees)&&slope_limit_degrees>0&&slope_limit_degrees<90&&fin(climb_speed)&&climb_speed>=0&&fin(swim_speed)&&swim_speed>=0;}
bool CharacterControllerInput::valid()const noexcept{return fin(move_x)&&fin(move_z)&&std::abs(move_x)<=1.0f&&std::abs(move_z)<=1.0f;}
bool CharacterControllerState::valid()const noexcept{return fin(velocity)&&fin(ground_normal)&&(!climbing||!swimming);}
void CharacterController::reset()noexcept{body=0;collider=0;state={};}
bool CharacterController::valid()const noexcept{return config.valid()&&state.valid()&&((body==0&&collider==0)||(body!=0&&collider!=0));}
bool CharacterController::create(PhysicsWorld&w,Vec3 p){if(!config.valid()||!fin(p)||body)return false;PhysicsRigidBodyDesc d;d.type=PhysicsBodyType::Kinematic;d.transform.position=p;d.flags=static_cast<PhysicsBodyFlags>(PhysicsBodyFlag::KinematicFollowsTransform);d.max_linear_speed=100;PhysicsBodyId b=w.create_body(d);if(!b)return false;PhysicsColliderDesc c;c.shape.type=PhysicsShapeType::Capsule;c.shape.data=PhysicsCapsuleShape{config.radius,std::max(0.01f,config.standing_height*.5f-config.radius)};c.layer=config.layer;c.mask=config.mask;PhysicsColliderId id=w.add_collider(b,c);if(!id){w.destroy_body(b);return false;}body=b;collider=id;state={};return true;}
bool CharacterController::destroy(PhysicsWorld&w)noexcept{bool ok=true;if(collider)ok=w.remove_collider(collider)&&ok;if(body)ok=w.destroy_body(body)&&ok;reset();return ok;}
std::optional<PhysicsTransform> CharacterController::transform(const PhysicsWorld&w)const noexcept{if(!body)return std::nullopt;return w.body_transform(body);}
bool CharacterController::update(PhysicsWorld&w,CharacterControllerInput in,float dt)noexcept{if(!valid()||!in.valid()||dt<=0||!fin(dt)||!body)return false;auto t=w.body_transform(body);if(!t)return false;state.posture=in.crouch?CharacterPosture::Crouching:CharacterPosture::Standing;state.climbing=in.climb;state.swimming=in.swim;Vec3 desired{in.move_x,0,in.move_z};float l=len(desired);if(l>1)desired=mul(desired,1/l);float speed=in.swim?config.swim_speed:(in.crouch?config.crouch_speed:(in.run?config.run_speed:config.walk_speed));desired=mul(desired,speed);Vec3 v=state.velocity;v.x=approach(v.x,desired.x,config.acceleration*dt);v.z=approach(v.z,desired.z,config.acceleration*dt);if(l<E){v.x=approach(v.x,0,config.braking*dt);v.z=approach(v.z,0,config.braking*dt);}if(in.climb){v.y=in.move_z*config.climb_speed;state.movement=CharacterMovementState::Climb;}else if(in.swim){v.y=in.move_z*config.swim_speed;state.movement=CharacterMovementState::Swim;}else{if(in.jump&&state.grounded)v.y=config.jump_speed;v.y-=9.80665f*config.gravity_scale*dt;state.movement=v.y>0.1f?CharacterMovementState::Jump:(std::abs(v.y)>0.1f?CharacterMovementState::Fall:(l<E?(in.crouch?CharacterMovementState::Crouch:CharacterMovementState::Idle):(in.crouch?CharacterMovementState::Crouch:(in.run?CharacterMovementState::Run:CharacterMovementState::Walk))));}v=clampv(v,100);PhysicsTransform nt=*t;nt.position=add(nt.position,mul(v,dt));if(!w.set_body_transform(body,nt,true))return false;state.velocity=v;state.grounded=false;return true;}
bool ItemDefinition::valid()const noexcept{return id!=0&&!name.empty()&&fin(mass)&&mass>0&&fin(value)&&value>=0&&fin(nutrition)&&nutrition>=0&&fin(hydration)&&hydration>=0&&fin(damage)&&damage>=0&&fin(range)&&range>0&&max_stack>0;}
Inventory::Inventory(uint32_t c):capacity_(std::max(1U,c)){} uint32_t Inventory::capacity()const noexcept{return capacity_;} const std::vector<InventorySlot>&Inventory::slots()const noexcept{return slots_;}
bool Inventory::add(ItemId id,uint32_t q,uint32_t max){if(!id||!q||!max)return false;uint32_t left=q;for(auto&s:slots_)if(s.item==id&&s.quantity<max){uint32_t n=std::min(left,max-s.quantity);s.quantity+=n;left-=n;if(!left)return true;}while(left&&slots_.size()<capacity_){uint32_t n=std::min(left,max);slots_.push_back({id,n});left-=n;}return left==0;}
bool Inventory::remove(ItemId id,uint32_t q){if(!id||!q||count(id)<q)return false;uint32_t left=q;for(auto&s:slots_)if(s.item==id&&left){uint32_t n=std::min(left,s.quantity);s.quantity-=n;left-=n;}slots_.erase(std::remove_if(slots_.begin(),slots_.end(),[](auto&s){return s.item==0||s.quantity==0;}),slots_.end());return true;}
uint32_t Inventory::count(ItemId id)const noexcept{uint32_t n=0;for(const auto&s:slots_)if(s.item==id)n+=s.quantity;return n;}void Inventory::clear()noexcept{slots_.clear();}
bool CharacterVitals::valid()const noexcept{return fin(health)&&fin(max_health)&&max_health>0&&health>=0&&health<=max_health&&fin(stamina)&&fin(max_stamina)&&max_stamina>0&&stamina>=0&&stamina<=max_stamina&&fin(hunger)&&hunger>=0&&hunger<=100&&fin(thirst)&&thirst>=0&&thirst<=100&&fin(fatigue)&&fatigue>=0&&fatigue<=100&&fin(oxygen)&&oxygen>=0&&oxygen<=100;}bool CharacterVitals::alive()const noexcept{return health>0;}
bool CharacterInstance::valid()const noexcept{return id!=0&&definition.appearance.height>0&&controller.valid()&&vitals.valid();}
bool InteractionTarget::valid()const noexcept{return id!=0&&fin(position)&&fin(radius)&&radius>0;}
bool ScheduleEntry::valid()const noexcept{return start_minute<1440&&end_minute<1440&&start_minute!=end_minute&&fin(target);}
bool NPCSchedule::valid()const noexcept{if(entries.empty())return true;for(const auto&e:entries)if(!e.valid())return false;return true;}
bool GameplayWorldSettings::valid()const noexcept{return fin(time_scale)&&time_scale>=0&&fin(seconds_per_game_minute)&&seconds_per_game_minute>0;}
struct GameplayWorld::Impl{GameplayWorldSettings settings;PhysicsWorld*physics=nullptr;std::unordered_map<CharacterId,CharacterInstance> chars;std::unordered_map<ItemId,ItemDefinition> items;std::unordered_map<InteractionId,InteractionTarget> interactions;std::unordered_map<CharacterId,NPCSchedule>schedules;std::unordered_map<CharacterId,NPCState>npc;std::vector<DamageEvent>events;CharacterId next_char=1;InteractionId next_interaction=1;float seconds=0;uint64_t minute=0;};
GameplayWorld::GameplayWorld(GameplayWorldSettings s):impl_(std::make_unique<Impl>()){impl_->settings=s;if(!s.valid())impl_->settings={};}GameplayWorld::~GameplayWorld()=default;GameplayWorld::GameplayWorld(GameplayWorld&&)noexcept=default;GameplayWorld&GameplayWorld::operator=(GameplayWorld&&)noexcept=default;const GameplayWorldSettings&GameplayWorld::settings()const noexcept{return impl_->settings;}
CharacterId GameplayWorld::create_character(CharacterDefinition d,Vec3 p){if(!impl_->physics||impl_->next_char==std::numeric_limits<CharacterId>::max())return 0;CharacterId id=impl_->next_char++;CharacterInstance c;c.id=id;c.type=d.type;c.definition=d;c.controller.config={};if(!c.controller.create(*impl_->physics,p))return 0;c.inventory=Inventory(32);impl_->chars.emplace(id,std::move(c));if(d.type==CharacterType::NPC)impl_->npc[id]={};return id;}
bool GameplayWorld::destroy_character(CharacterId id)noexcept{auto it=impl_->chars.find(id);if(it==impl_->chars.end())return false;if(impl_->physics)it->second.controller.destroy(*impl_->physics);impl_->chars.erase(it);impl_->npc.erase(id);impl_->schedules.erase(id);return true;}
CharacterInstance*GameplayWorld::character(CharacterId id)noexcept{auto i=impl_->chars.find(id);return i==impl_->chars.end()?nullptr:&i->second;}const CharacterInstance*GameplayWorld::character(CharacterId id)const noexcept{auto i=impl_->chars.find(id);return i==impl_->chars.end()?nullptr:&i->second;}std::vector<CharacterId>GameplayWorld::character_ids()const{std::vector<CharacterId>r;for(auto&[id,c]:impl_->chars)r.push_back(id);std::sort(r.begin(),r.end());return r;}
bool GameplayWorld::update_character(CharacterId id,CharacterControllerInput in,float dt)noexcept{auto*c=character(id);return c&&c->vitals.alive()&&!c->unconscious&&c->controller.update(*impl_->physics,in,dt);}
bool GameplayWorld::damage(const DamageEvent&e,CombatResult*r)noexcept{auto*t=character(e.target);if(!t||!t->vitals.alive()||!fin(e.amount)||e.amount<=0)return false;float amount=e.amount;t->vitals.health=std::max(0.0f,t->vitals.health-amount);t->unconscious=t->vitals.health<=0;if(t->unconscious)t->controller.state.movement=CharacterMovementState::Dead;impl_->events.push_back(e);if(r){r->hit=true;r->damage=amount;r->killed=t->unconscious;}return true;}
bool GameplayWorld::recover(CharacterId id,float a)noexcept{auto*c=character(id);if(!c||!fin(a)||a<=0)return false;c->vitals.health=std::min(c->vitals.max_health,c->vitals.health+a);if(c->vitals.health>0)c->unconscious=false;c->recovering=c->vitals.health<c->vitals.max_health;return true;}
bool GameplayWorld::set_equipped_item(CharacterId c,ItemId i)noexcept{auto*x=character(c);if(!x)return false;if(i&&x->inventory.count(i)==0)return false;x->equipped_item=i;return true;}
bool GameplayWorld::consume(CharacterId c,ItemId i)noexcept{auto*x=character(c);auto it=impl_->items.find(i);if(!x||it==impl_->items.end()||x->inventory.count(i)==0)return false;if(it->second.type!=ItemType::Food&&it->second.type!=ItemType::Drink)return false;if(!x->inventory.remove(i))return false;x->vitals.hunger=std::max(0.0f,x->vitals.hunger-it->second.nutrition);x->vitals.thirst=std::max(0.0f,x->vitals.thirst-it->second.hydration);return true;}
bool GameplayWorld::define_item(ItemDefinition d){if(!d.valid())return false;return impl_->items.emplace(d.id,std::move(d)).second;}const ItemDefinition*GameplayWorld::item(ItemId id)const noexcept{auto i=impl_->items.find(id);return i==impl_->items.end()?nullptr:&i->second;}bool GameplayWorld::remove_item_definition(ItemId id)noexcept{return impl_->items.erase(id)>0;}
InteractionId GameplayWorld::add_interaction(InteractionTarget t){if(!t.valid())return 0;if(!t.id)t.id=impl_->next_interaction++;if(impl_->interactions.count(t.id))return 0;impl_->interactions.emplace(t.id,t);return t.id;}bool GameplayWorld::remove_interaction(InteractionId id)noexcept{return impl_->interactions.erase(id)>0;}const InteractionTarget*GameplayWorld::interaction(InteractionId id)const noexcept{auto i=impl_->interactions.find(id);return i==impl_->interactions.end()?nullptr:&i->second;}
bool GameplayWorld::interact(CharacterId c,InteractionId id,InteractionType type)noexcept{auto*x=character(c);auto*t=impl_->interactions.find(id);if(!x||t==impl_->interactions.end()||!t->second.enabled||t->second.type!=type)return false;auto p=x->controller.transform(*impl_->physics);if(!p)return false;Vec3 d{p->position.x-t->second.position.x,p->position.y-t->second.position.y,p->position.z-t->second.position.z};if(len(d)>t->second.radius)return false;if(type==InteractionType::Pickup&&t->second.item){auto it=impl_->items.find(t->second.item);if(it==impl_->items.end()||!x->inventory.add(it->first,1,it->second.max_stack))return false;t->second.enabled=false;}else if(type==InteractionType::Sit)x->posture=CharacterPosture::Sitting;return true;}
bool GameplayWorld::set_schedule(CharacterId id,NPCSchedule s){auto*c=character(id);if(!c||c->type!=CharacterType::NPC||!s.valid())return false;impl_->schedules[id]=std::move(s);return true;}const NPCSchedule*GameplayWorld::schedule(CharacterId id)const noexcept{auto i=impl_->schedules.find(id);return i==impl_->schedules.end()?nullptr:&i->second;}const NPCState*GameplayWorld::npc_state(CharacterId id)const noexcept{auto i=impl_->npc.find(id);return i==impl_->npc.end()?nullptr:&i->second;}
void GameplayWorld::update(float dt)noexcept{if(dt<=0||!fin(dt))return;dt*=impl_->settings.time_scale;impl_->seconds+=dt;while(impl_->seconds>=impl_->settings.seconds_per_game_minute){impl_->seconds-=impl_->settings.seconds_per_game_minute;impl_->minute=(impl_->minute+1)%1440;}for(auto&[id,c]:impl_->chars){if(!c.vitals.alive()){c.recovering=true;continue;}c.vitals.hunger=std::min(100.0f,c.vitals.hunger+dt*.01f);c.vitals.thirst=std::min(100.0f,c.vitals.thirst+dt*.015f);c.vitals.fatigue=std::min(100.0f,c.vitals.fatigue+dt*.005f);if(c.vitals.hunger>=100||c.vitals.thirst>=100)c.vitals.health=std::max(0.0f,c.vitals.health-dt*.1f);auto s=impl_->schedules.find(id);if(s!=impl_->schedules.end()&&!s->second.entries.empty()){auto&ns=impl_->npc[id];for(size_t i=0;i<s->second.entries.size();++i){auto&e=s->second.entries[i];bool active=e.start_minute<e.end_minute?(impl_->minute>=e.start_minute&&impl_->minute<e.end_minute):(impl_->minute>=e.start_minute||impl_->minute<e.end_minute);if(active){ns.schedule_index=i;ns.activity=activity(e.action);ns.target=e.target;ns.target_entity=e.target_entity;break;}}}}}
impl_->events.clear();}
void GameplayWorld::clear()noexcept{if(impl_->physics)for(auto&[id,c]:impl_->chars)c.controller.destroy(*impl_->physics);impl_->chars.clear();impl_->npc.clear();impl_->schedules.clear();impl_->interactions.clear();impl_->items.clear();impl_->events.clear();impl_->minute=0;impl_->seconds=0;}
uint64_t GameplayWorld::game_minute()const noexcept{return impl_->minute;}const std::vector<DamageEvent>&GameplayWorld::damage_events()const noexcept{return impl_->events;}void GameplayWorld::bind_physics(PhysicsWorld*p)noexcept{impl_->physics=p;}PhysicsWorld*GameplayWorld::physics()noexcept{return impl_->physics;}
}