#include "exgine/gles_ibl.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <memory>
namespace exgine { namespace {
constexpr GlEnum FB=0x8D40,CA=0x8CE0,FBC=0x8CD5,CUBE=0x8513,MINF=0x2801,MAGF=0x2800,WS=0x2802,WT=0x2803,CLAMP=0x812F,LINEAR=0x2601,RGBA8=0x8058,RGBA16F=0x881A,RGBA=0x1908,UB=0x1401,HF=0x140B,VS=0x8B31,FS=0x8B30,COMPILE=0x8B81,LINK=0x8B82,LOG=0x8B84,TEX0=0x84C0,TRIS=0x0004;
const char*V=R"GLSL(#version 310 es
precision highp float;out vec2 v_uv;void main(){vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));vec2 q=p[gl_VertexID];gl_Position=vec4(q,0,1);v_uv=q*.5+.5;})GLSL";
const char*I=R"GLSL(#version 310 es
precision highp float;in vec2 v_uv;uniform samplerCube u_environment;uniform int u_face;out vec4 o;vec3 dir(){vec2 a=v_uv*2.-1.;if(u_face==0)return normalize(vec3(1.,-a.y,-a.x));if(u_face==1)return normalize(vec3(-1.,-a.y,a.x));if(u_face==2)return normalize(vec3(a.x,1.,a.y));if(u_face==3)return normalize(vec3(a.x,-1.,-a.y));if(u_face==4)return normalize(vec3(a.x,-a.y,1.));return normalize(vec3(-a.x,-a.y,-1.));}void basis(vec3 n,out vec3 t,out vec3 b){vec3 up=abs(n.y)<.999?vec3(0,1,0):vec3(1,0,0);t=normalize(cross(up,n));b=cross(n,t);}void main(){vec3 n=dir(),t,b;basis(n,t,b);vec3 c=vec3(0);float w=0.;const float pi=3.14159265359;for(int y=0;y<8;y++)for(int x=0;x<8;x++){float u=(float(x)+.5)/8.;float v=(float(y)+.5)/8.;float phi=2.*pi*u;float cosT=sqrt(1.-v);float sinT=sqrt(v);vec3 l=normalize(t*cos(phi)*sinT+b*sin(phi)*sinT+n*cosT);float nd=max(dot(n,l),0.);c+=texture(u_environment,l).rgb*nd;w+=nd;}o=vec4(c/max(w,1e-4),1);})GLSL";
const char*G=R"GLSL(#version 310 es
precision highp float;in vec2 v_uv;uniform samplerCube u_environment;uniform int u_face;uniform float u_roughness;uniform float u_source_max_lod;out vec4 o;const float pi=3.14159265359;vec3 dir(){vec2 a=v_uv*2.-1.;if(u_face==0)return normalize(vec3(1.,-a.y,-a.x));if(u_face==1)return normalize(vec3(-1.,-a.y,a.x));if(u_face==2)return normalize(vec3(a.x,1.,a.y));if(u_face==3)return normalize(vec3(a.x,-1.,-a.y));if(u_face==4)return normalize(vec3(a.x,-a.y,1.));return normalize(vec3(-a.x,-a.y,-1.));}float radicalInverse(uint bits){bits=(bits<<16u)|(bits>>16u);bits=((bits&0x55555555u)<<1u)|((bits&0xAAAAAAAAu)>>1u);bits=((bits&0x33333333u)<<2u)|((bits&0xCCCCCCCCu)>>2u);bits=((bits&0x0F0F0F0Fu)<<4u)|((bits&0xF0F0F0F0u)>>4u);bits=((bits&0x00FF00FFu)<<8u)|((bits&0xFF00FF00u)>>8u);return float(bits)*2.3283064365386963e-10;}vec2 hammersley(uint i,uint n){return vec2(float(i)/float(n),radicalInverse(i));}vec3 importance(vec2 xi,vec3 n,float a){float a2=a*a;float phi=2.*pi*xi.x;float cosT=sqrt((1.-xi.y)/(1.+(a2-1.)*xi.y));float sinT=sqrt(max(0.,1.-cosT*cosT));vec3 up=abs(n.y)<.999?vec3(0,1,0):vec3(1,0,0);vec3 t=normalize(cross(up,n)),b=cross(n,t);return normalize(t*cos(phi)*sinT+b*sin(phi)*sinT+n*cosT);}void main(){vec3 n=dir(),v=n;float a=max(.001,u_roughness*u_roughness);vec3 c=vec3(0);float w=0.;const uint N=256u;for(uint i=0u;i<N;i++){vec3 h=importance(hammersley(i,N),n,a);vec3 l=normalize(2.*dot(v,h)*h-v);float nd=max(dot(n,l),0.);if(nd>0.){float lod=0.;if(u_source_max_lod>0.){float d=abs(dot(n,l));float saTexel=4.*pi/(6.*1024.*1024.);float saSample=1./(float(N)*max(nd,1e-4));lod=max(0.,.5*log2(saSample/saTexel));lod=min(lod,u_source_max_lod);}c+=textureLod(u_environment,l,lod).rgb*nd;w+=nd;}}o=vec4(c/max(w,1e-4),1);})GLSL";
bool sh(OpenGLESApi&a,GlEnum t,const char*s,GlUInt&o,std::string&e){o=a.CreateShader(t);if(!o){e="IBL shader allocation failed";return false;}GlInt n=(GlInt)std::strlen(s);a.ShaderSource(o,1,&s,&n);a.CompileShader(o);GlInt ok=0;a.GetShaderiv(o,COMPILE,&ok);if(ok)return true;GlInt l=0,w=0;a.GetShaderiv(o,LOG,&l);std::vector<char>m(std::max(1,l));a.GetShaderInfoLog(o,l,&w,m.data());e.assign(m.data(),std::max(0,w));a.DeleteShader(o);o=0;return false;}
bool prog(OpenGLESApi&a,const char*v,const char*f,GlUInt&o,std::string&e){GlUInt vs=0,fs=0;if(!sh(a,VS,v,vs,e)||!sh(a,FS,f,fs,e)){if(vs)a.DeleteShader(vs);if(fs)a.DeleteShader(fs);return false;}o=a.CreateProgram();a.AttachShader(o,vs);a.AttachShader(o,fs);a.LinkProgram(o);a.DeleteShader(vs);a.DeleteShader(fs);GlInt ok=0;a.GetProgramiv(o,LINK,&ok);if(ok)return true;GlInt l=0,w=0;a.GetProgramiv(o,LOG,&l);std::vector<char>m(std::max(1,l));a.GetProgramInfoLog(o,l,&w,m.data());e.assign(m.data(),std::max(0,w));a.DeleteProgram(o);o=0;return false;}
bool target(OpenGLESApi&a,const GlesCubeResource&c,std::uint32_t face,std::uint32_t mip,GlUInt f,std::string&e){a.BindFramebuffer(FB,f);a.FramebufferTexture2D(FB,CA,CUBE,c.texture,cube_faces()[face].target);return a.CheckFramebufferStatus(FB)==FBC;}
bool alloc(OpenGLESApi&a,std::uint32_t size,std::uint32_t mips,GlInt fmt,GlesCubeResource&o,std::string&e){return create_cubemap(a,size,mips,fmt,o,e);}
bool render(OpenGLESRenderer&r,const GlesCubeResource&src,std::uint32_t dstSize,std::uint32_t mips,bool ggx,GlesCubeResource&dst,std::string&e){auto&a=const_cast<OpenGLESApi&>(r.api());if(!a.complete()||!src.valid){e="IBL requires complete GLES API and environment cube";return false;}if(!alloc(a,dstSize,mips,RGBA16F,dst,e))return false;GlUInt f=0;a.GenFramebuffers(1,&f);GlUInt p=0;if(!prog(a,V,ggx?G:I,p,e)){if(f)a.DeleteFramebuffers(1,&f);return false;}a.UseProgram(p);auto us=a.GetUniformLocation(p,"u_environment"),uf=a.GetUniformLocation(p,"u_face"),ur=a.GetUniformLocation(p,"u_roughness"),ul=a.GetUniformLocation(p,"u_source_max_lod");a.ActiveTexture(TEX0);a.BindTexture(CUBE,src.texture);if(us>=0)a.Uniform1i(us,0);if(ul>=0)a.Uniform1f(ul,float(src.mip_levels?src.mip_levels-1:0));a.BindVertexArray(0);for(std::uint32_t m=0;m<mips;m++){auto size=std::max(1u,dstSize>>m);a.Viewport(0,0,(GlInt)size,(GlInt)size);if(ur>=0)a.Uniform1f(ur,mips>1?float(m)/float(mips-1):0.f);for(int face=0;face<6;face++){if(!target(a,dst,std::uint32_t(face),m,f,e)){a.DeleteProgram(p);a.DeleteFramebuffers(1,&f);a.DeleteTextures(1,&dst.texture);dst={};return false;}if(uf>=0)a.Uniform1i(uf,face);a.Clear(0);a.DrawArrays(TRIS,0,3);}}a.BindFramebuffer(FB,0);a.DeleteProgram(p);a.DeleteFramebuffers(1,&f);dst.valid=true;return true;}
}
bool ingest_environment_cubemap(OpenGLESApi&a,const std::array<EnvironmentFacePixels,6>&faces,std::uint32_t size,GlesCubeResource&o,std::string&e)noexcept{if(size==0){e="environment cube size is zero";return false;}if(!create_cubemap(a,size,1,faces[0].internal_format,o,e))return false;for(std::size_t i=0;i<6;i++){if(!faces[i].data||faces[i].size!=size){e="environment cube face mismatch";if(o.texture)a.DeleteTextures(1,&o.texture);o={};return false;}if(!upload_cubemap_face(a,o,0,cube_faces()[i].target,faces[i].internal_format,faces[i].format,faces[i].type,faces[i].data,size)){e="environment face upload failed";a.DeleteTextures(1,&o.texture);o={};return false;}}o.valid=true;return true;}
bool gpu_convolve_irradiance(OpenGLESRenderer&r,const GlesCubeResource&src,std::uint32_t size,GlesCubeResource&o,std::string&e)noexcept{return render(r,src,size,1,false,o,e);}
bool gpu_prefilter_ggx(OpenGLESRenderer&r,const GlesCubeResource&src,std::uint32_t size,std::uint32_t mips,GlesCubeResource&o,std::string&e)noexcept{if(mips==0){e="GGX mip count is zero";return false;}return render(r,src,size,mips,true,o,e);}
bool build_gpu_ibl(OpenGLESRenderer&r,const GlesCubeResource&src,std::uint32_t irrSize,std::uint32_t specMips,GpuIblResources&o,std::string&e)noexcept{o={};o.environment=src;if(!gpu_convolve_irradiance(r,src,irrSize,o.irradiance,e))return false;if(!gpu_prefilter_ggx(r,src,src.size,specMips,o.specular,e))return false;o.valid=true;return true;}
const char* gpu_ibl_vertex_shader()noexcept{return V;}const char* gpu_irradiance_fragment_shader()noexcept{return I;}const char* gpu_ggx_prefilter_fragment_shader()noexcept{return G;}
}