#include "exgine/gles_tracks.hpp"
#include <algorithm>
#include <cmath>
#include <functional>
#include <utility>
namespace exgine{namespace{constexpr GlEnum CUBE=0x8513,CUBE_POS=0x8515,MINF=0x2801,MAGF=0x2800,WS=0x2802,WT=0x2803,WR=0x8072,CLAMP=0x812F,LINEAR=0x2601,LMIP=0x2703,RGBA=0x1908,UB=0x1401,HF=0x140B;std::pair<int,int>parse_version(std::string_view s)noexcept{int a=0,b=0;auto p=s.find("OpenGL ES ");std::size_t i=p==std::string_view::npos?0:p+10;while(i<s.size()&&s[i]>='0'&&s[i]<='9'){a=a*10+s[i]-'0';++i;}if(i<s.size()&&s[i]=='.'){++i;while(i<s.size()&&s[i]>='0'&&s[i]<='9'){b=b*10+s[i]-'0';++i;}}return{a,b};}bool has(std::string_view s,std::string_view n)noexcept{return s.find(n)!=std::string_view::npos;}}
GlesCapabilities profile_gles(OpenGLESApi&api,std::string_view version,std::string_view extensions)noexcept{GlesCapabilities c{};auto[a,b]=parse_version(version);c.major=a;c.minor=b;c.es31=a>3||(a==3&&b>=1);c.max_texture_size=c.es31?16384:4096;c.max_texture_units=c.es31?16:8;c.compute=c.es31;c.ssbo=c.es31&&api.BindBufferBase!=nullptr;c.indirect=c.es31&&api.DrawElementsInstanced!=nullptr;c.cubemap=api.GenTextures&&api.BindTexture&&api.TexImage2D;c.color_buffer_float=c.es31||has(extensions,"EXT_color_buffer_float")||has(extensions,"EXT_color_buffer_half_float");c.depth24=c.es31||has(extensions,"OES_depth24");c.highp_fragment=c.es31;return c;}
std::array<CubeFaceCapture,6>cube_faces()noexcept{return{{{CUBE_POS,{1,0,0},{0,-1,0}},{CUBE_POS+1,{-1,0,0},{0,-1,0}},{CUBE_POS+2,{0,1,0},{0,0,1}},{CUBE_POS+3,{0,-1,0},{0,0,-1}},{CUBE_POS+4,{0,0,1},{0,-1,0}},{CUBE_POS+5,{0,0,-1},{0,-1,0}}}};}
bool create_cubemap(OpenGLESApi&api,std::uint32_t size,std::uint32_t mips,GlInt internal,GlesCubeResource&out,std::string&err){if(!api.GenTextures||!api.BindTexture||!api.TexImage2D||!size||!mips){err="cubemap API unavailable";return false;}if(out.texture&&api.DeleteTextures)api.DeleteTextures(1,&out.texture);api.GenTextures(1,&out.texture);if(!out.texture){err="cubemap allocation failed";return false;}api.BindTexture(CUBE,out.texture);api.TexParameteri(CUBE,MINF,mips>1?LMIP:LINEAR);api.TexParameteri(CUBE,MAGF,LINEAR);api.TexParameteri(CUBE,WS,CLAMP);api.TexParameteri(CUBE,WT,CLAMP);api.TexParameteri(CUBE,WR,CLAMP);for(std::uint32_t mip=0;mip<mips;++mip){const GlInt s=(GlInt)std::max(1u,size>>mip);for(const auto&f:cube_faces())api.TexImage2D(f.target,(GlInt)mip,internal,s,s,0,RGBA,internal==0x881A?HF:UB,nullptr);}out={out.texture,size,mips,true};return true;}
bool upload_cubemap_face(OpenGLESApi&api,const GlesCubeResource&c,std::uint32_t mip,GlEnum face,GlInt internal,GlEnum format,GlEnum type,const void*p,std::uint32_t size){if(!c.valid||mip>=c.mip_levels||!api.BindTexture||!api.TexImage2D)return false;api.BindTexture(CUBE,c.texture);api.TexImage2D(face,(GlInt)mip,internal,(GlInt)size,(GlInt)size,0,format,type,p);return true;}
TerrainGpuPatch build_terrain_patch(std::uint32_t r,std::uint8_t mask,float morph)noexcept{TerrainGpuPatch p{};p.resolution=std::max(2u,r);p.stitch_mask=mask;p.morph=std::clamp(morph,0.f,1.f);const auto n=p.resolution;p.vertices.reserve(n*n);for(std::uint32_t z=0;z<n;++z)for(std::uint32_t x=0;x<n;++x){float fx=float(x)/float(n-1),fz=float(z)/float(n-1),edge=0;bool stitched=((mask&1)&&z==n-1)||((mask&2)&&x==n-1)||((mask&4)&&z==0)||((mask&8)&&x==0);if(stitched)edge=p.morph;p.vertices.push_back({{fx,0,fz},edge});}p.indices.reserve((n-1)*(n-1)*6);auto id=[&](std::uint32_t x,std::uint32_t z){return z*n+x;};for(std::uint32_t z=0;z+1<n;++z)for(std::uint32_t x=0;x+1<n;++x)p.indices.insert(p.indices.end(),{id(x,z),id(x+1,z),id(x+1,z+1),id(x,z),id(x+1,z+1),id(x,z+1)});return p;}
std::vector<VegetationBatch>build_vegetation_batches(const std::vector<RenderDrawCall>&draws){std::vector<VegetationBatch>out;std::unordered_map<std::uint64_t,std::size_t>map;for(const auto&d:draws){if(d.animated()||d.pass!=RenderPass::Opaque||!d.geometry||d.part_index>=d.geometry->parts.size())continue;auto k=(std::uint64_t)(reinterpret_cast<std::uintptr_t>(d.geometry.get()))^((std::uint64_t)(reinterpret_cast<std::uintptr_t>(d.material.textures.get()))<<1);auto it=map.find(k);if(it==map.end()){map.emplace(k,out.size());out.push_back({k,0,{}});it=map.find(k);}out[it->second].instances.push_back({d.model,0});}return out;}
IndirectElementsCommand make_indirect_command(std::uint32_t c,std::uint32_t n,std::uint32_t first)noexcept{return{c,n,first,0,0};}
bool GpuAssetStreamController::request(std::uint64_t id,float priority,std::uint32_t gen){if(!id)return false;queue_.request({id,priority,gen});states_[id]={StreamedAssetState::Stage::Requested,gen,0};return true;}bool GpuAssetStreamController::mark_decoded(std::uint64_t id,std::uint32_t gen,std::size_t bytes){auto i=states_.find(id);if(i==states_.end()||i->second.generation!=gen)return false;i->second.stage=StreamedAssetState::Stage::Decoded;i->second.decoded_bytes=bytes;return true;}bool GpuAssetStreamController::make_resident(std::uint64_t id,const Mesh&m,std::uint64_t frame,std::string&err){auto i=states_.find(id);if(i==states_.end())return false;if(!residency_.upload(id,m,frame,err)){i->second.stage=StreamedAssetState::Stage::Failed;return false;}i->second.stage=StreamedAssetState::Stage::Resident;return true;}bool GpuAssetStreamController::touch(std::uint64_t id,std::uint64_t frame)noexcept{return residency_.touch(id,frame);}bool GpuAssetStreamController::evict(std::uint64_t id)noexcept{if(!residency_.evict(id))return false;auto i=states_.find(id);if(i!=states_.end())i->second.stage=StreamedAssetState::Stage::Evicted;return true;}const StreamedAssetState*GpuAssetStreamController::state(std::uint64_t id)const noexcept{auto i=states_.find(id);return i==states_.end()?nullptr:&i->second;}}
