#include "exgine/gles_vegetation_pbr.hpp"
#include <algorithm>
#include <cstring>
namespace exgine { namespace {
constexpr GlEnum SSBO=0x90D2,ARRAY=0x8892,DYNAMIC=0x88E8,TEX0=0x84C0,T2D=0x0DE1;
const char*V=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=1)in vec3 a_normal;layout(location=2)in vec2 a_uv;layout(std430,binding=0)readonly buffer Models{mat4 model[];};uniform mat4 u_view_projection;uniform uint u_base_instance;out vec3 v_world_pos;out vec3 v_normal;out vec2 v_uv;void main(){mat4 m=model[uint(gl_InstanceID)+u_base_instance];vec4 p=m*vec4(a_position,1.);v_world_pos=p.xyz;v_normal=normalize(mat3(m)*a_normal);v_uv=a_uv;gl_Position=u_view_projection*p;})GLSL";
const char*F=R"GLSL(#version 310 es
precision highp float;struct M{vec4 base_rough;vec4 metal_spec;vec4 emission_opacity;vec4 use_maps;};layout(std430,binding=1)readonly buffer Materials{M material;};uniform sampler2D u_base_color,u_roughness,u_metallic,u_normal,u_ao,u_emission,u_opacity;uniform samplerCube u_ibl_irradiance,u_ibl_specular;uniform float u_ibl_intensity,u_ibl_max_lod;in vec3 v_world_pos;in vec3 v_normal;in vec2 v_uv;out vec4 o;void main(){M m=material;vec3 base=m.base_rough.rgb;if(m.use_maps.x>0.5)base*=texture(u_base_color,v_uv).rgb;float rough=clamp(m.base_rough.a*(m.use_maps.y>0.5?texture(u_roughness,v_uv).r:1.),.04,1.);float metal=clamp(m.metal_spec.x*(m.use_maps.z>0.5?texture(u_metallic,v_uv).r:1.),0.,1.);vec3 n=normalize(v_normal);if(m.use_maps.w>0.5)n=normalize(n+(texture(u_normal,v_uv).xyz*2.-1.));float ao=1.;if(m.use_maps.y>1.5)ao=texture(u_ao,v_uv).r;vec3 irr=texture(u_ibl_irradiance,n).rgb;vec3 r=reflect(normalize(-v_world_pos),n);vec3 spec=textureLod(u_ibl_specular,r,rough*u_ibl_max_lod).rgb;vec3 f0=mix(vec3(.04)*m.metal_spec.y,base,metal);vec3 kd=(1.-f0)*(1.-metal);vec3 c=(irr*base*kd+spec*f0)*u_ibl_intensity*ao+m.emission_opacity.rgb;o=vec4(c,m.emission_opacity.a);})GLSL";
}
bool upload_vegetation_material(OpenGLESApi&a,const Material&m,const VegetationTextureHandles&t,VegetationPbrBinding&o,std::string&e)noexcept{if(!a.GenBuffers||!a.BindBuffer||!a.BufferData||!a.BindBufferBase){e="vegetation PBR requires SSBO support";return false;}release_vegetation_material(a,o);o.material.base_color=m.base_color;o.material.roughness=m.roughness;o.material.metallic=m.metallic;o.material.specular=m.specular;o.material.emission=m.emission;o.material.opacity=m.opacity;o.textures=t;a.GenBuffers(1,&o.material_ssbo);if(!o.material_ssbo){e="vegetation material SSBO allocation failed";return false;}struct Packed{float base[4],metal[4],emission[4],maps[4];}p{{m.base_color.r,m.base_color.g,m.base_color.b,m.roughness},{m.metallic,m.specular,0,0},{m.emission.r,m.emission.g,m.emission.b,m.opacity},{t.valid[0]?1.f:0.f,t.valid[1]?1.f:0.f,t.valid[2]?1.f:0.f,t.valid[3]?1.f:0.f}};a.BindBuffer(SSBO,o.material_ssbo);a.BufferData(SSBO,sizeof(p),&p,DYNAMIC);a.BindBufferBase(SSBO,1,o.material_ssbo);return true;}
void release_vegetation_material(OpenGLESApi&a,VegetationPbrBinding&o)noexcept{if(o.material_ssbo&&a.DeleteBuffers)a.DeleteBuffers(1,&o.material_ssbo);o={};}
const char*vegetation_pbr_vertex_shader()noexcept{return V;}const char*vegetation_pbr_fragment_shader()noexcept{return F;}
}