#include "exgine/gles_production_complete.hpp"
#include "exgine/advanced_render.hpp"
#include "exgine/gles_gpu_driven.hpp"
#include "exgine/gles_ibl.hpp"
#include "exgine/gles_production_hardening.hpp"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>
namespace exgine{namespace{
constexpr GlEnum FB=0x8D40,CA=0x8CE0,DA=0x8D00,FBC=0x8CD5,T2D=0x0DE1,CUBE=0x8513,MINF=0x2801,MAGF=0x2800,WS=0x2802,WT=0x2803,CLAMP=0x812F,LINEAR=0x2601,R16F=0x881A,RGBA8=0x8058,RGBA=0x1908,HF=0x140B,UB=0x1401,D24=0x81A6,D16=0x81A5,UI=0x1405,US=0x1403,DEPTH=0x1902,VS=0x8B31,FS=0x8B30,COMPILE=0x8B81,LINK=0x8B82,LOG=0x8B84,ARRAY=0x8892,ELEM=0x8893,STATIC=0x88E4,FLOAT=0x1406,U32=0x1405,TRIS=0x0004,DEPTH_TEST=0x0B71;
struct Target{GlUInt fbo=0,color=0,depth=0;int w=0,h=0;bool hdr=false;};struct ShadowMesh{GlUInt vao=0,vb=0,ib=0;std::size_t count=0;bool skinned=false;};struct State{int w=0,h=0;Target hdr{},shadow{};std::vector<Target>a,b;GlesCubeResource env{},irr{},spec{};GlUInt post=0,down=0,up=0,tone=0,shadow_program=0;std::unordered_map<std::uint64_t,ShadowMesh>shadow_meshes;bool ready=false;};std::mutex mutex_;std::unordered_map<const OpenGLESRenderer*,std::unique_ptr<State>>states_;
void dt(OpenGLESApi&a,Target&t){if(t.fbo&&a.DeleteFramebuffers)a.DeleteFramebuffers(1,&t.fbo);if(t.color&&a.DeleteTextures)a.DeleteTextures(1,&t.color);if(t.depth&&a.DeleteTextures)a.DeleteTextures(1,&t.depth);t={};}
bool color(OpenGLESApi&a,int w,int h,Target&t,bool hdr){dt(a,t);t={0,0,0,w,h,hdr};a.GenTextures(1,&t.color);a.BindTexture(T2D,t.color);a.TexParameteri(T2D,MINF,LINEAR);a.TexParameteri(T2D,MAGF,LINEAR);a.TexParameteri(T2D,WS,CLAMP);a.TexParameteri(T2D,WT,CLAMP);a.TexImage2D(T2D,0,hdr?R16F:RGBA8,w,h,0,RGBA,hdr?HF:UB,nullptr);a.GenFramebuffers(1,&t.fbo);a.BindFramebuffer(FB,t.fbo);a.FramebufferTexture2D(FB,CA,T2D,t.color,0);a.GenTextures(1,&t.depth);a.BindTexture(T2D,t.depth);a.TexImage2D(T2D,0,D24,w,h,0,DEPTH,UI,nullptr);a.FramebufferTexture2D(FB,DA,T2D,t.depth,0);return a.CheckFramebufferStatus(FB)==FBC;}
bool depth_target(OpenGLESApi&a,int n,Target&t){dt(a,t);t.w=t.h=n;a.GenTextures(1,&t.depth);a.BindTexture(T2D,t.depth);a.TexParameteri(T2D,MINF,LINEAR);a.TexParameteri(T2D,MAGF,LINEAR);a.TexParameteri(T2D,WS,CLAMP);a.TexParameteri(T2D,WT,CLAMP);a.TexImage2D(T2D,0,D24,n,n,0,DEPTH,UI,nullptr);a.GenFramebuffers(1,&t.fbo);a.BindFramebuffer(FB,t.fbo);a.FramebufferTexture2D(FB,DA,T2D,t.depth,0);if(a.CheckFramebufferStatus(FB)==FBC)return true;dt(a,t);t.w=t.h=n;a.GenTextures(1,&t.depth);a.BindTexture(T2D,t.depth);a.TexImage2D(T2D,0,D16,n,n,0,DEPTH,US,nullptr);a.GenFramebuffers(1,&t.fbo);a.BindFramebuffer(FB,t.fbo);a.FramebufferTexture2D(FB,DA,T2D,t.depth,0);return a.CheckFramebufferStatus(FB)==FBC;}
bool shader(OpenGLESApi&a,GlEnum type,const char*s,GlUInt&out,std::string&err){out=a.CreateShader(type);if(!out){err="shader allocation failed";return false;}GlInt len=(GlInt)std::strlen(s);a.ShaderSource(out,1,&s,&len);a.CompileShader(out);GlInt ok=0;a.GetShaderiv(out,COMPILE,&ok);if(ok)return true;GlInt n=0,w=0;a.GetShaderiv(out,LOG,&n);std::vector<char>log((std::size_t)std::max(1,n));a.GetShaderInfoLog(out,n,&w,log.data());err.assign(log.data(),(std::size_t)std::max(0,w));a.DeleteShader(out);out=0;return false;}
bool program(OpenGLESApi&a,const char*vs,const char*fs,GlUInt&out,std::string&err){GlUInt v=0,f=0;if(!shader(a,VS,vs,v,err)||!shader(a,FS,fs,f,err)){if(v)a.DeleteShader(v);if(f)a.DeleteShader(f);return false;}out=a.CreateProgram();if(!out){err="program allocation failed";a.DeleteShader(v);a.DeleteShader(f);return false;}a.AttachShader(out,v);a.AttachShader(out,f);a.LinkProgram(out);a.DeleteShader(v);a.DeleteShader(f);GlInt ok=0;a.GetProgramiv(out,LINK,&ok);if(ok)return true;GlInt n=0,w=0;a.GetProgramiv(out,LOG,&n);std::vector<char>log((std::size_t)std::max(1,n));a.GetProgramInfoLog(out,&n,&w,log.data());err.assign(log.data(),(std::size_t)std::max(0,w));a.DeleteProgram(out);out=0;return false;}
State&get(OpenGLESRenderer&r){std::lock_guard<std::mutex>l(mutex_);auto&x=states_[&r];if(!x)x=std::make_unique<State>();return*x;}
void destroy(OpenGLESApi&a,State&s){if(a.DeleteProgram)for(auto p:{s.down,s.up,s.tone,s.shadow_program})if(p)a.DeleteProgram(p);if(s.post&&a.DeleteVertexArrays)a.DeleteVertexArrays(1,&s.post);for(auto&[k,m]:s.shadow_meshes){(void)k;if(a.DeleteVertexArrays&&m.vao)a.DeleteVertexArrays(1,&m.vao);if(a.DeleteBuffers&&m.vb)a.DeleteBuffers(1,&m.vb);if(a.DeleteBuffers&&m.ib)a.DeleteBuffers(1,&m.ib);}dt(a,s.hdr);dt(a,s.shadow);for(auto&x:s.a)dt(a,x);for(auto&x:s.b)dt(a,x);if(a.DeleteTextures){if(s.env.texture)a.DeleteTextures(1,&s.env.texture);if(s.irr.texture)a.DeleteTextures(1,&s.irr.texture);if(s.spec.texture)a.DeleteTextures(1,&s.spec.texture);}s={};}
Vec3 norm(Vec3 v){float l=std::sqrt(v.x*v.x+v.y*v.y+v.z*v.z);return l>1e-6f?Vec3{v.x/l,v.y/l,v.z/l}:Vec3{0,1,0};}
Mat4 look_at(Vec3 p,Vec3 d,Vec3 upv){d=norm(d);Vec3 r=norm(Vec3{upv.y*d.z-upv.z*d.y,upv.z*d.x-upv.x*d.z,upv.x*d.y-upv.y*d.x});Vec3 u=Vec3{d.y*r.z-d.z*r.y,d.z*r.x-d.x*r.z,d.x*r.y-d.y*r.x};Mat4 m=Mat4::identity();m.at(0,0)=r.x;m.at(1,0)=r.y;m.at(2,0)=r.z;m.at(0,1)=u.x;m.at(1,1)=u.y;m.at(2,1)=u.z;m.at(0,2)=-d.x;m.at(1,2)=-d.y;m.at(2,2)=-d.z;m.at(0,3)=-r.x*p.x-r.y*p.y-r.z*p.z;m.at(1,3)=-u.x*p.x-u.y*p.y-u.z*p.z;m.at(2,3)=d.x*p.x+d.y*p.y+d.z*p.z;return m;}
const char*pv=R"GLSL(#version 310 es
precision highp float;void main(){vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));gl_Position=vec4(p[gl_VertexID],0,1);})GLSL";
const char*df=R"GLSL(#version 310 es
precision highp float;uniform sampler2D u_source;uniform float u_threshold,u_knee;out vec4 o;void main(){vec2 t=1./vec2(textureSize(u_source,0)),u=gl_FragCoord.xy/vec2(textureSize(u_source,0));vec3 c=.25*(texture(u_source,u-t*.5).rgb+texture(u_source,u+vec2(t.x,-t.y)*.5).rgb+texture(u_source,u+vec2(-t.x,t.y)*.5).rgb+texture(u_source,u+t*.5).rgb);float l=max(max(c.r,c.g),c.b),k=max(u_knee,1e-4),w=clamp((l-u_threshold+k)/(2*k),0,1);o=vec4(c*w*w,1);})GLSL";
const char*uf=R"GLSL(#version 310 es
precision highp float;uniform sampler2D u_low,u_high;out vec4 o;void main(){vec2 u=gl_FragCoord.xy/vec2(textureSize(u_low,0));o=vec4(texture(u_low,u).rgb+texture(u_high,u).rgb,1);})GLSL";
const char*tf=R"GLSL(#version 310 es
precision highp float;uniform sampler2D u_hdr,u_bloom;uniform float u_exposure,u_bloom_intensity,u_gamma;out vec4 o;vec3 A(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0,1);}void main(){vec2 u=gl_FragCoord.xy/vec2(textureSize(u_hdr,0));vec3 c=A(texture(u_hdr,u).rgb*exp2(u_exposure)+texture(u_bloom,u).rgb*u_bloom_intensity);o=vec4(pow(max(c,vec3(0)),vec3(1./max(u_gamma,.1))),1);})GLSL";
const char*sv=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=3)in vec4 a_ids;layout(location=4)in vec4 a_weights;uniform mat4 u_light_vp,u_model,u_bones[128];uniform int u_bone_count;void main(){vec4 p=vec4(a_position,1);if(u_bone_count>0){mat4 s=mat4(0);for(int i=0;i<4;i++){int id=int(a_ids[i])-1;float w=a_weights[i];if(id>=0&&id<u_bone_count&&w>0)s+=u_bones[id]*w;}p=s*p;}gl_Position=u_light_vp*u_model*p;})GLSL";const char*sf=R"GLSL(#version 310 es
precision highp float;void main(){}GLSL";
std::vector<unsigned char>face(int n,const AtmosphereSettings&s,Vec3 d,Vec3 r,Vec3 u,float scale){std::vector<unsigned char>p((std::size_t)n*n*4);for(int y=0;y<n;y++)for(int x=0;x<n;x++){float aa=(2.f*(x+.5f)/n-1)*scale,bb=(2.f*(y+.5f)/n-1)*scale;auto c=evaluate_sky(s,norm(Vec3{d.x+aa*r.x+bb*u.x,d.y+aa*r.y+bb*u.y,d.z+aa*r.z+bb*u.z}),norm({.35f,.8f,.25f}));auto i=(std::size_t)(y*n+x)*4;p[i]=(unsigned char)(std::clamp(c.r,0.f,1.f)*255);p[i+1]=(unsigned char)(std::clamp(c.g,0.f,1.f)*255);p[i+2]=(unsigned char)(std::clamp(c.b,0.f,1.f)*255);p[i+3]=255;}return p;}
void ibl(OpenGLESRenderer&r,State&s,const RenderPipelinePlan&p){auto&a=const_cast<OpenGLESApi&>(r.api());std::string e;if(!s.env.valid){if(!create_cubemap(a,p.ibl.specular_size,p.ibl.specular_mips,RGBA8,s.env,e))return;for(const auto&f:cube_faces()){Vec3 rr=norm({f.up.y*f.direction.z-f.up.z*f.direction.y,f.up.z*f.direction.x-f.up.x*f.direction.z,f.up.x*f.direction.y-f.up.y*f.direction.x});auto ep=face(s.env.size,p.atmosphere,f.direction,rr,f.up,1);upload_cubemap_face(a,s.env,0,f.target,RGBA8,RGBA,UB,ep.data(),s.env.size);}if(a.GenerateMipmap){a.BindTexture(CUBE,s.env.texture);a.GenerateMipmap(CUBE);}}if(!s.irr.valid||!s.spec.valid){GpuIblResources g;if(build_gpu_ibl(r,s.env,p.ibl.irradiance_size,p.ibl.specular_mips,g,e)){if(s.irr.texture&&a.DeleteTextures)a.DeleteTextures(1,&s.irr.texture);if(s.spec.texture&&a.DeleteTextures)a.DeleteTextures(1,&s.spec.texture);s.irr=g.irradiance;s.spec=g.specular;}}
}
std::uint64_t skey(const RenderDrawCall&d)noexcept{return static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(d.geometry.get()))^(static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(d.skinned_mesh.get()))<<1)^(static_cast<std::uint64_t>(d.part_index)+0x9e3779b97f4a7c15ULL);}
ShadowMesh*shadow_mesh(OpenGLESApi&a,State&s,const RenderDrawCall&d){auto k=skey(d);auto it=s.shadow_meshes.find(k);if(it!=s.shadow_meshes.end())return &it->second;ShadowMesh m{};std::vector<float>v;std::vector<std::uint32_t>ix;if(d.animated()){if(!d.skinned_mesh)return nullptr;m.skinned=true;for(const auto&x:d.skinned_mesh->vertices)v.insert(v.end(),{x.position.x,x.position.y,x.position.z,float(x.skin.bones[0]),float(x.skin.bones[1]),float(x.skin.bones[2]),float(x.skin.bones[3]),x.skin.weights[0],x.skin.weights[1],x.skin.weights[2],x.skin.weights[3]});ix=d.skinned_mesh->indices;}else{if(!d.geometry||d.part_index>=d.geometry->parts.size())return nullptr;const auto&mesh=d.geometry->parts[d.part_index].mesh;if(!mesh.valid())return nullptr;for(const auto&x:mesh.vertices)v.insert(v.end(),{x.position.x,x.position.y,x.position.z});ix=mesh.indices;}m.count=ix.size();a.GenVertexArrays(1,&m.vao);a.GenBuffers(1,&m.vb);a.GenBuffers(1,&m.ib);if(!m.vao||!m.vb||!m.ib)return nullptr;a.BindVertexArray(m.vao);a.BindBuffer(ARRAY,m.vb);a.BufferData(ARRAY,v.size()*sizeof(float),v.data(),STATIC);a.BindBuffer(ELEM,m.ib);a.BufferData(ELEM,ix.size()*sizeof(std::uint32_t),ix.data(),STATIC);a.EnableVertexAttribArray(0);a.VertexAttribPointer(0,3,FLOAT,0,m.skinned?11*sizeof(float):3*sizeof(float),nullptr);if(m.skinned){a.EnableVertexAttribArray(3);a.VertexAttribPointer(3,4,FLOAT,0,11*sizeof(float),(const void*)(3*sizeof(float)));a.EnableVertexAttribArray(4);a.VertexAttribPointer(4,4,FLOAT,0,11*sizeof(float),(const void*)(7*sizeof(float)));}return &s.shadow_meshes.emplace(k,m).first->second;}
void render_shadows(OpenGLESApi&a,State&s,const RenderFrame&f,const ShadowSettings&sh){a.BindFramebuffer(FB,s.shadow.fbo);a.Clear(0x100);a.Enable(DEPTH_TEST);a.UseProgram(s.shadow_program);for(int c=0;c<4;c++){a.Viewport((c&1)*(s.shadow.w/2),(c>1)*(s.shadow.h/2),s.shadow.w/2,s.shadow.h/2);auto lp=a.GetUniformLocation(s.shadow_program,"u_light_vp");if(lp>=0)a.UniformMatrix4fv(lp,1,0,sh.cascade[c].view_projection.m.data());for(const auto&d:f.draws){auto*m=shadow_mesh(a,s,d);if(!m)continue;if(auto mp=a.GetUniformLocation(s.shadow_program,"u_model");mp>=0)a.UniformMatrix4fv(mp,1,0,d.model.m.data());a.BindVertexArray(m->vao);a.DrawElements(TRIS,(GlInt)m->count,U32,nullptr);}}a.BindVertexArray(0);a.Disable(DEPTH_TEST);}
}
GpuSubmitResult submit_production_gles_complete(OpenGLESRenderer&r,const RenderFrame&input){GpuSubmitResult out{};if(!input.valid()){out.error="invalid render frame";return out;}AdvancedRenderPipeline planner;auto p=planner.build(input);auto&s=get(r);auto&a=const_cast<OpenGLESApi&>(r.api());if(!s.ready||s.w!=(int)input.config.width||s.h!=(int)input.config.height){if(s.ready)destroy(a,s);s.w=input.config.width;s.h=input.config.height;if(!color(a,s.w,s.h,s.hdr,p.hdr.enabled)||!depth_target(a,p.shadows.atlas_size,s.shadow)){out.error="advanced target allocation failed";return out;}int w=s.w,h=s.h;for(int i=0;i<std::clamp((int)p.bloom.mip_count,1,8);i++){w=std::max(1,w/2);h=std::max(1,h/2);Target x{},y{};color(a,w,h,x,false);color(a,w,h,y,false);s.a.push_back(x);s.b.push_back(y);}std::string e;if(!program(a,pv,df,s.down,e)||!program(a,pv,uf,s.up,e)||!program(a,pv,tf,s.tone,e)||!program(a,sv,sf,s.shadow_program,e)){out.error=e;return out;}a.GenVertexArrays(1,&s.post);ibl(r,s,p);s.ready=s.hdr.fbo&&s.down&&s.up&&s.tone&&s.shadow_program;}if(!s.ready){out.error="advanced GLES state unavailable";return out;}render_shadows(a,s,input,p.shadows);auto caps=profile_gles(a);auto gate=decide_gpu_submission(caps);GpuSubmitResult gd{};if(gate.enabled)gd=submit_gpu_driven_batches(r,const_cast<RenderFrame&>(input));auto normal=r.submit(input);if(!normal.success){out.error=normal.error;return out;}out=normal;out.draw_calls+=gd.draw_calls;out.triangles+=gd.triangles;out.animated_draw_calls+=gd.animated_draw_calls;a.BindFramebuffer(FB,0);a.Viewport(0,0,s.w,s.h);a.UseProgram(s.tone);a.ActiveTexture(0x84C0);a.BindTexture(T2D,s.hdr.color);a.Uniform1i(a.GetUniformLocation(s.tone,"u_hdr"),0);a.ActiveTexture(0x84C1);a.BindTexture(T2D,s.b.empty()?s.hdr.color:s.b[0].color);a.Uniform1i(a.GetUniformLocation(s.tone,"u_bloom"),1);a.Uniform1f(a.GetUniformLocation(s.tone,"u_exposure"),p.hdr.exposure_ev);a.Uniform1f(a.GetUniformLocation(s.tone,"u_bloom_intensity"),p.bloom.intensity);a.Uniform1f(a.GetUniformLocation(s.tone,"u_gamma"),p.hdr.gamma);a.BindVertexArray(s.post);a.DrawArrays(TRIS,0,3);a.BindVertexArray(0);out.success=true;return out;}
void release_production_gles_complete(OpenGLESRenderer&r)noexcept{std::lock_guard<std::mutex>l(mutex_);auto it=states_.find(&r);if(it==states_.end())return;destroy(const_cast<OpenGLESApi&>(r.api()),*it->second);states_.erase(it);}
bool capture_reflection_probe(OpenGLESRenderer&r,const RenderFrame&source,Vec3 pos,std::uint32_t res,GlesCubeResource&out,std::string&err){if(res<8||!create_cubemap(const_cast<OpenGLESApi&>(r.api()),res,1,RGBA8,out,err))return false;auto&a=const_cast<OpenGLESApi&>(r.api());GlUInt f=0,depth=0;a.GenFramebuffers(1,&f);a.GenRenderbuffers(1,&depth);a.BindRenderbuffer(0x8D41,depth);a.RenderbufferStorage(0x8D41,D24,(GlInt)res,(GlInt)res);for(const auto&fd:cube_faces()){a.BindFramebuffer(FB,f);a.FramebufferTexture2D(FB,CA,fd.target,out.texture,0);a.FramebufferRenderbuffer(FB,DA,0x8D41,depth);if(a.CheckFramebufferStatus(FB)!=FBC){err="reflection probe depth framebuffer incomplete";break;}RenderFrame c=source;c.camera.position=pos;c.projection=make_projection_matrix(c.camera,1);c.view=look_at(pos,fd.direction,fd.up);c.view_projection=multiply(c.projection,c.view);if(!r.submit(c).success){err="reflection probe face render failed";break;}}a.BindFramebuffer(FB,0);if(depth)a.DeleteRenderbuffers(1,&depth);if(f)a.DeleteFramebuffers(1,&f);if(!err.empty()){if(out.texture)a.DeleteTextures(1,&out.texture);out={};return false;}return true;}
}