#include "exgine/gles_ibl.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
namespace exgine { namespace {
constexpr GlEnum FB=0x8D40,CA=0x8CE0,CUBE=0x8513,FBC=0x8CD5,RGBA16F=0x881A,VS=0x8B31,FS=0x8B30,COMPILE=0x8B81,LINK=0x8B82,LOG=0x8B84,TEX0=0x84C0,TRIS=0x0004,COLOR_BIT=0x00004000;
const char*V=R"GLSL(#version 310 es
precision highp float;out vec2 v_uv;void main(){vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));vec2 q=p[gl_VertexID];gl_Position=vec4(q,0,1);v_uv=q*.5+.5;})GLSL";
const char*I=R"GLSL(#version 310 es
precision highp float;in vec2 v_uv;uniform samplerCube u_environment;uniform int u_face;out vec4 o;vec3 D(){vec2 a=v_uv*2.-1.;if(u_face==0)return normalize(vec3(1.,-a.y,-a.x));if(u_face==1)return normalize(vec3(-1.,-a.y,a.x));if(u_face==2)return normalize(vec3(a.x,1.,a.y));if(u_face==3)return normalize(vec3(a.x,-1.,-a.y));if(u_face==4)return normalize(vec3(a.x,-a.y,1.));return normalize(vec3(-a.x,-a.y,-1.));}void main(){vec3 n=D(),up=abs(n.y)<.999?vec3(0,1,0):vec3(1,0,0),t=normalize(cross(up,n)),b=cross(n,t),c=vec3(0);float w=0.,pi=3.14159265359;for(int y=0;y<8;y++)for(int x=0;x<8;x++){float u=(float(x)+.5)/8.,v=(float(y)+.5)/8.,ph=2.*pi*u,ct=sqrt(1.-v),st=sqrt(v);vec3 l=normalize(t*cos(ph)*st+b*sin(ph)*st+n*ct);float nd=max(dot(n,l),0.);c+=texture(u_environment,l).rgb*nd;w+=nd;}o=vec4(c/max(w,1e-4),1);})GLSL";
const char*G=R"GLSL(#version 310 es
precision highp float;in vec2 v_uv;uniform samplerCube u_environment;uniform int u_face;uniform float u_roughness,u_source_max_lod;out vec4 o;const float pi=3.14159265359;vec3 D(){vec2 a=v_uv*2.-1.;if(u_face==0)return normalize(vec3(1.,-a.y,-a.x));if(u_face==1)return normalize(vec3(-1.,-a.y,a.x));if(u_face==2)return normalize(vec3(a.x,1.,a.y));if(u_face==3)return normalize(vec3(a.x,-1.,-a.y));if(u_face==4)return normalize(vec3(a.x,-a.y,1.));return normalize(vec3(-a.x,-a.y,-1.));}float RI(uint b){b=(b<<16u)|(b>>16u);b=((b&0x55555555u)<<1u)|((b&0xAAAAAAAAu)>>1u);b=((b&0x33333333u)<<2u)|((b&0xCCCCCCCCu)>>2u);b=((b&0x0F0F0F0Fu)<<4u)|((b&0xF0F0F0F0u)>>4u);b=((b&0x00FF00FFu)<<8u)|((b&0xFF00FF00u)>>8u);return float(b)*2.3283064365386963e-10;}vec3 H(uint i,vec3 n,float a){float xi=float(i)/256.,yi=RI(i),aa=a*a,ph=2.*pi*xi,ct=sqrt((1.-yi)/(1.+(aa-1.)*yi)),st=sqrt(max(0.,1.-ct*ct));vec3 up=abs(n.y)<.999?vec3(0,1,0):vec3(1,0,0),t=normalize(cross(up,n)),b=cross(n,t);return normalize(t*cos(ph)*st+b*sin(ph)*st+n*ct);}void main(){vec3 n=D(),v=n,c=vec3(0);float w=0.,a=max(.001,u_roughness*u_roughness);for(uint i=0u;i<256u;i++){vec3 h=H(i,n,a),l=normalize(2.*dot(v,h)*h-v);float nd=max(dot(n,l),0.);if(nd>0.){float lod=u_source_max_lod>0.?min(u_source_max_lod,max(0.,.5*log2((1./(256.*max(nd,1e-4)))/(4.*pi/(6.*1024.*1024.))))):0.;c+=textureLod(u_environment,l,lod).rgb*nd;w+=nd;}}o=vec4(c/max(w,1e-4),1);})GLSL";
bool sh(OpenGLESApi&a,GlEnum t,const char*s,GlUInt&o,std::string&e){o=a.CreateShader(t);if(!o){e="IBL shader allocation failed";return false;}GlInt n=(GlInt)std::strlen(s);a.ShaderSource(o,1,&s,&n);a.CompileShader(o);GlInt ok=0;a.GetShaderiv(o,COMPILE,&ok);if(ok)return true;GlInt l=0,w=0;a.GetShaderiv(o,LOG,&l);std::vector<char>m(std::max(1,l));a.GetShaderInfoLog(o,l,&w,m.data());e.assign(m.data(),std::max(0,w));a.DeleteShader(o);o=0;return false;}
bool prog(OpenGLESApi&a,const char*v,const char*f,GlUInt&o,std::string&e){GlUInt vs=0,fs=0;if(!sh(a,VS,v,vs,e)||!sh(a,FS,f,fs,e)){if(vs)a.DeleteShader(vs);if(fs)a.DeleteShader(fs);return false;}o=a.CreateProgram();if(!o){e="IBL program allocation failed";a.DeleteShader(vs);a.DeleteShader(fs);return false;}a.AttachShader(o,vs);a.AttachShader(o,fs);a.LinkProgram(o);a.DeleteShader(vs);a.DeleteShader(fs);GlInt ok=0;a.GetProgramiv(o,LINK,&ok);if(ok)return true;GlInt l=0,w=0;a.GetProgramiv(o,LOG,&l);std::vector<char>m(std::max(1,l));a.GetProgramInfoLog(o,l,&w,m.data());e.assign(m.data(),std::max(0,w));a.DeleteProgram(o);o=0;return false;}
bool render(OpenGLESRenderer&r,const GlesCubeResource&s,std::uint32_t n,std::uint32_t m,bool ggx,GlesCubeResource&o,std::string&e){auto&a=const_cast<OpenGLESApi&>(r.api());if(!a.complete()||!s.valid){e="IBL requires complete GLES API and a valid environment cubemap";return false;}if(!create_cubemap(a,n,m,RGBA16F,o,e))return false;GlUInt f=0,p=0;a.GenFramebuffers(1,&f);if(!f||!prog(a,V,ggx?G:I,p,e)){if(f)a.DeleteFramebuffers(1,&f);if(p)a.DeleteProgram(p);return false;}a.UseProgram(p);auto us=a.GetUniformLocation(p,"u_environment"),uf=a.GetUniformLocation(p,"u_face"),ur=a.GetUniformLocation(p,"u_roughness"),ul=a.GetUniformLocation(p,"u_source_max_lod");a.ActiveTexture(TEX0);a.BindTexture(CUBE,s.texture);if(us>=0)a.Uniform1i(us,0);if(ul>=0)a.Uniform1f(ul,float(s.mip_levels?s.mip_levels-1:0));for(std::uint32_t mip=0;mip<m;mip++){auto sz=std::max(1u,n>>mip);a.Viewport(0,0,(GlInt)sz,(GlInt)sz);if(ur>=0)a.Uniform1f(ur,m>1?float(mip)/float(m-1):0.f);for(std::uint32_t face=0;face<6;face++){a.BindFramebuffer(FB,f);a.FramebufferTexture2D(FB,CA,cube_faces()[face].target,o.texture,(GlInt)mip);if(a.CheckFramebufferStatus(FB)!=FBC){e="IBL framebuffer incomplete";a.DeleteProgram(p);a.DeleteFramebuffers(1,&f);a.DeleteTextures(1,&o.texture);o={};return false;}if(uf>=0)a.Uniform1i(uf,(GlInt)face);a.Clear(COLOR_BIT);a.DrawArrays(TRIS,0,3);}}a.BindFramebuffer(FB,0);a.DeleteProgram(p);a.DeleteFramebuffers(1,&f);o.valid=true;return true;}
}
bool ingest_environment_cubemap(OpenGLESApi&a,const std::array<EnvironmentFacePixels,6>&f,std::uint32_t n,GlesCubeResource&o,std::string&e)noexcept{if(n==0||!f[0].data){e="invalid environment cubemap";return false;}if(!create_cubemap(a,n,1,f[0].internal_format,o,e))return false;for(std::size_t i=0;i<6;i++){if(!f[i].data||f[i].size!=n||f[i].internal_format!=f[0].internal_format||f[i].format!=f[0].format||f[i].type!=f[0].type){e="environment cubemap face mismatch";a.DeleteTextures(1,&o.texture);o={};return false;}if(!upload_cubemap_face(a,o,0,cube_faces()[i].target,f[i].internal_format,f[i].format,f[i].type,f[i].data,n)){e="environment cubemap upload failed";a.DeleteTextures(1,&o.texture);o={};return false;}}o.valid=true;return true;}
bool gpu_convolve_irradiance(OpenGLESRenderer&r,const GlesCubeResource&s,std::uint32_t n,GlesCubeResource&o,std::string&e)noexcept{return render(r,s,n,1,false,o,e);}
bool gpu_prefilter_ggx(OpenGLESRenderer&r,const GlesCubeResource&s,std::uint32_t n,std::uint32_t m,GlesCubeResource&o,std::string&e)noexcept{if(m==0){e="GGX requires mip levels";return false;}return render(r,s,n,m,true,o,e);}
bool build_gpu_ibl(OpenGLESRenderer&r,const GlesCubeResource&s,std::uint32_t irr,std::uint32_t m,GpuIblResources&o,std::string&e)noexcept{o={};o.environment=s;if(!gpu_convolve_irradiance(r,s,irr,o.irradiance,e))return false;if(!gpu_prefilter_ggx(r,s,s.size,m,o.specular,e))return false;o.valid=true;return true;}
const char*gpu_ibl_vertex_shader()noexcept{return V;}const char*gpu_irradiance_fragment_shader()noexcept{return I;}const char*gpu_ggx_prefilter_fragment_shader()noexcept{return G;}
}