#include "exgine/gles_probe_capture.hpp"
#include <algorithm>
#include <cmath>
namespace exgine { namespace {
constexpr GlEnum FB=0x8D40,CA=0x8CE0,DA=0x8D00,FBC=0x8CD5,CUBE=0x8513,RGBA8=0x8058,RGBA=0x1908,UB=0x1401,DEPTH24=0x81A6,DEPTH16=0x81A5,RENDERBUFFER=0x8D41,DEPTH_COMPONENT=0x1902,DEPTH_BIT=0x00000100,TRIS=0x0004;
Mat4 perspective(float fov,float aspect,float near,float far){Mat4 m{};float t=1.f/std::tan(fov*.5f);m.at(0,0)=t/aspect;m.at(1,1)=t;m.at(2,2)=-(far+near)/(far-near);m.at(2,3)=-1.f;m.at(3,2)=-(2.f*far*near)/(far-near);return m;}
}
bool create_probe_capture_target(OpenGLESApi&a,std::uint32_t n,ReflectionProbeCaptureTarget&o,std::string&e)noexcept{if(!a.GenFramebuffers||!a.GenTextures||!a.GenRenderbuffers){e="probe capture requires framebuffer, texture and renderbuffer support";return false;}destroy_probe_capture_target(a,o);o.size=n;a.GenTextures(1,&o.color_cube);a.BindTexture(CUBE,o.color_cube);a.TexParameteri(CUBE,0x2801,0x2601);a.TexParameteri(CUBE,0x2800,0x2601);a.TexParameteri(CUBE,0x2802,0x812F);a.TexParameteri(CUBE,0x2803,0x812F);for(auto f:cube_faces())a.TexImage2D(CUBE,0,RGBA8,(GlInt)n,(GlInt)n,0,RGBA,UB,nullptr);a.GenRenderbuffers(1,&o.depth_rbo);a.BindRenderbuffer(RENDERBUFFER,o.depth_rbo);a.RenderbufferStorage(RENDERBUFFER,DEPTH24,(GlInt)n,(GlInt)n);a.GenFramebuffers(1,&o.fbo);a.BindFramebuffer(FB,o.fbo);a.FramebufferRenderbuffer(FB,DA,RENDERBUFFER,o.depth_rbo);a.FramebufferTexture2D(FB,CA,CUBE,o.color_cube,cube_faces()[0].target);if(a.CheckFramebufferStatus(FB)!=FBC){a.BindRenderbuffer(RENDERBUFFER,o.depth_rbo);a.RenderbufferStorage(RENDERBUFFER,DEPTH16,(GlInt)n,(GlInt)n);a.BindFramebuffer(FB,o.fbo);a.FramebufferRenderbuffer(FB,DA,RENDERBUFFER,o.depth_rbo);}if(a.CheckFramebufferStatus(FB)!=FBC){e="reflection probe framebuffer incomplete";destroy_probe_capture_target(a,o);return false;}a.BindFramebuffer(FB,0);return true;}
void destroy_probe_capture_target(OpenGLESApi&a,ReflectionProbeCaptureTarget&o)noexcept{if(o.fbo&&a.DeleteFramebuffers)a.DeleteFramebuffers(1,&o.fbo);if(o.depth_rbo&&a.DeleteRenderbuffers)a.DeleteRenderbuffers(1,&o.depth_rbo);if(o.color_cube&&a.DeleteTextures)a.DeleteTextures(1,&o.color_cube);o={};}
bool capture_probe_six_faces(OpenGLESRenderer&r,const RenderFrame&frame,Vec3 position,std::uint32_t size,ReflectionProbeCaptureTarget&t,const ProbeFaceRenderer&draw,std::string&e)noexcept{if(!t.fbo||!t.color_cube||!t.depth_rbo||t.size!=size){if(!create_probe_capture_target(const_cast<OpenGLESApi&>(r.api()),size,t,e))return false;}static const Vec3 dirs[6]={{1,0,0},{-1,0,0},{0,1,0},{0,-1,0},{0,0,1},{0,0,-1}};static const Vec3 ups[6]={{0,-1,0},{0,-1,0},{0,0,1},{0,0,-1},{0,-1,0},{0,-1,0}};auto&a=const_cast<OpenGLESApi&>(r.api());Mat4 proj=perspective(1.57079632679f,1.f,.05f,1000.f);for(std::uint32_t i=0;i<6;i++){a.BindFramebuffer(FB,t.fbo);a.FramebufferTexture2D(FB,CA,CUBE,t.color_cube,cube_faces()[i].target,0);a.FramebufferRenderbuffer(FB,DA,RENDERBUFFER,t.depth_rbo);if(a.CheckFramebufferStatus(FB)!=FBC){e="probe face framebuffer incomplete";return false;}a.Viewport(0,0,(GlInt)size,(GlInt)size);a.Clear(DEPTH_BIT|0x4000);a.Enable(0x0B71);a.DepthFunc(0x0203);Mat4 view=look_at(position,dirs[i],ups[i]);if(!draw(r,frame,view,proj,i,e))return false;}a.BindFramebuffer(FB,0);return true;}
}