#include "exgine/import.hpp"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace exgine { namespace {

struct JsonValue {
    enum class Type { Null, Bool, Number, String, Array, Object } type=Type::Null;
    double number=0.0; bool boolean=false; std::string string;
    std::vector<JsonValue> array; std::unordered_map<std::string,JsonValue> object;
    const JsonValue* get(std::string_view key) const { auto it=object.find(std::string(key)); return it==object.end()?nullptr:&it->second; }
};

class JsonParser {
public:
    explicit JsonParser(std::string_view input):input_(input){}
    bool parse(JsonValue& out){skip();if(!value(out))return false;skip();return pos_==input_.size();}
private:
    std::string_view input_; std::size_t pos_=0;
    void skip(){while(pos_<input_.size()&&std::isspace(static_cast<unsigned char>(input_[pos_])))++pos_;}
    bool take(char c){skip();if(pos_<input_.size()&&input_[pos_]==c){++pos_;return true;}return false;}
    bool string(std::string& out){if(!take('"'))return false;out.clear();while(pos_<input_.size()){char c=input_[pos_++];if(c=='"')return true;if(c=='\\'){if(pos_>=input_.size())return false;char e=input_[pos_++];switch(e){case '"':case '\\':case '/':out+=e;break;case 'b':out+='\b';break;case 'f':out+='\f';break;case 'n':out+='\n';break;case 'r':out+='\r';break;case 't':out+='\t';break;default:return false;}}else if(static_cast<unsigned char>(c)<32)return false;else out+=c;}return false;}
    bool value(JsonValue& v){skip();if(pos_>=input_.size())return false;if(input_[pos_]=='{')return object(v);if(input_[pos_]=='[')return array(v);if(input_[pos_]=='"'){v.type=JsonValue::Type::String;return string(v.string);}if(input_.substr(pos_,4)=="true"){pos_+=4;v.type=JsonValue::Type::Bool;v.boolean=true;return true;}if(input_.substr(pos_,5)=="false"){pos_+=5;v.type=JsonValue::Type::Bool;v.boolean=false;return true;}if(input_.substr(pos_,4)=="null"){pos_+=4;v.type=JsonValue::Type::Null;return true;}std::string temp(input_.substr(pos_));char*end=nullptr;const double n=std::strtod(temp.c_str(),&end);if(end==temp.c_str()||!std::isfinite(n))return false;pos_+=static_cast<std::size_t>(end-temp.c_str());v.type=JsonValue::Type::Number;v.number=n;return true;}
    bool object(JsonValue& v){if(!take('{'))return false;v.type=JsonValue::Type::Object;v.object.clear();skip();if(take('}'))return true;while(true){std::string key;if(!string(key)||!take(':'))return false;JsonValue child;if(!value(child))return false;v.object.emplace(std::move(key),std::move(child));skip();if(take('}'))return true;if(!take(','))return false;}}
    bool array(JsonValue& v){if(!take('['))return false;v.type=JsonValue::Type::Array;v.array.clear();skip();if(take(']'))return true;while(true){JsonValue child;if(!value(child))return false;v.array.push_back(std::move(child));skip();if(take(']'))return true;if(!take(','))return false;}}
};

const JsonValue* get(const JsonValue* value,std::string_view key){return value&&value->type==JsonValue::Type::Object?value->get(key):nullptr;}
int integer(const JsonValue* value,int fallback=-1){return value&&value->type==JsonValue::Type::Number?static_cast<int>(value->number):fallback;}
double real(const JsonValue* value,double fallback=0.0){return value&&value->type==JsonValue::Type::Number?value->number:fallback;}
std::string text(const JsonValue* value,std::string fallback={}){return value&&value->type==JsonValue::Type::String?value->string:fallback;}

std::size_t component_size(int component_type){switch(component_type){case 5120:case 5121:return 1;case 5122:case 5123:return 2;case 5125:case 5126:return 4;default:return 0;}}
int component_count(std::string_view type){if(type=="SCALAR")return 1;if(type=="VEC2")return 2;if(type=="VEC3")return 3;if(type=="VEC4")return 4;if(type=="MAT4")return 16;return 0;}
double read_component(const std::uint8_t* p,int component_type){switch(component_type){case 5120:return *reinterpret_cast<const std::int8_t*>(p);case 5121:return p[0];case 5122:{std::int16_t x;std::memcpy(&x,p,2);return x;}case 5123:{std::uint16_t x;std::memcpy(&x,p,2);return x;}case 5125:{std::uint32_t x;std::memcpy(&x,p,4);return x;}case 5126:{float x;std::memcpy(&x,p,4);return x;}default:return 0.0;}}

std::vector<std::uint8_t> decode_base64(std::string_view value){std::vector<std::uint8_t> out;int acc=0,bits=-8;auto digit=[](char c){if(c>='A'&&c<='Z')return c-'A';if(c>='a'&&c<='z')return c-'a'+26;if(c>='0'&&c<='9')return c-'0'+52;if(c=='+')return 62;if(c=='/')return 63;return -1;};for(char c:value){if(c=='=')break;const int d=digit(c);if(d<0)continue;acc=(acc<<6)|d;bits+=6;if(bits>=0){out.push_back(static_cast<std::uint8_t>((acc>>bits)&255));bits-=8;}}return out;}

bool load_buffers(const JsonValue& root,const std::vector<std::uint8_t>& glb_bin,std::vector<std::vector<std::uint8_t>>& buffers,std::string& error){const auto* list=get(&root,"buffers");if(!list||list->type!=JsonValue::Type::Array){error="glTF buffers are missing";return false;}for(std::size_t i=0;i<list->array.size();++i){const auto& desc=list->array[i];const auto uri=text(get(&desc,"uri"));std::vector<std::uint8_t> data;if(!uri.empty()){const std::string prefix="data:application/octet-stream;base64,";if(uri.rfind(prefix,0)!=0){error="external glTF buffer URI is unsupported";return false;}data=decode_base64(uri.substr(prefix.size()));}else if(i==0&&!glb_bin.empty())data=glb_bin;else{error="buffer has no embedded data";return false;}const std::size_t expected=static_cast<std::size_t>(std::max(0,integer(get(&desc,"byteLength"),0)));if(data.size()<expected){error="buffer is shorter than byteLength";return false;}buffers.push_back(std::move(data));}return true;}

bool read_accessor(const JsonValue& root,int accessor_index,const std::vector<std::vector<std::uint8_t>>& buffers,std::vector<double>& out,int& count,int& components){const auto* accessors=get(&root,"accessors");if(!accessors||accessor_index<0||static_cast<std::size_t>(accessor_index)>=accessors->array.size())return false;const auto& a=accessors->array[accessor_index];const int view_index=integer(get(&a,"bufferView"));const auto* views=get(&root,"bufferViews");if(!views||view_index<0||static_cast<std::size_t>(view_index)>=views->array.size())return false;const auto& view=views->array[view_index];const int buffer_index=integer(get(&view,"buffer"));if(buffer_index<0||static_cast<std::size_t>(buffer_index)>=buffers.size())return false;const int component_type=integer(get(&a,"componentType"),0);const std::size_t component_bytes=component_size(component_type);components=component_count(text(get(&a,"type")));count=integer(get(&a,"count"),0);if(component_bytes==0||components==0||count<0)return false;const std::size_t base=static_cast<std::size_t>(std::max(0,integer(get(&view,"byteOffset"),0)))+static_cast<std::size_t>(std::max(0,integer(get(&a,"byteOffset"),0)));const std::size_t stride_value=static_cast<std::size_t>(std::max(0,integer(get(&view,"byteStride"),0)));const std::size_t stride=stride_value?stride_value:component_bytes*static_cast<std::size_t>(components);const auto& bytes=buffers[buffer_index];if(base>bytes.size())return false;out.resize(static_cast<std::size_t>(count)*static_cast<std::size_t>(components));for(int i=0;i<count;++i){const std::size_t offset=base+static_cast<std::size_t>(i)*stride;if(offset+component_bytes*static_cast<std::size_t>(components)>bytes.size())return false;for(int c=0;c<components;++c)out[static_cast<std::size_t>(i)*components+c]=read_component(bytes.data()+offset+c*component_bytes,component_type);}return true;}

ImportResult parse_gltf(std::string_view uri,std::string_view json_text,ImportFormat format,const std::vector<std::uint8_t>& glb_bin){ImportResult result;result.format=format;JsonValue root;if(!JsonParser(json_text).parse(root)){result.error="invalid glTF JSON";return result;}const auto* asset=get(&root,"asset");if(!asset||text(get(asset,"version"))!="2.0"){result.error="glTF 2.0 is required";return result;}std::vector<std::vector<std::uint8_t>> buffers;if(const auto* list=get(&root,"buffers");list&&list->type==JsonValue::Type::Array&&!list->array.empty()){if(!load_buffers(root,glb_bin,buffers,result.error))return result;}
if(const auto* mats=get(&root,"materials");mats&&mats->type==JsonValue::Type::Array)for(std::size_t i=0;i<mats->array.size();++i){ImportedMaterial item;item.name=text(get(&mats->array[i],"name"),"material_"+std::to_string(i));item.source_material=static_cast<std::uint32_t>(i);item.material.name=item.name;if(const auto* pbr=get(&mats->array[i],"pbrMetallicRoughness")){if(const auto* factor=get(pbr,"baseColorFactor");factor&&factor->type==JsonValue::Type::Array&&factor->array.size()>=4){item.material.base_color={static_cast<float>(real(&factor->array[0],1)),static_cast<float>(real(&factor->array[1],1)),static_cast<float>(real(&factor->array[2],1))};item.material.opacity=static_cast<float>(real(&factor->array[3],1));}item.material.metallic=static_cast<float>(real(get(pbr,"metallicFactor"),0));item.material.roughness=static_cast<float>(real(get(pbr,"roughnessFactor"),1));}result.materials.push_back(std::move(item));}
const auto* meshes=get(&root,"meshes");if(meshes&&meshes->type==JsonValue::Type::Array)for(std::size_t mi=0;mi<meshes->array.size();++mi){const auto* primitives=get(&meshes->array[mi],"primitives");if(!primitives||primitives->type!=JsonValue::Type::Array)continue;for(std::size_t pi=0;pi<primitives->array.size();++pi){const auto& primitive=primitives->array[pi];const auto* attrs=get(&primitive,"attributes");const int position_index=integer(get(attrs,"POSITION"));std::vector<double> positions,normals,uvs;int vertex_count=0,components=0,unused=0;if(!read_accessor(root,position_index,buffers,positions,vertex_count,components)||components!=3){result.error="invalid POSITION accessor";return result;}const int normal_index=integer(get(attrs,"NORMAL"));if(normal_index>=0&&!read_accessor(root,normal_index,buffers,normals,unused,components)){result.error="invalid NORMAL accessor";return result;}const int uv_index=integer(get(attrs,"TEXCOORD_0"));if(uv_index>=0&&!read_accessor(root,uv_index,buffers,uvs,unused,components)){result.error="invalid TEXCOORD_0 accessor";return result;}ImportedMesh mesh;mesh.uri=std::string(uri)+"#mesh"+std::to_string(mi)+"/primitive"+std::to_string(pi);mesh.asset_id=make_asset_id(mesh.uri,std::vector<std::uint8_t>(json_text.begin(),json_text.end()));mesh.source_mesh=static_cast<std::uint32_t>(mi);mesh.source_primitive=static_cast<std::uint32_t>(pi);const int material_index=integer(get(&primitive,"material"));if(material_index>=0&&static_cast<std::size_t>(material_index)<result.materials.size())mesh.material_name=result.materials[material_index].name;mesh.mesh.vertices.resize(static_cast<std::size_t>(vertex_count));for(int i=0;i<vertex_count;++i){auto& v=mesh.mesh.vertices[static_cast<std::size_t>(i)];v.position={static_cast<float>(positions[static_cast<std::size_t>(i)*3]),static_cast<float>(positions[static_cast<std::size_t>(i)*3+1]),static_cast<float>(positions[static_cast<std::size_t>(i)*3+2])};if(normals.size()>=static_cast<std::size_t>(i*3+3))v.normal={static_cast<float>(normals[static_cast<std::size_t>(i)*3]),static_cast<float>(normals[static_cast<std::size_t>(i)*3+1]),static_cast<float>(normals[static_cast<std::size_t>(i)*3+2])};if(uvs.size()>=static_cast<std::size_t>(i*2+2))v.uv={static_cast<float>(uvs[static_cast<std::size_t>(i)*2]),static_cast<float>(uvs[static_cast<std::size_t>(i)*2+1])};}
const int index_accessor=integer(get(&primitive,"indices"));if(index_accessor>=0){std::vector<double> indices;int index_count=0,index_components=0;if(!read_accessor(root,index_accessor,buffers,indices,index_count,index_components)||index_components!=1){result.error="invalid index accessor";return result;}mesh.mesh.indices.reserve(static_cast<std::size_t>(index_count));for(double index:indices)mesh.mesh.indices.push_back(static_cast<std::uint32_t>(index));}else for(std::uint32_t i=0;i<static_cast<std::uint32_t>(vertex_count);++i)mesh.mesh.indices.push_back(i);if(!mesh.mesh.valid()){result.error="invalid glTF primitive mesh";return result;}if(std::all_of(mesh.mesh.vertices.begin(),mesh.mesh.vertices.end(),[](const Vertex& v){return std::fabs(v.normal.x)+std::fabs(v.normal.y)+std::fabs(v.normal.z)<1e-6f;})){for(std::size_t i=0;i+2<mesh.mesh.indices.size();i+=3){auto&a=mesh.mesh.vertices[mesh.mesh.indices[i]];auto&b=mesh.mesh.vertices[mesh.mesh.indices[i+1]];auto&c=mesh.mesh.vertices[mesh.mesh.indices[i+2]];const Vec3 ab{b.position.x-a.position.x,b.position.y-a.position.y,b.position.z-a.position.z};const Vec3 ac{c.position.x-a.position.x,c.position.y-a.position.y,c.position.z-a.position.z};const Vec3 n{ab.y*ac.z-ab.z*ac.y,ab.z*ac.x-ab.x*ac.z,ab.x*ac.y-ab.y*ac.x};for(auto index:{mesh.mesh.indices[i],mesh.mesh.indices[i+1],mesh.mesh.indices[i+2]}){mesh.mesh.vertices[index].normal.x+=n.x;mesh.mesh.vertices[index].normal.y+=n.y;mesh.mesh.vertices[index].normal.z+=n.z;}}for(auto&v:mesh.mesh.vertices){const float l=std::sqrt(v.normal.x*v.normal.x+v.normal.y*v.normal.y+v.normal.z*v.normal.z);if(l>1e-6f){v.normal.x/=l;v.normal.y/=l;v.normal.z/=l;}}}result.meshes.push_back(std::move(mesh));}}
if(const auto* nodes=get(&root,"nodes");nodes&&nodes->type==JsonValue::Type::Array)for(std::size_t i=0;i<nodes->array.size();++i){ImportedNode node;node.source_node=static_cast<std::uint32_t>(i);node.name=text(get(&nodes->array[i],"name"),"node_"+std::to_string(i));node.mesh_index=integer(get(&nodes->array[i],"mesh"));if(const auto*t=get(&nodes->array[i],"translation");t&&t->type==JsonValue::Type::Array&&t->array.size()>=3)node.translation={static_cast<float>(real(&t->array[0])),static_cast<float>(real(&t->array[1])),static_cast<float>(real(&t->array[2]))};if(const auto*s=get(&nodes->array[i],"scale");s&&s->type==JsonValue::Type::Array&&s->array.size()>=3)node.scale={static_cast<float>(real(&s->array[0],1)),static_cast<float>(real(&s->array[1],1)),static_cast<float>(real(&s->array[2],1))};result.nodes.push_back(std::move(node));}
result.success=!result.meshes.empty()||!result.materials.empty()||!result.nodes.empty();if(!result.success)result.error="glTF contains no supported content";return result;}

} // namespace

bool ImportedNode::valid()const noexcept{return !name.empty()&&std::isfinite(translation.x)&&std::isfinite(translation.y)&&std::isfinite(translation.z)&&std::isfinite(scale.x)&&std::isfinite(scale.y)&&std::isfinite(scale.z)&&scale.x!=0&&scale.y!=0&&scale.z!=0;}
ImportResult import_gltf(std::string_view uri,std::string_view payload){return detect_import_format(uri,payload)==ImportFormat::Glb?import_glb(uri,payload):parse_gltf(uri,payload,ImportFormat::Gltf,{});}
ImportResult import_glb(std::string_view uri,std::string_view payload){ImportResult result;result.format=ImportFormat::Glb;if(payload.size()<20||payload.substr(0,4)!="glTF"){result.error="invalid GLB magic";return result;}auto u32=[&](std::size_t p){return static_cast<std::uint32_t>(static_cast<unsigned char>(payload[p]))|(static_cast<std::uint32_t>(static_cast<unsigned char>(payload[p+1]))<<8)|(static_cast<std::uint32_t>(static_cast<unsigned char>(payload[p+2]))<<16)|(static_cast<std::uint32_t>(static_cast<unsigned char>(payload[p+3]))<<24);};const auto version=u32(4),length=u32(8);if(version!=2||length>payload.size()){result.error="unsupported GLB version or length";return result;}std::size_t p=12;std::string json;std::vector<std::uint8_t>bin;while(p+8<=length){const auto chunk_length=u32(p),chunk_type=u32(p+4);p+=8;if(p+chunk_length>length){result.error="truncated GLB chunk";return result;}if(chunk_type==0x4E4F534A)json.assign(payload.data()+p,chunk_length);else if(chunk_type==0x004E4942)bin.assign(reinterpret_cast<const std::uint8_t*>(payload.data()+p),reinterpret_cast<const std::uint8_t*>(payload.data()+p+chunk_length));p+=chunk_length;}if(json.empty()){result.error="GLB JSON chunk missing";return result;}return parse_gltf(uri,json,ImportFormat::Glb,bin);}
}