#include "exgine/import.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace exgine { namespace {
struct J{enum K{N,B,F,S,A,O}k=N;double n=0;bool b=false;std::string s;std::vector<J>a;std::unordered_map<std::string,J>o;const J*g(std::string_view x)const{auto i=o.find(std::string(x));return i==o.end()?nullptr:&i->second;}};
class P{std::string_view s;std::size_t p=0;void ws(){while(p<s.size()&&std::isspace((unsigned char)s[p]))++p;}bool ch(char c){ws();if(p<s.size()&&s[p]==c){++p;return true;}return false;}bool val(J&v){ws();if(p>=s.size())return false;if(s[p]=='{')return obj(v);if(s[p]=='[')return arr(v);if(s[p]=='"'){v.k=J::S;return str(v.s);}if(s.substr(p,4)=="true"){p+=4;v.k=J::B;v.b=true;return true;}if(s.substr(p,5)=="false"){p+=5;v.k=J::B;v.b=false;return true;}if(s.substr(p,4)=="null"){p+=4;return true;}std::string t(s.substr(p));char*e=nullptr;double n=std::strtod(t.c_str(),&e);if(e==t.c_str()||!std::isfinite(n))return false;p+=std::size_t(e-t.c_str());v.k=J::F;v.n=n;return true;}bool str(std::string&v){if(!ch('"'))return false;v.clear();while(p<s.size()){char c=s[p++];if(c=='"')return true;if(c=='\\'){if(p>=s.size())return false;char e=s[p++];if(e=='"'||e=='\\'||e=='/')v+=e;else if(e=='n')v+='\n';else if(e=='r')v+='\r';else if(e=='t')v+='\t';else if(e=='b')v+='\b';else if(e=='f')v+='\f';else return false;}else if((unsigned char)c<32)return false;else v+=c;}return false;}bool obj(J&v){if(!ch('{'))return false;v.k=J::O;ws();if(ch('}'))return true;for(;;){std::string k;if(!str(k)||!ch(':'))return false;J x;if(!val(x))return false;v.o.emplace(std::move(k),std::move(x));ws();if(ch('}'))return true;if(!ch(','))return false;}}bool arr(J&v){if(!ch('['))return false;v.k=J::A;ws();if(ch(']'))return true;for(;;){J x;if(!val(x))return false;v.a.push_back(std::move(x));ws();if(ch(']'))return true;if(!ch(','))return false;}}public:explicit P(std::string_view x):s(x){}bool parse(J&v){if(!val(v))return false;ws();return p==s.size();}};
const J*o(const J*x,std::string_view k){return x&&x->k==J::O?x->g(k):nullptr;}int ni(const J*x,int d=-1){return x&&x->k==J::F?(int)x->n:d;}double nf(const J*x,double d=0){return x&&x->k==J::F?x->n:d;}std::string ns(const J*x,std::string d={}){return x&&x->k==J::S?x->s:d;}
std::size_t cs(int c){return c==5120||c==5121?1:c==5122||c==5123?2:c==5125||c==5126?4:0;}int cc(std::string_view t){return t=="SCALAR"?1:t=="VEC2"?2:t=="VEC3"?3:t=="VEC4"?4:t=="MAT4"?16:0;}
double rd(const std::uint8_t*p,int c){switch(c){case 5120:return *(const std::int8_t*)p;case 5121:return p[0];case 5122:{std::int16_t x;std::memcpy(&x,p,2);return x;}case 5123:{std::uint16_t x;std::memcpy(&x,p,2);return x;}case 5125:{std::uint32_t x;std::memcpy(&x,p,4);return x;}case 5126:{float x;std::memcpy(&x,p,4);return x;}default:return 0;}}
std::vector<std::uint8_t> b64(std::string_view s){std::vector<std::uint8_t>r;int v=0,b=-8;auto cv=[](char c){return c>='A'&&c<='Z'?c-'A':c>='a'&&c<='z'?c-'a'+26:c>='0'&&c<='9'?c-'0'+52:c=='+'?62:c=='/'?63:-1;};for(char c:s){if(c=='=')break;int x=cv(c);if(x<0)continue;v=(v<<6)|x;b+=6;if(b>=0){r.push_back((std::uint8_t)((v>>b)&255));b-=8;}}return r;}
bool buffers(const J&root,std::vector<std::vector<std::uint8_t>>&out,std::string&err){const J*b=o(&root,"buffers");if(!b||b->k!=J::A){err="glTF buffers missing";return false;}for(const auto&x:b->a){auto u=ns(o(&x,"uri"));const std::string p="data:application/octet-stream;base64,";if(u.rfind(p,0)!=0){err="external glTF buffers are not supported by the memory importer";return false;}auto d=b64(u.substr(p.size()));auto need=(std::size_t)std::max(0,ni(o(&x,"byteLength"),0));if(d.size()<need){err="buffer shorter than byteLength";return false;}out.push_back(std::move(d));}return true;}
bool acc(const J&root,int ai,const std::vector<std::vector<std::uint8_t>>&bufs,std::vector<double>&out,int&count,int&ncomp){const J*as=o(&root,"accessors");const J*a=as?as->a.size()>0&&ai>=0&&std::size_t(ai)<as->a.size()?&as->a[ai]:nullptr;if(!a)return false;int bvi=ni(o(a,"bufferView"));const J*bvs=o(&root,"bufferViews");const J*bv=bvs&&bvi>=0&&std::size_t(bvi)<bvs->a.size()?&bvs->a[bvi]:nullptr;if(!bv)return false;int bi=ni(o(bv,"buffer"));if(bi<0||std::size_t(bi)>=bufs.size())return false;int ct=ni(o(a,"componentType"),0);auto size=cs(ct);ncomp=cc(ns(o(a,"type")));count=ni(o(a,"count"),0);if(!size||!ncomp||count<0)return false;std::size_t base=(std::size_t)std::max(0,ni(o(bv,"byteOffset"),0))+(std::size_t)std::max(0,ni(o(a,"byteOffset"),0));std::size_t stride=(std::size_t)std::max(0,ni(o(bv,"byteStride"),0));stride=stride?stride:size*std::size_t(ncomp);if(base+stride*std::size_t(count)>bufs[bi].size()+stride)return false;out.resize(std::size_t(count)*std::size_t(ncomp));for(int i=0;i<count;++i){auto pos=base+std::size_t(i)*stride;if(pos+size*std::size_t(ncomp)>bufs[bi].size())return false;for(int c=0;c<ncomp;++c)out[std::size_t(i)*ncomp+c]=rd(bufs[bi].data()+pos+c*size,ct);}return true;}
ImportResult parse(std::string_view uri,std::string_view text,ImportFormat fmt){ImportResult r;r.format=fmt;J root;if(!P(text).parse(root)){r.error="invalid JSON";return r;}const J*a=o(&root,"asset");if(!a||ns(o(a,"version"))!="2.0"){r.error="glTF 2.0 required";return r;}std::vector<std::vector<std::uint8_t>>bufs;if(o(&root,"buffers")&&!buffers(root,bufs,r.error))return r;
if(const J*m=o(&root,"materials");m&&m->k==J::A)for(std::size_t i=0;i<m->a.size();++i){ImportedMaterial x;x.name=ns(o(&m->a[i],"name"),"material_"+std::to_string(i));x.material.name=x.name;x.source_material=(std::uint32_t)i;if(const J*p=o(&m->a[i],"pbrMetallicRoughness")){if(const J*c=o(p,"baseColorFactor");c&&c->k==J::A&&c->a.size()>=4)x.material.base_color={(float)nf(&c->a[0],1),(float)nf(&c->a[1],1),(float)nf(&c->a[2],1)};x.material.opacity=(float)nf(o(p,"baseColorFactor")&&o(p,"baseColorFactor")->k==J::A&&o(p,"baseColorFactor")->a.size()>3?&o(p,"baseColorFactor")->a[3]:nullptr,1);x.material.metallic=(float)nf(o(p,"metallicFactor"),0);x.material.roughness=(float)nf(o(p,"roughnessFactor"),1);}r.materials.push_back(std::move(x));}
const J*ms=o(&root,"meshes");if(ms&&ms->k==J::A)for(std::size_t mi=0;mi<ms->a.size();++mi){const J*pr=o(&ms->a[mi],"primitives");if(!pr||pr->k!=J::A)continue;for(std::size_t pi=0;pi<pr->a.size();++pi){const J&pp=pr->a[pi];const J*at=o(&pp,"attributes");int pos=ni(o(at,"POSITION"));std::vector<double>pv,nv,uv;int n=0,k=0,d=0;if(!acc(root,pos,bufs,pv,n,k)||k!=3){r.error="invalid POSITION accessor";return r;}int na=ni(o(at,"NORMAL")),ua=ni(o(at,"TEXCOORD_0"));if(na>=0&&!acc(root,na,bufs,nv,d,k)){r.error="invalid NORMAL accessor";return r;}if(ua>=0&&!acc(root,ua,bufs,uv,d,k)){r.error="invalid TEXCOORD_0 accessor";return r;}ImportedMesh x;x.uri=std::string(uri)+"#"+std::to_string(mi)+":"+std::to_string(pi);x.asset_id=make_asset_id(x.uri,std::vector<std::uint8_t>(text.begin(),text.end()));x.source_mesh=(std::uint32_t)mi;x.source_primitive=(std::uint32_t)pi;int mat=ni(o(&pp,"material"));if(mat>=0&&std::size_t(mat)<r.materials.size())x.material_name=r.materials[mat].name;x.mesh.vertices.resize((std::size_t)n);for(int i=0;i<n;++i){auto&v=x.mesh.vertices[i];v.position={(float)pv[i*3],(float)pv[i*3+1],(float)pv[i*3+2]};if(nv.size()>std::size_t(i*3+2))v.normal={(float)nv[i*3],(float)nv[i*3+1],(float)nv[i*3+2]};if(uv.size()>std::size_t(i*2+1))v.uv={(float)uv[i*2],(float)uv[i*2+1]};}int ind=ni(o(&pp,"indices"));if(ind>=0){const J*as=o(&root,"accessors");int ic=(as&&std::size_t(ind)<as->a.size())?ni(o(&as->a[ind],"count"),0):0;for(int i=0;i<ic;++i){std::vector<double>z;int zn=0,zc=0;const J*accs=o(&root,"accessors");const J*aa=&accs->a[ind];const J*bvs=o(&root,"bufferViews");int bvi=ni(o(aa,"bufferView"));int bi=ni(o(&bvs->a[bvi],"buffer"));std::size_t off=(std::size_t)std::max(0,ni(o(&bvs->a[bvi],"byteOffset"),0))+(std::size_t)std::max(0,ni(o(aa,"byteOffset"),0));std::size_t stride=cs(ni(o(aa,"componentType")));if(i>=0&&off+std::size_t(i)*stride+stride<=bufs[bi].size())x.mesh.indices.push_back((std::uint32_t)rd(bufs[bi].data()+off+std::size_t(i)*stride,ni(o(aa,"componentType"))));}}else for(std::uint32_t i=0;i<(std::uint32_t)n;++i)x.mesh.indices.push_back(i);if(x.mesh.indices.size()<3||!x.mesh.valid()){r.error="invalid glTF primitive";return r;}r.meshes.push_back(std::move(x));}}
if(const J*nd=o(&root,"nodes");nd&&nd->k==J::A){r.nodes.resize(nd->a.size());for(std::size_t i=0;i<nd->a.size();++i){auto&x=r.nodes[i];x.name=ns(o(&nd->a[i],"name"),"node_"+std::to_string(i));x.source_node=(std::uint32_t)i;x.mesh_index=ni(o(&nd->a[i],"mesh"));if(const J*t=o(&nd->a[i],"translation");t&&t->k==J::A&&t->a.size()>=3)x.translation={(float)nf(&t->a[0]),(float)nf(&t->a[1]),(float)nf(&t->a[2])};if(const J*s=o(&nd->a[i],"scale");s&&s->k==J::A&&s->a.size()>=3)x.scale={(float)nf(&s->a[0],1),(float)nf(&s->a[1],1),(float)nf(&s->a[2],1)};}}
r.success=!r.meshes.empty()||!r.materials.empty()||!r.nodes.empty();if(!r.success)r.error="glTF contains no supported content";return r;}
}
bool ImportedNode::valid()const noexcept{return !name.empty()&&std::isfinite(translation.x)&&std::isfinite(translation.y)&&std::isfinite(translation.z)&&std::isfinite(scale.x)&&std::isfinite(scale.y)&&std::isfinite(scale.z)&&scale.x!=0&&scale.y!=0&&scale.z!=0;}
ImportResult import_gltf(std::string_view uri,std::string_view text_or_glb){return detect_import_format(uri,text_or_glb)==ImportFormat::Glb?import_glb(uri,text_or_glb):parse(uri,text_or_glb,ImportFormat::Gltf);}
ImportResult import_glb(std::string_view uri,std::string_view bin){ImportResult r;r.format=ImportFormat::Glb;if(bin.size()<20||bin.substr(0,4)!="glTF"){r.error="invalid GLB header";return r;}auto u32=[&](std::size_t p){return(std::uint32_t)(unsigned char)bin[p]|((std::uint32_t)(unsigned char)bin[p+1]<<8)|((std::uint32_t)(unsigned char)bin[p+2]<<16)|((std::uint32_t)(unsigned char)bin[p+3]<<24);};if(u32(4)!=2||u32(8)>bin.size()){r.error="unsupported GLB header";return r;}std::size_t p=12;std::string json;while(p+8<=u32(8)){auto n=u32(p),t=u32(p+4);p+=8;if(p+n>u32(8)){r.error="truncated GLB chunk";return r;}if(t==0x4E4F534A)json.assign(bin.data()+p,n);p+=n;}if(json.empty()){r.error="missing GLB JSON chunk";return r;}return parse(uri,json,ImportFormat::Glb);}
}