#include "exgine/gpu_residency.hpp"
#include <algorithm>
#include <cstddef>
#include <cstring>

namespace exgine { namespace {
constexpr GlEnum GL_ARRAY_BUFFER=0x8892,GL_ELEMENT_ARRAY_BUFFER=0x8893,GL_STATIC_DRAW=0x88E4,GL_FLOAT=0x1406,GL_UNSIGNED_INT=0x1405;
}
OpenGLESAssetResidency::OpenGLESAssetResidency(OpenGLESApi api,GpuResidencyConfig config) noexcept:api_(api),config_(config){stats_.max_meshes=config_.max_meshes;}
OpenGLESAssetResidency::~OpenGLESAssetResidency(){clear();}
bool OpenGLESAssetResidency::ready()const noexcept{return config_.valid()&&api_.GenBuffers&&api_.BindBuffer&&api_.BufferData&&api_.DeleteBuffers&&api_.GenVertexArrays&&api_.BindVertexArray&&api_.DeleteVertexArrays&&api_.EnableVertexAttribArray&&api_.VertexAttribPointer;}
const GpuResidentMesh*OpenGLESAssetResidency::find(std::uint64_t id)const noexcept{auto i=std::find_if(meshes_.begin(),meshes_.end(),[&](const auto&m){return m.asset_id==id;});return i==meshes_.end()?nullptr:&*i;}
void OpenGLESAssetResidency::release_mesh(GpuResidentMesh&m)noexcept{if(m.vertex_buffer&&api_.DeleteBuffers)api_.DeleteBuffers(1,&m.vertex_buffer);if(m.index_buffer&&api_.DeleteBuffers)api_.DeleteBuffers(1,&m.index_buffer);if(m.vao&&api_.DeleteVertexArrays)api_.DeleteVertexArrays(1,&m.vao);m={};}
bool OpenGLESAssetResidency::ensure_capacity(std::size_t bytes,std::uint64_t protected_id,std::string&error){if(bytes>config_.budget_bytes){error="mesh exceeds GPU residency budget";return false;}while((stats_.resident_bytes+bytes>config_.budget_bytes)||meshes_.size()>=config_.max_meshes){auto it=meshes_.end();for(auto i=meshes_.begin();i!=meshes_.end();++i)if(i->resident&&i->asset_id!=protected_id&&(it==meshes_.end()||i->last_used_frame<it->last_used_frame))it=i;if(it==meshes_.end()){error="GPU residency has no evictable capacity";return false;}stats_.resident_bytes-=it->bytes();release_mesh(*it);meshes_.erase(it);--stats_.resident_meshes;++stats_.evictions;}return true;}
bool OpenGLESAssetResidency::upload(std::uint64_t id,const Mesh&mesh,std::uint64_t frame,std::string&error){if(!ready()){error="OpenGL ES residency API is incomplete";++stats_.rejected_uploads;return false;}if(id==0||!mesh.valid()){error="invalid mesh residency input";++stats_.rejected_uploads;return false;}if(auto*existing=const_cast<GpuResidentMesh*>(find(id))){existing->last_used_frame=frame;return true;}std::vector<float>v;v.reserve(mesh.vertices.size()*8);for(const auto&x:mesh.vertices)v.insert(v.end(),{x.position.x,x.position.y,x.position.z,x.normal.x,x.normal.y,x.normal.z,x.uv.x,x.uv.y});const std::size_t vb=v.size()*sizeof(float),ib=mesh.indices.size()*sizeof(std::uint32_t);if(!ensure_capacity(vb+ib,id,error)){++stats_.rejected_uploads;return false;}GpuResidentMesh r;r.asset_id=id;r.vertex_bytes=vb;r.index_bytes=ib;r.index_count=mesh.indices.size();r.last_used_frame=frame;api_.GenVertexArrays(1,&r.vao);api_.GenBuffers(1,&r.vertex_buffer);api_.GenBuffers(1,&r.index_buffer);if(!r.vao||!r.vertex_buffer||!r.index_buffer){release_mesh(r);error="GPU mesh allocation failed";++stats_.rejected_uploads;return false;}api_.BindVertexArray(r.vao);api_.BindBuffer(GL_ARRAY_BUFFER,r.vertex_buffer);api_.BufferData(GL_ARRAY_BUFFER,(GlSize)vb,v.data(),GL_STATIC_DRAW);api_.BindBuffer(GL_ELEMENT_ARRAY_BUFFER,r.index_buffer);api_.BufferData(GL_ELEMENT_ARRAY_BUFFER,(GlSize)ib,mesh.indices.data(),GL_STATIC_DRAW);const GlInt stride=(GlInt)(8*sizeof(float));api_.EnableVertexAttribArray(0);api_.VertexAttribPointer(0,3,GL_FLOAT,0,stride,nullptr);api_.EnableVertexAttribArray(1);api_.VertexAttribPointer(1,3,GL_FLOAT,0,stride,(const void*)(3*sizeof(float)));api_.EnableVertexAttribArray(2);api_.VertexAttribPointer(2,2,GL_FLOAT,0,stride,(const void*)(6*sizeof(float)));r.resident=true;meshes_.push_back(r);++stats_.resident_meshes;stats_.resident_bytes+=r.bytes();++stats_.uploads;return true;}
bool OpenGLESAssetResidency::touch(std::uint64_t id,std::uint64_t frame)noexcept{auto i=std::find_if(meshes_.begin(),meshes_.end(),[&](const auto&m){return m.asset_id==id&&m.resident;});if(i==meshes_.end())return false;i->last_used_frame=frame;return true;}
bool OpenGLESAssetResidency::evict(std::uint64_t id)noexcept{auto i=std::find_if(meshes_.begin(),meshes_.end(),[&](const auto&m){return m.asset_id==id;});if(i==meshes_.end())return false;stats_.resident_bytes-=i->bytes();release_mesh(*i);meshes_.erase(i);--stats_.resident_meshes;++stats_.evictions;return true;}
std::size_t OpenGLESAssetResidency::evict_until_within_budget()noexcept{std::size_t n=0;while(stats_.resident_bytes>config_.budget_bytes&& !meshes_.empty()){auto i=std::min_element(meshes_.begin(),meshes_.end(),[](const auto&a,const auto&b){return a.last_used_frame<b.last_used_frame;});stats_.resident_bytes-=i->bytes();release_mesh(*i);meshes_.erase(i);--stats_.resident_meshes;++stats_.evictions;++n;}return n;}
void OpenGLESAssetResidency::clear()noexcept{for(auto&m:meshes_)release_mesh(m);meshes_.clear();stats_.resident_meshes=stats_.resident_bytes=0;}
}