#include "exgine/high_fidelity.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <numeric>

namespace exgine {
namespace {
float clamp01(float v) noexcept { return std::clamp(v,0.0f,1.0f); }
float length2(Vec3 v) noexcept { return std::sqrt(v.x*v.x+v.y*v.y+v.z*v.z); }
Vec3 normalize(Vec3 v) noexcept { const float l=length2(v); return l>1e-6f?Vec3{v.x/l,v.y/l,v.z/l}:Vec3{0,0,1}; }
std::uint64_t hash64(std::uint64_t x) noexcept { x^=x>>30; x*=0xbf58476d1ce4e5b9ULL; x^=x>>27; x*=0x94d049bb133111ebULL; return x^(x>>31); }
float unit(std::uint64_t x) noexcept { return static_cast<float>((hash64(x)>>40)&0xFFFFFFu)/16777215.0f; }
void put32(std::vector<std::uint8_t>& b,std::uint32_t v){for(int i=0;i<4;++i)b.push_back(static_cast<std::uint8_t>(v>>(i*8)));}
void put64(std::vector<std::uint8_t>& b,std::uint64_t v){for(int i=0;i<8;++i)b.push_back(static_cast<std::uint8_t>(v>>(i*8)));}
void putf(std::vector<std::uint8_t>& b,float v){std::uint32_t x=0;std::memcpy(&x,&v,4);put32(b,x);} 
void putd(std::vector<std::uint8_t>& b,double v){std::uint64_t x=0;std::memcpy(&x,&v,8);put64(b,x);} 
void puts(std::vector<std::uint8_t>& b,std::string_view s){put32(b,static_cast<std::uint32_t>(s.size()));b.insert(b.end(),s.begin(),s.end());}
bool get32(const std::vector<std::uint8_t>& b,std::size_t& p,std::uint32_t& v){if(p+4>b.size())return false;v=static_cast<std::uint32_t>(b[p])|(static_cast<std::uint32_t>(b[p+1])<<8)|(static_cast<std::uint32_t>(b[p+2])<<16)|(static_cast<std::uint32_t>(b[p+3])<<24);p+=4;return true;}
bool get64(const std::vector<std::uint8_t>& b,std::size_t& p,std::uint64_t& v){if(p+8>b.size())return false;v=0;for(int i=0;i<8;++i)v|=static_cast<std::uint64_t>(b[p+i])<<(8*i);p+=8;return true;}
bool getf(const std::vector<std::uint8_t>& b,std::size_t& p,float& v){std::uint32_t x=0;if(!get32(b,p,x))return false;std::memcpy(&v,&x,4);return true;}
bool getd(const std::vector<std::uint8_t>& b,std::size_t& p,double& v){std::uint64_t x=0;if(!get64(b,p,x))return false;std::memcpy(&v,&x,8);return true;}
bool gets(const std::vector<std::uint8_t>& b,std::size_t& p,std::string& s){std::uint32_t n=0;if(!get32(b,p,n)||p+n>b.size())return false;s.assign(reinterpret_cast<const char*>(b.data()+p),n);p+=n;return true;}
}

bool MaterialRuntimeState::set(std::string name,MaterialRuntimeDesc desc){if(name.empty())return false;desc.clear_coat=clamp01(desc.clear_coat);desc.transmission=clamp01(desc.transmission);desc.subsurface=clamp01(desc.subsurface);desc.sheen=clamp01(desc.sheen);desc.wetness=clamp01(desc.wetness);desc.dust=clamp01(desc.dust);desc.mud=clamp01(desc.mud);desc.snow=clamp01(desc.snow);desc.rust=clamp01(desc.rust);desc.moss=clamp01(desc.moss);materials_[std::move(name)]=desc;return true;}
bool MaterialRuntimeState::set_weathering(std::string_view name,float wetness,float dust,float mud,float snow,float rust,float moss) noexcept {auto it=materials_.find(std::string(name));if(it==materials_.end())return false;it->second.wetness=clamp01(wetness);it->second.dust=clamp01(dust);it->second.mud=clamp01(mud);it->second.snow=clamp01(snow);it->second.rust=clamp01(rust);it->second.moss=clamp01(moss);return true;}
const MaterialRuntimeDesc* MaterialRuntimeState::get(std::string_view name) const noexcept {auto it=materials_.find(std::string(name));return it==materials_.end()?nullptr:&it->second;}
MeshRuntimeStats inspect_mesh(const MeshAssembly& a) noexcept {MeshRuntimeStats s{};for(const auto& p:a.parts){s.vertices+=p.mesh.vertices.size();s.indices+=p.mesh.indices.size();s.triangles+=p.mesh.indices.size()/3;++s.draw_parts;}return s;}

float eroded_height(float base,float slope,float moisture,std::uint64_t seed) noexcept {const float noise=unit(seed)*2.0f-1.0f;const float erosion=std::clamp(std::abs(slope)*0.35f+moisture*0.25f,0.0f,1.0f);return base+(noise*erosion*8.0f)-std::max(0.0f,slope)*erosion*3.0f;}
std::vector<Vec3> generate_vegetation(const VegetationPatch& patch,std::uint32_t count) noexcept {std::vector<Vec3> out;out.reserve(count);if(count==0||patch.radius<=0)return out;for(std::uint32_t i=0;i<count;++i){const float a=unit(patch.species.empty()?i:patch.species[i%patch.species.size()].seed+i)*6.2831853f;const float r=std::sqrt(unit(i*7919ULL+static_cast<std::uint64_t>(patch.radius)*31))*patch.radius;out.push_back({patch.center.x+std::cos(a)*r,patch.center.y,patch.center.z+std::sin(a)*r});}return out;}

std::uint64_t ParticleWorld::create(ParticleEmitter e){if(e.max_particles==0)return 0;const auto id=next_id_++;emitters_.emplace(id,EmitterState{std::move(e),0,{}});return id;}
bool ParticleWorld::destroy(std::uint64_t id) noexcept{return emitters_.erase(id)>0;}
bool ParticleWorld::update(std::uint64_t id,float dt) noexcept {if(dt<0)return false;auto it=emitters_.find(id);if(it==emitters_.end())return false;auto& s=it->second;s.accumulator+=std::max(0.0f,s.emitter.rate)*dt;const auto spawn=std::min<std::size_t>(static_cast<std::size_t>(s.accumulator),s.emitter.max_particles-s.particles.size());s.accumulator-=static_cast<float>(spawn);for(std::size_t i=0;i<spawn;++i){const auto k=s.emitter.seed+i+s.particles.size()*17ULL;const float jitter=unit(k)*0.25f;s.particles.push_back({s.emitter.position,{s.emitter.direction.x*(s.emitter.speed+jitter),s.emitter.direction.y*(s.emitter.speed+jitter),s.emitter.direction.z*(s.emitter.speed+jitter)},s.emitter.lifetime});}for(auto& p:s.particles){p.position.x+=p.velocity.x*dt;p.position.y+=p.velocity.y*dt;p.position.z+=p.velocity.z*dt;p.life-=dt;}s.particles.erase(std::remove_if(s.particles.begin(),s.particles.end(),[](const ParticleState& p){return p.life<=0;}),s.particles.end());return true;}
const std::vector<ParticleState>* ParticleWorld::particles(std::uint64_t id) const noexcept {auto it=emitters_.find(id);return it==emitters_.end()?nullptr:&it->second.particles;}
void ParticleWorld::clear() noexcept {emitters_.clear();}

LocomotionState LocomotionController::select(float hs,float vs,bool grounded,bool swimming,bool climbing) const noexcept {if(swimming)return LocomotionState::Swim;if(climbing)return LocomotionState::Climb;if(!grounded)return vs>0.1f?LocomotionState::Jump:LocomotionState::Fall;if(hs<0.05f)return LocomotionState::Idle;if(hs<1.7f)return LocomotionState::Walk;return LocomotionState::Run;}
bool LocomotionController::update(CharacterMotionState& s,float hs,float vs,bool grounded,bool swimming,bool climbing,float dt) noexcept {if(dt<0)return false;const auto next=select(std::abs(hs),vs,grounded,swimming,climbing);if(next!=s.state){s.state=next;s.blend=0;}s.speed=std::max(0.0f,hs);s.vertical_speed=vs;s.grounded=grounded;s.blend=std::min(1.0f,s.blend+dt*8.0f);return true;}

void AdvancedPhysicsPolicy::set_surface(std::string material,PhysicalSurface surface){if(material.empty())return;surface.friction=std::max(0.0f,surface.friction);surface.restitution=clamp01(surface.restitution);surface.rolling_resistance=std::max(0.0f,surface.rolling_resistance);surfaces_[std::move(material)]=surface;}
const PhysicalSurface* AdvancedPhysicsPolicy::surface(std::string_view material) const noexcept {auto it=surfaces_.find(std::string(material));return it==surfaces_.end()?nullptr:&it->second;}
float AdvancedPhysicsPolicy::effective_friction(std::string_view a,std::string_view b) const noexcept {const auto* sa=surface(a);const auto* sb=surface(b);if(!sa&&!sb)return .5f;const float fa=sa?sa->friction:.5f,fb=sb?sb->friction:.5f;return std::sqrt(std::max(0.0f,fa*fb));}

HighFidelityVehicle::HighFidelityVehicle(float mass):mass_(std::max(1.0f,mass)){for(auto& t:state_.tires)t.radius=.34f;}
void HighFidelityVehicle::set_input(float throttle,float brake,float steer,bool reverse) noexcept {state_.drivetrain.throttle=clamp01(throttle);state_.drivetrain.brake=clamp01(brake);state_.drivetrain.steer=std::clamp(steer,-1.0f,1.0f);state_.drivetrain.reverse=reverse;}
void HighFidelityVehicle::update(float dt,float forward_speed,float normal_load[4]) noexcept {if(dt<=0)return;state_.speed=forward_speed;const float target_rpm=800.0f+std::abs(forward_speed)*85.0f;state_.drivetrain.rpm+= (target_rpm-state_.drivetrain.rpm)*std::min(1.0f,dt*6.0f);const float torque_curve=std::clamp(1.0f-std::abs(state_.drivetrain.rpm-4500.0f)/4500.0f,0.1f,1.0f);state_.drivetrain.engine_torque=420.0f*state_.drivetrain.throttle*torque_curve;state_.drivetrain.drive_torque=state_.drivetrain.engine_torque*(state_.drivetrain.gear<=0?-1.0f:state_.drivetrain.gear*0.85f);for(std::size_t i=0;i<4;++i){auto& t=state_.tires[i];t.load=normal_load?std::max(0.0f,normal_load[i]):mass_*9.81f/4.0f;const float wheel_speed=forward_speed/std::max(0.1f,t.radius);t.slip_ratio=(wheel_speed-std::abs(forward_speed))/std::max(1.0f,std::abs(forward_speed));t.slip_ratio=std::clamp(t.slip_ratio,-1.0f,1.0f);const float steer_scale=(i<2?state_.drivetrain.steer:0.0f);t.slip_angle=std::atan2(steer_scale,std::max(.5f,std::abs(forward_speed)));const float mu=1.05f;const float max_force=t.load*mu;t.longitudinal_force=std::clamp(state_.drivetrain.drive_torque/std::max(.1f,t.radius),-max_force,max_force);t.lateral_force=std::clamp(-t.slip_angle*90000.0f,-max_force,max_force);state_.suspension[i].length=state_.suspension[i].rest_length;state_.suspension[i].spring_force=state_.suspension[i].compression*30000.0f;state_.suspension[i].damper_force=state_.suspension[i].velocity*3500.0f;}}
float HighFidelityVehicle::longitudinal_force(std::size_t i) const noexcept {return i<4?state_.tires[i].longitudinal_force:0.0f;}
float HighFidelityVehicle::lateral_force(std::size_t i) const noexcept {return i<4?state_.tires[i].lateral_force:0.0f;}
bool VehiclePossession::enter(EntityId player,EntityId vehicle) noexcept {if(player==invalid_entity||vehicle==invalid_entity||player==vehicle)return false;player_=player;vehicle_=vehicle;return true;}
bool VehiclePossession::exit() noexcept {if(!active())return false;player_=vehicle_=invalid_entity;return true;}

void CrowdSolver::add(CrowdAgent a){if(a.entity==invalid_entity)return;a.radius=std::max(.05f,a.radius);a.max_speed=std::max(0.0f,a.max_speed);a.acceleration=std::max(0.0f,a.acceleration);agents_.push_back(a);}
void CrowdSolver::clear() noexcept {agents_.clear();}
std::vector<CrowdAgent> CrowdSolver::solve(const std::vector<Vec3>& positions,float dt) const noexcept {auto out=agents_;if(dt<=0)return out;for(std::size_t i=0;i<out.size();++i){Vec3 separation{};for(std::size_t j=0;j<out.size()&&j<positions.size()&&i<positions.size();++j){if(i==j)continue;Vec3 d{positions[i].x-positions[j].x,positions[i].y-positions[j].y,positions[i].z-positions[j].z};const float l=length2(d);const float min_d=out[i].radius+out[j].radius;if(l>1e-4f&&l<min_d*2.0f){const float w=(min_d*2.0f-l)/(min_d*2.0f);separation.x+=d.x/l*w;separation.z+=d.z/l*w;}}const float target=length2(separation)>1e-4f?out[i].max_speed:0.0f;const Vec3 desired=normalize(separation);out[i].velocity.x+=std::clamp(desired.x*target-out[i].velocity.x,-out[i].acceleration*dt,out[i].acceleration*dt);out[i].velocity.z+=std::clamp(desired.z*target-out[i].velocity.z,-out[i].acceleration*dt,out[i].acceleration*dt);}return out;}

void LivingWorld::set_time(double seconds) noexcept {state_.time_seconds=std::max(0.0,seconds);const double day=1200.0;state_.day=static_cast<std::uint32_t>(state_.time_seconds/day);state_.season=(state_.day/30)%4;}
void LivingWorld::advance(double dt,float day_length_seconds) noexcept {if(dt<0)return;state_.time_seconds+=dt;const float d=std::max(1.0f,day_length_seconds);state_.day=static_cast<std::uint32_t>(state_.time_seconds/d);state_.season=(state_.day/30)%4;}
void LivingWorld::set_density(float t,float p,float w) noexcept {state_.traffic_density=std::max(0.0f,t);state_.pedestrian_density=std::max(0.0f,p);state_.wildlife_activity=std::max(0.0f,w);}

AudioMixResult SpatialAudioProcessor::process(const AudioListener& listener,const AudioCue& cue,float occlusion) noexcept {const Vec3 d{cue.position.x-listener.position.x,cue.position.y-listener.position.y,cue.position.z-listener.position.z};const float dist=length2(d);const float attenuation=1.0f/std::max(1.0f,dist/std::max(.01f,cue.radius));const Vec3 f=normalize(listener.forward);const Vec3 dir=normalize(d);const float right=f.z*dir.x-f.x*dir.z;return {cue.gain*attenuation*(1.0f-clamp01(occlusion)*.8f),std::clamp(right,-1.0f,1.0f),1.0f-clamp01(occlusion)*.9f};}

std::uint64_t GameplayEventBus::subscribe(Handler h){if(!h)return 0;const auto id=next_id_++;handlers_.emplace(id,std::move(h));return id;}
bool GameplayEventBus::unsubscribe(std::uint64_t id) noexcept{return handlers_.erase(id)>0;}
void GameplayEventBus::emit(const GameplayEvent& e){std::vector<Handler> handlers;handlers.reserve(handlers_.size());for(const auto& [id,h]:handlers_)if(h)handlers.push_back(h);for(auto& h:handlers)h(e);}
void GameplayEventBus::clear() noexcept {handlers_.clear();}

std::vector<std::uint8_t> PersistentWorldStore::encode(const PersistentWorldState& s){std::vector<std::uint8_t>b{'X','G','W','2'};put32(b,s.version);puts(b,s.project);puts(b,s.scene);putd(b,s.world_time);put32(b,static_cast<std::uint32_t>(s.entities.size()));for(const auto&e:s.entities){put64(b,e.id);putf(b,e.position.x);putf(b,e.position.y);putf(b,e.position.z);putf(b,e.velocity.x);putf(b,e.velocity.y);putf(b,e.velocity.z);putf(b,e.health);put32(b,e.flags);put32(b,static_cast<std::uint32_t>(e.variables.size()));for(const auto& [k,v]:e.variables){puts(b,k);puts(b,v);}}put32(b,static_cast<std::uint32_t>(s.variables.size()));for(const auto& [k,v]:s.variables){puts(b,k);puts(b,v);}return b;}
bool PersistentWorldStore::decode(const std::vector<std::uint8_t>&b,PersistentWorldState&s,std::string&e){if(b.size()<8||b[0]!='X'||b[1]!='G'||b[2]!='W'||b[3]!='2'){e="invalid world save";return false;}std::size_t p=4;std::uint32_t version=0,n=0;if(!get32(b,p,version)||!gets(b,p,s.project)||!gets(b,p,s.scene)||!getd(b,p,s.world_time)||!get32(b,p,n)){e="truncated world save";return false;}s={};s.version=version;if(p>0){/* strings were decoded into s before reset; decode below keeps offsets deterministic */}p=8;s.project.clear();s.scene.clear();if(!gets(b,p,s.project)||!gets(b,p,s.scene)||!getd(b,p,s.world_time)||!get32(b,p,n)){e="truncated world save";return false;}for(std::uint32_t i=0;i<n;++i){PersistedEntityState x;std::uint64_t id=0;if(!get64(b,p,id)||!getf(b,p,x.position.x)||!getf(b,p,x.position.y)||!getf(b,p,x.position.z)||!getf(b,p,x.velocity.x)||!getf(b,p,x.velocity.y)||!getf(b,p,x.velocity.z)||!getf(b,p,x.health)||!get32(b,p,x.flags)){e="truncated entity";return false;}x.id=id;std::uint32_t m=0;if(!get32(b,p,m)){e="truncated entity variables";return false;}for(std::uint32_t j=0;j<m;++j){std::string k,v;if(!gets(b,p,k)||!gets(b,p,v)){e="truncated entity variable";return false;}x.variables.emplace_back(std::move(k),std::move(v));}s.entities.push_back(std::move(x));}if(!get32(b,p,n)){e="truncated global variables";return false;}for(std::uint32_t i=0;i<n;++i){std::string k,v;if(!gets(b,p,k)||!gets(b,p,v)){e="truncated global variable";return false;}s.variables.emplace_back(std::move(k),std::move(v));}return p==b.size();}

void AdaptiveQuality::sample(float frame_ms,float gpu_ms,float temperature_c) noexcept {const float pressure=std::max(frame_ms,gpu_ms);if(pressure>20.0f||temperature_c>42.0f){++pressure_frames_;headroom_frames_=0;}else if(pressure<13.0f&&temperature_c<38.0f){++headroom_frames_;pressure_frames_=0;}else{pressure_frames_=headroom_frames_=0;}if(settings_.tier==QualityTier::Auto&&pressure_frames_>=8){settings_.render_scale=std::max(.65f,settings_.render_scale-.05f);settings_.shadow_distance=std::max(40.0f,settings_.shadow_distance-10.0f);settings_.vegetation_scale=std::max(.5f,settings_.vegetation_scale-.1f);settings_.particle_scale=std::max(.5f,settings_.particle_scale-.1f);pressure_frames_=0;}if(settings_.tier==QualityTier::Auto&&headroom_frames_>=30){settings_.render_scale=std::min(1.0f,settings_.render_scale+.025f);settings_.shadow_distance=std::min(180.0f,settings_.shadow_distance+5.0f);settings_.vegetation_scale=std::min(1.0f,settings_.vegetation_scale+.05f);settings_.particle_scale=std::min(1.0f,settings_.particle_scale+.05f);headroom_frames_=0;}}

bool WorldStreamScheduler::enqueue(std::string uri,float distance,bool visible){if(uri.empty())return false;queue_.push_back({std::move(uri),std::max(0.0f,distance),visible});return true;}
std::vector<std::string> WorldStreamScheduler::dispatch(){std::stable_sort(queue_.begin(),queue_.end(),[](const Job&a,const Job&b){if(a.visible!=b.visible)return a.visible>b.visible;return a.distance<b.distance;});const std::size_t n=std::min<std::size_t>(budget_.max_uploads,queue_.size());std::vector<std::string> out;out.reserve(n);for(std::size_t i=0;i<n;++i)out.push_back(std::move(queue_[i].uri));queue_.erase(queue_.begin(),queue_.begin()+static_cast<std::ptrdiff_t>(n));return out;}

bool WorldTemplateLibrary::define(WorldObjectTemplate o){if(o.name.empty())return false;objects_[o.name]=std::move(o);return true;}
const WorldObjectTemplate* WorldTemplateLibrary::find(std::string_view n) const noexcept {auto it=objects_.find(std::string(n));return it==objects_.end()?nullptr:&it->second;}
bool ScriptEnvironment::set(std::string n,ScriptValue v){if(n.empty())return false;values_[std::move(n)]=std::move(v);return true;}
const ScriptValue* ScriptEnvironment::get(std::string_view n) const noexcept {auto it=values_.find(std::string(n));return it==values_.end()?nullptr:&it->second;}

void SnapshotInterpolator::push(NetworkEntitySnapshot s){snapshots_.push_back(s);std::stable_sort(snapshots_.begin(),snapshots_.end(),[](const auto&a,const auto&b){return a.tick<b.tick;});if(snapshots_.size()>32)snapshots_.erase(snapshots_.begin(),snapshots_.begin()+static_cast<std::ptrdiff_t>(snapshots_.size()-32));}
std::optional<NetworkEntitySnapshot> SnapshotInterpolator::sample(std::uint32_t tick) const noexcept {if(snapshots_.empty())return std::nullopt;auto it=std::lower_bound(snapshots_.begin(),snapshots_.end(),tick,[](const auto&a,std::uint32_t t){return a.tick<t;});if(it==snapshots_.begin())return *it;if(it==snapshots_.end())return snapshots_.back();const auto&b=*it;const auto&a=*(it-1);const float t=(b.tick==a.tick)?1.0f:static_cast<float>(tick-a.tick)/static_cast<float>(b.tick-a.tick);NetworkEntitySnapshot r=a;r.tick=tick;r.position.x=a.position.x+(b.position.x-a.position.x)*t;r.position.y=a.position.y+(b.position.y-a.position.y)*t;r.position.z=a.position.z+(b.position.z-a.position.z)*t;r.velocity.x=a.velocity.x+(b.velocity.x-a.velocity.x)*t;r.velocity.y=a.velocity.y+(b.velocity.y-a.velocity.y)*t;r.velocity.z=a.velocity.z+(b.velocity.z-a.velocity.z)*t;return r;}
bool DestructibleObject::apply(const DestructionImpulse& impulse) noexcept {if(state_.destroyed||impulse.energy<=0)return false;state_.integrity=std::max(0.0f,state_.integrity-impulse.energy);if(state_.integrity<=0)state_.destroyed=true;return true;}

AndroidPackagingPlan make_android_packaging_plan(const AndroidPackagingConfig& c){AndroidPackagingPlan p;if(c.application_id.empty()||c.display_name.empty()||c.min_sdk.empty()||c.target_sdk.empty())return p;p.valid=true;p.gradle_project="plugins { id('com.android.application') version '8.7.3' apply false }\n";p.gradle_project+="android { namespace '"+c.application_id+"'; compileSdk 35 }\n";p.gradle_project+="defaultConfig { applicationId '"+c.application_id+"'; minSdk "+c.min_sdk+"; targetSdk "+c.target_sdk+"; versionCode "+std::to_string(c.version_code)+"; versionName '"+c.version_name+"' }\n";p.app_manifest="<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"><application android:label=\""+c.display_name+"\"><activity android:name=\"android.app.NativeActivity\" android:exported=\"true\"><meta-data android:name=\"android.app.lib_name\" android:value=\"exgine\"/><intent-filter><action android:name=\"android.intent.action.MAIN\"/><category android:name=\"android.intent.category.LAUNCHER\"/></intent-filter></activity></application></manifest>\n";p.cmake_arguments="-DANDROID_PLATFORM=android-"+c.min_sdk+" -DANDROID_STL=c++_shared";return p;}

} // namespace exgine
