#include "exgine/performance.hpp"
#include <cmath>
namespace exgine { namespace { constexpr float kMinScale=.5f,kMaxScale=1.0f; float clamp_scale(float v)noexcept{return std::clamp(v,kMinScale,kMaxScale);}float tier_min_scale(PerformanceTier t)noexcept{switch(t){case PerformanceTier::Ultra:return 1;case PerformanceTier::High:return .85f;case PerformanceTier::Medium:return .70f;case PerformanceTier::Low:return .60f;case PerformanceTier::BatterySaver:return .50f;}return .50f;}float tier_max_scale(PerformanceTier t)noexcept{switch(t){case PerformanceTier::Ultra:return 1;case PerformanceTier::High:return 1;case PerformanceTier::Medium:return .90f;case PerformanceTier::Low:return .80f;case PerformanceTier::BatterySaver:return .70f;}return .70f;}std::uint32_t tier_fps(PerformanceTier t)noexcept{switch(t){case PerformanceTier::Ultra:return 120;case PerformanceTier::High:return 90;case PerformanceTier::Medium:return 60;case PerformanceTier::Low:return 45;case PerformanceTier::BatterySaver:return 30;}return 60;}bool at_most(PerformanceTier a,PerformanceTier b)noexcept{return static_cast<std::uint8_t>(a)<=static_cast<std::uint8_t>(b);}}
bool PerformanceProfile::valid()const noexcept{return render_width>=320&&render_height>=240&&render_scale>=kMinScale&&render_scale<=kMaxScale&&target_fps>=20&&target_fps<=240&&max_dynamic_lights>0&&shadow_cascades<=8&&shadow_map_size>=256&&shadow_map_size<=8192&&world_active_radius<=64&&world_prefetch_radius>=world_active_radius&&world_prefetch_radius<=64&&max_loaded_chunks>0&&vegetation_density_percent<=100&&texture_budget_mb>0&&geometry_budget_mb>0;}
bool DevicePerformanceLimits::valid()const noexcept{return max_render_width>=320&&max_render_height>=240&&max_target_fps>=20&&max_dynamic_lights>0&&max_texture_budget_mb>0&&max_geometry_budget_mb>0&&max_resident_bytes>0;}
bool FrameBudget::valid()const noexcept{return std::isfinite(target_ms)&&std::isfinite(cpu_budget_ms)&&std::isfinite(gpu_budget_ms)&&std::isfinite(streaming_budget_ms)&&std::isfinite(physics_budget_ms)&&target_ms>0&&cpu_budget_ms>0&&gpu_budget_ms>0&&streaming_budget_ms>0&&physics_budget_ms>0;}
bool PerformanceTelemetry::valid()const noexcept{return std::isfinite(cpu_frame_ms)&&std::isfinite(gpu_frame_ms)&&std::isfinite(streaming_ms)&&std::isfinite(physics_ms)&&cpu_frame_ms>=0&&gpu_frame_ms>=0&&streaming_ms>=0&&physics_ms>=0;}
bool PerformanceDecision::valid()const noexcept{return render_scale>=kMinScale&&render_scale<=kMaxScale;}
PerformanceProfile PerformanceController::normalize(PerformanceProfile p,const DevicePerformanceLimits&l)noexcept{p.render_width=std::clamp(p.render_width,320u,l.max_render_width);p.render_height=std::clamp(p.render_height,240u,l.max_render_height);p.render_scale=clamp_scale(p.render_scale);p.target_fps=std::clamp(p.target_fps,20u,l.max_target_fps);p.max_dynamic_lights=std::clamp(p.max_dynamic_lights,1u,l.max_dynamic_lights);p.shadow_cascades=std::min(p.shadow_cascades,8u);p.shadow_map_size=std::clamp(p.shadow_map_size,256u,8192u);p.world_active_radius=std::min(p.world_active_radius,64u);p.world_prefetch_radius=std::clamp(p.world_prefetch_radius,p.world_active_radius,64u);p.max_loaded_chunks=std::clamp(p.max_loaded_chunks,1u,4096u);p.vegetation_density_percent=std::min(p.vegetation_density_percent,100u);p.texture_budget_mb=std::clamp(p.texture_budget_mb,16u,l.max_texture_budget_mb);p.geometry_budget_mb=std::clamp(p.geometry_budget_mb,16u,l.max_geometry_budget_mb);return p;}
PerformanceController::PerformanceController(PerformanceProfile p,DevicePerformanceLimits l):profile_(normalize(p,l)),limits_(l){}
float PerformanceController::min_scale(PerformanceTier t)noexcept{return tier_min_scale(t);}float PerformanceController::max_scale(PerformanceTier t)noexcept{return tier_max_scale(t);}std::uint32_t PerformanceController::fps_for(PerformanceTier t)noexcept{return tier_fps(t);}
FrameBudget PerformanceController::frame_budget()const noexcept{const float target=1000.0f/static_cast<float>(profile_.target_fps);return{target,target*.5f,target*.5f,target*.10f,target*.20f};}
PerformanceDecision PerformanceController::update(const PerformanceTelemetry&t)noexcept{PerformanceDecision d{profile_.tier,profile_.render_scale,false,false};if(!t.valid())return d;const auto b=frame_budget();const bool overloaded=t.cpu_frame_ms>b.cpu_budget_ms*1.15f||t.gpu_frame_ms>b.gpu_budget_ms*1.15f||t.streaming_ms>b.streaming_budget_ms*1.5f||t.physics_ms>b.physics_budget_ms*1.5f;const bool healthy=t.cpu_frame_ms<b.cpu_budget_ms*.80f&&t.gpu_frame_ms<b.gpu_budget_ms*.80f&&t.streaming_ms<b.streaming_budget_ms&&t.physics_ms<b.physics_budget_ms;if(overloaded){++overload_frames_;recovery_frames_=0;}else if(healthy){++recovery_frames_;overload_frames_=0;}else{overload_frames_=recovery_frames_=0;}if(t.thermal==ThermalState::Critical||overload_frames_>=8){const auto old=profile_.tier;if(profile_.tier!=PerformanceTier::BatterySaver)profile_.tier=static_cast<PerformanceTier>(static_cast<std::uint8_t>(profile_.tier)+1u);profile_.render_scale=std::max(tier_min_scale(profile_.tier),profile_.render_scale*.90f);profile_.target_fps=std::min(profile_.target_fps,tier_fps(profile_.tier));d.quality_changed=old!=profile_.tier;overload_frames_=0;}else if(recovery_frames_>=120&&profile_.tier!=PerformanceTier::Ultra){const auto old=profile_.tier;profile_.tier=static_cast<PerformanceTier>(static_cast<std::uint8_t>(profile_.tier)-1u);profile_.render_scale=std::min(tier_max_scale(profile_.tier),profile_.render_scale*1.05f);profile_.target_fps=std::min(limits_.max_target_fps,tier_fps(profile_.tier));d.quality_changed=old!=profile_.tier;recovery_frames_=0;}d.tier=profile_.tier;d.render_scale=profile_.render_scale;d.throttle_simulation=t.thermal>=ThermalState::Serious||t.physics_ms>b.physics_budget_ms*2.0f;return d;}
void PerformanceController::set_profile(PerformanceProfile p)noexcept{profile_=normalize(p,limits_);overload_frames_=recovery_frames_=0;}void PerformanceController::reset()noexcept{overload_frames_=recovery_frames_=0;}
PerformanceProfile make_mobile_profile(PerformanceTier tier,std::uint32_t w,std::uint32_t h)noexcept{PerformanceProfile p;p.tier=tier;p.render_width=std::min(w,1920u);p.render_height=std::min(h,1080u);p.render_scale=tier_max_scale(tier);p.target_fps=tier_fps(tier);p.max_dynamic_lights=tier==PerformanceTier::Ultra?96u:tier==PerformanceTier::High?64u:tier==PerformanceTier::Medium?32u:16u;p.shadow_cascades=tier==PerformanceTier::Ultra?4u:tier==PerformanceTier::High?3u:tier==PerformanceTier::Medium?2u:1u;p.shadow_map_size=(tier==PerformanceTier::Ultra||tier==PerformanceTier::High)?2048u:1024u;p.world_active_radius=tier==PerformanceTier::Ultra?6u:tier==PerformanceTier::High?5u:tier==PerformanceTier::Medium?4u:3u;p.world_prefetch_radius=std::min(8u,p.world_active_radius+2u);p.max_loaded_chunks=tier==PerformanceTier::Ultra?192u:tier==PerformanceTier::High?144u:tier==PerformanceTier::Medium?96u:64u;p.vegetation_density_percent=tier==PerformanceTier::Ultra?100u:tier==PerformanceTier::High?85u:tier==PerformanceTier::Medium?65u:tier==PerformanceTier::Low?45u:30u;p.texture_budget_mb=tier==PerformanceTier::Ultra?512u:tier==PerformanceTier::High?384u:tier==PerformanceTier::Medium?256u:160u;p.geometry_budget_mb=tier==PerformanceTier::Ultra?384u:tier==PerformanceTier::High?288u:tier==PerformanceTier::Medium?192u:128u;p.hdr=tier!=PerformanceTier::BatterySaver;p.ambient_occlusion=at_most(tier,PerformanceTier::Medium);p.bloom=at_most(tier,PerformanceTier::High);p.motion_blur=false;return p;}
} // namespace exgine
