#include "exgine/physics.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <limits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace exgine {
namespace {
constexpr float kEps = 1.0e-6f;

Vec3 add(Vec3 a, Vec3 b) noexcept { return {a.x+b.x,a.y+b.y,a.z+b.z}; }
Vec3 sub(Vec3 a, Vec3 b) noexcept { return {a.x-b.x,a.y-b.y,a.z-b.z}; }
Vec3 mul(Vec3 a, float s) noexcept { return {a.x*s,a.y*s,a.z*s}; }
float dot(Vec3 a, Vec3 b) noexcept { return a.x*b.x+a.y*b.y+a.z*b.z; }
Vec3 cross(Vec3 a, Vec3 b) noexcept { return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x}; }
float len_sq(Vec3 v) noexcept { return dot(v,v); }
float len(Vec3 v) noexcept { return std::sqrt(std::max(0.0f,len_sq(v))); }
Vec3 norm(Vec3 v) noexcept { const float l=len(v); return l>kEps?mul(v,1.0f/l):Vec3{0,1,0}; }
bool finite(Vec3 v) noexcept { return std::isfinite(v.x)&&std::isfinite(v.y)&&std::isfinite(v.z); }
bool finite(float v) noexcept { return std::isfinite(v); }

struct Quat { float x=0,y=0,z=0,w=1; };
Quat normalize(Quat q) noexcept { const float l=std::sqrt(q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w); return l>kEps?Quat{q.x/l,q.y/l,q.z/l,q.w/l}:Quat{}; }
Quat multiply(Quat a,Quat b) noexcept { return normalize({a.w*b.x+a.x*b.w+a.y*b.z-a.z*b.y,a.w*b.y-a.x*b.z+a.y*b.w+a.z*b.x,a.w*b.z+a.x*b.y-a.y*b.x+a.z*b.w,a.w*b.w-a.x*b.x-a.y*b.y-a.z*b.z}); }
Quat conjugate(Quat q) noexcept { return {-q.x,-q.y,-q.z,q.w}; }
Quat from_euler(Vec3 r) noexcept { const float cx=std::cos(r.x*.5f),sx=std::sin(r.x*.5f),cy=std::cos(r.y*.5f),sy=std::sin(r.y*.5f),cz=std::cos(r.z*.5f),sz=std::sin(r.z*.5f); return normalize({sx*cy*cz-cx*sy*sz,cx*sy*cz+sx*cy*sz,cx*cy*sz-sx*sy*cz,cx*cy*cz+sx*sy*sz}); }
Vec3 rotate(Quat q,Vec3 v) noexcept { const Quat p{v.x,v.y,v.z,0}; const Quat r=multiply(multiply(q,p),conjugate(q)); return {r.x,r.y,r.z}; }
Vec3 to_euler(Quat q) noexcept { q=normalize(q); const float sinp=2.0f*(q.w*q.x-q.z*q.y); const float pitch=std::abs(sinp)>=1.0f?std::copysign(1.57079632679f,sinp):std::asin(sinp); const float yaw=std::atan2(2.0f*(q.w*q.y+q.z*q.x),1.0f-2.0f*(q.x*q.x+q.y*q.y)); const float roll=std::atan2(2.0f*(q.w*q.z+q.x*q.y),1.0f-2.0f*(q.y*q.y+q.z*q.z)); return {pitch,yaw,roll}; }
PhysicsTransform compose(PhysicsTransform a,PhysicsTransform b) noexcept { const Quat qa=from_euler(a.rotation); return {add(a.position,rotate(qa,b.position)),to_euler(multiply(qa,from_euler(b.rotation)))}; }

PhysicsAabb merge(PhysicsAabb a,PhysicsAabb b) noexcept { return {{std::min(a.min.x,b.min.x),std::min(a.min.y,b.min.y),std::min(a.min.z,b.min.z)},{std::max(a.max.x,b.max.x),std::max(a.max.y,b.max.y),std::max(a.max.z,b.max.z)}}; }
bool overlaps(PhysicsAabb a,PhysicsAabb b) noexcept { return a.min.x<=b.max.x&&a.max.x>=b.min.x&&a.min.y<=b.max.y&&a.max.y>=b.min.y&&a.min.z<=b.max.z&&a.max.z>=b.min.z; }

PhysicsAabb shape_local_bounds(const PhysicsShape& s) noexcept {
    switch(s.type) {
    case PhysicsShapeType::Sphere: { const auto q=std::get<PhysicsSphereShape>(s.data); const float r=std::max(0.0f,q.radius); return {{-r,-r,-r},{r,r,r}}; }
    case PhysicsShapeType::Box: { const auto e=std::get<PhysicsBoxShape>(s.data).half_extents; return {{-e.x,-e.y,-e.z},e}; }
    case PhysicsShapeType::Capsule: { const auto q=std::get<PhysicsCapsuleShape>(s.data); const float r=std::max(0.0f,q.radius),h=std::max(0.0f,q.half_height); return {{-r,-h-r,-r},{r,h+r,r}}; }
    case PhysicsShapeType::Cylinder: { const auto q=std::get<PhysicsCylinderShape>(s.data); const float r=std::max(0.0f,q.radius),h=std::max(0.0f,q.half_height); return {{-r,-h,-r},{r,h,r}}; }
    case PhysicsShapeType::ConvexHull: { const auto& points=std::get<PhysicsConvexHullShape>(s.data).points; if(!points||points->empty())return {}; PhysicsAabb r{{std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity()},{-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity()}}; for(const auto p:*points){if(!finite(p))return {};r.min.x=std::min(r.min.x,p.x);r.min.y=std::min(r.min.y,p.y);r.min.z=std::min(r.min.z,p.z);r.max.x=std::max(r.max.x,p.x);r.max.y=std::max(r.max.y,p.y);r.max.z=std::max(r.max.z,p.z);}return r; }
    case PhysicsShapeType::TriangleMesh: { const auto& mesh=std::get<PhysicsTriangleMeshShape>(s.data).mesh; if(!mesh||!mesh->valid())return {}; PhysicsAabb r{{std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity()},{-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity()}}; for(const auto& v:mesh->vertices){r.min.x=std::min(r.min.x,v.position.x);r.min.y=std::min(r.min.y,v.position.y);r.min.z=std::min(r.min.z,v.position.z);r.max.x=std::max(r.max.x,v.position.x);r.max.y=std::max(r.max.y,v.position.y);r.max.z=std::max(r.max.z,v.position.z);}return r; }
    case PhysicsShapeType::HeightField: { const auto& h=std::get<PhysicsHeightFieldShape>(s.data); if(h.width<2||h.depth<2||h.cell_size<=0||!h.heights||h.heights->size()<static_cast<std::size_t>(h.width)*h.depth)return {}; float mn=std::numeric_limits<float>::infinity(),mx=-mn; for(std::size_t i=0;i<static_cast<std::size_t>(h.width)*h.depth;++i){const float v=(*h.heights)[i];if(!finite(v))return {};mn=std::min(mn,v);mx=std::max(mx,v);}const float w=(h.width-1U)*h.cell_size,d=(h.depth-1U)*h.cell_size;return {{-w*.5f,mn,-d*.5f},{w*.5f,mx,d*.5f}}; }
    case PhysicsShapeType::Compound: { const auto& children=std::get<PhysicsCompoundShape>(s.data).children; if(!children||children->empty())return {}; bool first=true;PhysicsAabb r{};for(const auto& ch:*children){if(!ch.shape||!ch.shape->valid())return {};const auto b=shape_local_bounds(*ch.shape);const Quat q=from_euler(ch.local_transform.rotation);const Vec3 c[8]={{b.min.x,b.min.y,b.min.z},{b.min.x,b.min.y,b.max.z},{b.min.x,b.max.y,b.min.z},{b.min.x,b.max.y,b.max.z},{b.max.x,b.min.y,b.min.z},{b.max.x,b.min.y,b.max.z},{b.max.x,b.max.y,b.min.z},{b.max.x,b.max.y,b.max.z}};PhysicsAabb x{{std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity()},{-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity()}};for(const auto p:c){const auto w=add(ch.local_transform.position,rotate(q,p));x.min.x=std::min(x.min.x,w.x);x.min.y=std::min(x.min.y,w.y);x.min.z=std::min(x.min.z,w.z);x.max.x=std::max(x.max.x,w.x);x.max.y=std::max(x.max.y,w.y);x.max.z=std::max(x.max.z,w.z);}if(first){r=x;first=false;}else r=merge(r,x);}return first?PhysicsAabb{}:r; }
    }
    return {};
}
PhysicsAabb shape_world_bounds(const PhysicsShape& s,PhysicsTransform t) noexcept { const auto b=shape_local_bounds(s);if(!b.valid())return {};const Quat q=from_euler(t.rotation);const Vec3 c[8]={{b.min.x,b.min.y,b.min.z},{b.min.x,b.min.y,b.max.z},{b.min.x,b.max.y,b.min.z},{b.min.x,b.max.y,b.max.z},{b.max.x,b.min.y,b.min.z},{b.max.x,b.min.y,b.max.z},{b.max.x,b.max.y,b.min.z},{b.max.x,b.max.y,b.max.z}};PhysicsAabb r{{std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity(),std::numeric_limits<float>::infinity()},{-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity()}};for(const auto p:c){const auto w=add(t.position,rotate(q,p));r.min.x=std::min(r.min.x,w.x);r.min.y=std::min(r.min.y,w.y);r.min.z=std::min(r.min.z,w.z);r.max.x=std::max(r.max.x,w.x);r.max.y=std::max(r.max.y,w.y);r.max.z=std::max(r.max.z,w.z);}return r;}

float inv_mass(const PhysicsRigidBodyDesc& d) noexcept { return d.type==PhysicsBodyType::Dynamic?1.0f/d.mass_properties.mass:0.0f; }
Vec3 inv_inertia(Vec3 inertia,Vec3 v) noexcept { return {inertia.x>kEps?v.x/inertia.x:0.0f,inertia.y>kEps?v.y/inertia.y:0.0f,inertia.z>kEps?v.z/inertia.z:0.0f}; }
std::uint64_t key(PhysicsColliderId a,PhysicsColliderId b) noexcept { if(a>b)std::swap(a,b);return (a*0x9e3779b97f4a7c15ULL)^b; }

struct Contact { PhysicsContactManifold m; float friction=0.5f; float restitution=0.0f; };

bool sphere_sphere(const PhysicsSphereShape&a,PhysicsTransform ta,const PhysicsSphereShape&b,PhysicsTransform tb,Contact&out) noexcept { const Vec3 d=sub(tb.position,ta.position);const float r=a.radius+b.radius;const float ls=len_sq(d);if(ls>=r*r)return false;const float dlen=std::sqrt(std::max(ls,kEps));const Vec3 n=dlen>kEps?mul(d,1.0f/dlen):Vec3{1,0,0};out.m.points[0]={add(ta.position,mul(n,a.radius)),n,r-dlen,0,0,0};out.m.point_count=1;return true; }
bool sphere_box(const PhysicsSphereShape&s,PhysicsTransform ts,const PhysicsBoxShape&b,PhysicsTransform tb,Contact&out) noexcept {const Quat q=from_euler(tb.rotation),qi=conjugate(q);const Vec3 local=rotate(qi,sub(ts.position,tb.position));const auto e=b.half_extents;const Vec3 closest{std::clamp(local.x,-e.x,e.x),std::clamp(local.y,-e.y,e.y),std::clamp(local.z,-e.z,e.z)};const Vec3 d=sub(local,closest);const float ls=len_sq(d),rr=s.radius*s.radius;if(ls>rr)return false;Vec3 nlocal;float penetration;if(ls>kEps){const float dl=std::sqrt(ls);nlocal=mul(d,1.0f/dl);penetration=s.radius-dl;}else{const float px=e.x-std::abs(local.x),py=e.y-std::abs(local.y),pz=e.z-std::abs(local.z);if(px<=py&&px<=pz)nlocal={local.x>=0?1.0f:-1.0f,0,0};else if(py<=pz)nlocal={0,local.y>=0?1.0f:-1.0f,0};else nlocal={0,0,local.z>=0?1.0f:-1.0f};penetration=s.radius+std::min({px,py,pz});}const Vec3 n=rotate(q,nlocal);out.m.points[0]={sub(ts.position,mul(n,s.radius-penetration*.5f)),n,penetration,0,0,0};out.m.point_count=1;return true;}
bool generic_aabb(const PhysicsShape&a,PhysicsTransform ta,const PhysicsShape&b,PhysicsTransform tb,Contact&out) noexcept {const auto A=shape_world_bounds(a,ta),B=shape_world_bounds(b,tb);if(!overlaps(A,B))return false;const float px=std::min(A.max.x-B.min.x,B.max.x-A.min.x),py=std::min(A.max.y-B.min.y,B.max.y-A.min.y),pz=std::min(A.max.z-B.min.z,B.max.z-A.min.z);float penetration=px;Vec3 n{tb.position.x>=ta.position.x?1.0f:-1.0f,0,0};if(py<penetration){penetration=py;n={0,tb.position.y>=ta.position.y?1.0f:-1.0f,0};}if(pz<penetration){penetration=pz;n={0,0,tb.position.z>=ta.position.z?1.0f:-1.0f};}const Vec3 p{(std::max(A.min.x,B.min.x)+std::min(A.max.x,B.max.x))*.5f,(std::max(A.min.y,B.min.y)+std::min(A.max.y,B.max.y))*.5f,(std::max(A.min.z,B.min.z)+std::min(A.max.z,B.max.z))*.5f};out.m.points[0]={p,n,penetration,0,0,0};out.m.point_count=1;return true;}
bool collide(const PhysicsShape&a,PhysicsTransform ta,const PhysicsShape&b,PhysicsTransform tb,Contact&out) noexcept {if(a.type==PhysicsShapeType::Sphere&&b.type==PhysicsShapeType::Sphere)return sphere_sphere(std::get<PhysicsSphereShape>(a.data),ta,std::get<PhysicsSphereShape>(b.data),tb,out);if(a.type==PhysicsShapeType::Sphere&&b.type==PhysicsShapeType::Box)return sphere_box(std::get<PhysicsSphereShape>(a.data),ta,std::get<PhysicsBoxShape>(b.data),tb,out);if(a.type==PhysicsShapeType::Box&&b.type==PhysicsShapeType::Sphere){if(!sphere_box(std::get<PhysicsSphereShape>(b.data),tb,std::get<PhysicsBoxShape>(a.data),ta,out))return false;for(std::uint8_t i=0;i<out.m.point_count;++i)out.m.points[i].normal=mul(out.m.points[i].normal,-1.0f);return true;}return generic_aabb(a,ta,b,tb,out);}

bool filter_pair(const PhysicsColliderDesc&a,const PhysicsColliderDesc&b) noexcept {return (a.layer&b.mask)!=0U&&(b.layer&a.mask)!=0U;}
}

bool PhysicsMaterial::valid() const noexcept { return finite(density)&&density>0&&finite(static_friction)&&static_friction>=0&&finite(dynamic_friction)&&dynamic_friction>=0&&finite(restitution)&&restitution>=0&&restitution<=1&&finite(rolling_friction)&&rolling_friction>=0&&finite(spinning_friction)&&spinning_friction>=0; }
bool PhysicsShape::valid() const noexcept { switch(type){case PhysicsShapeType::Sphere:return std::get<PhysicsSphereShape>(data).radius>0&&finite(std::get<PhysicsSphereShape>(data).radius);case PhysicsShapeType::Box:{const auto e=std::get<PhysicsBoxShape>(data).half_extents;return finite(e)&&e.x>0&&e.y>0&&e.z>0;}case PhysicsShapeType::Capsule:{const auto q=std::get<PhysicsCapsuleShape>(data);return finite(q.radius)&&finite(q.half_height)&&q.radius>0&&q.half_height>=0;}case PhysicsShapeType::Cylinder:{const auto q=std::get<PhysicsCylinderShape>(data);return finite(q.radius)&&finite(q.half_height)&&q.radius>0&&q.half_height>0;}default:return shape_local_bounds(*this).valid();} }
PhysicsAabb PhysicsShape::local_bounds() const noexcept { return shape_local_bounds(*this); }
bool PhysicsMassProperties::valid() const noexcept { return finite(mass)&&mass>0&&finite(center_of_mass)&&finite(diagonal_inertia)&&diagonal_inertia.x>0&&diagonal_inertia.y>0&&diagonal_inertia.z>0; }
bool PhysicsRigidBodyDesc::valid() const noexcept { return mass_properties.valid()&&finite(transform.position)&&finite(transform.rotation)&&finite(linear_velocity)&&finite(angular_velocity)&&finite(linear_damping)&&finite(angular_damping)&&finite(gravity_scale)&&linear_damping.x>=0&&linear_damping.y>=0&&linear_damping.z>=0&&angular_damping.x>=0&&angular_damping.y>=0&&angular_damping.z>=0&&finite(max_linear_speed)&&max_linear_speed>0&&finite(max_angular_speed)&&max_angular_speed>0; }
bool PhysicsColliderDesc::valid() const noexcept { return shape.valid()&&finite(local_transform.position)&&finite(local_transform.rotation)&&material.valid()&&layer!=0&&finite(contact_offset)&&contact_offset>=0&&finite(rest_offset)&&rest_offset>=0; }
bool PhysicsContactManifold::valid() const noexcept { return body_a!=invalid_physics_body&&body_b!=invalid_physics_body&&collider_a!=invalid_physics_collider&&collider_b!=invalid_physics_collider&&point_count>0&&point_count<=4; }
bool PhysicsConstraintDesc::valid() const noexcept { if(body_a==invalid_physics_body||body_b==invalid_physics_body||body_a==body_b||!finite(frame_a.position)||!finite(frame_a.rotation)||!finite(frame_b.position)||!finite(frame_b.rotation)||!finite(stiffness)||stiffness<0||!finite(damping)||damping<0)return false;for(const auto& x:linear_limits)if(!finite(x.lower)||!finite(x.upper)||x.lower>x.upper||!finite(x.softness)||x.softness<0)return false;for(const auto& x:angular_limits)if(!finite(x.lower)||!finite(x.upper)||x.lower>x.upper||!finite(x.softness)||x.softness<0)return false;return (finite(break_force)||std::isinf(break_force))&&(finite(break_torque)||std::isinf(break_torque)); }
bool PhysicsQueryHit::valid() const noexcept { return body!=invalid_physics_body&&collider!=invalid_physics_collider&&finite(fraction)&&fraction>=0&&fraction<=1&&finite(distance)&&distance>=0&&finite(position)&&finite(normal); }
bool PhysicsWorldSettings::valid() const noexcept { return finite(gravity)&&finite(fixed_timestep)&&fixed_timestep>0&&max_substeps>0&&velocity_iterations>0&&position_iterations>0&&velocity_iterations_toi>0&&finite(max_accumulated_time)&&max_accumulated_time>0&&finite(sleep_linear_threshold)&&sleep_linear_threshold>=0&&finite(sleep_angular_threshold)&&sleep_angular_threshold>=0&&finite(time_to_sleep)&&time_to_sleep>=0&&finite(allowed_penetration)&&allowed_penetration>=0&&finite(baumgarte)&&baumgarte>=0&&baumgarte<=1; }

struct PhysicsWorld::Impl {
    struct Body { PhysicsBodyId id=0; PhysicsRigidBodyDesc desc{}; bool awake=true; float sleep_time=0; Vec3 force{}; Vec3 torque{}; std::vector<PhysicsColliderId> colliders; };
    struct Collider { PhysicsColliderId id=0; PhysicsBodyId body=0; PhysicsColliderDesc desc{}; };
    struct Constraint { PhysicsConstraintId id=0; PhysicsConstraintDesc desc{}; };
    PhysicsWorldSettings settings{}; PhysicsCallbacks callbacks{}; std::unordered_map<PhysicsBodyId,Body> bodies; std::unordered_map<PhysicsColliderId,Collider> colliders; std::unordered_map<PhysicsConstraintId,Constraint> constraints; std::unordered_set<std::uint64_t> active_contacts; PhysicsBodyId next_body=1; PhysicsColliderId next_collider=1; PhysicsConstraintId next_constraint=1; std::uint64_t simulation_step=0; float accumulator=0; float alpha=0;
    explicit Impl(PhysicsWorldSettings s):settings(s){if(!settings.valid())settings=PhysicsWorldSettings{};}
    Body* get(PhysicsBodyId id) noexcept {auto i=bodies.find(id);return i==bodies.end()?nullptr:&i->second;} const Body* get(PhysicsBodyId id) const noexcept {auto i=bodies.find(id);return i==bodies.end()?nullptr:&i->second;} const Collider* getc(PhysicsColliderId id) const noexcept {auto i=colliders.find(id);return i==colliders.end()?nullptr:&i->second;}
    void wake(Body& b){b.sleep_time=0;if(!b.awake){b.awake=true;if(callbacks.on_body_wake)callbacks.on_body_wake(b.id);}}
    bool dynamic(const Body& b) const noexcept{return b.desc.type==PhysicsBodyType::Dynamic;}
    PhysicsAabb aabb(const Collider& c) const noexcept {const auto*b=get(c.body);return b?shape_world_bounds(c.desc.shape,compose(b->desc.transform,c.desc.local_transform)):PhysicsAabb{};}

    void solve_constraints(float dt){for(auto& entry:constraints){auto& c=entry.second;auto*a=get(c.desc.body_a);auto*b=get(c.desc.body_b);if(!a||!b)continue;const float wa=inv_mass(a->desc),wb=inv_mass(b->desc),sum=wa+wb;if(sum<=0)continue;const auto fa=compose(a->desc.transform,c.desc.frame_a),fb=compose(b->desc.transform,c.desc.frame_b);const Vec3 delta=sub(fb.position,fa.position);const float dist=len(delta);if(c.desc.type==PhysicsConstraintType::Distance||c.desc.type==PhysicsConstraintType::Spring){if(dist>kEps){const Vec3 n=mul(delta,1.0f/dist);float target=dist;if(c.desc.linear_limits[0].enabled)target=std::max(0.0f,c.desc.linear_limits[0].upper);const float stiffness=c.desc.type==PhysicsConstraintType::Spring?c.desc.stiffness:1.0f;const float rel=dot(sub(b->desc.linear_velocity,a->desc.linear_velocity),n);const float j=-(rel+(dist-target)*stiffness/std::max(dt,1e-5f))/(sum);if(dynamic(*a))a->desc.linear_velocity=sub(a->desc.linear_velocity,mul(n,j*wa));if(dynamic(*b))b->desc.linear_velocity=add(b->desc.linear_velocity,mul(n,j*wb));}}
            else if(c.desc.type==PhysicsConstraintType::Fixed||c.desc.type==PhysicsConstraintType::BallSocket||c.desc.type==PhysicsConstraintType::Hinge||c.desc.type==PhysicsConstraintType::SixDegreesOfFreedom){const Vec3 v=mul(delta,std::clamp(c.desc.stiffness*dt+0.2f,0.0f,1.0f)/std::max(dt,1e-5f));if(dynamic(*a))a->desc.linear_velocity=add(a->desc.linear_velocity,mul(v,wa/sum));if(dynamic(*b))b->desc.linear_velocity=sub(b->desc.linear_velocity,mul(v,wb/sum));}
            if(c.desc.motor.enabled){const Vec3 axis=norm(rotate(from_euler(fa.rotation),{0,1,0}));const float rel=dot(sub(b->desc.angular_velocity,a->desc.angular_velocity),axis);const float desired=c.desc.motor.target_velocity-rel;const float max_imp=std::max(c.desc.motor.max_torque,c.desc.motor.max_force)*dt;const float j=std::clamp(desired/(sum+1e-5f),-max_imp,max_imp);if(dynamic(*a))a->desc.angular_velocity=sub(a->desc.angular_velocity,mul(axis,j));if(dynamic(*b))b->desc.angular_velocity=add(b->desc.angular_velocity,mul(axis,j));}}
    }

    void solve_contacts(std::vector<Contact>& contacts,float dt){for(std::uint32_t iteration=0;iteration<settings.velocity_iterations;++iteration)for(auto& c:contacts){auto*a=get(c.m.body_a);auto*b=get(c.m.body_b);if(!a||!b)continue;const float ima=inv_mass(a->desc),imb=inv_mass(b->desc);if(ima+imb<=0)continue;for(std::uint8_t i=0;i<c.m.point_count;++i){auto&p=c.m.points[i];const Vec3 ra=sub(p.position,a->desc.transform.position),rb=sub(p.position,b->desc.transform.position);const Vec3 va=add(a->desc.linear_velocity,cross(a->desc.angular_velocity,ra)),vb=add(b->desc.linear_velocity,cross(b->desc.angular_velocity,rb)),rv=sub(vb,va);const float vn=dot(rv,p.normal);if(vn>0)continue;const Vec3 ra_n=cross(inv_inertia(a->desc.mass_properties.diagonal_inertia,cross(ra,p.normal)),ra);const Vec3 rb_n=cross(inv_inertia(b->desc.mass_properties.diagonal_inertia,cross(rb,p.normal)),rb);const float denom=ima+imb+dot(add(ra_n,rb_n),p.normal);if(denom<=kEps)continue;const float e=std::abs(vn)>0.5f?c.restitution:0.0f;const float j=std::max(0.0f,-(1.0f+e)*vn/denom);const Vec3 impulse=mul(p.normal,j);if(dynamic(*a)){a->desc.linear_velocity=sub(a->desc.linear_velocity,mul(impulse,ima));a->desc.angular_velocity=sub(a->desc.angular_velocity,inv_inertia(a->desc.mass_properties.diagonal_inertia,cross(ra,impulse)));}if(dynamic(*b)){b->desc.linear_velocity=add(b->desc.linear_velocity,mul(impulse,imb));b->desc.angular_velocity=add(b->desc.angular_velocity,inv_inertia(b->desc.mass_properties.diagonal_inertia,cross(rb,impulse)));}p.normal_impulse=j;wake(*a);wake(*b);
                Vec3 tangent=sub(rv,mul(p.normal,vn));const float tl=len(tangent);if(tl>kEps){tangent=mul(tangent,1.0f/tl);const float denom_t=ima+imb+dot(add(cross(inv_inertia(a->desc.mass_properties.diagonal_inertia,cross(ra,tangent)),ra),cross(inv_inertia(b->desc.mass_properties.diagonal_inertia,cross(rb,tangent)),rb)),tangent);float jt=denom_t>kEps?-dot(rv,tangent)/denom_t:0;const float max_jt=c.friction*j;jt=std::clamp(jt,-max_jt,max_jt);const Vec3 ti=mul(tangent,jt);if(dynamic(*a)){a->desc.linear_velocity=sub(a->desc.linear_velocity,mul(ti,ima));a->desc.angular_velocity=sub(a->desc.angular_velocity,inv_inertia(a->desc.mass_properties.diagonal_inertia,cross(ra,ti)));}if(dynamic(*b)){b->desc.linear_velocity=add(b->desc.linear_velocity,mul(ti,imb));b->desc.angular_velocity=add(b->desc.angular_velocity,inv_inertia(b->desc.mass_properties.diagonal_inertia,cross(rb,ti)));}p.tangent_impulse_0=jt;}}}
        for(std::uint32_t iteration=0;iteration<settings.position_iterations;++iteration)for(auto& c:contacts){auto*a=get(c.m.body_a);auto*b=get(c.m.body_b);if(!a||!b)continue;const float ima=inv_mass(a->desc),imb=inv_mass(b->desc),sum=ima+imb;if(sum<=0)continue;for(std::uint8_t i=0;i<c.m.point_count;++i){const auto&p=c.m.points[i];const float depth=std::max(0.0f,p.penetration-settings.allowed_penetration);if(depth<=0)continue;const Vec3 correction=mul(p.normal,settings.baumgarte*depth/sum);if(dynamic(*a))a->desc.transform.position=sub(a->desc.transform.position,mul(correction,ima));if(dynamic(*b))b->desc.transform.position=add(b->desc.transform.position,mul(correction,imb));}}
    }

    void integrate(float dt){for(auto& entry:bodies){auto& b=entry.second;if(b.desc.type==PhysicsBodyType::Static||!b.awake)continue;if(dynamic(b)){Vec3 acc=add(settings.gravity,mul(b.force,inv_mass(b.desc)));b.desc.linear_velocity=add(b.desc.linear_velocity,mul(acc,dt));b.desc.angular_velocity=add(b.desc.angular_velocity,mul(inv_inertia(b.desc.mass_properties.diagonal_inertia,b.torque),dt));b.desc.linear_velocity.x*=std::exp(-b.desc.linear_damping.x*dt);b.desc.linear_velocity.y*=std::exp(-b.desc.linear_damping.y*dt);b.desc.linear_velocity.z*=std::exp(-b.desc.linear_damping.z*dt);b.desc.angular_velocity.x*=std::exp(-b.desc.angular_damping.x*dt);b.desc.angular_velocity.y*=std::exp(-b.desc.angular_damping.y*dt);b.desc.angular_velocity.z*=std::exp(-b.desc.angular_damping.z*dt);}const float v=len(b.desc.linear_velocity);if(v>b.desc.max_linear_speed)b.desc.linear_velocity=mul(b.desc.linear_velocity,b.desc.max_linear_speed/v);const float w=len(b.desc.angular_velocity);if(w>b.desc.max_angular_speed)b.desc.angular_velocity=mul(b.desc.angular_velocity,b.desc.max_angular_speed/w);b.desc.transform.position=add(b.desc.transform.position,mul(b.desc.linear_velocity,dt));const Quat q=from_euler(b.desc.transform.rotation);const Quat dq{b.desc.angular_velocity.x*dt*.5f,b.desc.angular_velocity.y*dt*.5f,b.desc.angular_velocity.z*dt*.5f,1.0f};b.desc.transform.rotation=to_euler(multiply(q,dq));b.force={};b.torque={};}}

    void substep(float dt){integrate(dt);struct Candidate{PhysicsColliderId id;PhysicsAabb box;};std::vector<Candidate> broad;for(const auto&e:colliders)if(e.second.desc.enabled)broad.push_back({e.first,aabb(e.second)});std::sort(broad.begin(),broad.end(),[](const auto&a,const auto&b){if(a.box.min.x!=b.box.min.x)return a.box.min.x<b.box.min.x;return a.id<b.id;});std::vector<Contact> contacts;std::unordered_set<std::uint64_t> current;for(std::size_t i=0;i<broad.size();++i){const auto*ca=getc(broad[i].id);if(!ca)continue;for(std::size_t j=i+1;j<broad.size()&&broad[j].box.min.x<=broad[i].box.max.x;++j){const auto*cb=getc(broad[j].id);if(!cb||ca->body==cb->body||!filter_pair(ca->desc,cb->desc)||!overlaps(broad[i].box,broad[j].box))continue;const auto*ba=get(ca->body);const auto*bb=get(cb->body);if(!ba||!bb||((ba->desc.type==PhysicsBodyType::Static)&&(bb->desc.type==PhysicsBodyType::Static))||(!ba->awake&&!bb->awake))continue;Contact c;c.m.body_a=ca->body;c.m.body_b=cb->body;c.m.collider_a=ca->id;c.m.collider_b=cb->id;c.m.sensor=ca->desc.sensor||cb->desc.sensor;c.friction=std::sqrt(std::max(0.0f,ca->desc.material.dynamic_friction*cb->desc.material.dynamic_friction));c.restitution=std::max(ca->desc.material.restitution,cb->desc.material.restitution);if(!collide(ca->desc.shape,compose(ba->desc.transform,ca->desc.local_transform),cb->desc.shape,compose(bb->desc.transform,cb->desc.local_transform),c))continue;current.insert(key(ca->id,cb->id));contacts.push_back(c);}}
        std::sort(contacts.begin(),contacts.end(),[](const auto&a,const auto&b){if(a.m.collider_a!=b.m.collider_a)return a.m.collider_a<b.m.collider_a;return a.m.collider_b<b.m.collider_b;});
        for(const auto&c:contacts){if(!callbacks.on_contact)break;PhysicsContactEvent e;e.type=active_contacts.count(key(c.m.collider_a,c.m.collider_b))?PhysicsContactEvent::Type::Persist:PhysicsContactEvent::Type::Begin;e.manifold=c.m;callbacks.on_contact(e);}if(callbacks.on_contact){for(const auto old:active_contacts)if(!current.count(old)){for(const auto&[id,c]:colliders){for(const auto&[id2,d]:colliders)if(id<id2&&key(id,id2)==old){PhysicsContactEvent e;e.type=PhysicsContactEvent::Type::End;e.manifold.collider_a=id;e.manifold.collider_b=id2;e.manifold.body_a=c.body;e.manifold.body_b=d.body;callbacks.on_contact(e);break;}}}}
        std::vector<Contact> solids;for(auto&c:contacts)if(!c.m.sensor)solids.push_back(c);solve_constraints(dt);solve_contacts(solids,dt);active_contacts=std::move(current);++simulation_step;
        for(auto&entry:bodies){auto&b=entry.second;if(b.desc.type!=PhysicsBodyType::Dynamic||(static_cast<PhysicsBodyFlags>(b.desc.flags)&static_cast<PhysicsBodyFlags>(PhysicsBodyFlag::AllowSleep))==0)continue;const bool slow=len_sq(b.desc.linear_velocity)<=settings.sleep_linear_threshold*settings.sleep_linear_threshold&&len_sq(b.desc.angular_velocity)<=settings.sleep_angular_threshold*settings.sleep_angular_threshold;if(slow)b.sleep_time+=dt;else b.sleep_time=0;if(b.awake&&b.sleep_time>=settings.time_to_sleep){b.awake=false;b.desc.linear_velocity={};b.desc.angular_velocity={};if(callbacks.on_body_sleep)callbacks.on_body_sleep(b.id);}}
    }
};

PhysicsWorld::PhysicsWorld(PhysicsWorldSettings settings):impl_(std::make_unique<Impl>(settings)){}
PhysicsWorld::~PhysicsWorld()=default;
PhysicsWorld::PhysicsWorld(PhysicsWorld&&) noexcept=default;
PhysicsWorld& PhysicsWorld::operator=(PhysicsWorld&&) noexcept=default;
const PhysicsWorldSettings& PhysicsWorld::settings() const noexcept{return impl_->settings;}
bool PhysicsWorld::set_gravity(Vec3 gravity) noexcept{if(!finite(gravity))return false;impl_->settings.gravity=gravity;return true;}
PhysicsBodyId PhysicsWorld::create_body(const PhysicsRigidBodyDesc& desc){if(!desc.valid()||impl_->next_body==invalid_physics_body)return invalid_physics_body;const auto id=impl_->next_body++;const bool awake=(static_cast<PhysicsBodyFlags>(desc.flags)&static_cast<PhysicsBodyFlags>(PhysicsBodyFlag::StartAwake))!=0;impl_->bodies.emplace(id,Impl::Body{id,desc,awake,0,{},{},{}});return id;}
bool PhysicsWorld::destroy_body(PhysicsBodyId id) noexcept{auto i=impl_->bodies.find(id);if(i==impl_->bodies.end())return false;for(const auto cid:i->second.colliders)impl_->colliders.erase(cid);for(auto c=impl_->constraints.begin();c!=impl_->constraints.end();)if(c->second.desc.body_a==id||c->second.desc.body_b==id)c=impl_->constraints.erase(c);else ++c;impl_->bodies.erase(i);return true;}
bool PhysicsWorld::has_body(PhysicsBodyId id) const noexcept{return impl_->bodies.count(id)!=0;}
std::optional<PhysicsTransform> PhysicsWorld::body_transform(PhysicsBodyId id) const noexcept{const auto*b=impl_->get(id);return b?std::optional<PhysicsTransform>{b->desc.transform}:std::nullopt;}
bool PhysicsWorld::set_body_transform(PhysicsBodyId id,PhysicsTransform t,bool wake) noexcept{auto*b=impl_->get(id);if(!b||!finite(t.position)||!finite(t.rotation))return false;b->desc.transform=t;if(wake)impl_->wake(*b);return true;}
bool PhysicsWorld::set_linear_velocity(PhysicsBodyId id,Vec3 v,bool wake) noexcept{auto*b=impl_->get(id);if(!b||!finite(v))return false;b->desc.linear_velocity=v;if(wake)impl_->wake(*b);return true;}
bool PhysicsWorld::set_angular_velocity(PhysicsBodyId id,Vec3 v,bool wake) noexcept{auto*b=impl_->get(id);if(!b||!finite(v))return false;b->desc.angular_velocity=v;if(wake)impl_->wake(*b);return true;}
bool PhysicsWorld::apply_force(PhysicsBodyId id,Vec3 force,Vec3 position) noexcept{auto*b=impl_->get(id);if(!b||b->desc.type!=PhysicsBodyType::Dynamic||!finite(force)||!finite(position))return false;b->force=add(b->force,force);b->torque=add(b->torque,cross(sub(position,b->desc.transform.position),force));impl_->wake(*b);return true;}
bool PhysicsWorld::apply_torque(PhysicsBodyId id,Vec3 torque) noexcept{auto*b=impl_->get(id);if(!b||b->desc.type!=PhysicsBodyType::Dynamic||!finite(torque))return false;b->torque=add(b->torque,torque);impl_->wake(*b);return true;}
bool PhysicsWorld::wake_body(PhysicsBodyId id) noexcept{auto*b=impl_->get(id);if(!b)return false;impl_->wake(*b);return true;}
bool PhysicsWorld::sleep_body(PhysicsBodyId id) noexcept{auto*b=impl_->get(id);if(!b)return false;b->awake=false;b->sleep_time=impl_->settings.time_to_sleep;b->desc.linear_velocity={};b->desc.angular_velocity={};if(impl_->callbacks.on_body_sleep)impl_->callbacks.on_body_sleep(id);return true;}
bool PhysicsWorld::is_awake(PhysicsBodyId id) const noexcept{const auto*b=impl_->get(id);return b&&b->awake;}
PhysicsColliderId PhysicsWorld::add_collider(PhysicsBodyId body,const PhysicsColliderDesc& desc){auto*b=impl_->get(body);if(!b||!desc.valid()||impl_->next_collider==invalid_physics_collider)return invalid_physics_collider;const auto id=impl_->next_collider++;impl_->colliders.emplace(id,Impl::Collider{id,body,desc});b->colliders.push_back(id);return id;}
bool PhysicsWorld::remove_collider(PhysicsColliderId id) noexcept{auto i=impl_->colliders.find(id);if(i==impl_->colliders.end())return false;if(auto*b=impl_->get(i->second.body))b->colliders.erase(std::remove(b->colliders.begin(),b->colliders.end(),id),b->colliders.end());impl_->colliders.erase(i);return true;}
bool PhysicsWorld::has_collider(PhysicsColliderId id) const noexcept{return impl_->colliders.count(id)!=0;}
bool PhysicsWorld::set_collider_enabled(PhysicsColliderId id,bool enabled) noexcept{auto i=impl_->colliders.find(id);if(i==impl_->colliders.end())return false;i->second.desc.enabled=enabled;return true;}
PhysicsConstraintId PhysicsWorld::add_constraint(const PhysicsConstraintDesc& desc){if(!desc.valid()||!has_body(desc.body_a)||!has_body(desc.body_b)||impl_->next_constraint==invalid_physics_constraint)return invalid_physics_constraint;const auto id=impl_->next_constraint++;impl_->constraints.emplace(id,Impl::Constraint{id,desc});return id;}
bool PhysicsWorld::remove_constraint(PhysicsConstraintId id) noexcept{return impl_->constraints.erase(id)!=0;}
bool PhysicsWorld::has_constraint(PhysicsConstraintId id) const noexcept{return impl_->constraints.count(id)!=0;}
bool PhysicsWorld::set_constraint_motor(PhysicsConstraintId id,PhysicsConstraintMotor motor) noexcept{auto i=impl_->constraints.find(id);if(i==impl_->constraints.end()||!finite(motor.target_velocity)||!finite(motor.max_force)||!finite(motor.max_torque)||motor.max_force<0||motor.max_torque<0)return false;i->second.desc.motor=motor;return true;}
PhysicsStepResult PhysicsWorld::step(float real_dt) noexcept{if(!finite(real_dt)||real_dt<0)return {0,impl_->alpha,impl_->simulation_step};impl_->accumulator=std::min(impl_->accumulator+real_dt,impl_->settings.max_accumulated_time);std::uint32_t substeps=0;while(impl_->accumulator+1e-7f>=impl_->settings.fixed_timestep&&substeps<impl_->settings.max_substeps){impl_->substep(impl_->settings.fixed_timestep);impl_->accumulator-=impl_->settings.fixed_timestep;++substeps;}impl_->alpha=impl_->accumulator/impl_->settings.fixed_timestep;return {substeps,impl_->alpha,impl_->simulation_step};}
float PhysicsWorld::interpolation_alpha() const noexcept{return impl_->alpha;}
PhysicsWorldStats PhysicsWorld::stats() const noexcept{PhysicsWorldStats s;s.bodies=impl_->bodies.size();s.colliders=impl_->colliders.size();s.constraints=impl_->constraints.size();s.contacts=impl_->active_contacts.size();for(const auto&entry:impl_->bodies)if(entry.second.awake)++s.awake_bodies;return s;}
std::vector<PhysicsQueryHit> PhysicsWorld::raycast(const PhysicsRay& ray,const PhysicsQueryFilter& filter) const {std::vector<PhysicsQueryHit> hits;if(!finite(ray.origin)||!finite(ray.direction)||ray.max_distance<=0)return hits;const float dl=len(ray.direction);if(dl<=kEps)return hits;const Vec3 d=mul(ray.direction,1.0f/dl);for(const auto&entry:impl_->colliders){const auto&c=entry.second;if(!c.desc.enabled||(!filter.include_sensors&&c.desc.sensor)||!(filter.layer&c.desc.mask)||!(c.desc.layer&filter.mask)||c.body==filter.ignore_body||c.id==filter.ignore_collider)continue;const auto a=impl_->aabb(c);float tmin=0,tmax=ray.max_distance;const float o[3]={ray.origin.x,ray.origin.y,ray.origin.z},v[3]={d.x,d.y,d.z},mn[3]={a.min.x,a.min.y,a.min.z},mx[3]={a.max.x,a.max.y,a.max.z};bool hit=true;for(int axis=0;axis<3;++axis){if(std::abs(v[axis])<kEps){if(o[axis]<mn[axis]||o[axis]>mx[axis]){hit=false;break;}}else{float t1=(mn[axis]-o[axis])/v[axis],t2=(mx[axis]-o[axis])/v[axis];if(t1>t2)std::swap(t1,t2);tmin=std::max(tmin,t1);tmax=std::min(tmax,t2);if(tmin>tmax){hit=false;break;}}}if(hit&&tmin<=ray.max_distance){const Vec3 p=add(ray.origin,mul(d,tmin));Vec3 n{0,1,0};const float ex=std::min(std::abs(p.x-a.min.x),std::abs(p.x-a.max.x)),ey=std::min(std::abs(p.y-a.min.y),std::abs(p.y-a.max.y)),ez=std::min(std::abs(p.z-a.min.z),std::abs(p.z-a.max.z));if(ex<=ey&&ex<=ez)n={p.x>(a.min.x+a.max.x)*.5f?1.0f:-1.0f,0,0};else if(ey<=ez)n={0,p.y>(a.min.y+a.max.y)*.5f?1.0f:-1.0f,0};else n={0,0,p.z>(a.min.z+a.max.z)*.5f?1.0f:-1.0f};hits.push_back({c.body,c.id,tmin/ray.max_distance,tmin,p,n});}}std::sort(hits.begin(),hits.end(),[](const auto&a,const auto&b){if(a.distance!=b.distance)return a.distance<b.distance;return a.collider<b.collider;});return hits;}
std::vector<PhysicsQueryHit> PhysicsWorld::shapecast(const PhysicsShapeCast& cast,const PhysicsQueryFilter& filter) const {std::vector<PhysicsQueryHit> hits;if(!cast.shape.valid()||!finite(cast.start.position)||!finite(cast.start.rotation)||!finite(cast.translation))return hits;const auto start=shape_world_bounds(cast.shape,cast.start);const auto end=shape_world_bounds(cast.shape,{add(cast.start.position,cast.translation),cast.start.rotation});const auto sweep=merge(start,end);for(const auto&entry:impl_->colliders){const auto&c=entry.second;if(!c.desc.enabled||(!filter.include_sensors&&c.desc.sensor)||!(filter.layer&c.desc.mask)||!(c.desc.layer&filter.mask)||c.body==filter.ignore_body||c.id==filter.ignore_collider)continue;if(overlaps(sweep,impl_->aabb(c)))hits.push_back({c.body,c.id,0,0,cast.start.position,norm(mul(cast.translation,-1.0f))});}std::sort(hits.begin(),hits.end(),[](const auto&a,const auto&b){return a.collider<b.collider;});return hits;}
std::vector<PhysicsQueryHit> PhysicsWorld::overlap(const PhysicsShape& shape,const PhysicsTransform& transform,const PhysicsQueryFilter& filter) const {std::vector<PhysicsQueryHit> hits;if(!shape.valid()||!finite(transform.position)||!finite(transform.rotation))return hits;const auto a=shape_world_bounds(shape,transform);for(const auto&entry:impl_->colliders){const auto&c=entry.second;if(!c.desc.enabled||(!filter.include_sensors&&c.desc.sensor)||!(filter.layer&c.desc.mask)||!(c.desc.layer&filter.mask)||c.body==filter.ignore_body||c.id==filter.ignore_collider)continue;if(overlaps(a,impl_->aabb(c)))hits.push_back({c.body,c.id,0,0,transform.position,{0,1,0}});}std::sort(hits.begin(),hits.end(),[](const auto&a,const auto&b){return a.collider<b.collider;});return hits;}
void PhysicsWorld::set_callbacks(PhysicsCallbacks callbacks){impl_->callbacks=std::move(callbacks);}void PhysicsWorld::clear_callbacks(){impl_->callbacks={};}
void PhysicsWorld::clear() noexcept{impl_->bodies.clear();impl_->colliders.clear();impl_->constraints.clear();impl_->active_contacts.clear();impl_->next_body=1;impl_->next_collider=1;impl_->next_constraint=1;impl_->simulation_step=0;impl_->accumulator=0;impl_->alpha=0;}

} // namespace exgine
