#include "exgine/production.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <condition_variable>
#include <cstring>
#include <limits>
#include <queue>
#include <thread>

namespace exgine { namespace {
std::string ext(std::string_view uri){auto p=uri.find_last_of('.');std::string s(p==std::string_view::npos?uri:uri.substr(p+1));for(char&c:s)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));return s;}
std::uint16_t rd16(const std::vector<std::uint8_t>&b,std::size_t p){return static_cast<std::uint16_t>(b[p]|(b[p+1]<<8));}
std::uint32_t rd32(const std::vector<std::uint8_t>&b,std::size_t p){return static_cast<std::uint32_t>(b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24));}
void w32(std::vector<std::uint8_t>&b,std::uint32_t v){for(int i=0;i<4;++i)b.push_back(static_cast<std::uint8_t>(v>>(8*i)));}
void w64(std::vector<std::uint8_t>&b,std::uint64_t v){for(int i=0;i<8;++i)b.push_back(static_cast<std::uint8_t>(v>>(8*i)));}
void wf(std::vector<std::uint8_t>&b,double v){std::uint64_t u;std::memcpy(&u,&v,8);w64(b,u);}
void ws(std::vector<std::uint8_t>&b,std::string_view s){w32(b,static_cast<std::uint32_t>(s.size()));b.insert(b.end(),s.begin(),s.end());}
bool g32(const std::vector<std::uint8_t>&b,std::size_t&p,std::uint32_t&v){if(p+4>b.size())return false;v=rd32(b,p);p+=4;return true;}
bool g64(const std::vector<std::uint8_t>&b,std::size_t&p,std::uint64_t&v){if(p+8>b.size())return false;v=0;for(int i=0;i<8;++i)v|=static_cast<std::uint64_t>(b[p+i])<<(8*i);p+=8;return true;}
bool gf(const std::vector<std::uint8_t>&b,std::size_t&p,double&v){std::uint64_t u;if(!g64(b,p,u))return false;std::memcpy(&v,&u,8);return true;}
bool gs(const std::vector<std::uint8_t>&b,std::size_t&p,std::string&s){std::uint32_t n;if(!g32(b,p,n)||p+n>b.size())return false;s.assign(reinterpret_cast<const char*>(b.data()+p),n);p+=n;return true;}
bool ppm(std::string_view,const std::vector<std::uint8_t>&b,ImageData&o,std::string&e){std::string s(b.begin(),b.end());std::size_t p=0;auto tok=[&](){while(p<s.size()&&(std::isspace(static_cast<unsigned char>(s[p]))||s[p]=='#')){if(s[p]=='#')while(p<s.size()&&s[p]!='\n')++p;else ++p;}std::size_t q=p;while(p<s.size()&&!std::isspace(static_cast<unsigned char>(s[p])))++p;return s.substr(q,p-q);};const auto m=tok();if(m!="P3"&&m!="P6"){e="unsupported PPM";return false;}std::uint32_t w=0,h=0,max=0;try{w=std::stoul(tok());h=std::stoul(tok());max=std::stoul(tok());}catch(...){e="invalid PPM header";return false;}if(!w||!h||!max||max>255){e="invalid PPM dimensions";return false;}o={w,h,ImagePixelFormat::RGB8,{}};o.pixels.resize(static_cast<std::size_t>(w)*h*3);if(m=="P3"){for(auto&v:o.pixels){try{v=static_cast<std::uint8_t>(std::min<std::uint32_t>(255,std::stoul(tok())*255/max));}catch(...){e="truncated PPM";return false;}}}else{while(p<b.size()&&std::isspace(b[p]))++p;if(b.size()-p<o.pixels.size()){e="truncated PPM";return false;}std::copy(b.begin()+static_cast<std::ptrdiff_t>(p),b.begin()+static_cast<std::ptrdiff_t>(p+o.pixels.size()),o.pixels.begin());}return true;}
bool bmp(std::string_view,const std::vector<std::uint8_t>&b,ImageData&o,std::string&e){if(b.size()<54||b[0]!='B'||b[1]!='M'){e="invalid BMP";return false;}auto off=rd32(b,10),w=rd32(b,18),h=rd32(b,22);auto bits=rd16(b,28);if(!w||!h||(bits!=24&&bits!=32)||rd32(b,30)!=0){e="unsupported BMP";return false;}auto ch=bits/8,row=((w*bits+31)/32)*4;if(b.size()<static_cast<std::size_t>(off)+static_cast<std::size_t>(row)*h){e="truncated BMP";return false;}o={w,h,ch==4?ImagePixelFormat::RGBA8:ImagePixelFormat::RGB8,{}};o.pixels.resize(static_cast<std::size_t>(w)*h*ch);for(std::uint32_t y=0;y<h;++y)for(std::uint32_t x=0;x<w;++x){auto s=off+static_cast<std::size_t>(y)*row+static_cast<std::size_t>(x)*ch,d=(static_cast<std::size_t>(h-1-y)*w+x)*ch;o.pixels[d]=b[s+2];o.pixels[d+1]=b[s+1];o.pixels[d+2]=b[s];if(ch==4)o.pixels[d+3]=b[s+3];}return true;}
bool tga(std::string_view,const std::vector<std::uint8_t>&b,ImageData&o,std::string&e){if(b.size()<18){e="truncated TGA";return false;}auto type=b[2],w=rd16(b,12),h=rd16(b,14),depth=b[16],desc=b[17];if(!w||!h||type!=2||(depth!=24&&depth!=32)){e="unsupported TGA";return false;}std::size_t ch=depth/8,start=18+b[0],count=static_cast<std::size_t>(w)*h;if(b.size()<start+count*ch){e="truncated TGA";return false;}o={w,h,ch==4?ImagePixelFormat::RGBA8:ImagePixelFormat::RGB8,{}};o.pixels.resize(count*ch);bool fy=(desc&0x20U)==0,fx=(desc&0x10U)!=0;for(std::uint32_t y=0;y<h;++y)for(std::uint32_t x=0;x<w;++x){auto sx=fx?w-1-x:x,sy=fy?h-1-y:y,s=start+(static_cast<std::size_t>(sy)*w+sx)*ch,d=(static_cast<std::size_t>(y)*w+x)*ch;o.pixels[d]=b[s+2];o.pixels[d+1]=b[s+1];o.pixels[d+2]=b[s];if(ch==4)o.pixels[d+3]=b[s+3];}return true;}
std::vector<std::string> uris(std::string_view j){std::vector<std::string>r;std::size_t p=0;while((p=j.find("\"uri\"",p))!=std::string_view::npos){p=j.find(':',p+5);if(p==std::string_view::npos)break;while(++p<j.size()&&std::isspace(static_cast<unsigned char>(j[p])));if(p>=j.size()||j[p]!='\"')continue;++p;std::string x;while(p<j.size()&&j[p]!='\"'){if(j[p]=='\\'&&p+1<j.size())++p;x.push_back(j[p++]);}r.push_back(std::move(x));}return r;}
}

bool ImageData::valid()const noexcept{return width&&height&&pixels.size()==static_cast<std::size_t>(width)*height*channels();}
ImageDecoderRegistry::ImageDecoderRegistry(){decoders_.emplace("ppm",ppm);decoders_.emplace("pnm",ppm);decoders_.emplace("bmp",bmp);decoders_.emplace("tga",tga);}
bool ImageDecoderRegistry::register_decoder(std::string extension,ImageDecoder decoder){if(extension.empty()||!decoder)return false;extension=ext(extension);std::lock_guard<std::mutex>l(mutex_);decoders_[std::move(extension)]=std::move(decoder);return true;}
bool ImageDecoderRegistry::decode(std::string_view uri,const std::vector<std::uint8_t>&bytes,ImageData&out,std::string&error)const{ImageDecoder d;{std::lock_guard<std::mutex>l(mutex_);auto it=decoders_.find(ext(uri));if(it!=decoders_.end())d=it->second;}if(!d){error="no image decoder registered";return false;}return d(uri,bytes,out,error);}
MaterialPipelineResult GltfMaterialPipeline::build(std::string_view base,std::string_view json,const AssetBytesLoader&loader,const ImageDecoderRegistry&decoders)const{MaterialPipelineResult r;std::size_t i=0;static const char*slots[]={"base_color","metallic_roughness","normal","occlusion","emission"};for(const auto&u:uris(json)){if(u.rfind("data:",0)==0)continue;if(!loader){r.error="missing asset loader";return r;}std::string full=u;auto p=base.find_last_of('/');if(p!=std::string_view::npos&&u.find('/')==std::string::npos)full=std::string(base.substr(0,p+1))+u;std::vector<std::uint8_t>b;std::string e;if(!loader(full,b,e)){r.error=e.empty()?"texture load failed":e;return r;}ImageData im;if(!decoders.decode(full,b,im,e)){r.error=e;return r;}auto ptr=std::make_shared<ImageData>(std::move(im));r.textures.push_back({slots[std::min(i,std::size_t(4))],full,std::move(ptr),make_asset_id(full,b)});++i;}r.success=true;return r;}

AsyncAssetStreamer::AsyncAssetStreamer(Loader loader,std::uint32_t workers):loader_(std::move(loader)),queue_([](const Task&a,const Task&b){return static_cast<int>(a.request.priority)<static_cast<int>(b.request.priority);}){workers=std::max(1U,workers);for(std::uint32_t i=0;i<workers;++i)workers_.emplace_back(&AsyncAssetStreamer::worker_loop,this);}
AsyncAssetStreamer::~AsyncAssetStreamer(){shutdown();}
std::uint64_t AsyncAssetStreamer::submit(std::string uri,StreamPriority priority){if(uri.empty())return 0;std::lock_guard<std::mutex>l(mutex_);if(stopping_)return 0;auto id=next_id_++;queue_.push({{id,std::move(uri),priority}});++stats_.submitted;cv_.notify_one();return id;}
std::vector<AssetStreamResult> AsyncAssetStreamer::poll(std::size_t n){std::lock_guard<std::mutex>l(mutex_);std::vector<AssetStreamResult>o;while(!completed_.empty()&&o.size()<n){o.push_back(std::move(completed_.front()));completed_.pop();}return o;}
bool AsyncAssetStreamer::cancel(std::uint64_t id){std::lock_guard<std::mutex>l(mutex_);if(!id||stopping_)return false;cancelled_[id]=true;++stats_.cancelled;return true;}
void AsyncAssetStreamer::shutdown()noexcept{{std::lock_guard<std::mutex>l(mutex_);if(stopping_)return;stopping_=true;}cv_.notify_all();for(auto&t:workers_)if(t.joinable())t.join();workers_.clear();}
AssetStreamingStats AsyncAssetStreamer::stats()const noexcept{std::lock_guard<std::mutex>l(mutex_);auto s=stats_;s.active=queue_.size();return s;}
void AsyncAssetStreamer::worker_loop(){for(;;){Task task;{std::unique_lock<std::mutex>l(mutex_);cv_.wait(l,[&]{return stopping_||!queue_.empty();});if(stopping_&&queue_.empty())return;task=queue_.top();queue_.pop();if(cancelled_.erase(task.request.request_id)){continue;}}AssetStreamResult r;r.request=task.request;if(loader_){std::string e;r.success=loader_(r.request.uri,r.bytes,e);r.error=std::move(e);}else r.error="no stream loader";{std::lock_guard<std::mutex>l(mutex_);completed_.push(std::move(r));++stats_.completed;if(!completed_.back().success)++stats_.failed;}}}

NavigationMesh::NavigationMesh(NavMeshConfig c):config_(c){config_.width=std::max(1U,c.width);config_.depth=std::max(1U,c.depth);config_.cell_size=std::max(.05f,c.cell_size);cells_.resize(static_cast<std::size_t>(config_.width)*config_.depth);for(std::uint32_t z=0;z<config_.depth;++z)for(std::uint32_t x=0;x<config_.width;++x){auto&c2=cells_[static_cast<std::size_t>(z)*config_.width+x];c2.id=static_cast<NavNodeId>(z*config_.width+x+1);c2.x=static_cast<std::int32_t>(x);c2.z=static_cast<std::int32_t>(z);}}
NavNodeId NavigationMesh::index(std::int32_t x,std::int32_t z)const noexcept{return x<0||z<0||x>=static_cast<int>(config_.width)||z>=static_cast<int>(config_.depth)?0:static_cast<NavNodeId>(z*config_.width+x+1);}
bool NavigationMesh::build(const std::function<float(float,float)>&h,const std::function<bool(float,float)>&w){if(!h||!w)return false;for(auto&c:cells_){auto wx=(c.x+.5f)*config_.cell_size,wz=(c.z+.5f)*config_.cell_size;c.height=h(wx,wz);c.walkable=w(wx,wz);}return true;}
bool NavigationMesh::set_cell(std::int32_t x,std::int32_t z,bool w,float h){auto i=index(x,z);if(!i)return false;cells_[i-1].walkable=w;cells_[i-1].height=h;return true;}
const NavCell* NavigationMesh::cell(std::int32_t x,std::int32_t z)const noexcept{auto i=index(x,z);return i?&cells_[i-1]:nullptr;}
NavPath NavigationMesh::find_path(Vec3 a,Vec3 b)const{NavPath r;auto cv=[&](Vec3 p){return std::pair<int,int>{static_cast<int>(std::floor(p.x/config_.cell_size)),static_cast<int>(std::floor(p.z/config_.cell_size))};};auto s=cv(a),g=cv(b);auto sc=cell(s.first,s.second),gc=cell(g.first,g.second);if(!sc||!gc||!sc->walkable||!gc->walkable)return r;struct I{NavNodeId id;float f;};struct C{bool operator()(const I&a,const I&b)const{return a.f>b.f;}};std::priority_queue<I,std::vector<I>,C>q;std::vector<float>cost(cells_.size(),std::numeric_limits<float>::infinity());std::vector<NavNodeId>par(cells_.size());auto h=[&](const NavCell&x){return std::fabs(static_cast<float>(x.x-gc->x))+std::fabs(static_cast<float>(x.z-gc->z));};cost[sc->id-1]=0;q.push({sc->id,h(*sc)});while(!q.empty()){auto id=q.top().id;q.pop();if(id==gc->id)break;auto&c=cells_[id-1];for(int dz=-1;dz<=1;++dz)for(int dx=-1;dx<=1;++dx){if(!dx&&!dz)continue;auto*n=cell(c.x+dx,c.z+dz);if(!n||!n->walkable)continue;float nc=cost[id-1]+((dx&&dz)?1.41421356f:1)+.05f*std::fabs(n->height-c.height);if(nc<cost[n->id-1]){cost[n->id-1]=nc;par[n->id-1]=id;q.push({n->id,nc+h(*n)});}}}if(sc->id!=gc->id&&!par[gc->id-1])return r;for(auto id=gc->id;;id=par[id-1]){auto&c=cells_[id-1];r.points.push_back({(c.x+.5f)*config_.cell_size,c.height,(c.z+.5f)*config_.cell_size});if(id==sc->id)break;}std::reverse(r.points.begin(),r.points.end());r.cost=cost[gc->id-1];r.success=true;return r;}
NavigationSystem::NavigationSystem(NavMeshConfig c):mesh_(c){}bool NavigationSystem::build(const std::function<float(float,float)>&h,const std::function<bool(float,float)>&w){return mesh_.build(h,w);}bool NavigationSystem::set_destination(NavigationAgent&a,Vec3 d){a.destination=d;Vec3 start=a.path.points.empty()?Vec3{}:a.path.points.front();a.path=mesh_.find_path(start,d);a.waypoint=0;a.active=a.path.success;return a.active;}bool NavigationSystem::update(NavigationAgent&a,Vec3&p,float dt)const noexcept{if(!a.active||dt<=0)return false;if(a.waypoint>=a.path.points.size()){a.active=false;return true;}auto t=a.path.points[a.waypoint];auto dx=t.x-p.x,dy=t.y-p.y,dz=t.z-p.z,len=std::sqrt(dx*dx+dy*dy+dz*dz);if(len<=a.stopping_distance){++a.waypoint;if(a.waypoint>=a.path.points.size()){a.active=false;return true;}}else{auto step=std::min(len,a.speed*dt);p.x+=dx/len*step;p.y+=dy/len*step;p.z+=dz/len*step;}return true;}

bool AnimationStateMachine::add_state(AnimationState s){if(!s.id||s.name.empty()||!s.clip)return false;if(std::any_of(states_.begin(),states_.end(),[&](const auto&x){return x.id==s.id;}))return false;states_.push_back(std::move(s));if(!state_)state_=states_.front().id;return true;}bool AnimationStateMachine::add_transition(AnimationTransition t){if(!t.from||!t.to||t.parameter.empty())return false;transitions_.push_back(std::move(t));return true;}bool AnimationStateMachine::set_initial(AnimationStateId id){if(!std::any_of(states_.begin(),states_.end(),[&](const auto&s){return s.id==id;}))return false;state_=id;elapsed_=0;return true;}bool AnimationStateMachine::set_float(std::string n,float v){if(n.empty()||!std::isfinite(v))return false;parameters_.floats[std::move(n)]=v;return true;}bool AnimationStateMachine::set_bool(std::string n,bool v){if(n.empty())return false;parameters_.bools[std::move(n)]=v;return true;}const AnimationState* AnimationStateMachine::current()const noexcept{for(const auto&s:states_)if(s.id==state_)return &s;return nullptr;}bool AnimationStateMachine::update(float dt,std::function<void(AnimationClipId,float)> play)noexcept{if(dt<0)return false;const auto*cur=current();if(!cur)return false;elapsed_+=dt;for(const auto&t:transitions_)if(t.from==state_){bool hit=false;if(auto f=parameters_.floats.find(t.parameter);f!=parameters_.floats.end())hit=t.greater?f->second>=t.threshold:f->second<=t.threshold;if(auto b=parameters_.bools.find(t.parameter);b!=parameters_.bools.end())hit=b->second;if(hit){state_=t.to;elapsed_=0;if(play)if(auto*n=current())play(n->clip,t.blend);return true;}}if(play&&elapsed_==dt)play(cur->clip,cur->blend);return false;}void AnimationStateMachine::reset()noexcept{parameters_={};elapsed_=0;state_=states_.empty()?0:states_.front().id;}

void EnvironmentRendererState::update(const EnvironmentState&e)noexcept{float sun=std::clamp((e.sun_elevation+.15f)/1.15f,0.f,1.f);sky_.zenith={.02f+.12f*sun,.04f+.28f*sun,.12f+.48f*sun};sky_.horizon={.16f+.62f*sun,.2f+.68f*sun,.28f+.7f*sun};sky_.star_visibility=1-sun;sky_.sun_disk=sun;weather_={};switch(e.weather){case WeatherType::Cloudy:weather_.cloud_cover=.65f;break;case WeatherType::Rain:weather_.cloud_cover=.8f;weather_.cloud_density=.8f;weather_.precipitation=e.weather_intensity;break;case WeatherType::Storm:weather_.cloud_cover=1;weather_.cloud_density=1;weather_.precipitation=e.weather_intensity;break;case WeatherType::Snow:weather_.cloud_cover=.75f;weather_.precipitation=e.weather_intensity;weather_.snow_cover=.8f;break;case WeatherType::Fog:weather_.fog_density=e.weather_intensity;break;case WeatherType::Wind:weather_.wind_speed=e.weather_intensity*20;break;default:break;}}

AudioSourceId AudioWorld::create_source(AudioSource s){if(!s.id)s.id=next_id_++;if(std::any_of(sources_.begin(),sources_.end(),[&](const auto&x){return x.id==s.id}))return 0;sources_.push_back(std::move(s));return sources_.back().id;}bool AudioWorld::destroy_source(AudioSourceId id)noexcept{auto i=std::find_if(sources_.begin(),sources_.end(),[&](const auto&s){return s.id==id;});if(i==sources_.end())return false;sources_.erase(i);return true;}bool AudioWorld::play(AudioSourceId id,bool l)noexcept{for(auto&s:sources_)if(s.id==id){s.playing=true;s.looping=l;return true;}return false;}bool AudioWorld::stop(AudioSourceId id)noexcept{for(auto&s:sources_)if(s.id==id){s.playing=false;return true;}return false;}bool AudioWorld::set_listener(AudioListener l)noexcept{if(!std::isfinite(l.position.x)||!std::isfinite(l.position.y)||!std::isfinite(l.position.z))return false;listener_=l;return true;}const AudioSource*AudioWorld::source(AudioSourceId id)const noexcept{for(const auto&s:sources_)if(s.id==id)return&s;return nullptr;}std::vector<AudioSource>AudioWorld::mix(float)const{std::vector<AudioSource>o;for(const auto&s:sources_)if(s.playing){auto x=s;if(s.spatial){auto dx=s.position.x-listener_.position.x,dy=s.position.y-listener_.position.y,dz=s.position.z-listener_.position.z,d=std::sqrt(dx*dx+dy*dy+dz*dz);x.gain*=std::clamp(1-d/std::max(.01f,s.max_distance),0.f,1.f);}o.push_back(x);}return o;}

UiWidgetId UiWorld::create(UiWidgetType t,UiWidgetId p){UiWidget w;w.id=next_id_++;w.parent=p;w.type=t;widgets_.push_back(std::move(w));return widgets_.back().id;}bool UiWorld::destroy(UiWidgetId id)noexcept{auto i=std::remove_if(widgets_.begin(),widgets_.end(),[&](const auto&w){return w.id==id||w.parent==id;});if(i==widgets_.end())return false;widgets_.erase(i,widgets_.end());return true;}bool UiWorld::set_text(UiWidgetId id,std::string t){for(auto&w:widgets_)if(w.id==id){w.text=std::move(t);return true;}return false;}bool UiWorld::set_value(UiWidgetId id,float v)noexcept{if(!std::isfinite(v))return false;for(auto&w:widgets_)if(w.id==id){w.value=v;return true;}return false;}bool UiWorld::set_visible(UiWidgetId id,bool v)noexcept{for(auto&w:widgets_)if(w.id==id){w.visible=v;return true;}return false;}const UiWidget*UiWorld::widget(UiWidgetId id)const noexcept{for(const auto&w:widgets_)if(w.id==id)return&w;return nullptr;}std::vector<UiWidget>UiWorld::visible_widgets()const{std::vector<UiWidget>o;for(const auto&w:widgets_)if(w.visible)o.push_back(w);return o;}void UiWorld::clear()noexcept{widgets_.clear();next_id_=1;}

bool ProductionSave::valid()const noexcept{return version>0&&game.valid();}std::vector<std::uint8_t>SaveStore::encode(const ProductionSave&s){if(!s.valid())return{};std::vector<std::uint8_t>b={'X','G','S','V',1};ws(b,s.game.project_name);ws(b,s.game.scene_name);wf(b,s.game.environment_seconds);w64(b,s.game.runtime_tick);w32(b,static_cast<std::uint32_t>(s.game.variables.size()));for(auto&x:s.game.variables){ws(b,x.first);ws(b,x.second);}w32(b,static_cast<std::uint32_t>(s.blobs.size()));for(auto&x:s.blobs){ws(b,x.key);w32(b,static_cast<std::uint32_t>(x.bytes.size()));b.insert(b.end(),x.bytes.begin(),x.bytes.end());}return b;}bool SaveStore::decode(const std::vector<std::uint8_t>&b,ProductionSave&s,std::string&e){if(b.size()<5||std::memcmp(b.data(),"XGSV",4)||b[4]!=1){e="invalid save header";return false;}s=ProductionSave{};std::size_t p=5;if(!gs(b,p,s.game.project_name)||!gs(b,p,s.game.scene_name)||!gf(b,p,s.game.environment_seconds)||!g64(b,p,s.game.runtime_tick)){e="truncated save";return false;}std::uint32_t n=0;if(!g32(b,p,n)){e="truncated variables";return false;}for(std::uint32_t i=0;i<n;++i){std::string k,v;if(!gs(b,p,k)||!gs(b,p,v)){e="truncated variable";return false;}s.game.variables.emplace(std::move(k),std::move(v));}if(!g32(b,p,n)){e="truncated blobs";return false;}for(std::uint32_t i=0;i<n;++i){GameStateBlob x;if(!gs(b,p,x.key)||!g32(b,p,n)||p+n>b.size()){e="truncated blob";return false;}x.bytes.assign(b.begin()+static_cast<std::ptrdiff_t>(p),b.begin()+static_cast<std::ptrdiff_t>(p+n));p+=n;s.blobs.push_back(std::move(x));}return s.valid();}

GameSession::GameSession(GameSessionConfig c,ProjectSourceLoader l):config_(c),project_loader_(std::move(l)),streaming_([this](std::string_view u,std::vector<std::uint8_t>&b,std::string&e){if(!project_loader_){e="no project loader";return false;}std::string s;if(!project_loader_(u,s)){e="asset load failed";return false;}b.assign(s.begin(),s.end());return true;}){}
bool GameSession::open_project(std::string_view source){auto p=parse_project(source);if(!p.success)return false;GameRuntime::SceneLoader sl=[this](std::string_view uri,IR&ir){if(!project_loader_)return false;std::string text;if(!project_loader_(uri,text))return false;auto c=Compiler{}.compile(SourceText(text));if(!c.succeeded()||!c.ir)return false;ir=*c.ir;return true;};if(!game_.load_project(p.project,sl))return false;open_=true;stats_={};nav_timer_=0;return true;}
bool GameSession::update(double dt)noexcept{if(!open_||dt<0)return false;if(!game_.update(dt))return false;environment_renderer_.update(game_.environment().state());auto r=streaming_.poll(config_.max_stream_results_per_frame);stats_.stream_results+=r.size();nav_timer_+=static_cast<float>(dt);if(nav_timer_>=config_.navigation_update_interval){nav_timer_=0;++stats_.navigation_updates;}if(config_.enable_audio)(void)audio_.mix(static_cast<float>(dt));++stats_.frames;return true;}std::vector<std::uint8_t>GameSession::save()const{ProductionSave s;s.game=game_.save();return SaveStore::encode(s);}bool GameSession::restore(const std::vector<std::uint8_t>&b)noexcept{ProductionSave s;std::string e;return SaveStore::decode(b,s,e)&&game_.restore(s.game);}bool GameSession::close()noexcept{if(!open_)return false;game_.reset();ui_.clear();open_=false;return true;}
} // namespace exgine
