#include "exgine/production.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <condition_variable>
#include <cstring>
#include <limits>
#include <queue>
#include <thread>

namespace exgine {
namespace {
std::string extension(std::string_view uri) {
    const auto dot=uri.find_last_of('.');
    std::string s=dot==std::string_view::npos?std::string(uri):std::string(uri.substr(dot+1));
    for(char& c:s) c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return s;
}
std::uint16_t read16(const std::vector<std::uint8_t>& b,std::size_t p){return static_cast<std::uint16_t>(static_cast<std::uint16_t>(b[p])|(static_cast<std::uint16_t>(b[p+1])<<8));}
std::uint32_t read32(const std::vector<std::uint8_t>& b,std::size_t p){return static_cast<std::uint32_t>(b[p])|(static_cast<std::uint32_t>(b[p+1])<<8)|(static_cast<std::uint32_t>(b[p+2])<<16)|(static_cast<std::uint32_t>(b[p+3])<<24);}
void write32(std::vector<std::uint8_t>& b,std::uint32_t v){for(int i=0;i<4;++i)b.push_back(static_cast<std::uint8_t>(v>>(8*i)));}
void write64(std::vector<std::uint8_t>& b,std::uint64_t v){for(int i=0;i<8;++i)b.push_back(static_cast<std::uint8_t>(v>>(8*i)));}
void write_double(std::vector<std::uint8_t>& b,double v){std::uint64_t bits=0;std::memcpy(&bits,&v,sizeof(bits));write64(b,bits);}
void write_string(std::vector<std::uint8_t>& b,std::string_view s){write32(b,static_cast<std::uint32_t>(s.size()));b.insert(b.end(),s.begin(),s.end());}
bool read32(const std::vector<std::uint8_t>& b,std::size_t& p,std::uint32_t& v){if(p+4>b.size())return false;v=read32(b,p);p+=4;return true;}
bool read64(const std::vector<std::uint8_t>& b,std::size_t& p,std::uint64_t& v){if(p+8>b.size())return false;v=0;for(int i=0;i<8;++i)v|=static_cast<std::uint64_t>(b[p+i])<<(8*i);p+=8;return true;}
bool read_double(const std::vector<std::uint8_t>& b,std::size_t& p,double& v){std::uint64_t bits=0;if(!read64(b,p,bits))return false;std::memcpy(&v,&bits,sizeof(v));return true;}
bool read_string(const std::vector<std::uint8_t>& b,std::size_t& p,std::string& s){std::uint32_t n=0;if(!read32(b,p,n)||p+n>b.size())return false;s.assign(reinterpret_cast<const char*>(b.data()+p),n);p+=n;return true;}

bool decode_ppm(std::string_view,const std::vector<std::uint8_t>& bytes,ImageData& out,std::string& error){
    std::string text(bytes.begin(),bytes.end());std::size_t p=0;
    auto token=[&](){while(p<text.size()){if(std::isspace(static_cast<unsigned char>(text[p]))){++p;continue;}if(text[p]=='#'){while(p<text.size()&&text[p]!='\n')++p;continue;}break;}const auto start=p;while(p<text.size()&&!std::isspace(static_cast<unsigned char>(text[p])))++p;return text.substr(start,p-start);};
    const std::string magic=token();if(magic!="P3"&&magic!="P6"){error="unsupported PPM";return false;}
    std::uint32_t w=0,h=0,maxv=0;try{w=static_cast<std::uint32_t>(std::stoul(token()));h=static_cast<std::uint32_t>(std::stoul(token()));maxv=static_cast<std::uint32_t>(std::stoul(token()));}catch(...){error="invalid PPM header";return false;}
    if(w==0||h==0||maxv==0||maxv>255){error="invalid PPM dimensions";return false;}
    out.width=w;out.height=h;out.format=ImagePixelFormat::RGB8;out.pixels.resize(static_cast<std::size_t>(w)*h*3);
    if(magic=="P3"){for(auto& v:out.pixels){try{v=static_cast<std::uint8_t>(std::min<std::uint32_t>(255,(static_cast<std::uint32_t>(std::stoul(token()))*255U)/maxv));}catch(...){error="truncated PPM";return false;}}return true;}
    while(p<bytes.size()&&std::isspace(static_cast<unsigned char>(bytes[p])))++p;
    if(bytes.size()-p<out.pixels.size()){error="truncated PPM";return false;}std::copy(bytes.begin()+static_cast<std::ptrdiff_t>(p),bytes.begin()+static_cast<std::ptrdiff_t>(p+out.pixels.size()),out.pixels.begin());return true;
}
bool decode_bmp(std::string_view,const std::vector<std::uint8_t>& b,ImageData& o,std::string& e){
    if(b.size()<54||b[0]!='B'||b[1]!='M'){e="invalid BMP";return false;}const std::uint32_t off=read32(b,10),w=read32(b,18),h=read32(b,22);const std::uint16_t bits=read16(b,28);
    if(w==0||h==0||(bits!=24&&bits!=32)||read32(b,30)!=0){e="unsupported BMP";return false;}const std::size_t channels=static_cast<std::size_t>(bits/8),row=((static_cast<std::size_t>(w)*bits+31)/32)*4;
    if(b.size()<static_cast<std::size_t>(off)+row*h){e="truncated BMP";return false;}o.width=w;o.height=h;o.format=channels==4?ImagePixelFormat::RGBA8:ImagePixelFormat::RGB8;o.pixels.resize(static_cast<std::size_t>(w)*h*channels);
    for(std::uint32_t y=0;y<h;++y)for(std::uint32_t x=0;x<w;++x){const auto src=static_cast<std::size_t>(off)+static_cast<std::size_t>(y)*row+static_cast<std::size_t>(x)*channels;const auto dst=(static_cast<std::size_t>(h-1-y)*w+x)*channels;o.pixels[dst]=b[src+2];o.pixels[dst+1]=b[src+1];o.pixels[dst+2]=b[src];if(channels==4)o.pixels[dst+3]=b[src+3];}return true;
}
bool decode_tga(std::string_view,const std::vector<std::uint8_t>& b,ImageData& o,std::string& e){
    if(b.size()<18){e="truncated TGA";return false;}const std::uint8_t type=b[2],depth=b[16],descriptor=b[17];const std::uint16_t w=read16(b,12),h=read16(b,14);
    if(w==0||h==0||type!=2||(depth!=24&&depth!=32)){e="unsupported TGA";return false;}const std::size_t channels=static_cast<std::size_t>(depth/8),start=18+static_cast<std::size_t>(b[0]),count=static_cast<std::size_t>(w)*h;
    if(b.size()<start+count*channels){e="truncated TGA";return false;}o.width=w;o.height=h;o.format=channels==4?ImagePixelFormat::RGBA8:ImagePixelFormat::RGB8;o.pixels.resize(count*channels);const bool flip_y=(descriptor&0x20U)==0,flip_x=(descriptor&0x10U)!=0;
    for(std::uint32_t y=0;y<h;++y)for(std::uint32_t x=0;x<w;++x){const std::uint32_t sx=flip_x?w-1-x:x,sy=flip_y?h-1-y:y;const auto src=start+(static_cast<std::size_t>(sy)*w+sx)*channels;const auto dst=(static_cast<std::size_t>(y)*w+x)*channels;o.pixels[dst]=b[src+2];o.pixels[dst+1]=b[src+1];o.pixels[dst+2]=b[src];if(channels==4)o.pixels[dst+3]=b[src+3];}return true;
}
std::vector<std::string> external_uris(std::string_view json){std::vector<std::string> out;std::size_t p=0;while((p=json.find("\"uri\"",p))!=std::string_view::npos){p=json.find(':',p+5);if(p==std::string_view::npos)break;++p;while(p<json.size()&&std::isspace(static_cast<unsigned char>(json[p])))++p;if(p>=json.size()||json[p]!='\"')continue;++p;std::string s;while(p<json.size()&&json[p]!='\"'){if(json[p]=='\\'&&p+1<json.size())++p;s.push_back(json[p++]);}if(p<json.size())++p;out.push_back(std::move(s));}return out;}
}

bool ImageData::valid()const noexcept{return width>0&&height>0&&pixels.size()==static_cast<std::size_t>(width)*height*channels();}
ImageDecoderRegistry::ImageDecoderRegistry(){decoders_.emplace("ppm",decode_ppm);decoders_.emplace("pnm",decode_ppm);decoders_.emplace("bmp",decode_bmp);decoders_.emplace("tga",decode_tga);}
bool ImageDecoderRegistry::register_decoder(std::string e,ImageDecoder d){if(e.empty()||!d)return false;e=extension(e);std::lock_guard<std::mutex> lock(mutex_);decoders_[std::move(e)]=std::move(d);return true;}
bool ImageDecoderRegistry::decode(std::string_view uri,const std::vector<std::uint8_t>& bytes,ImageData& out,std::string& error)const{ImageDecoder d;{std::lock_guard<std::mutex>lock(mutex_);auto it=decoders_.find(extension(uri));if(it!=decoders_.end())d=it->second;}if(!d){error="no image decoder registered";return false;}return d(uri,bytes,out,error);}
MaterialPipelineResult GltfMaterialPipeline::build(std::string_view base,std::string_view json,const AssetBytesLoader& loader,const ImageDecoderRegistry& decoders)const{MaterialPipelineResult r;static constexpr const char* slots[]={"base_color","metallic_roughness","normal","occlusion","emission"};std::size_t slot=0;for(const auto& uri:external_uris(json)){if(uri.rfind("data:",0)==0)continue;if(!loader){r.error="missing asset loader";return r;}std::string resolved=uri;const auto slash=base.find_last_of('/');if(slash!=std::string_view::npos&&uri.find('/')==std::string::npos)resolved=std::string(base.substr(0,slash+1))+uri;std::vector<std::uint8_t> bytes;std::string error;if(!loader(resolved,bytes,error)){r.error=error.empty()?"texture load failed":error;return r;}ImageData image;if(!decoders.decode(resolved,bytes,image,error)){r.error=error;return r;}r.textures.push_back({slots[std::min(slot,std::size_t(4))],resolved,std::make_shared<ImageData>(std::move(image)),make_asset_id(resolved,bytes)});++slot;}r.success=true;return r;}

AsyncAssetStreamer::AsyncAssetStreamer(Loader loader,std::uint32_t workers):queue_([](const Task&a,const Task&b){return static_cast<int>(a.request.priority)<static_cast<int>(b.request.priority);}),loader_(std::move(loader)){workers=std::max<std::uint32_t>(1,workers);workers_.reserve(workers);for(std::uint32_t i=0;i<workers;++i)workers_.emplace_back(&AsyncAssetStreamer::worker_loop,this);}
AsyncAssetStreamer::~AsyncAssetStreamer(){shutdown();}
std::uint64_t AsyncAssetStreamer::submit(std::string uri,StreamPriority priority){if(uri.empty())return 0;std::lock_guard<std::mutex>lock(mutex_);if(stopping_)return 0;const auto id=next_id_++;queue_.push({{id,std::move(uri),priority}});++stats_.submitted;cv_.notify_one();return id;}
std::vector<AssetStreamResult> AsyncAssetStreamer::poll(std::size_t limit){std::lock_guard<std::mutex>lock(mutex_);std::vector<AssetStreamResult> out;while(!completed_.empty()&&out.size()<limit){out.push_back(std::move(completed_.front()));completed_.pop();}return out;}
bool AsyncAssetStreamer::cancel(std::uint64_t id){std::lock_guard<std::mutex>lock(mutex_);if(id==0||stopping_)return false;cancelled_[id]=true;++stats_.cancelled;return true;}
void AsyncAssetStreamer::shutdown()noexcept{{std::lock_guard<std::mutex>lock(mutex_);if(stopping_)return;stopping_=true;}cv_.notify_all();for(auto& worker:workers_)if(worker.joinable())worker.join();workers_.clear();}
AssetStreamingStats AsyncAssetStreamer::stats()const noexcept{std::lock_guard<std::mutex>lock(mutex_);auto s=stats_;s.active=queue_.size();return s;}
void AsyncAssetStreamer::worker_loop(){for(;;){Task task;{std::unique_lock<std::mutex>lock(mutex_);cv_.wait(lock,[&]{return stopping_||!queue_.empty();});if(stopping_&&queue_.empty())return;task=queue_.top();queue_.pop();if(cancelled_.erase(task.request.request_id))continue;}AssetStreamResult result;result.request=task.request;if(loader_){std::string error;result.success=loader_(result.request.uri,result.bytes,error);result.error=std::move(error);}else result.error="no stream loader";{std::lock_guard<std::mutex>lock(mutex_);++stats_.completed;if(!result.success)++stats_.failed;completed_.push(std::move(result));}}}

NavigationMesh::NavigationMesh(NavMeshConfig c):config_(c){config_.width=std::max<std::uint32_t>(1,c.width);config_.depth=std::max<std::uint32_t>(1,c.depth);config_.cell_size=std::max(.05f,c.cell_size);cells_.resize(static_cast<std::size_t>(config_.width)*config_.depth);for(std::uint32_t z=0;z<config_.depth;++z)for(std::uint32_t x=0;x<config_.width;++x){auto& cell=cells_[static_cast<std::size_t>(z)*config_.width+x];cell.id=static_cast<NavNodeId>(z*config_.width+x+1);cell.x=static_cast<std::int32_t>(x);cell.z=static_cast<std::int32_t>(z);}}
NavNodeId NavigationMesh::index(std::int32_t x,std::int32_t z)const noexcept{return x<0||z<0||x>=static_cast<std::int32_t>(config_.width)||z>=static_cast<std::int32_t>(config_.depth)?0:static_cast<NavNodeId>(z*config_.width+x+1);}
bool NavigationMesh::build(const std::function<float(float,float)>& height,const std::function<bool(float,float)>& walkable){if(!height||!walkable)return false;for(auto& c:cells_){c.height=height((c.x+.5f)*config_.cell_size,(c.z+.5f)*config_.cell_size);c.walkable=walkable((c.x+.5f)*config_.cell_size,(c.z+.5f)*config_.cell_size);}return true;}
bool NavigationMesh::set_cell(std::int32_t x,std::int32_t z,bool walkable,float height){const auto i=index(x,z);if(!i)return false;cells_[i-1].walkable=walkable;cells_[i-1].height=height;return true;}
const NavCell* NavigationMesh::cell(std::int32_t x,std::int32_t z)const noexcept{const auto i=index(x,z);return i?&cells_[i-1]:nullptr;}
NavPath NavigationMesh::find_path(Vec3 start,Vec3 goal)const{NavPath r;auto tocell=[&](Vec3 p){return std::pair<int,int>{static_cast<int>(std::floor(p.x/config_.cell_size)),static_cast<int>(std::floor(p.z/config_.cell_size))};};const auto s=tocell(start),g=tocell(goal);const auto* source=cell(s.first,s.second);const auto* target=cell(g.first,g.second);if(!source||!target||!source->walkable||!target->walkable)return r;struct Item{NavNodeId id;float f;};struct Compare{bool operator()(const Item&a,const Item&b)const{return a.f>b.f;}};std::priority_queue<Item,std::vector<Item>,Compare> open;std::vector<float> costs(cells_.size(),std::numeric_limits<float>::infinity());std::vector<NavNodeId> parent(cells_.size(),0);auto heuristic=[&](const NavCell& c){return std::fabs(static_cast<float>(c.x-target->x))+std::fabs(static_cast<float>(c.z-target->z));};costs[source->id-1]=0;open.push({source->id,heuristic(*source)});while(!open.empty()){const auto id=open.top().id;open.pop();if(id==target->id)break;const auto& c=cells_[id-1];for(int dz=-1;dz<=1;++dz)for(int dx=-1;dx<=1;++dx){if(dx==0&&dz==0)continue;const auto* n=cell(c.x+dx,c.z+dz);if(!n||!n->walkable)continue;const float step=(dx!=0&&dz!=0)?1.41421356f:1.f;const float next=costs[id-1]+step+.05f*std::fabs(n->height-c.height);if(next<costs[n->id-1]){costs[n->id-1]=next;parent[n->id-1]=id;open.push({n->id,next+heuristic(*n)});}}}if(source->id!=target->id&&parent[target->id-1]==0)return r;for(NavNodeId id=target->id;;id=parent[id-1]){const auto& c=cells_[id-1];r.points.push_back({(c.x+.5f)*config_.cell_size,c.height,(c.z+.5f)*config_.cell_size});if(id==source->id)break;}std::reverse(r.points.begin(),r.points.end());r.cost=costs[target->id-1];r.success=true;return r;}
NavigationSystem::NavigationSystem(NavMeshConfig c):mesh_(c){} bool NavigationSystem::build(const std::function<float(float,float)>&h,const std::function<bool(float,float)>&w){return mesh_.build(h,w);} bool NavigationSystem::set_destination(NavigationAgent&a,Vec3 d){a.destination=d;const Vec3 start=a.path.points.empty()?Vec3{}:a.path.points.front();a.path=mesh_.find_path(start,d);a.waypoint=0;a.active=a.path.success;return a.active;} bool NavigationSystem::update(NavigationAgent&a,Vec3&p,float dt)const noexcept{if(!a.active||dt<=0)return false;if(a.waypoint>=a.path.points.size()){a.active=false;return true;}const auto target=a.path.points[a.waypoint];const float dx=target.x-p.x,dy=target.y-p.y,dz=target.z-p.z,len=std::sqrt(dx*dx+dy*dy+dz*dz);if(len<=a.stopping_distance){++a.waypoint;if(a.waypoint>=a.path.points.size())a.active=false;}else{const float step=std::min(len,a.speed*dt);p.x+=dx/len*step;p.y+=dy/len*step;p.z+=dz/len*step;}return true;}

bool AnimationStateMachine::add_state(AnimationState s){if(s.id==0||s.name.empty()||s.clip==0)return false;if(std::any_of(states_.begin(),states_.end(),[&](const auto&x){return x.id==s.id;}))return false;states_.push_back(std::move(s));if(state_==0)state_=states_.front().id;return true;} bool AnimationStateMachine::add_transition(AnimationTransition t){if(t.from==0||t.to==0||t.parameter.empty())return false;transitions_.push_back(std::move(t));return true;} bool AnimationStateMachine::set_initial(AnimationStateId id){if(!std::any_of(states_.begin(),states_.end(),[&](const auto&s){return s.id==id;}))return false;state_=id;elapsed_=0;return true;} bool AnimationStateMachine::set_float(std::string name,float value){if(name.empty()||!std::isfinite(value))return false;parameters_.floats[std::move(name)]=value;return true;} bool AnimationStateMachine::set_bool(std::string name,bool value){if(name.empty())return false;parameters_.bools[std::move(name)]=value;return true;} const AnimationState* AnimationStateMachine::current()const noexcept{for(const auto&s:states_)if(s.id==state_)return&s;return nullptr;} bool AnimationStateMachine::update(float dt,std::function<void(AnimationClipId,float)> play)noexcept{if(dt<0)return false;const auto* cur=current();if(!cur)return false;const bool first=elapsed_==0;elapsed_+=dt;for(const auto&t:transitions_)if(t.from==state_){bool hit=false;if(const auto f=parameters_.floats.find(t.parameter);f!=parameters_.floats.end())hit=t.greater?f->second>=t.threshold:f->second<=t.threshold;if(const auto b=parameters_.bools.find(t.parameter);b!=parameters_.bools.end())hit=b->second;if(hit){state_=t.to;elapsed_=0;if(play)if(const auto*n=current())play(n->clip,n->blend);return true;}}if(first&&play)play(cur->clip,cur->blend);return false;} void AnimationStateMachine::reset()noexcept{parameters_={};elapsed_=0;state_=states_.empty()?0:states_.front().id;}

void EnvironmentRendererState::update(const EnvironmentState&e)noexcept{const float sun=std::clamp((e.sun_elevation+.15f)/1.15f,0.f,1.f);sky_.zenith={.02f+.12f*sun,.04f+.28f*sun,.12f+.48f*sun};sky_.horizon={.16f+.62f*sun,.20f+.68f*sun,.28f+.70f*sun};sky_.star_visibility=1.f-sun;sky_.sun_disk=sun;weather_={};switch(e.weather){case WeatherType::Cloudy:weather_.cloud_cover=.65f;break;case WeatherType::Rain:weather_.cloud_cover=.8f;weather_.cloud_density=.8f;weather_.precipitation=e.weather_intensity;break;case WeatherType::Storm:weather_.cloud_cover=1.f;weather_.cloud_density=1.f;weather_.precipitation=e.weather_intensity;break;case WeatherType::Snow:weather_.cloud_cover=.75f;weather_.precipitation=e.weather_intensity;weather_.snow_cover=.8f;break;case WeatherType::Fog:weather_.fog_density=e.weather_intensity;break;case WeatherType::Wind:weather_.wind_speed=e.weather_intensity*20.f;break;default:break;}}

AudioSourceId AudioWorld::create_source(AudioSource source){if(source.id==0)source.id=next_id_++;if(std::any_of(sources_.begin(),sources_.end(),[&](const auto&s){return s.id==source.id;}))return 0;sources_.push_back(std::move(source));return sources_.back().id;} bool AudioWorld::destroy_source(AudioSourceId id)noexcept{const auto i=std::find_if(sources_.begin(),sources_.end(),[&](const auto&s){return s.id==id;});if(i==sources_.end())return false;sources_.erase(i);return true;} bool AudioWorld::play(AudioSourceId id,bool looping)noexcept{for(auto&s:sources_)if(s.id==id){s.playing=true;s.looping=looping;return true;}return false;} bool AudioWorld::stop(AudioSourceId id)noexcept{for(auto&s:sources_)if(s.id==id){s.playing=false;return true;}return false;} bool AudioWorld::set_listener(AudioListener l)noexcept{if(!std::isfinite(l.position.x)||!std::isfinite(l.position.y)||!std::isfinite(l.position.z))return false;listener_=l;return true;} const AudioSource* AudioWorld::source(AudioSourceId id)const noexcept{for(const auto&s:sources_)if(s.id==id)return&s;return nullptr;} std::vector<AudioSource> AudioWorld::mix(float)const{std::vector<AudioSource> out;for(const auto&s:sources_)if(s.playing){auto copy=s;if(s.spatial){const float dx=s.position.x-listener_.position.x,dy=s.position.y-listener_.position.y,dz=s.position.z-listener_.position.z,dist=std::sqrt(dx*dx+dy*dy+dz*dz);copy.gain*=std::clamp(1.f-dist/std::max(.01f,s.max_distance),0.f,1.f);}out.push_back(std::move(copy));}return out;}

UiWidgetId UiWorld::create(UiWidgetType type,UiWidgetId parent){UiWidget w;w.id=next_id_++;w.parent=parent;w.type=type;widgets_.push_back(std::move(w));return widgets_.back().id;} bool UiWorld::destroy(UiWidgetId id)noexcept{const auto i=std::remove_if(widgets_.begin(),widgets_.end(),[&](const auto&w){return w.id==id||w.parent==id;});if(i==widgets_.end())return false;widgets_.erase(i,widgets_.end());return true;} bool UiWorld::set_text(UiWidgetId id,std::string text){for(auto&w:widgets_)if(w.id==id){w.text=std::move(text);return true;}return false;} bool UiWorld::set_value(UiWidgetId id,float value)noexcept{if(!std::isfinite(value))return false;for(auto&w:widgets_)if(w.id==id){w.value=value;return true;}return false;} bool UiWorld::set_visible(UiWidgetId id,bool visible)noexcept{for(auto&w:widgets_)if(w.id==id){w.visible=visible;return true;}return false;} const UiWidget* UiWorld::widget(UiWidgetId id)const noexcept{for(const auto&w:widgets_)if(w.id==id)return&w;return nullptr;} std::vector<UiWidget> UiWorld::visible_widgets()const{std::vector<UiWidget>out;for(const auto&w:widgets_)if(w.visible)out.push_back(w);return out;} void UiWorld::clear()noexcept{widgets_.clear();next_id_=1;}

bool ProductionSave::valid()const noexcept{return version>0&&game.valid();} std::vector<std::uint8_t> SaveStore::encode(const ProductionSave&s){if(!s.valid())return{};std::vector<std::uint8_t>b={'X','G','S','V',1};write_string(b,s.game.project_name);write_string(b,s.game.scene_name);write_double(b,s.game.environment_seconds);write64(b,s.game.runtime_tick);write32(b,static_cast<std::uint32_t>(s.game.variables.size()));for(const auto&x:s.game.variables){write_string(b,x.first);write_string(b,x.second);}write32(b,static_cast<std::uint32_t>(s.blobs.size()));for(const auto&x:s.blobs){write_string(b,x.key);write32(b,static_cast<std::uint32_t>(x.bytes.size()));b.insert(b.end(),x.bytes.begin(),x.bytes.end());}return b;}
}
