#include "exgine/gles_production_complete.hpp"
#include <algorithm>
#include <cmath>
namespace exgine {
std::uint64_t ReflectionProbeRegistry::create(Vec3 p,float radius,float weight){Record q{};q.meta.id=next_id_++;q.meta.position=p;q.meta.extents={radius,radius,radius};q.meta.blend_distance=std::max(.001f,radius);q.meta.resolution=128;q.meta.realtime=true;q.blend_weight=std::max(0.f,weight);probes_.push_back(q);return q.meta.id;}
bool ReflectionProbeRegistry::destroy(std::uint64_t id,OpenGLESApi&a)noexcept{auto it=std::find_if(probes_.begin(),probes_.end(),[&](const auto&q){return q.meta.id==id;});if(it==probes_.end())return false;auto del=[&](GlesCubeResource&r){if(r.texture&&a.DeleteTextures)a.DeleteTextures(1,&r.texture);r={};};del(it->gpu.environment);del(it->gpu.irradiance);del(it->gpu.specular);if(it->gpu.depth_rbo&&a.DeleteRenderbuffers)a.DeleteRenderbuffers(1,&it->gpu.depth_rbo);probes_.erase(it);return true;}
ReflectionProbe*ReflectionProbeRegistry::find(std::uint64_t id)noexcept{for(auto&q:probes_)if(q.meta.id==id)return&q.meta;return nullptr;}const ReflectionProbe*ReflectionProbeRegistry::find(std::uint64_t id)const noexcept{for(const auto&q:probes_)if(q.meta.id==id)return&q.meta;return nullptr;}
ReflectionProbeGpuData*ReflectionProbeRegistry::gpu_find(std::uint64_t id)noexcept{for(auto&q:probes_)if(q.meta.id==id)return&q.gpu;return nullptr;}const ReflectionProbeGpuData*ReflectionProbeRegistry::gpu_find(std::uint64_t id)const noexcept{for(const auto&q:probes_)if(q.meta.id==id)return&q.gpu;return nullptr;}
bool ReflectionProbeRegistry::set_gpu(std::uint64_t id,const ReflectionProbeGpuData&g)noexcept{auto*p=gpu_find(id);if(!p)return false;*p=g;return true;}float ReflectionProbeRegistry::weight(std::uint64_t id)const noexcept{for(const auto&q:probes_)if(q.meta.id==id)return q.blend_weight;return 0.f;}
const ReflectionProbe*ReflectionProbeRegistry::select(Vec3 p)const noexcept{const ReflectionProbe*best=nullptr;float score=-1;for(const auto&q:probes_){if(!q.gpu.valid)continue;float dx=p.x-q.meta.position.x,dy=p.y-q.meta.position.y,dz=p.z-q.meta.position.z,d=std::sqrt(dx*dx+dy*dy+dz*dz),r=std::max(.001f,q.meta.blend_distance);if(d>r)continue;float s=q.blend_weight*(1.f-d/r);if(s>score){score=s;best=&q.meta;}}return best;}
std::vector<const ReflectionProbe*>ReflectionProbeRegistry::blend(Vec3 p,std::size_t max)const{std::vector<const ReflectionProbe*>r;for(const auto&q:probes_){if(!q.gpu.valid)continue;float dx=p.x-q.meta.position.x,dy=p.y-q.meta.position.y,dz=p.z-q.meta.position.z,d=std::sqrt(dx*dx+dy*dy+dz*dz);if(d<=q.meta.blend_distance&&q.blend_weight>0)r.push_back(&q.meta);}std::sort(r.begin(),r.end(),[&](auto*a,auto*b){auto score=[&](auto*x){float dx=p.x-x->position.x,dy=p.y-x->position.y,dz=p.z-x->position.z;float d=std::sqrt(dx*dx+dy*dy+dz*dz);return weight(x->id)*(1.f-d/std::max(.001f,x->blend_distance));};return score(a)>score(b);});if(r.size()>max)r.resize(max);return r;}
void ReflectionProbeRegistry::clear(OpenGLESApi&a)noexcept{while(!probes_.empty())destroy(probes_.back().meta.id,a);}
}