#include "exgine/render.hpp"
#include "exgine/runtime.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <utility>
namespace exgine { namespace {
constexpr float pi=3.14159265358979323846f;
float rad(float d)noexcept{return d*pi/180.0f;} bool fin(float v)noexcept{return std::isfinite(v);} bool finv(Vec3 v)noexcept{return fin(v.x)&&fin(v.y)&&fin(v.z);}
Mat4 T(Vec3 p)noexcept{auto r=Mat4::identity();r.at(0,3)=p.x;r.at(1,3)=p.y;r.at(2,3)=p.z;return r;} Mat4 S(Vec3 s)noexcept{auto r=Mat4::identity();r.at(0,0)=s.x;r.at(1,1)=s.y;r.at(2,2)=s.z;return r;}
Mat4 Rx(float a)noexcept{auto r=Mat4::identity();auto c=std::cos(a),s=std::sin(a);r.at(1,1)=c;r.at(1,2)=-s;r.at(2,1)=s;r.at(2,2)=c;return r;} Mat4 Ry(float a)noexcept{auto r=Mat4::identity();auto c=std::cos(a),s=std::sin(a);r.at(0,0)=c;r.at(0,2)=s;r.at(2,0)=-s;r.at(2,2)=c;return r;} Mat4 Rz(float a)noexcept{auto r=Mat4::identity();auto c=std::cos(a),s=std::sin(a);r.at(0,0)=c;r.at(0,1)=-s;r.at(1,0)=s;r.at(1,1)=c;return r;}
Mat4 quat_matrix(Quat q)noexcept{q=normalize(q);Mat4 r=Mat4::identity();const float xx=q.x*q.x,yy=q.y*q.y,zz=q.z*q.z,xy=q.x*q.y,xz=q.x*q.z,yz=q.y*q.z,wx=q.w*q.x,wy=q.w*q.y,wz=q.w*q.z;r.at(0,0)=1-2*(yy+zz);r.at(0,1)=2*(xy-wz);r.at(0,2)=2*(xz+wy);r.at(1,0)=2*(xy+wz);r.at(1,1)=1-2*(xx+zz);r.at(1,2)=2*(yz-wx);r.at(2,0)=2*(xz-wy);r.at(2,1)=2*(yz+wx);r.at(2,2)=1-2*(xx+yy);return r;}
Mat4 anim_matrix(const AnimTransform&t)noexcept{return multiply(multiply(T(t.translation),quat_matrix(t.rotation)),S(t.scale));}
Vec3 tp(const Mat4&m,Vec3 p)noexcept{float x=m.at(0,0)*p.x+m.at(0,1)*p.y+m.at(0,2)*p.z+m.at(0,3);float y=m.at(1,0)*p.x+m.at(1,1)*p.y+m.at(1,2)*p.z+m.at(1,3);float z=m.at(2,0)*p.x+m.at(2,1)*p.y+m.at(2,2)*p.z+m.at(2,3);float w=m.at(3,0)*p.x+m.at(3,1)*p.y+m.at(3,2)*p.z+m.at(3,3);if(fin(w)&&std::fabs(w)>1e-7f){x/=w;y/=w;z/=w;}return{x,y,z};}
struct P{Vec3 n{};float d=0;}; P plane(float a,float b,float c,float d)noexcept{float l=std::sqrt(a*a+b*b+c*c);if(!fin(l)||l<1e-7f)return{};return{{a/l,b/l,c/l},d/l};}
std::array<P,6> planes(const Mat4&m)noexcept{return{plane(m.at(3,0)+m.at(0,0),m.at(3,1)+m.at(0,1),m.at(3,2)+m.at(0,2),m.at(3,3)+m.at(0,3)),plane(m.at(3,0)-m.at(0,0),m.at(3,1)-m.at(0,1),m.at(3,2)-m.at(0,2),m.at(3,3)-m.at(0,3)),plane(m.at(3,0)+m.at(1,0),m.at(3,1)+m.at(1,1),m.at(3,2)+m.at(1,2),m.at(3,3)+m.at(1,3)),plane(m.at(3,0)-m.at(1,0),m.at(3,1)-m.at(1,1),m.at(3,2)-m.at(1,2),m.at(3,3)-m.at(1,3)),plane(m.at(3,0)+m.at(2,0),m.at(3,1)+m.at(2,1),m.at(3,2)+m.at(2,2),m.at(3,3)+m.at(2,3)),plane(m.at(3,0)-m.at(2,0),m.at(3,1)-m.at(2,1),m.at(3,2)-m.at(2,2),m.at(3,3)-m.at(2,3))};}
bool visible(Bounds3 b,const Mat4&vp)noexcept{for(const auto&p:planes(vp)){Vec3 q{p.n.x>=0?b.max.x:b.min.x,p.n.y>=0?b.max.y:b.min.y,p.n.z>=0?b.max.z:b.min.z};if(p.n.x*q.x+p.n.y*q.y+p.n.z*q.z+p.d<0)return false;}return true;}
bool cfg_ok(const RenderConfig&c)noexcept{return c.width&&c.height&&c.max_lights&&c.max_bones_per_draw>0&&c.max_bones_per_draw<=128;}
Bounds3 invalid_bounds()noexcept{return{{1,1,1},{-1,-1,-1}};}
Bounds3 skinned_bounds(const SkinnedMesh&m)noexcept{if(m.vertices.empty()||m.indices.empty()||m.indices.size()%3)return invalid_bounds();Bounds3 b{{std::numeric_limits<float>::max(),std::numeric_limits<float>::max(),std::numeric_limits<float>::max()},{std::numeric_limits<float>::lowest(),std::numeric_limits<float>::lowest(),std::numeric_limits<float>::lowest()}};for(const auto&v:m.vertices){if(!finv(v.position))return invalid_bounds();b.min.x=std::min(b.min.x,v.position.x);b.min.y=std::min(b.min.y,v.position.y);b.min.z=std::min(b.min.z,v.position.z);b.max.x=std::max(b.max.x,v.position.x);b.max.y=std::max(b.max.y,v.position.y);b.max.z=std::max(b.max.z,v.position.z);}return b;}
bool skinned_payload_valid(const SkinnedMesh&m)noexcept{if(m.vertices.empty()||m.indices.empty()||m.indices.size()%3)return false;for(auto i:m.indices)if(i>=m.vertices.size())return false;for(const auto&v:m.vertices){float sum=0;for(std::size_t i=0;i<4;++i){if(!fin(v.skin.weights[i])||v.skin.weights[i]<0||v.skin.bones[i]>128)return false;if(v.skin.weights[i]>0&&v.skin.bones[i]==0)return false;sum+=v.skin.weights[i];}if(sum<=0||sum>1.001f)return false;}return true;}
}
Mat4 Mat4::identity()noexcept{Mat4 r{};r.at(0,0)=r.at(1,1)=r.at(2,2)=r.at(3,3)=1;return r;}
Mat4 multiply(const Mat4&a,const Mat4&b)noexcept{Mat4 r{};for(std::size_t i=0;i<4;i++)for(std::size_t j=0;j<4;j++)for(std::size_t k=0;k<4;k++)r.at(i,j)+=a.at(i,k)*b.at(k,j);return r;}
Mat4 make_model_matrix(const SceneTransform&t)noexcept{return multiply(multiply(T(t.position),multiply(multiply(Rz(t.rotation.z),Ry(t.rotation.y)),Rx(t.rotation.x))),S(t.scale));}
Mat4 make_view_matrix(const Camera&c)noexcept{return multiply(multiply(multiply(Rx(-c.rotation.x),Ry(-c.rotation.y)),Rz(-c.rotation.z)),T({-c.position.x,-c.position.y,-c.position.z}));}
Mat4 make_projection_matrix(const Camera&c,float aspect)noexcept{if(!c.valid()||!fin(aspect)||aspect<=0)return Mat4::identity();if(c.orthographic){float hh=c.orthographic_size*.5f,hw=hh*aspect;Mat4 r{};r.at(0,0)=1/hw;r.at(1,1)=1/hh;r.at(2,2)=-2/(c.far_plane-c.near_plane);r.at(2,3)=-(c.far_plane+c.near_plane)/(c.far_plane-c.near_plane);r.at(3,3)=1;return r;}float f=1/std::tan(rad(c.vertical_fov_degrees)*.5f);Mat4 r{};r.at(0,0)=f/aspect;r.at(1,1)=f;r.at(2,2)=(c.far_plane+c.near_plane)/(c.near_plane-c.far_plane);r.at(2,3)=2*c.far_plane*c.near_plane/(c.near_plane-c.far_plane);r.at(3,2)=-1;return r;}
bool finite_matrix(const Mat4&m)noexcept{for(float v:m.m)if(!fin(v))return false;return true;}
bool Bounds3::valid()const noexcept{return finv(min)&&finv(max)&&min.x<=max.x&&min.y<=max.y&&min.z<=max.z;}
Bounds3 mesh_bounds(const Mesh&m)noexcept{if(!m.valid())return invalid_bounds();Bounds3 b{{std::numeric_limits<float>::max(),std::numeric_limits<float>::max(),std::numeric_limits<float>::max()},{std::numeric_limits<float>::lowest(),std::numeric_limits<float>::lowest(),std::numeric_limits<float>::lowest()}};for(const auto&v:m.vertices){if(!finv(v.position))return invalid_bounds();b.min.x=std::min(b.min.x,v.position.x);b.min.y=std::min(b.min.y,v.position.y);b.min.z=std::min(b.min.z,v.position.z);b.max.x=std::max(b.max.x,v.position.x);b.max.y=std::max(b.max.y,v.position.y);b.max.z=std::max(b.max.z,v.position.z);}return b;}
Bounds3 transform_bounds(const Bounds3&b,const Mat4&m)noexcept{if(!b.valid()||!finite_matrix(m))return invalid_bounds();std::array<Vec3,8> c{{{b.min.x,b.min.y,b.min.z},{b.max.x,b.min.y,b.min.z},{b.min.x,b.max.y,b.min.z},{b.max.x,b.max.y,b.min.z},{b.min.x,b.min.y,b.max.z},{b.max.x,b.min.y,b.max.z},{b.min.x,b.max.y,b.max.z},{b.max.x,b.max.y,b.max.z}}};Bounds3 r{{std::numeric_limits<float>::max(),std::numeric_limits<float>::max(),std::numeric_limits<float>::max()},{std::numeric_limits<float>::lowest(),std::numeric_limits<float>::lowest(),std::numeric_limits<float>::lowest()}};for(auto p:c){p=tp(m,p);if(!finv(p))return invalid_bounds();r.min.x=std::min(r.min.x,p.x);r.min.y=std::min(r.min.y,p.y);r.min.z=std::min(r.min.z,p.z);r.max.x=std::max(r.max.x,p.x);r.max.y=std::max(r.max.y,p.y);r.max.z=std::max(r.max.z,p.z);}return r;}
bool RenderMaterialBinding::valid()const noexcept{return material.valid()&&textures&&textures->valid();}
bool RenderDrawCall::valid()const noexcept{if(!entity_id||!scene_node||!finite_matrix(model)||!world_bounds.valid()||!material.valid())return false;if(animated())return skinned_mesh&&skinned_payload_valid(*skinned_mesh)&&!bone_palette.empty()&&bone_palette.size()<=128;return geometry&&geometry->valid()&&part_index<geometry->parts.size()&&geometry->parts[part_index].mesh.valid();}
bool RenderFrame::valid()const noexcept{if(!frame_id||!cfg_ok(config)||!camera.valid()||!finite_matrix(view)||!finite_matrix(projection)||!finite_matrix(view_projection)||lights.size()>config.max_lights)return false;for(const auto&l:lights)if(!l.valid())return false;for(const auto&d:draws)if(!d.valid())return false;return true;}
Renderer::Renderer(RenderConfig c):config_(c){}
bool Renderer::build_frame(const Runtime&rt,RenderFrame&f)const{if(!cfg_ok(config_)||!rt.state().world_entity)return false;auto cam=rt.lighting().main_camera();if(!cam.valid()||next_frame_id_==0||next_frame_id_==std::numeric_limits<std::uint64_t>::max())return false;f=RenderFrame{};f.frame_id=next_frame_id_;f.config=config_;f.camera=cam;float aspect=float(config_.width)/float(config_.height);f.view=make_view_matrix(cam);f.projection=make_projection_matrix(cam,aspect);f.view_projection=multiply(f.projection,f.view);f.lighting=rt.lighting().settings();auto ls=rt.lighting().active_lights();if(ls.size()>config_.max_lights)return false;for(auto*p:ls)if(p)f.lights.push_back(*p);auto ids=rt.state().entities.ids();std::sort(ids.begin(),ids.end());for(auto id:ids){auto*e=rt.state().entities.get(id);if(!e||!e->active)continue;auto*sn=rt.scene().get(e->scene_node);if(!sn||!sn->active)return false;auto em=make_model_matrix(sn->world);
if(e->geometry){for(std::size_t i=0;i<e->geometry->parts.size();++i){const auto&p=e->geometry->parts[i];if(!p.mesh.valid()||p.material_slot.empty())return false;auto res=rt.material_resource(p.material_slot);if(!res||!res->material.valid()||!res->textures||!res->textures->valid())return false;SceneTransform pt{};pt.position=p.position;pt.scale=p.scale;pt.rotation=p.rotation;auto model=multiply(em,make_model_matrix(pt));auto bounds=transform_bounds(mesh_bounds(p.mesh),model);if(!bounds.valid())return false;if(config_.frustum_culling&&!visible(bounds,f.view_projection))continue;RenderDrawCall d;d.entity_id=id;d.scene_node=e->scene_node;d.pass=res->material.opacity<.999f?RenderPass::Transparent:RenderPass::Opaque;d.geometry=e->geometry;d.part_index=i;d.model=model;d.world_bounds=bounds;d.material.material=res->material;d.material.textures=res->textures;if(!d.valid())return false;f.draws.push_back(std::move(d));}}}
const auto*sm=rt.skinned_mesh(id);const auto*pose=rt.animation_pose(id);const auto*sk=rt.skeleton(id);if(sm||pose||sk){if(!sm||!pose||!sk||!sk->valid()||!pose->valid_for(*sk)||!skinned_payload_valid(*sm))return false;auto material_name=rt.skinned_material(id);auto res=rt.material_resource(material_name);if(!res||!res->material.valid()||!res->textures||!res->textures->valid())return false;if(pose->model.empty()||pose->model.size()>config_.max_bones_per_draw)return false;RenderDrawCall d;d.entity_id=id;d.scene_node=e->scene_node;d.pass=res->material.opacity<.999f?RenderPass::Transparent:RenderPass::Opaque;d.skinned_mesh=std::shared_ptr<const SkinnedMesh>(sm,[](const SkinnedMesh*){});d.model=em;d.world_bounds=transform_bounds(skinned_bounds(*sm),em);d.material.material=res->material;d.material.textures=res->textures;d.bone_palette.reserve(pose->model.size());for(const auto&b:pose->model)d.bone_palette.push_back(anim_matrix(b));if(!d.world_bounds.valid()||!d.valid())return false;f.draws.push_back(std::move(d));}
}
return f.valid();}
RenderResult Renderer::submit(const RenderFrame&f){RenderResult r;if(!validate(f)){r.error="invalid render frame";return r;}if(f.config.backend!=RenderBackend::Headless){r.error="selected GPU backend has no platform implementation in Phase 7";return r;}r.success=true;r.stats.submitted_draws=r.stats.visible_draws=f.draws.size();for(const auto&d:f.draws)if(d.animated())++r.stats.animated_draws;r.stats.submitted_lights=f.lights.size();++next_frame_id_;return r;}
bool Renderer::validate(const RenderFrame&f)const noexcept{return f.valid();}
} // namespace exgine
