#include "exgine/runtime.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <utility>
namespace exgine { namespace {
const Node* terrain_node(const IR& ir){for(const auto& n:ir.root.children)if(n.kind==NodeKind::Terrain)return &n;return nullptr;}
std::int64_t int_prop(const Node*n,std::string_view k,std::int64_t f){if(!n)return f;const auto*p=n->find_property(std::string{k});if(!p)return f;if(auto*v=std::get_if<std::int64_t>(&p->value))return*v;if(auto*v=std::get_if<double>(&p->value))return static_cast<std::int64_t>(*v);return f;}
double float_prop(const Node*n,std::string_view k,double f){if(!n)return f;const auto*p=n->find_property(std::string{k});if(!p)return f;if(auto*v=std::get_if<double>(&p->value))return*v;if(auto*v=std::get_if<std::int64_t>(&p->value))return static_cast<double>(*v);return f;}
}
EntityId EntityRegistry::create(NodeKind k,std::string n){if(next_id_==invalid_entity||next_id_==std::numeric_limits<EntityId>::max())return 0;auto id=next_id_++;entities_.emplace(id,Entity{id,k,std::move(n),{},true,{},nullptr,invalid_scene_node});return id;}bool EntityRegistry::destroy(EntityId id)noexcept{return entities_.erase(id)!=0;}Entity*EntityRegistry::get(EntityId id)noexcept{auto i=entities_.find(id);return i==entities_.end()?nullptr:&i->second;}const Entity*EntityRegistry::get(EntityId id)const noexcept{auto i=entities_.find(id);return i==entities_.end()?nullptr:&i->second;}std::vector<EntityId>EntityRegistry::ids()const{std::vector<EntityId>r;for(auto&x:entities_)r.push_back(x.first);return r;}void EntityRegistry::clear()noexcept{entities_.clear();next_id_=1;}
namespace {bool instantiate(const Node&n,EntityRegistry&r,SceneGraph&s,EntityId&w,SceneNodeId parent){auto id=r.create(n.kind,n.name);if(!id)return false;if(n.kind==NodeKind::World)w=id;auto*e=r.get(id);if(!e)return false;auto sn=s.create(parent);if(!sn)return false;e->scene_node=sn;e->properties=n.properties;for(auto&c:n.children)if(!instantiate(c,r,s,w,sn))return false;return true;}}
bool Runtime::load(const IR&ir){reset();if(ir.root.kind!=NodeKind::World)return false;TerrainConfig c;auto*t=terrain_node(ir);c.amplitude=static_cast<float>(float_prop(t,"amplitude",c.amplitude));c.chunk_size=static_cast<float>(float_prop(t,"chunk_size",c.chunk_size));c.base_frequency=static_cast<float>(float_prop(t,"base_frequency",c.base_frequency));c.detail_frequency=static_cast<float>(float_prop(t,"detail_frequency",c.detail_frequency));c.sea_level=static_cast<float>(float_prop(t,"sea_level",c.sea_level));c.resolution=static_cast<uint32_t>(std::clamp<int64_t>(int_prop(t,"resolution",c.resolution),2,512));c.vegetation_density=static_cast<uint32_t>(std::clamp<int64_t>(int_prop(t,"vegetation_density",c.vegetation_density),0,4096));c.seed=static_cast<uint64_t>(std::max<int64_t>(0,int_prop(t,"seed",static_cast<int64_t>(c.seed))));world_=std::make_unique<ProceduralWorld>(c);streamer_=std::make_unique<WorldStreamer>(*world_);open_streamer_=std::make_unique<OpenWorldStreamer>(*world_);physics_=std::make_unique<PhysicsWorld>();gameplay_=std::make_unique<GameplayWorld>();gameplay_->bind_physics(physics_.get());if(!instantiate(ir.root,state_.entities,scene_,state_.world_entity,scene_.root())){reset();return false;}scene_.update_world_transforms();loaded_=state_.world_entity!=0;return loaded_;}
void Runtime::update(double dt)noexcept{if(!loaded_||dt<0||!std::isfinite(dt))return;scene_.update_world_transforms();if(physics_)static_cast<void>(physics_->step(static_cast<float>(dt)));if(gameplay_)gameplay_->update(static_cast<float>(dt));state_.elapsed_seconds+=dt;++state_.tick;}
bool Runtime::attach_geometry(EntityId id,MeshAssembly g){auto*e=state_.entities.get(id);if(!e||!g.valid())return false;e->geometry=std::make_shared<MeshAssembly>(std::move(g));return true;}
bool Runtime::generate_building(EntityId id,BuildingConfig c){if(!loaded_)return false;auto*e=state_.entities.get(id);if(!e||e->kind!=NodeKind::Building)return false;for(const std::string*s:{&c.wall_material,&c.floor_material,&c.glass_material,&c.door_material,&c.furniture_material})if(!materials_.find(*s))return false;auto d=exgine::generate_building(c);if(!d.valid())return false;e->geometry=std::make_shared<MeshAssembly>(d.geometry);buildings_.insert_or_assign(id,std::move(d));return true;}bool Runtime::set_building_door(EntityId id,uint64_t d,bool o)noexcept{auto i=buildings_.find(id);return i!=buildings_.end()&&set_building_door_open(i->second,d,o);}const BuildingInstance*Runtime::building(EntityId id)const noexcept{auto i=buildings_.find(id);return i==buildings_.end()?nullptr:&i->second;}std::vector<BuildingCollisionVolume>Runtime::building_collision(EntityId id)const{auto i=buildings_.find(id);return i==buildings_.end()?std::vector<BuildingCollisionVolume>{}:active_building_collision(i->second);}const BuildingRoom*Runtime::find_building_room(EntityId id,Vec3 p)const noexcept{auto i=buildings_.find(id);return i==buildings_.end()?nullptr:exgine::find_building_room(i->second,p);}
bool Runtime::generate_vehicle(EntityId id,VehicleConfig c){if(!loaded_)return false;auto*e=state_.entities.get(id);if(!e||e->kind!=NodeKind::Vehicle)return false;for(const std::string*s:{&c.body_material,&c.glass_material,&c.rubber_material,&c.metal_material,&c.interior_material})if(!materials_.find(*s))return false;auto d=exgine::generate_vehicle(c);if(!d.valid())return false;e->geometry=std::make_shared<MeshAssembly>(d.geometry);vehicles_.insert_or_assign(id,std::move(d));return true;}bool Runtime::set_vehicle_door(EntityId id,uint64_t d,bool o)noexcept{auto i=vehicles_.find(id);return i!=vehicles_.end()&&set_vehicle_door_open(i->second,d,o);}const VehicleInstance*Runtime::vehicle(EntityId id)const noexcept{auto i=vehicles_.find(id);return i==vehicles_.end()?nullptr:&i->second;}std::vector<VehicleCollisionVolume>Runtime::vehicle_collision(EntityId id)const{auto i=vehicles_.find(id);return i==vehicles_.end()?std::vector<VehicleCollisionVolume>{}:active_vehicle_collision(i->second);}
bool Runtime::define_material(Material m,TextureGenerationSettings s){if(!loaded_||!m.valid())return false;auto n=m.name;if(!materials_.define(std::move(m)))return false;auto*x=materials_.find(n);auto r=x?build_material_resource(*x,s):nullptr;return r&&resources_.store_material(std::move(r));}bool Runtime::stream_world(Vec3 p,uint32_t r){if(!loaded_||!streamer_)return false;streamer_->update(p,r);return true;}bool Runtime::stream_open_world(Vec3 p)noexcept{return loaded_&&open_streamer_&&open_streamer_->update(p);}bool Runtime::set_main_camera(Camera c)noexcept{return lighting_.set_main_camera(c);}uint64_t Runtime::create_light(Light l){return loaded_?lighting_.create_light(l):0;}bool Runtime::destroy_light(uint64_t id)noexcept{return lighting_.destroy_light(id);}
CharacterId Runtime::create_character(CharacterDefinition d,Vec3 p){return loaded_&&gameplay_?gameplay_->create_character(d,p):0;}bool Runtime::destroy_character(CharacterId id)noexcept{return gameplay_&&gameplay_->destroy_character(id);}bool Runtime::update_character(CharacterId id,CharacterControllerInput in,float dt)noexcept{return gameplay_&&gameplay_->update_character(id,in,dt);}bool Runtime::damage_character(const DamageEvent&e,CombatResult*r)noexcept{return gameplay_&&gameplay_->damage(e,r);}bool Runtime::recover_character(CharacterId id,float a)noexcept{return gameplay_&&gameplay_->recover(id,a);}GameplayWorld*Runtime::gameplay()noexcept{return gameplay_.get();}const GameplayWorld*Runtime::gameplay()const noexcept{return gameplay_.get();}
const Material*Runtime::material(std::string_view n)const noexcept{return materials_.find(n);}std::shared_ptr<const MaterialResource>Runtime::material_resource(std::string_view n)const noexcept{return resources_.find_material(n);}void Runtime::reset()noexcept{gameplay_.reset();state_={};materials_.clear();resources_.clear();buildings_.clear();vehicles_.clear();physics_.reset();open_streamer_.reset();streamer_.reset();world_.reset();scene_.clear();lighting_.clear();loaded_=false;}
}
