#include "exgine/runtime.hpp"
#include <algorithm>
#include <limits>
#include <utility>
namespace exgine { namespace {
const Node* terrain_node(const IR& ir){for(const auto& n:ir.root.children)if(n.kind==NodeKind::Terrain)return &n;return nullptr;}
std::int64_t int_prop(const Node* n,std::string_view key,std::int64_t fallback){if(!n)return fallback;const auto* p=n->find_property(std::string{key});if(!p)return fallback;if(const auto* v=std::get_if<std::int64_t>(&p->value))return *v;if(const auto* v=std::get_if<double>(&p->value))return static_cast<std::int64_t>(*v);return fallback;}
double float_prop(const Node* n,std::string_view key,double fallback){if(!n)return fallback;const auto* p=n->find_property(std::string{key});if(!p)return fallback;if(const auto* v=std::get_if<double>(&p->value))return *v;if(const auto* v=std::get_if<std::int64_t>(&p->value))return static_cast<double>(*v);return fallback;}
}
EntityId EntityRegistry::create(NodeKind kind,std::string name){if(next_id_==invalid_entity||next_id_==std::numeric_limits<EntityId>::max())return invalid_entity;const EntityId id=next_id_++;entities_.emplace(id,Entity{id,kind,std::move(name),{},true,{},nullptr,invalid_scene_node});return id;}
bool EntityRegistry::destroy(EntityId id) noexcept{return entities_.erase(id)!=0;}
Entity* EntityRegistry::get(EntityId id) noexcept{const auto it=entities_.find(id);return it==entities_.end()?nullptr:&it->second;}
const Entity* EntityRegistry::get(EntityId id) const noexcept{const auto it=entities_.find(id);return it==entities_.end()?nullptr:&it->second;}
std::vector<EntityId> EntityRegistry::ids() const{std::vector<EntityId> result;result.reserve(entities_.size());for(const auto& entry:entities_)result.push_back(entry.first);return result;}
void EntityRegistry::clear() noexcept{entities_.clear();next_id_=1;}
namespace {bool instantiate(const Node& n,EntityRegistry& r,SceneGraph& scene,EntityId& world,SceneNodeId parent_scene){const EntityId id=r.create(n.kind,n.name);if(id==invalid_entity)return false;if(n.kind==NodeKind::World)world=id;auto* e=r.get(id);if(!e)return false;const SceneNodeId scene_id=scene.create(parent_scene);if(scene_id==invalid_scene_node)return false;e->scene_node=scene_id;e->properties=n.properties;for(const auto& child:n.children)if(!instantiate(child,r,scene,world,scene_id))return false;return true;}}
bool Runtime::load(const IR& ir){reset();if(ir.root.kind!=NodeKind::World)return false;TerrainConfig cfg;const Node* t=terrain_node(ir);cfg.amplitude=static_cast<float>(float_prop(t,"amplitude",cfg.amplitude));cfg.chunk_size=static_cast<float>(float_prop(t,"chunk_size",cfg.chunk_size));cfg.base_frequency=static_cast<float>(float_prop(t,"base_frequency",cfg.base_frequency));cfg.detail_frequency=static_cast<float>(float_prop(t,"detail_frequency",cfg.detail_frequency));cfg.sea_level=static_cast<float>(float_prop(t,"sea_level",cfg.sea_level));cfg.resolution=static_cast<std::uint32_t>(std::clamp<std::int64_t>(int_prop(t,"resolution",cfg.resolution),2,512));cfg.vegetation_density=static_cast<std::uint32_t>(std::clamp<std::int64_t>(int_prop(t,"vegetation_density",cfg.vegetation_density),0,4096));cfg.seed=static_cast<std::uint64_t>(std::max<std::int64_t>(1,int_prop(t,"seed",static_cast<std::int64_t>(cfg.seed))));world_=std::make_unique<ProceduralWorld>(cfg);streamer_=std::make_unique<WorldStreamer>(*world_);if(!instantiate(ir.root,state_.entities,scene_,state_.world_entity,scene_.root())){reset();return false;}scene_.update_world_transforms();loaded_=state_.world_entity!=invalid_entity;return loaded_;}
void Runtime::update(double dt) noexcept{if(!loaded_||dt<0)return;scene_.update_world_transforms();state_.elapsed_seconds+=dt;++state_.tick;}
bool Runtime::attach_geometry(EntityId id,MeshAssembly g){auto* e=state_.entities.get(id);if(!e||!g.valid())return false;e->geometry=std::make_shared<MeshAssembly>(std::move(g));return true;}
bool Runtime::generate_building(EntityId id,BuildingConfig config){if(!loaded_)return false;auto* e=state_.entities.get(id);if(!e||e->kind!=NodeKind::Building)return false;for(const std::string* slot:{&config.wall_material,&config.floor_material,&config.glass_material,&config.door_material,&config.furniture_material})if(!materials_.find(*slot))return false;auto definition=exgine::generate_building(config);if(!definition.valid())return false;e->geometry=std::make_shared<MeshAssembly>(definition.geometry);buildings_.insert_or_assign(id,std::move(definition));return true;}
bool Runtime::set_building_door(EntityId id,std::uint64_t door_id,bool open) noexcept{auto it=buildings_.find(id);if(it==buildings_.end())return false;return set_building_door_open(it->second,door_id,open);}
const BuildingInstance* Runtime::building(EntityId id) const noexcept{const auto it=buildings_.find(id);return it==buildings_.end()?nullptr:&it->second;}
std::vector<BuildingCollisionVolume> Runtime::building_collision(EntityId id) const{const auto it=buildings_.find(id);if(it==buildings_.end())return {};return active_building_collision(it->second);}
const BuildingRoom* Runtime::find_building_room(EntityId id,Vec3 position) const noexcept{const auto it=buildings_.find(id);if(it==buildings_.end())return nullptr;return exgine::find_building_room(it->second,position);}
bool Runtime::generate_vehicle(EntityId id,VehicleConfig config){if(!loaded_)return false;auto* e=state_.entities.get(id);if(!e||e->kind!=NodeKind::Vehicle)return false;for(const std::string* slot:{&config.body_material,&config.glass_material,&config.rubber_material,&config.metal_material,&config.interior_material})if(!materials_.find(*slot))return false;auto definition=exgine::generate_vehicle(config);if(!definition.valid())return false;e->geometry=std::make_shared<MeshAssembly>(definition.geometry);vehicles_.insert_or_assign(id,std::move(definition));return true;}
bool Runtime::set_vehicle_door(EntityId id,std::uint64_t door_id,bool open) noexcept{auto it=vehicles_.find(id);if(it==vehicles_.end())return false;return set_vehicle_door_open(it->second,door_id,open);}
const VehicleInstance* Runtime::vehicle(EntityId id) const noexcept{const auto it=vehicles_.find(id);return it==vehicles_.end()?nullptr:&it->second;}
std::vector<VehicleCollisionVolume> Runtime::vehicle_collision(EntityId id) const{const auto it=vehicles_.find(id);if(it==vehicles_.end())return {};return active_vehicle_collision(it->second);}
bool Runtime::define_material(Material m,TextureGenerationSettings settings){if(!loaded_||!m.valid())return false;const std::string name=m.name;if(!materials_.define(std::move(m)))return false;const Material* stored=materials_.find(name);if(!stored)return false;auto resource=build_material_resource(*stored,settings);if(!resource)return false;return resources_.store_material(std::move(resource));}
bool Runtime::stream_world(Vec3 focus,std::uint32_t radius){if(!loaded_||!streamer_)return false;streamer_->update(focus,radius);return true;}
bool Runtime::set_main_camera(Camera camera) noexcept{return lighting_.set_main_camera(camera);}
std::uint64_t Runtime::create_light(Light light){if(!loaded_)return 0;return lighting_.create_light(light);}
bool Runtime::destroy_light(std::uint64_t id) noexcept{return lighting_.destroy_light(id);}
const Material* Runtime::material(std::string_view name) const noexcept{return materials_.find(name);} std::shared_ptr<const MaterialResource> Runtime::material_resource(std::string_view name) const noexcept{return resources_.find_material(name);} void Runtime::reset() noexcept{state_={};materials_.clear();resources_.clear();buildings_.clear();vehicles_.clear();streamer_.reset();world_.reset();scene_.clear();lighting_.clear();loaded_=false;}
} // namespace exgine
