#include "exgine/shaders.hpp"
#include <string>
#include <utility>
namespace exgine{namespace{
const char*vs=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=1)in vec3 a_normal;layout(location=2)in vec2 a_uv;uniform mat4 u_view_projection;uniform mat4 u_model;out vec3 v_world;out vec3 v_normal;out vec2 v_uv;void main(){vec4 p=u_model*vec4(a_position,1);v_world=p.xyz;v_normal=normalize(mat3(u_model)*a_normal);v_uv=a_uv;gl_Position=u_view_projection*p;})GLSL";
const char*svs=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=1)in vec3 a_normal;layout(location=2)in vec2 a_uv;layout(location=3)in vec4 a_bone_ids;layout(location=4)in vec4 a_bone_weights;uniform mat4 u_view_projection;uniform mat4 u_model;uniform mat4 u_bones[128];uniform int u_bone_count;out vec3 v_world;out vec3 v_normal;out vec2 v_uv;void main(){mat4 s=mat4(0);float sum=0;for(int i=0;i<4;i++){int id=int(a_bone_ids[i])-1;float w=a_bone_weights[i];if(id>=0&&id<u_bone_count&&w>0){s+=u_bones[id]*w;sum+=w;}}if(sum<=0)s=mat4(1);else if(sum<1)s+=mat4(1)*(1-sum);vec4 p=u_model*s*vec4(a_position,1);v_world=p.xyz;v_normal=normalize(mat3(u_model*s)*a_normal);v_uv=a_uv;gl_Position=u_view_projection*p;})GLSL";
const char*fs=R"GLSL(#version 310 es
precision highp float;out vec4 o;layout(binding=7)uniform sampler2D u_shadow_map;layout(binding=8)uniform samplerCube u_environment_map;layout(binding=9)uniform samplerCube u_ibl_irradiance;uniform vec4 u_base_roughness;uniform vec4 u_metal_specular;uniform vec4 u_emission_opacity;uniform vec3 u_camera_position;uniform float u_ambient_intensity;uniform vec3 u_light_direction;uniform vec3 u_light_color;uniform float u_light_intensity;uniform mat4 u_shadow_vp[4];uniform vec4 u_shadow_splits;uniform int u_shadow_cascade_count;uniform float u_shadow_bias;uniform float u_ibl_intensity;uniform float u_ibl_max_lod;in vec3 v_world;in vec3 v_normal;const float PI=3.14159265;float sat(float x){return clamp(x,0.,1.);}int ci(float d){if(u_shadow_cascade_count<=1)return 0;if(d<=u_shadow_splits.x)return 0;if(d<=u_shadow_splits.y)return 1;if(d<=u_shadow_splits.z)return 2;return 3;}float shadow(vec3 p){float d=length(u_camera_position-p);int c=ci(d);vec4 q=u_shadow_vp[c]*vec4(p,1);if(abs(q.w)<1e-6)return 1;q.xyz/=q.w;vec2 uv=q.xy*.5+.5;uv=uv*.5+vec2((c==1||c==3)?.5:0,(c>=2)?.5:0);float z=q.z*.5+.5;if(any(lessThan(uv,vec2(0)))||any(greaterThan(uv,vec2(1))))return 1;vec2 t=1./vec2(textureSize(u_shadow_map,0));float s=0;for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++)s+=(z-u_shadow_bias<=texture(u_shadow_map,uv+vec2(x,y)*t).r)?1.:0.;return s/9.;}void main(){vec3 n=normalize(v_normal),v=normalize(u_camera_position-v_world),l=normalize(-u_light_direction),h=normalize(v+l);float ndl=sat(dot(n,l)),nv=sat(dot(n,v)),nh=sat(dot(n,h)),vh=sat(dot(v,h));float rough=clamp(u_base_roughness.a,.045,1),metal=sat(u_metal_specular.x);vec3 base=max(u_base_roughness.rgb,vec3(.001)),f0=mix(vec3(.04),base,metal);float a=rough*rough,a2=a*a,den=nh*nh*(a2-1)+1,D=a2/(PI*den*den),k=(rough+1)*(rough+1)/8,Gv=nv/(nv*(1-k)+k),Gl=ndl/(ndl*(1-k)+k);vec3 F=f0+(1-f0)*pow(1-vh,5),spec=(D*Gv*Gl*F)/max(4*nv*max(ndl,.001),.001),kd=(1-F)*(1-metal);float sh=shadow(v_world);vec3 direct=(kd*base/PI+spec)*u_light_color*u_light_intensity*ndl*sh;vec3 irr=texture(u_ibl_irradiance,n).rgb,pre=textureLod(u_environment_map,reflect(-v,n),rough*u_ibl_max_lod);vec3 color=direct+base*u_ambient_intensity+(kd*base*irr+pre*f0)*u_ibl_intensity+u_emission_opacity.rgb;color=color/(color+1);o=vec4(pow(max(color,vec3(0)),vec3(1/2.2)),u_emission_opacity.a);})GLSL";
const char*tfs=R"GLSL(#version 310 es
precision highp float;out vec4 o;layout(binding=7)uniform sampler2D u_shadow_map;layout(binding=8)uniform samplerCube u_environment_map;layout(binding=9)uniform samplerCube u_ibl_irradiance;uniform sampler2D u_base_texture;uniform sampler2D u_roughness_texture;uniform sampler2D u_metallic_texture;uniform sampler2D u_normal_texture;uniform sampler2D u_ao_texture;uniform sampler2D u_emission_texture;uniform sampler2D u_opacity_texture;uniform float u_use_textures;uniform vec4 u_base_roughness;uniform vec4 u_metal_specular;uniform vec4 u_emission_opacity;uniform vec3 u_camera_position;uniform float u_ambient_intensity;uniform vec3 u_light_direction;uniform vec3 u_light_color;uniform float u_light_intensity;uniform mat4 u_shadow_vp[4];uniform vec4 u_shadow_splits;uniform int u_shadow_cascade_count;uniform float u_shadow_bias;uniform float u_ibl_intensity;uniform float u_ibl_max_lod;in vec3 v_world;in vec3 v_normal;in vec2 v_uv;float sat(float x){return clamp(x,0.,1.);}int ci(float d){if(d<=u_shadow_splits.x)return 0;if(d<=u_shadow_splits.y)return 1;if(d<=u_shadow_splits.z)return 2;return 3;}float shad(vec3 p){int c=ci(length(u_camera_position-p));vec4 q=u_shadow_vp[c]*vec4(p,1);q.xyz/=q.w;vec2 uv=q.xy*.5+.5;uv=uv*.5+vec2((c==1||c==3)?.5:0,(c>=2)?.5:0);float z=q.z*.5+.5,t=1./vec2(textureSize(u_shadow_map,0)),s=0;for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++)s+=(z-u_shadow_bias<=texture(u_shadow_map,uv+vec2(x,y)*t).r)?1.:0.;return s/9.;}void main(){vec4 bc=texture(u_base_texture,v_uv);float rough=mix(u_base_roughness.a,texture(u_roughness_texture,v_uv).r,u_use_textures),metal=mix(u_metal_specular.x,texture(u_metallic_texture,v_uv).r,u_use_textures),ao=mix(1,texture(u_ao_texture,v_uv).r,u_use_textures);vec3 base=mix(u_base_roughness.rgb,bc.rgb,u_use_textures),n=normalize(v_normal);vec3 v=normalize(u_camera_position-v_world),l=normalize(-u_light_direction),h=normalize(v+l);float ndl=sat(dot(n,l)),nv=sat(dot(n,v)),nh=sat(dot(n,h)),vh=sat(dot(v,h));rough=max(rough,.045);metal=sat(metal);vec3 f0=mix(vec3(.04),base,metal),F=f0+(1-f0)*pow(1-vh,5);float a=rough*rough,aa=a*a,den=nh*nh*(aa-1)+1,D=aa/(3.14159265*den*den),k=(rough+1)*(rough+1)/8,Gv=nv/(nv*(1-k)+k),Gl=ndl/(ndl*(1-k)+k);vec3 spec=(D*Gv*Gl*F)/max(4*nv*max(ndl,.001),.001),kd=(1-F)*(1-metal);float sh=shad(v_world);vec3 direct=(kd*base/3.14159265+spec)*u_light_color*u_light_intensity*ndl*sh;vec3 irr=texture(u_ibl_irradiance,n).rgb,pre=textureLod(u_environment_map,reflect(-v,n),rough*u_ibl_max_lod).rgb;vec3 color=direct+base*u_ambient_intensity*ao+(kd*base*irr+pre*f0)*u_ibl_intensity+mix(u_emission_opacity.rgb,texture(u_emission_texture,v_uv).rgb,u_use_textures);float alpha=mix(u_emission_opacity.a,texture(u_opacity_texture,v_uv).r,u_use_textures);color=color/(color+1);o=vec4(pow(max(color,vec3(0)),vec3(1/2.2)),sat(alpha));})GLSL";
const char*unlitvs=vs;const char*unlitfs=R"GLSL(#version 310 es
precision highp float;out vec4 o;uniform vec4 u_color;void main(){o=u_color;})GLSL";
}
bool ShaderProgram::valid()const noexcept{return!name.empty()&&!vertex_source.empty()&&!fragment_source.empty();}
ShaderProgram make_pbr_shader(){return{"pbr",vs,fs};}ShaderProgram make_unlit_shader(){return{"unlit",unlitvs,unlitfs};}ShaderProgram make_mobile_pbr_shader(){return{"mobile_pbr",vs,fs};}ShaderProgram make_mobile_skinned_pbr_shader(){return{"mobile_skinned_pbr",svs,fs};}ShaderProgram make_mobile_textured_pbr_shader(){return{"mobile_textured_pbr",vs,tfs};}ShaderProgram make_mobile_skinned_textured_pbr_shader(){return{"mobile_skinned_textured_pbr",svs,tfs};}ShaderLibrary::ShaderLibrary(){for(auto p:{make_pbr_shader(),make_unlit_shader(),make_mobile_pbr_shader(),make_mobile_skinned_pbr_shader(),make_mobile_textured_pbr_shader(),make_mobile_skinned_textured_pbr_shader()})programs_.emplace(p.name,std::move(p));}const ShaderProgram*ShaderLibrary::find(std::string_view n)const noexcept{auto i=programs_.find(std::string(n));return i==programs_.end()?nullptr:&i->second;}
}