#include "exgine/shaders.hpp"
namespace exgine { namespace {
const char* pbr_vs=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=1)in vec3 a_normal;layout(location=2)in vec2 a_uv;layout(std140,binding=0)uniform Camera{mat4 u_view_projection;};uniform mat4 u_model;out vec3 v_world_position;out vec3 v_normal;out vec2 v_uv;void main(){vec4 p=u_model*vec4(a_position,1.);v_world_position=p.xyz;v_normal=normalize(mat3(u_model)*a_normal);v_uv=a_uv;gl_Position=u_view_projection*p;}
)GLSL";
const char* pbr_fs=R"GLSL(#version 310 es
precision highp float;layout(location=0)out vec4 o_color;struct Light{vec4 position_type;vec4 direction_intensity;vec4 color_range;};layout(std140,binding=1)uniform Lights{Light u_lights[256];uint u_light_count;};layout(std140,binding=2)uniform Material{vec4 u_base_roughness;vec4 u_metal_specular;vec4 u_emission_opacity;};uniform vec3 u_camera_position;uniform float u_ambient_intensity;in vec3 v_world_position;in vec3 v_normal;in vec2 v_uv;const float PI=3.14159265359;float saturate(float x){return clamp(x,0.,1.);}vec3 fresnel(vec3 f0,float c){return f0+(1.-f0)*pow(1.-c,5.);}void main(){vec3 n=normalize(v_normal);vec3 v=normalize(u_camera_position-v_world_position);vec3 base=u_base_roughness.rgb;float rough=max(u_base_roughness.a,.045);float metallic=saturate(u_metal_specular.x);vec3 f0=mix(vec3(.04),base,metallic);vec3 lo=vec3(0);for(uint i=0u;i<u_light_count&&i<256u;++i){Light l=u_lights[i];vec3 L=l.position_type.w<.5?normalize(-l.direction_intensity.xyz):normalize(l.position_type.xyz-v_world_position);float dist=length(l.position_type.xyz-v_world_position);float att=l.position_type.w<.5?1.:saturate(1.-dist/max(l.color_range.w,.001));float ndl=saturate(dot(n,L));if(ndl<=0.)continue;vec3 h=normalize(v+L);float ndh=saturate(dot(n,h));float vdh=saturate(dot(v,h));float a=rough*rough,a2=a*a,den=ndh*ndh*(a2-1.)+1.;float D=a2/(PI*den*den),k=(rough+1.)*(rough+1.)/8.,nv=saturate(dot(n,v));float Gv=nv/(nv*(1.-k)+k),Gl=ndl/(ndl*(1.-k)+k);vec3 F=fresnel(f0,vdh);vec3 spec=(D*Gv*Gl*F)/max(4.*nv*ndl,.001);vec3 kd=(1.-F)*(1.-metallic);lo+=(kd*base/PI+spec)*l.color_range.rgb*l.direction_intensity.w*ndl*att;}vec3 color=lo+base*u_ambient_intensity+u_emission_opacity.rgb;color=color/(color+1.);color=pow(max(color,vec3(0)),vec3(1./2.2));o_color=vec4(color,saturate(u_emission_opacity.a));}
)GLSL";
const char* mobile_vs=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=1)in vec3 a_normal;layout(location=2)in vec2 a_uv;uniform mat4 u_view_projection;uniform mat4 u_model;uniform float u_time;uniform float u_water;out vec3 v_normal;out vec3 v_world_position;out vec2 v_uv;void main(){vec3 local=a_position;if(u_water>.5){float w1=sin(local.x*.75+u_time*1.35);float w2=cos(local.z*1.10-u_time*.92);float w3=sin((local.x+local.z)*1.8+u_time*.55);local.y+=(w1+w2*.55+w3*.2)*.045;}vec4 p=u_model*vec4(local,1.);v_world_position=p.xyz;v_normal=normalize(mat3(u_model)*a_normal);v_uv=a_uv;gl_Position=u_view_projection*p;}
)GLSL";
const char* mobile_fs=R"GLSL(#version 310 es
precision highp float;layout(location=0)out vec4 o_color;uniform vec4 u_base_roughness;uniform vec4 u_metal_specular;uniform vec4 u_emission_opacity;uniform vec3 u_camera_position;uniform float u_ambient_intensity;uniform vec3 u_light_direction;uniform vec3 u_light_color;uniform float u_light_intensity;in vec3 v_normal;in vec3 v_world_position;in vec2 v_uv;void main(){vec3 n=normalize(v_normal),l=normalize(-u_light_direction);float ndl=max(dot(n,l),0.);vec3 base=u_base_roughness.rgb;float metallic=clamp(u_metal_specular.x,0.,1.);vec3 f0=mix(vec3(.04),base,metallic);vec3 v=normalize(u_camera_position-v_world_position),h=normalize(l+v);float spec=pow(max(dot(n,h),0.),mix(64.,4.,u_base_roughness.a))*mix(.04,1.,metallic);vec3 color=base*(u_ambient_intensity+ndl*u_light_intensity*u_light_color)+f0*spec+u_emission_opacity.rgb;color=color/(color+1.);color=pow(max(color,vec3(0)),vec3(1./2.2));o_color=vec4(color,clamp(u_emission_opacity.a,0.,1.));}
)GLSL";
const char* textured_fs=R"GLSL(#version 310 es
precision highp float;layout(location=0)out vec4 o_color;uniform vec4 u_base_roughness;uniform vec4 u_metal_specular;uniform vec4 u_emission_opacity;uniform vec3 u_camera_position;uniform float u_ambient_intensity;uniform vec3 u_light_direction;uniform vec3 u_light_color;uniform float u_light_intensity;uniform sampler2D u_base_texture;uniform sampler2D u_roughness_texture;uniform sampler2D u_metallic_texture;uniform sampler2D u_normal_texture;uniform sampler2D u_ao_texture;uniform sampler2D u_emission_texture;uniform sampler2D u_opacity_texture;uniform float u_use_textures;in vec3 v_normal;in vec3 v_world_position;in vec2 v_uv;const float PI=3.14159265359;float sat(float x){return clamp(x,0.,1.);}vec3 F(vec3 f0,float c){return f0+(1.-f0)*pow(1.-c,5.);}mat3 tbn(vec3 n){vec3 dp1=dFdx(v_world_position),dp2=dFdy(v_world_position);vec2 duv1=dFdx(v_uv),duv2=dFdy(v_uv);float den=duv1.x*duv2.y-duv1.y*duv2.x;vec3 t;if(abs(den)>1e-5)t=normalize((dp1*duv2.y-dp2*duv1.y)/den);else{vec3 a=abs(n.y)<.9?vec3(0,1,0):vec3(1,0,0);t=normalize(cross(a,n));}vec3 b=normalize(cross(n,t));return mat3(t,b,n);}void main(){vec3 n=normalize(v_normal);vec4 base_sample=texture(u_base_texture,v_uv);float rough_tex=texture(u_roughness_texture,v_uv).r;float metal_tex=texture(u_metallic_texture,v_uv).r;float ao=texture(u_ao_texture,v_uv).r;vec3 normal_sample=texture(u_normal_texture,v_uv).xyz*2.-1.;vec3 emission_sample=texture(u_emission_texture,v_uv).rgb;float opacity_sample=texture(u_opacity_texture,v_uv).r;vec3 base=mix(u_base_roughness.rgb,base_sample.rgb,u_use_textures);float rough=mix(u_base_roughness.a,rough_tex,u_use_textures);float metallic=mix(u_metal_specular.x,metal_tex,u_use_textures);if(u_use_textures>.5)n=normalize(tbn(n)*normalize(normal_sample));vec3 v=normalize(u_camera_position-v_world_position),l=normalize(-u_light_direction),h=normalize(v+l);float ndl=sat(dot(n,l)),ndl2=max(ndl,.0001),nv=sat(dot(n,v)),ndh=sat(dot(n,h)),vdh=sat(dot(v,h));rough=max(rough,.045);float a=rough*rough,a2=a*a,den=ndh*ndh*(a2-1.)+1.;float D=a2/(PI*den*den),k=(rough+1.)*(rough+1.)/8.;float Gv=nv/(nv*(1.-k)+k),Gl=ndl2/(ndl2*(1.-k)+k);vec3 f0=mix(vec3(.04),base,clamp(metallic,0.,1.));vec3 spec=(D*Gv*Gl*F(f0,vdh))/max(4.*nv*ndl2,.001);vec3 kd=(1.-F(f0,vdh))*(1.-clamp(metallic,0.,1.));vec3 direct=(kd*base/PI+spec)*u_light_color*u_light_intensity*ndl;vec3 emission=mix(u_emission_opacity.rgb,emission_sample,u_use_textures);float alpha=mix(u_emission_opacity.a,opacity_sample,u_use_textures);vec3 color=direct+base*u_ambient_intensity*mix(1.,ao,u_use_textures)+emission;color=color/(color+1.);color=pow(max(color,vec3(0)),vec3(1./2.2));o_color=vec4(color,sat(alpha));}
)GLSL";
const char* skinned_vs=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=1)in vec3 a_normal;layout(location=2)in vec2 a_uv;layout(location=3)in vec4 a_bone_ids;layout(location=4)in vec4 a_bone_weights;uniform mat4 u_view_projection;uniform mat4 u_model;uniform mat4 u_bones[128];uniform int u_bone_count;out vec3 v_normal;out vec3 v_world_position;out vec2 v_uv;void main(){vec4 local_p=vec4(a_position,1.);vec3 local_n=a_normal;mat4 skin=mat4(0.);float weight_sum=0.;for(int i=0;i<4;++i){float w=a_bone_weights[i];int id=int(a_bone_ids[i])-1;if(w>0.&&id>=0&&id<u_bone_count){skin+=u_bones[id]*w;weight_sum+=w;}}if(weight_sum<=0.)skin=mat4(1.);else if(weight_sum<1.)skin+=mat4(1.)*(1.-weight_sum);vec4 p=u_model*skin*local_p;v_world_position=p.xyz;v_normal=normalize(mat3(u_model*skin)*local_n);v_uv=a_uv;gl_Position=u_view_projection*p;}
)GLSL";
const char* unlit_vs=R"GLSL(#version 310 es
precision highp float;layout(location=0)in vec3 a_position;layout(location=2)in vec2 a_uv;layout(std140,binding=0)uniform Camera{mat4 u_view_projection;};uniform mat4 u_model;out vec2 v_uv;void main(){v_uv=a_uv;gl_Position=u_view_projection*u_model*vec4(a_position,1.);}
)GLSL";
const char* unlit_fs=R"GLSL(#version 310 es
precision highp float;layout(location=0)out vec4 o_color;uniform vec4 u_color;void main(){o_color=u_color;}
)GLSL";
}
bool ShaderProgram::valid()const noexcept{return !name.empty()&&!vertex_source.empty()&&!fragment_source.empty()&&vertex_source.find("#version 310 es")!=std::string::npos&&fragment_source.find("#version 310 es")!=std::string::npos;}
ShaderProgram make_pbr_shader(){return {"pbr",pbr_vs,pbr_fs};} ShaderProgram make_unlit_shader(){return {"unlit",unlit_vs,unlit_fs};} ShaderProgram make_mobile_pbr_shader(){return {"mobile_pbr",mobile_vs,mobile_fs};} ShaderProgram make_mobile_skinned_pbr_shader(){return {"mobile_skinned_pbr",skinned_vs,mobile_fs};} ShaderProgram make_mobile_textured_pbr_shader(){return {"mobile_textured_pbr",mobile_vs,textured_fs};} ShaderProgram make_mobile_skinned_textured_pbr_shader(){return {"mobile_skinned_textured_pbr",skinned_vs,textured_fs};}
ShaderLibrary::ShaderLibrary(){auto p=make_pbr_shader(),u=make_unlit_shader();if(p.valid())programs_.emplace(p.name,std::move(p));if(u.valid())programs_.emplace(u.name,std::move(u));}
const ShaderProgram* ShaderLibrary::find(std::string_view name)const noexcept{auto it=programs_.find(std::string{name});return it==programs_.end()?nullptr:&it->second;}
}
