#include "exgine/showcase.hpp"
#include <algorithm>
#include <chrono>
#include <cstring>
#include <vector>
namespace exgine { namespace {
EntityId find_entity(const Runtime&r,std::string_view n){for(auto id:r.state().entities.ids()){auto*e=r.state().entities.get(id);if(e&&e->name==n)return id;}return invalid_entity;}
void put32(std::vector<std::uint8_t>&b,std::uint32_t v){for(int i=0;i<4;++i)b.push_back(static_cast<std::uint8_t>(v>>(8*i)));}
void putf(std::vector<std::uint8_t>&b,float v){std::uint32_t x;std::memcpy(&x,&v,4);put32(b,x);}
bool get32(const std::vector<std::uint8_t>&b,std::size_t&p,std::uint32_t&v){if(p+4>b.size())return false;v=static_cast<std::uint32_t>(b[p])|(static_cast<std::uint32_t>(b[p+1])<<8)|(static_cast<std::uint32_t>(b[p+2])<<16)|(static_cast<std::uint32_t>(b[p+3])<<24);p+=4;return true;}
bool getf(const std::vector<std::uint8_t>&b,std::size_t&p,float&v){std::uint32_t x;if(!get32(b,p,x))return false;std::memcpy(&v,&x,4);return true;}
MeshAssembly box_mesh(Vec3 s,std::string m){MeshAssembly a;a.parts.push_back({"mesh",make_box({s}),std::move(m),{},{1,1,1},{}});return a;}
MeshAssembly quad_mesh(float w,float h,std::string m){Mesh x;x.vertices={{{-w*.5f,-h*.5f,0},{0,0,1},{0,0}},{{w*.5f,-h*.5f,0},{0,0,1},{1,0}},{{w*.5f,h*.5f,0},{0,0,1},{1,1}},{{-w*.5f,h*.5f,0},{0,0,1},{0,1}}};x.indices={0,1,2,0,2,3};MeshAssembly a;a.parts.push_back({"quad",std::move(x),std::move(m),{},{1,1,1},{}});return a;}
MeshAssembly rain_mesh(const std::vector<ParticleState>&p){MeshAssembly a;Mesh m;m.vertices.reserve(p.size()*4);m.indices.reserve(p.size()*6);std::uint32_t b=0;for(const auto&s:p){const float w=.01f;const float h=std::min(-.12f,s.velocity.y*.02f);m.vertices.push_back({{s.position.x-w,s.position.y,s.position.z},{0,1,0},{0,0}});m.vertices.push_back({{s.position.x+w,s.position.y,s.position.z},{0,1,0},{1,0}});m.vertices.push_back({{s.position.x+w,s.position.y+h,s.position.z},{0,1,0},{1,1}});m.vertices.push_back({{s.position.x-w,s.position.y+h,s.position.z},{0,1,0},{0,1}});m.indices.insert(m.indices.end(),{b,b+1,b+2,b,b+2,b+3});b+=4;}if(m.valid())a.parts.push_back({"rain",std::move(m),"rain",{},{1,1,1},{}});return a;}
}
ShowcaseGame::ShowcaseGame(FileLoader loader):loader_(std::move(loader)),game_({},loader_){}
bool ShowcaseGame::open(std::string_view manifest){metrics_={};ready_=configured_=false;if(!game_.open_project(manifest)||!configure_world()||!load_authored_asset()||!create_physics_probe()||!configure_ui())return false;rain_emitter_=particles_.create({ParticleKind::Rain,{7,9,5},{0,-1,0},180,2,15,.025f,256,0x53484f57ULL});if(!rain_emitter_)return false;if(!audio_.create_source({0,invalid_asset,{5,2,5},{},.35f,1,1,50,true,true,true}))return false;audio_.set_listener({{7.5f,5.2f,12},{},{0,0,-1},{0,1,0}});weather_.update(game_.session().game().environment().state(),0);configured_=true;return game_.show_menu();}
bool ShowcaseGame::start()noexcept{ready_=configured_&&game_.start();return ready_;}
bool ShowcaseGame::configure_world(){auto&r=game_.session().game().runtime();if(!r.world()||!r.physics())return false;Camera c;c.position={7.5f,5.2f,12};c.rotation={-.18f,.53f,0};c.vertical_fov_degrees=58;c.near_plane=.05f;c.far_plane=3000;if(!r.set_main_camera(c))return false;Light sun;sun.type=LightType::Directional;sun.direction={-.45f,-.78f,-.2f};sun.color={1,.92f,.78f};sun.intensity=4;sun.shadow_mode=ShadowMode::Cascaded;if(!r.create_light(sun))return false;Light fill;fill.type=LightType::Point;fill.position={5,4,5};fill.color={.55f,.68f,1};fill.intensity=18;fill.range=20;if(!r.create_light(fill))return false;return r.define_material(make_real_world_material("showcase_surface",42))&&r.define_material(make_real_world_material("rain",77))&&r.define_material(make_real_world_material("hud",91));}
bool ShowcaseGame::load_authored_asset(){auto&r=game_.session().game().runtime();prop_entity_=find_entity(r,"HouseAsset");rain_entity_=find_entity(r,"RainFX");if(!prop_entity_||!rain_entity_||!loader_)return false;std::string obj,ppm;if(!loader_("showcase/assets/house.obj",obj)||!loader_("showcase/assets/house.ppm",ppm))return false;std::vector<std::uint8_t>bytes(ppm.begin(),ppm.end());ImageData image;std::string err;if(!images_.decode("house.ppm",bytes,image,err)||!image.valid())return false;return assets_.import_and_attach(r,prop_entity_,"showcase/assets/house.obj",obj,"showcase_surface").success;}
bool ShowcaseGame::create_physics_probe(){auto*p=game_.session().game().runtime().physics();if(!p)return false;PhysicsRigidBodyDesc d;d.type=PhysicsBodyType::Dynamic;d.transform.position={2,5,2};d.mass_properties.mass=30;d.mass_properties.diagonal_inertia={10,10,10};d.flags=static_cast<std::uint32_t>(PhysicsBodyFlag::StartAwake)|static_cast<std::uint32_t>(PhysicsBodyFlag::AllowSleep);physics_body_=p->create_body(d);if(!physics_body_)return false;PhysicsColliderDesc c;c.shape.type=PhysicsShapeType::Box;c.shape.data=PhysicsBoxShape{{.5f,.5f,.5f}};c.material.static_friction=.8f;c.material.dynamic_friction=.65f;if(p->add_collider(physics_body_,c)==invalid_physics_collider)return false;const auto id=find_entity(game_.session().game().runtime(),"PhysicsCrate");return id&&game_.session().game().runtime().attach_geometry(id,box_mesh({1,1,1},"showcase_surface"));}
bool ShowcaseGame::configure_ui(){crosshair_widget_=ui_.create(UiWidgetType::Label);health_widget_=ui_.create(UiWidgetType::Progress);if(!crosshair_widget_||!health_widget_||!ui_.set_text(crosshair_widget_,"+")||!ui_.set_value(health_widget_,1))return false;auto&r=game_.session().game().runtime();const auto c=find_entity(r,"HUDCrosshair"),h=find_entity(r,"HUDHealth");if(!c||!h)return false;return r.attach_geometry(c,quad_mesh(.18f,.18f,"hud"))&&r.attach_geometry(h,quad_mesh(2.4f,.12f,"hud"));}
void ShowcaseGame::update_physics_state(float)noexcept{auto*p=game_.session().game().runtime().physics();if(!p||!physics_body_)return;const auto t=p->body_transform(physics_body_);const auto id=find_entity(game_.session().game().runtime(),"PhysicsCrate");if(!t||!id)return;auto*e=game_.session().game().runtime().state().entities.get(id);if(!e)return;e->transform={t->position.x,t->position.y,t->position.z};(void)game_.session().game().runtime().scene().set_local_transform(e->scene_node,{t->position,t->rotation,{1,1,1}});}
void ShowcaseGame::update_weather_mesh()noexcept{const auto*p=particles_.particles(rain_emitter_);if(!p||rain_entity_==invalid_entity)return;auto a=rain_mesh(*p);if(a.valid())(void)game_.session().game().runtime().attach_geometry(rain_entity_,std::move(a));}
bool ShowcaseGame::update(double dt)noexcept{if(!ready_||dt<0)return false;const auto t0=std::chrono::steady_clock::now();if(!game_.update(dt))return false;(void)particles_.update(rain_emitter_,static_cast<float>(dt));update_weather_mesh();update_physics_state(static_cast<float>(dt));weather_.update(game_.session().game().environment().state(),0);const auto mix=audio_.mix(static_cast<float>(dt));if(!mix.empty())(void)audio_runtime_.evaluate(audio_.listener(),{mix.front().clip,mix.front().position,mix.front().gain,mix.front().pitch,mix.front().max_distance,mix.front().looping},.1f);++metrics_.frames;metrics_.stream_results=game_.session().stats().stream_results;metrics_.weather_particles=particles_.particles(rain_emitter_)?particles_.particles(rain_emitter_)->size():0;metrics_.audio_sources=mix.size();metrics_.ui_widgets=ui_.visible_widgets().size();metrics_.physics_steps=game_.session().game().runtime().state().tick;const auto t1=std::chrono::steady_clock::now();const double ms=std::chrono::duration<double,std::milli>(t1-t0).count();metrics_.total_frame_ms+=ms;metrics_.max_frame_ms=std::max(metrics_.max_frame_ms,ms);return true;}
bool ShowcaseGame::build_frame(RenderFrame&f,RenderResult&r)noexcept{if(!ready_)return false;Renderer renderer({RenderBackend::Headless,1280,720,true,true,256,128});if(!renderer.build_frame(game_.session().game().runtime(),f))return false;r=renderer.submit(f);if(r.success){++metrics_.rendered_frames;metrics_.draw_calls+=r.stats.submitted_draws;metrics_.visible_draws+=r.stats.visible_draws;}return r.success;}
bool ShowcaseGame::present(AndroidEglPresenter&p)noexcept{if(!ready_)return false;RenderFrame f;Renderer renderer({RenderBackend::OpenGLES,1280,720,true,true,256,128});if(!renderer.build_frame(game_.session().game().runtime(),f)||!renderer.validate(f))return false;return p.present(f);}
std::vector<std::uint8_t> ShowcaseGame::save(){const auto game=game_.save();std::vector<std::uint8_t>b={'X','G','S','H',1};put32(b,static_cast<std::uint32_t>(game.size()));b.insert(b.end(),game.begin(),game.end());auto*p=game_.session().game().runtime().physics();const auto t=p&&physics_body_?p->body_transform(physics_body_):std::nullopt;b.push_back(t?1:0);if(t){putf(b,t->position.x);putf(b,t->position.y);putf(b,t->position.z);putf(b,t->rotation.x);putf(b,t->rotation.y);putf(b,t->rotation.z);}return b;}
bool ShowcaseGame::restore(const std::vector<std::uint8_t>&b)noexcept{if(b.size()<10||std::memcmp(b.data(),"XGSH",4)!=0||b[4]!=1)return false;std::size_t p=5;std::uint32_t n=0;if(!get32(b,p,n)||p+n>b.size())return false;std::vector<std::uint8_t>g(b.begin()+static_cast<std::ptrdiff_t>(p),b.begin()+static_cast<std::ptrdiff_t>(p+n));p+=n;if(!game_.restore(g))return false;if(p>=b.size())return true;if(b[p++]){float x,y,z,rx,ry,rz;if(!getf(b,p,x)||!getf(b,p,y)||!getf(b,p,z)||!getf(b,p,rx)||!getf(b,p,ry)||!getf(b,p,rz))return false;auto*ph=game_.session().game().runtime().physics();if(ph&&physics_body_)return ph->set_body_transform(physics_body_,{{x,y,z},{rx,ry,rz}},true);}return true;}
} // namespace exgine
