#include "exgine/texture.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
namespace exgine { namespace {
std::uint32_t hash2(std::int32_t x,std::int32_t y,std::uint64_t seed)noexcept{std::uint64_t h=seed+static_cast<std::uint64_t>(static_cast<std::uint32_t>(x))*0x9e3779b9U;h^=static_cast<std::uint64_t>(static_cast<std::uint32_t>(y))*0x85ebca6bU;h^=h>>16;h*=0x7feb352dU;h^=h>>15;h*=0x846ca68bU;h^=h>>16;return static_cast<std::uint32_t>(h);}
float random2(std::int32_t x,std::int32_t y,std::uint64_t seed)noexcept{return static_cast<float>(hash2(x,y,seed))/static_cast<float>(std::numeric_limits<std::uint32_t>::max());}
float smooth(float t)noexcept{return t*t*(3.0f-2.0f*t);} float lerp(float a,float b,float t)noexcept{return a+(b-a)*t;}
float value_noise(float x,float y,std::uint64_t seed)noexcept{const auto ix=static_cast<std::int32_t>(std::floor(x)),iy=static_cast<std::int32_t>(std::floor(y));const float fx=smooth(x-ix),fy=smooth(y-iy);return lerp(lerp(random2(ix,iy,seed),random2(ix+1,iy,seed),fx),lerp(random2(ix,iy+1,seed),random2(ix+1,iy+1,seed),fx),fy)*2.0f-1.0f;}
float perlin_noise(float x,float y,std::uint64_t seed)noexcept{const auto ix=static_cast<std::int32_t>(std::floor(x)),iy=static_cast<std::int32_t>(std::floor(y));const float fx=x-ix,fy=y-iy;auto grad=[seed](std::int32_t gx,std::int32_t gy,float dx,float dy){const float a=random2(gx,gy,seed)*6.28318530718f;return std::cos(a)*dx+std::sin(a)*dy;};const float sx=smooth(fx),sy=smooth(fy);return lerp(lerp(grad(ix,iy,fx,fy),grad(ix+1,iy,fx-1,fy),sx),lerp(grad(ix,iy+1,fx,fy-1),grad(ix+1,iy+1,fx-1,fy-1),sx),sy)*1.41421356f;}
float voronoi_noise(float x,float y,std::uint64_t seed)noexcept{const auto ix=static_cast<std::int32_t>(std::floor(x)),iy=static_cast<std::int32_t>(std::floor(y));float nearest=2.0f;for(std::int32_t oy=-1;oy<=1;++oy)for(std::int32_t ox=-1;ox<=1;++ox){const float px=ox+random2(ix+ox,iy+oy,seed),py=oy+random2(ix+ox,iy+oy,seed+17);const float dx=px-(x-ix),dy=py-(y-iy);nearest=std::min(nearest,std::sqrt(dx*dx+dy*dy));}return 1.0f-std::clamp(nearest,0.0f,1.0f);}
float base_noise(float x,float y,const NoiseSettings&s)noexcept{switch(s.type){case NoiseType::Value:return value_noise(x,y,s.seed);case NoiseType::Perlin:return perlin_noise(x,y,s.seed);case NoiseType::Simplex:return perlin_noise(x*.97f+y*.23f,y*.97f-x*.23f,s.seed+31);case NoiseType::Voronoi:return voronoi_noise(x,y,s.seed)*2.0f-1.0f;default:return value_noise(x,y,s.seed);}}
float clamp01(float v)noexcept{return std::clamp(v,0.0f,1.0f);}
std::shared_ptr<Texture2D> solid(std::uint32_t channels,float a,float b,float c=0,float d=1){auto t=std::make_shared<Texture2D>();t->width=t->height=1;t->channels=channels;t->format=channels==1?TextureFormat::R32F:channels==2?TextureFormat::RG32F:channels==3?TextureFormat::RGB32F:TextureFormat::RGBA32F;t->data.resize(channels);const float v[4]={a,b,c,d};for(std::uint32_t i=0;i<channels;++i)t->data[i]=v[i];return t;}
}
bool Texture2D::valid()const noexcept{if(width==0||height==0||channels==0)return false;return data.size()==static_cast<std::size_t>(width)*height*channels;}
std::size_t Texture2D::index(std::uint32_t x,std::uint32_t y,std::uint32_t channel)const noexcept{return(static_cast<std::size_t>(y)*width+x)*channels+channel;}
float Texture2D::get(std::uint32_t x,std::uint32_t y,std::uint32_t channel)const noexcept{if(!valid()||x>=width||y>=height||channel>=channels)return 0;return data[index(x,y,channel)];}
void Texture2D::set(std::uint32_t x,std::uint32_t y,std::uint32_t channel,float value)noexcept{if(!valid()||x>=width||y>=height||channel>=channels)return;data[index(x,y,channel)]=value;}
bool TextureSet::valid()const noexcept{
    if(!base_color||!base_color->valid())return false;
    const auto compatible=[&](const std::shared_ptr<Texture2D>&t){return !t||(t->valid()&&t->width==base_color->width&&t->height==base_color->height);};
    return compatible(roughness)&&compatible(metallic)&&compatible(normal)&&compatible(ambient_occlusion)&&compatible(emission)&&compatible(opacity)&&compatible(height);
}
float sample_noise(float x,float y,const NoiseSettings&s)noexcept{const float scale=std::max(s.scale,1e-5f);x*=scale;y*=scale;if(s.type==NoiseType::Fbm||s.type==NoiseType::Ridged||s.type==NoiseType::Turbulence){float amplitude=1,frequency=1,sum=0,weight=0;const auto octaves=std::max(s.octaves,1u);for(std::uint32_t i=0;i<octaves;++i){float n=base_noise(x*frequency,y*frequency,{NoiseType::Perlin,1,1,.5f,2,s.seed+i*101});if(s.type==NoiseType::Ridged)n=1-std::abs(n);if(s.type==NoiseType::Turbulence)n=std::abs(n);sum+=n*amplitude;weight+=amplitude;amplitude*=std::clamp(s.persistence,0.f,1.f);frequency*=std::max(s.lacunarity,1.01f);}return weight>0?sum/weight:0;}return base_noise(x,y,s);}
Texture2D generate_noise_texture(const TextureGenerationSettings&s,std::uint32_t channels){Texture2D t;t.width=std::max(s.width,1u);t.height=std::max(s.height,1u);t.channels=std::max(channels,1u);t.format=t.channels==1?TextureFormat::R32F:t.channels==2?TextureFormat::RG32F:t.channels==3?TextureFormat::RGB32F:TextureFormat::RGBA32F;t.data.resize(static_cast<std::size_t>(t.width)*t.height*t.channels);for(std::uint32_t y=0;y<t.height;++y)for(std::uint32_t x=0;x<t.width;++x){const float u=float(x)/float(t.width-1+(t.width==1)),v=float(y)/float(t.height-1+(t.height==1));const float n=clamp01(sample_noise(u,v,s.noise)*.5f+.5f);for(std::uint32_t c=0;c<t.channels;++c)t.data[t.index(x,y,c)]=n;}return t;}
TextureSet generate_material_textures(const Material&m,const TextureGenerationSettings&s){auto make=[&](std::uint32_t c){auto t=std::make_shared<Texture2D>();t->width=std::max(s.width,1u);t->height=std::max(s.height,1u);t->channels=c;t->format=c==1?TextureFormat::R32F:c==3?TextureFormat::RGB32F:TextureFormat::RGBA32F;t->data.resize(static_cast<std::size_t>(t->width)*t->height*c);return t;};TextureSet o{make(3),make(1),make(1),make(3),make(1),make(3),make(1),make(1)};for(std::uint32_t y=0;y<o.base_color->height;++y)for(std::uint32_t x=0;x<o.base_color->width;++x){const float u=float(x)/float(o.base_color->width-1+(o.base_color->width==1)),v=float(y)/float(o.base_color->height-1+(o.base_color->height==1));float n=clamp01(sample_noise(u,v,s.noise)*.5f+.5f),rough=m.roughness,metal=m.metallic,height=n;for(const auto&l:m.layers){auto ns=s.noise;ns.scale=std::max(l.scale,.001f);ns.seed^=l.seed;const float lv=sample_noise(u,v,ns)*.5f+.5f;if(l.generator=="grain"||l.generator=="noise"||l.generator=="fbm"){n=clamp01(n+(lv-.5f)*l.strength);rough=clamp01(rough+(lv-.5f)*l.strength*.5f);height=clamp01(height+(lv-.5f)*l.strength);}else if(l.generator=="scratches"||l.generator=="cracks"){const float mark=lv>.72f?l.strength:0;rough=clamp01(rough+mark);height=clamp01(height-mark*.25f);}else if(l.generator=="oxidation")metal=clamp01(metal-lv*l.strength*.2f);}const float albedo[3]={clamp01(m.base_color.r*(.82f+.36f*n)),clamp01(m.base_color.g*(.82f+.36f*n)),clamp01(m.base_color.b*(.82f+.36f*n))};for(std::uint32_t c=0;c<3;++c)o.base_color->data[o.base_color->index(x,y,c)]=albedo[c];o.roughness->data[o.roughness->index(x,y)]=rough;o.metallic->data[o.metallic->index(x,y)]=metal;o.ambient_occlusion->data[o.ambient_occlusion->index(x,y)]=1;o.height->data[o.height->index(x,y)]=height;o.opacity->data[o.opacity->index(x,y)]=clamp01(m.opacity);for(std::uint32_t c=0;c<3;++c)o.emission->data[o.emission->index(x,y,c)]=c==0?m.emission.r:c==1?m.emission.g:m.emission.b;o.normal->data[o.normal->index(x,y,0)]=.5f;o.normal->data[o.normal->index(x,y,1)]=.5f;o.normal->data[o.normal->index(x,y,2)]=1;}return o;}
} // namespace exgine
