#include "exgine/vehicle.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <limits>
#include <string>
#include <utility>

namespace exgine {
namespace {
constexpr float kPi=3.14159265358979323846f;
std::uint64_t mix64(std::uint64_t v) noexcept{v+=0x9e3779b97f4a7c15ULL;v=(v^(v>>30U))*0xbf58476d1ce4e5b9ULL;v=(v^(v>>27U))*0x94d049bb133111ebULL;return v^(v>>31U);}
float unit(std::uint64_t v) noexcept{return static_cast<float>(mix64(v)>>40U)/static_cast<float>(1U<<24U);}
bool finite(float v) noexcept{return std::isfinite(v);}bool finite(Vec3 v) noexcept{return finite(v.x)&&finite(v.y)&&finite(v.z);}
std::uint64_t stable_id(std::uint64_t seed,std::uint64_t domain,std::uint64_t index) noexcept{return mix64(seed^mix64(domain)^mix64(index))|1ULL;}
void add_box(MeshAssembly&a,std::string name,Vec3 size,const std::string&m,Vec3 p,Vec3 r={}){if(size.x<=0||size.y<=0||size.z<=0||m.empty())return;MeshPart part{std::move(name),make_box({size}),m,p,{1,1,1},r};if(part.mesh.valid())a.parts.push_back(std::move(part));}
void add_cylinder(MeshAssembly&a,std::string name,float radius,float height,const std::string&m,Vec3 p,Vec3 r={0,kPi*.5f,0}){if(radius<=0||height<=0||m.empty())return;MeshPart part{std::move(name),make_cylinder({radius,height,24}),m,p,{1,1,1},r};if(part.mesh.valid())a.parts.push_back(std::move(part));}
void add_collision(VehicleDefinition&v,Vec3 size,Vec3 p,bool wheel=false){if(size.x<=0||size.y<=0||size.z<=0)return;const auto i=static_cast<std::uint64_t>(v.collision.size()+1U);v.collision.push_back({i,{p.x-size.x*.5f,p.y-size.y*.5f,p.z-size.z*.5f},{p.x+size.x*.5f,p.y+size.y*.5f,p.z+size.z*.5f},wheel});}

VehicleConfig normalize(VehicleConfig c){
    if(!finite(c.length)||c.length<=0)c.length=4.6f;if(!finite(c.width)||c.width<=0)c.width=1.84f;if(!finite(c.height)||c.height<=0)c.height=1.55f;
    c.length=std::max(c.length,.8f);c.width=std::max(c.width,.35f);c.height=std::max(c.height,.45f);
    c.ground_clearance=finite(c.ground_clearance)?std::clamp(c.ground_clearance,0.0f,c.height*.65f):0.1f;
    c.chassis_height=finite(c.chassis_height)?std::clamp(c.chassis_height,.02f,std::max(.02f,c.height-c.ground_clearance)):.18f;
    c.wheel_radius=finite(c.wheel_radius)?std::clamp(c.wheel_radius,.03f,std::min(c.height*.48f,c.length*.20f)):.3f;
    c.wheel_width=finite(c.wheel_width)?std::clamp(c.wheel_width,.02f,c.width*.3f):.2f;
    c.wheelbase=finite(c.wheelbase)?c.wheelbase:c.length*.58f;c.track_width=finite(c.track_width)?c.track_width:c.width*.82f;
    c.axles=std::clamp(c.axles,1U,8U);c.wheels_per_axle=std::clamp(c.wheels_per_axle,1U,4U);
    c.wheelbase=std::clamp(c.wheelbase,.1f,std::max(.1f,c.length-2*c.wheel_radius));c.track_width=std::clamp(c.track_width,.05f,std::max(.05f,c.width-c.wheel_width));
    c.cabin_length=finite(c.cabin_length)?std::clamp(c.cabin_length,.1f,c.length):c.length*.45f;c.cabin_width=finite(c.cabin_width)?std::clamp(c.cabin_width,.1f,c.width):c.width*.88f;c.cabin_height=finite(c.cabin_height)?std::clamp(c.cabin_height,.1f,c.height):c.height*.48f;
    c.front_overhang=finite(c.front_overhang)?std::max(0.0f,c.front_overhang):0.6f;c.rear_overhang=finite(c.rear_overhang)?std::max(0.0f,c.rear_overhang):0.7f;c.hood_length=finite(c.hood_length)?std::clamp(c.hood_length,0.0f,c.length):0.7f;
    c.doors=std::min(c.doors,8U);c.seats=std::min(c.seats,64U);c.wing_span=finite(c.wing_span)?std::clamp(c.wing_span,0.0f,c.width):0.0f;c.waterline=finite(c.waterline)?std::clamp(c.waterline,-c.height,c.height):0.0f;return c;}

void add_wheels(VehicleDefinition&v,float front_z,float rear_z,bool steering_front){const auto&c=v.config;for(std::uint32_t axle=0;axle<c.axles;++axle){const float t=c.axles==1?.5f:static_cast<float>(axle)/static_cast<float>(c.axles-1U);const float z=front_z+(rear_z-front_z)*t;for(std::uint32_t wi=0;wi<c.wheels_per_axle;++wi){float x=0.0f;if(c.wheels_per_axle==2||c.wheels_per_axle==4)x=(wi%2U==0?-1.0f:1.0f)*(c.wheels_per_axle==4?(wi<2?0.5f:1.0f):0.5f)*c.track_width;else if(c.wheels_per_axle>1)x=(static_cast<float>(wi)-static_cast<float>(c.wheels_per_axle-1U)*.5f)*c.track_width*.65f;const bool steering=steering_front&&axle==0;const bool driven=(axle==c.axles-1U)||(c.type==VehicleType::SportsCar&&axle==0);const auto wid=stable_id(v.seed,0x5000ULL,(static_cast<std::uint64_t>(axle)<<16U)|wi);v.wheels.push_back({wid,axle,wi,steering?VehicleWheelRole::Steering:(driven?VehicleWheelRole::Driven:VehicleWheelRole::FreeRolling),{x,c.wheel_radius,z},c.wheel_radius,c.wheel_width,c.wheel_radius*.25f,c.wheel_radius*.35f,driven,steering});add_cylinder(v.geometry,"wheel_"+std::to_string(axle)+"_"+std::to_string(wi),c.wheel_radius,c.wheel_width,c.rubber_material,{x,c.wheel_radius,z},{0,kPi*.5f,0});add_collision(v,{std::max(c.wheel_width,.01f),c.wheel_radius*2,c.wheel_radius*2},{x,c.wheel_radius,z},true);v.physics_attachments.push_back({stable_id(v.seed,0x6000ULL,(static_cast<std::uint64_t>(axle)<<16U)|wi),"wheel_mount_"+std::to_string(axle)+"_"+std::to_string(wi),{x,c.ground_clearance+c.wheel_radius,z},{0,1,0}});}}}

void add_land_vehicle(VehicleDefinition&v){auto&c=v.config;const float half_l=c.length*.5f,half_w=c.width*.5f,bottom=c.ground_clearance;const float body_bottom=bottom+c.chassis_height;const float cabin_h=std::clamp(c.cabin_height,.1f,std::max(.1f,c.height-body_bottom-.05f));const float body_h=std::max(.08f,c.height-body_bottom-cabin_h);const float body_len=std::max(.2f,c.length-c.front_overhang-c.rear_overhang);const float body_z=(c.rear_overhang-c.front_overhang)*.5f;
    add_box(v.geometry,"chassis",{c.width*.86f,c.chassis_height,c.length},c.metal_material,{0,bottom+c.chassis_height*.5f,0});add_collision(v,{c.width*.86f,c.chassis_height,c.length},{0,bottom+c.chassis_height*.5f,0});
    const bool utility=c.type==VehicleType::Pickup||c.type==VehicleType::Truck||c.type==VehicleType::Construction;const float lower_len=utility?body_len*.78f:body_len;add_box(v.geometry,"body_lower",{c.width*.94f,body_h,lower_len},c.body_material,{0,body_bottom+body_h*.5f,body_z});add_collision(v,{c.width*.94f,body_h,lower_len},{0,body_bottom+body_h*.5f,body_z});
    float cabin_len=std::min(c.cabin_length,body_len);float cabin_z=body_z;if(utility){cabin_len=std::min(cabin_len,body_len*.55f);cabin_z=-half_l+c.front_overhang+cabin_len*.5f;const float bed_len=std::max(.15f,body_len-cabin_len);const float bed_z=cabin_z+cabin_len*.5f+bed_len*.5f;add_box(v.geometry,"cargo_bed",{c.width*.88f,body_h*.65f,bed_len},c.body_material,{0,body_bottom+body_h*.70f,bed_z});add_collision(v,{c.width*.88f,body_h*.65f,bed_len},{0,body_bottom+body_h*.70f,bed_z});}
    const Vec3 cabin_size{c.cabin_width,cabin_h,cabin_len};add_box(v.geometry,"cabin",cabin_size,c.glass_material,{0,body_bottom+body_h+cabin_h*.5f,cabin_z});add_collision(v,cabin_size,{0,body_bottom+body_h+cabin_h*.5f,cabin_z});add_box(v.geometry,"interior",{std::max(.1f,c.cabin_width-.10f),std::max(.1f,cabin_h*.70f),std::max(.1f,cabin_len-.10f)},c.interior_material,{0,body_bottom+body_h+cabin_h*.36f,cabin_z});
    const float door_z_front=cabin_z-cabin_len*.28f,door_z_rear=cabin_z+cabin_len*.28f;for(std::uint32_t i=0;i<c.doors;++i){const bool rear_pair=i>=2;const float side=(i%2U==0)?-1.0f:1.0f;const float z=rear_pair?door_z_rear:door_z_front;const Vec3 size{std::min(.06f,c.width*.03f),cabin_h*.76f,std::max(.25f,cabin_len*.28f)};const auto id=stable_id(v.seed,0x1000ULL,i);v.doors.push_back({id,side<0?VehicleDoorSide::Left:VehicleDoorSide::Right,{side*(c.cabin_width*.5f+.006f),body_bottom+body_h+cabin_h*.47f,z},size,false});add_box(v.geometry,"door_"+std::to_string(i),size,c.body_material,v.doors.back().position);}
    const std::uint32_t row_capacity=std::max(1U,static_cast<std::uint32_t>(std::floor(cabin_len/.58f)));const std::uint32_t capacity=row_capacity*(c.cabin_width>=1.2f?2U:1U);const std::uint32_t seat_count=std::min(c.seats,capacity);for(std::uint32_t i=0;i<seat_count;++i){const std::uint32_t row=i/(c.cabin_width>=1.2f?2U:1U),side=(c.cabin_width>=1.2f)?i%2U:0U;const float x=side?c.cabin_width*.25f:-c.cabin_width*.25f;const float z=cabin_z-cabin_len*.32f+std::min(cabin_len*.64f-.25f,static_cast<float>(row)*.58f)+(unit(stable_id(v.seed,0x2200ULL,i))-.5f)*.02f;const auto id=stable_id(v.seed,0x2000ULL,i);v.seats.push_back({id,{x,body_bottom+body_h+.18f,z},c.cabin_width*.26f,i==0});add_box(v.geometry,"seat_"+std::to_string(i),{std::min(.48f,c.cabin_width*.28f),std::min(.32f,cabin_h*.32f),std::min(.54f,cabin_len*.20f)},c.interior_material,v.seats.back().position);}
    const float front_axle=std::min(c.wheelbase*.5f,half_l-c.wheel_radius),rear_axle=-front_axle;add_wheels(v,front_axle,rear_axle,true);
    const float front=-half_l+c.front_overhang*.5f,rear=half_l-c.rear_overhang*.5f;v.lights.push_back({stable_id(v.seed,0x3000ULL,0),{-c.width*.30f,body_bottom+body_h+cabin_h*.25f,front},{0,0,-1},1,false,false});v.lights.push_back({stable_id(v.seed,0x3000ULL,1),{c.width*.30f,body_bottom+body_h+cabin_h*.25f,front},{0,0,-1},1,false,false});v.lights.push_back({stable_id(v.seed,0x3000ULL,2),{-c.width*.30f,body_bottom+body_h*.42f,rear},{0,0,1},1,true,false});v.lights.push_back({stable_id(v.seed,0x3000ULL,3),{c.width*.30f,body_bottom+body_h*.42f,rear},{0,0,1},1,true,false});
    for(const auto&l:v.lights)add_box(v.geometry,"light_"+std::to_string(l.id),{.07f,.07f,.07f},c.metal_material,l.position);v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,0),"center_of_mass",{0,bottom+c.height*.46f,0},{0,1,0}});v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,1),"front_axle",{0,c.wheel_radius,front_axle},{0,1,0}});v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,2),"rear_axle",{0,c.wheel_radius,rear_axle},{0,1,0}});
}

void add_motorcycle(VehicleDefinition&v){auto&c=v.config;add_box(v.geometry,"frame",{c.width*.22f,c.chassis_height,c.length*.74f},c.metal_material,{0,c.ground_clearance+c.chassis_height*.5f,0});add_box(v.geometry,"tank",{c.width*.52f,c.height*.24f,c.length*.22f},c.body_material,{0,c.ground_clearance+c.chassis_height+c.height*.28f,-c.length*.08f});add_box(v.geometry,"seat",{c.width*.46f,c.height*.12f,c.length*.25f},c.interior_material,{0,c.ground_clearance+c.height*.48f,c.length*.17f});add_wheels(v,c.length*.36f,-c.length*.36f,true);add_box(v.geometry,"handlebar",{c.width*.70f,.05f,.08f},c.metal_material,{0,c.ground_clearance+c.height*.73f,-c.length*.36f});v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,0),"center_of_mass",{0,c.ground_clearance+c.height*.38f,0},{0,1,0}});}

void add_boat(VehicleDefinition&v){auto&c=v.config;const float hull_h=std::max(.08f,c.height*.42f);add_box(v.geometry,"hull",{c.width*.94f,hull_h,c.length*.94f},c.body_material,{0,c.waterline-hull_h*.25f,0});add_box(v.geometry,"deck",{c.width*.84f,std::max(.06f,c.height*.10f),c.length*.76f},c.metal_material,{0,c.waterline+c.height*.12f,0});const float cabin_len=std::min(c.cabin_length,c.length*.55f);const float cabin_w=std::min(c.cabin_width,c.width*.82f);add_box(v.geometry,"cabin",{cabin_w,c.cabin_height,cabin_len},c.glass_material,{0,c.waterline+c.height*.18f+c.cabin_height*.5f,c.length*.12f});add_collision(v,{c.width*.94f,hull_h,c.length*.94f},{0,c.waterline-hull_h*.25f,0});v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,0),"buoyancy_center",{0,c.waterline-hull_h*.20f,0},{0,1,0}});v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,1),"center_of_mass",{0,c.waterline+c.height*.05f,0},{0,1,0}});}

void add_aircraft(VehicleDefinition&v){auto&c=v.config;const float span=c.wing_span>0?c.wing_span:std::min(c.width*.95f,c.length*.9f);const float center_y=c.ground_clearance+c.height*.48f;add_box(v.geometry,"fuselage",{std::min(c.width*.40f,c.width),std::max(.08f,c.height*.34f),c.length*.92f},c.body_material,{0,center_y,0});add_box(v.geometry,"wing",{std::min(span,c.width),std::max(.04f,c.height*.06f),std::max(.2f,c.length*.30f)},c.metal_material,{0,center_y,0});add_box(v.geometry,"tailplane",{std::min(span*.48f,c.width),std::max(.03f,c.height*.045f),std::max(.16f,c.length*.12f)},c.metal_material,{0,center_y+c.height*.10f,c.length*.36f});add_box(v.geometry,"cockpit",{std::min(c.width*.34f,c.width),std::max(.05f,c.height*.18f),std::min(c.length*.20f,c.length)},c.glass_material,{0,center_y+c.height*.13f,-c.length*.23f});add_collision(v,{std::min(c.width*.40f,c.width),std::max(.08f,c.height*.34f),c.length*.92f},{0,center_y,0});const float gear_z=-c.length*.24f;for(std::uint32_t i=0;i<3;++i){const float x=i==0?0.0f:(i==1?-std::min(span*.22f,c.width*.22f):std::min(span*.22f,c.width*.22f));add_cylinder(v.geometry,"landing_gear_"+std::to_string(i),c.wheel_radius,c.wheel_width,c.rubber_material,{x,c.wheel_radius,gear_z});}v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,0),"center_of_mass",{0,center_y,0},{0,1,0}});v.physics_attachments.push_back({stable_id(v.seed,0x7000ULL,1),"lift_axis",{0,center_y,0},{0,1,0}});}
}

VehicleConfig make_vehicle_config(VehicleType type){VehicleConfig c;c.type=type;switch(type){case VehicleType::SUV:c.length=4.9f;c.width=2.0f;c.height=1.82f;c.wheelbase=2.9f;c.track_width=1.68f;c.wheel_radius=.37f;c.cabin_length=2.35f;c.cabin_width=1.76f;c.cabin_height=.90f;c.seats=7;c.doors=4;break;case VehicleType::SportsCar:c.length=4.45f;c.width=1.92f;c.height=1.20f;c.ground_clearance=.12f;c.wheelbase=2.65f;c.track_width=1.66f;c.wheel_radius=.34f;c.cabin_length=1.85f;c.cabin_width=1.55f;c.cabin_height=.70f;c.seats=2;c.doors=2;break;case VehicleType::Pickup:c.length=5.35f;c.width=1.95f;c.height=1.85f;c.wheelbase=3.10f;c.track_width=1.62f;c.wheel_radius=.38f;c.cabin_length=2.0f;c.cabin_width=1.72f;c.cabin_height=.86f;c.seats=5;c.doors=4;break;case VehicleType::Truck:c.length=10.0f;c.width=2.5f;c.height=3.2f;c.axles=3;c.wheels_per_axle=2;c.wheelbase=6.5f;c.track_width=2.1f;c.wheel_radius=.55f;c.cabin_length=3.0f;c.cabin_width=2.1f;c.cabin_height=1.5f;c.seats=3;c.doors=2;break;case VehicleType::Bus:c.length=12.0f;c.width=2.5f;c.height=3.2f;c.axles=2;c.wheels_per_axle=2;c.wheelbase=7.0f;c.track_width=2.1f;c.wheel_radius=.52f;c.cabin_length=8.5f;c.cabin_width=2.05f;c.cabin_height=1.65f;c.seats=32;c.doors=3;break;case VehicleType::Motorcycle:c.length=2.2f;c.width=.82f;c.height=1.35f;c.ground_clearance=.14f;c.wheelbase=1.45f;c.track_width=.62f;c.wheel_radius=.30f;c.wheel_width=.12f;c.axles=2;c.wheels_per_axle=1;c.cabin_length=.8f;c.cabin_width=.5f;c.cabin_height=.35f;c.seats=2;c.doors=0;break;case VehicleType::Construction:c.length=7.0f;c.width=2.6f;c.height=3.1f;c.axles=3;c.wheels_per_axle=2;c.wheelbase=4.5f;c.track_width=2.2f;c.wheel_radius=.52f;c.cabin_length=2.3f;c.cabin_width=2.0f;c.cabin_height=1.2f;c.seats=2;c.doors=2;break;case VehicleType::Emergency:c.length=5.7f;c.width=2.0f;c.height=2.35f;c.wheelbase=3.25f;c.track_width=1.68f;c.wheel_radius=.39f;c.cabin_length=2.3f;c.cabin_width=1.75f;c.cabin_height=1.0f;c.seats=5;c.doors=5;break;case VehicleType::Boat:c.length=8.0f;c.width=2.6f;c.height=2.1f;c.cabin_length=2.5f;c.cabin_width=2.0f;c.cabin_height=.95f;c.seats=6;c.doors=1;c.waterline=.25f;break;case VehicleType::Aircraft:c.length=14.0f;c.width=3.2f;c.height=3.8f;c.wing_span=14.0f;c.cabin_length=3.0f;c.cabin_width=1.4f;c.cabin_height=1.1f;c.seats=8;c.doors=2;break;case VehicleType::Car:break;}return c;}

bool VehicleDefinition::valid() const noexcept{if(!geometry.valid()||config.length<=0||config.width<=0||config.height<=0||!finite(config.length)||!finite(config.width)||!finite(config.height))return false;for(const auto&w:wheels)if(!w.id||!finite(w.position)||w.radius<=0||w.width<=0)return false;for(const auto&d:doors)if(!d.id||!finite(d.position)||!finite(d.size)||d.size.x<=0||d.size.y<=0||d.size.z<=0)return false;for(const auto&s:seats)if(!s.id||!finite(s.position)||s.width<=0)return false;for(const auto&l:lights)if(!l.id||!finite(l.position)||!finite(l.direction)||l.intensity<0)return false;for(const auto&a:physics_attachments)if(!a.id||a.name.empty()||!finite(a.position)||!finite(a.axis))return false;for(const auto&c:collision)if(!c.id||!finite(c.min)||!finite(c.max)||c.min.x>c.max.x||c.min.y>c.max.y||c.min.z>c.max.z)return false;return true;}

VehicleDefinition generate_vehicle(const VehicleConfig& input){VehicleDefinition v;v.config=normalize(input);v.seed=v.config.seed;switch(v.config.type){case VehicleType::Motorcycle:add_motorcycle(v);break;case VehicleType::Boat:add_boat(v);break;case VehicleType::Aircraft:add_aircraft(v);break;default:add_land_vehicle(v);break;}return v;}
bool set_vehicle_door_open(VehicleDefinition&v,std::uint64_t id,bool open) noexcept{for(auto&d:v.doors)if(d.id==id){d.open=open;return true;}return false;}
const VehicleDoor* find_vehicle_door(const VehicleDefinition&v,std::uint64_t id) noexcept{for(const auto&d:v.doors)if(d.id==id)return &d;return nullptr;}
const VehicleWheel* find_vehicle_wheel(const VehicleDefinition&v,std::uint64_t id) noexcept{for(const auto&w:v.wheels)if(w.id==id)return &w;return nullptr;}
std::vector<VehicleCollisionVolume> active_vehicle_collision(const VehicleDefinition&v){return v.collision;}

} // namespace exgine
