#include "exgine/vehicle_dynamics.hpp"
#include <algorithm>
#include <cmath>
namespace exgine { namespace { float clamp(float v,float a,float b){return std::clamp(v,a,b);} float mag(Vec3 v){return std::sqrt(v.x*v.x+v.y*v.y+v.z*v.z);} }
VehicleDynamicsController::VehicleDynamicsController(PhysicsWorld&p,VehicleDynamicsConfig c,VehicleDynamicsState s):physics_(&p),config_(c),state_(s){if(config_.mass<=0)config_.mass=1500;if(config_.engine_force<0)config_.engine_force=0;if(config_.brake_force<0)config_.brake_force=0;if(config_.max_speed<=0)config_.max_speed=70;for(auto&w:config_.wheels){w.radius=std::max(.05f,w.radius);w.suspension_stiffness=std::max(0.f,w.suspension_stiffness);w.suspension_damping=std::max(0.f,w.suspension_damping);w.longitudinal_grip=std::max(0.f,w.longitudinal_grip);w.lateral_grip=std::max(0.f,w.lateral_grip);}}
bool VehicleDynamicsController::bind_body(PhysicsBodyId b)noexcept{if(!physics_||!physics_->has_body(b))return false;state_.body=b;return true;}bool VehicleDynamicsController::set_input(VehicleInput i)noexcept{if(!std::isfinite(i.throttle)||!std::isfinite(i.brake)||!std::isfinite(i.steering))return false;state_.input.throttle=clamp(i.throttle,-1,1);state_.input.brake=clamp(i.brake,0,1);state_.input.steering=clamp(i.steering,-1,1);state_.input.handbrake=i.handbrake;return true;}bool VehicleDynamicsController::possess(bool v)noexcept{state_.possessed=v;return true;}
bool VehicleDynamicsController::update(float dt)noexcept{if(!physics_||state_.body==invalid_physics_body||dt<=0||!physics_->has_body(state_.body))return false;auto t=physics_->body_transform(state_.body);if(!t)return false;const float yaw=t->rotation.y;const Vec3 forward{std::sin(yaw),0,std::cos(yaw)};const Vec3 right{std::cos(yaw),0,-std::sin(yaw)};const auto speed_vec=forward*0.0f; (void)speed_vec; const float throttle=state_.input.throttle, brake=state_.input.brake; const float requested=throttle*config_.engine_force; const float stopping=-brake*config_.brake_force; for(std::size_t i=0;i<config_.wheels.size();++i){const auto&w=config_.wheels[i];const Vec3 wp{t->position.x+w.local_position.x,t->position.y+w.local_position.y,t->position.z+w.local_position.z};if(w.driven&&std::fabs(throttle)>0.001f){physics_->apply_force(state_.body,forward*requested/2.f,wp);}if(std::fabs(stopping)>0.001f){physics_->apply_force(state_.body,forward*stopping/4.f,wp);} if(w.steerable&&std::fabs(state_.input.steering)>0.001f)physics_->apply_torque(state_.body,{0,state_.input.steering*requested*.02f,0});}
const float drag=config_.aerodynamic_drag*dt;physics_->apply_force(state_.body,forward*(-drag*config_.mass),t->position);state_.speed=std::min(config_.max_speed,state_.speed+throttle*8.f*dt-brake*12.f*dt);state_.speed=std::max(0.f,state_.speed);for(std::size_t i=0;i<4;++i){state_.wheel_angular_speed[i]=state_.speed/std::max(.05f,config_.wheels[i].radius);state_.wheel_slip[i]=clamp(std::fabs(throttle)*.05f,0.f,1.f);}return true;}
} // namespace exgine
