#include "exgine/world_high_fidelity.hpp"
#include <algorithm>
#include <cmath>
#include <limits>

namespace exgine {
namespace {
std::uint64_t hash64(std::uint64_t x) noexcept { x^=x>>30; x*=0xbf58476d1ce4e5b9ULL; x^=x>>27; x*=0x94d049bb133111ebULL; return x^(x>>31); }
float unit(std::uint64_t x) noexcept { return static_cast<float>((hash64(x)>>40)&0xFFFFFFu)/16777215.0f; }
float smooth(float x) noexcept { return x*x*(3.0f-2.0f*x); }
float noise2(float x,float z,std::uint64_t seed) noexcept {
    const int xi=static_cast<int>(std::floor(x)); const int zi=static_cast<int>(std::floor(z)); const float fx=x-xi,fz=z-zi;
    auto n=[&](int a,int b){return unit(seed+static_cast<std::uint64_t>(a)*0x9e3779b97f4a7c15ULL+static_cast<std::uint64_t>(b)*0xc2b2ae3d27d4eb4fULL)*2.0f-1.0f;};
    const float u=smooth(fx),v=smooth(fz),n00=n(xi,zi),n10=n(xi+1,zi),n01=n(xi,zi+1),n11=n(xi+1,zi+1); const float nx0=n00+(n10-n00)*u,nx1=n01+(n11-n01)*u; return nx0+(nx1-nx0)*v;
}
float erode(float base,float slope,float moisture,std::uint64_t seed,const WorldTerrainDetailConfig& c) noexcept { const float erosion=std::clamp(std::abs(slope)*c.erosion_strength+moisture*c.thermal_strength,0.0f,1.0f); return base+(unit(seed)*2.0f-1.0f)*erosion*8.0f-std::max(0.0f,slope)*erosion*3.0f; }
float dist_sq(Vec3 a,Vec3 b) noexcept { const float x=a.x-b.x,z=a.z-b.z; return x*x+z*z; }
}

HighFidelityWorld::HighFidelityWorld(WorldBuildConfig config):config_(config){ config_.chunk_size=std::max(1.0f,config_.chunk_size);config_.samples_per_axis=std::max<std::uint32_t>(3,config_.samples_per_axis);config_.vegetation_instances=std::max<std::uint32_t>(1,config_.vegetation_instances);config_.terrain.chunk_resolution=std::max<std::uint32_t>(3,config_.terrain.chunk_resolution); }
WorldChunkCoord HighFidelityWorld::chunk_for(Vec3 p) const noexcept { return {static_cast<std::int32_t>(std::floor(p.x/config_.chunk_size)),static_cast<std::int32_t>(std::floor(p.z/config_.chunk_size))}; }
std::uint64_t HighFidelityWorld::region_seed(WorldChunkCoord c) const noexcept { std::uint64_t x=config_.seed^0x6a09e667f3bcc909ULL; x^=static_cast<std::uint64_t>(static_cast<std::int64_t>(c.x))*0x9e3779b97f4a7c15ULL; x^=static_cast<std::uint64_t>(static_cast<std::int64_t>(c.z))*0xc2b2ae3d27d4eb4fULL; return hash64(x)|1ULL; }
float HighFidelityWorld::terrain_height(float x,float z) const noexcept { const float s=std::max(.001f,config_.terrain.world_scale); float h=0,amp=1,freq=.0035f; for(int o=0;o<5;++o){h+=noise2(x*freq/s,z*freq/s,config_.seed+static_cast<std::uint64_t>(o)*1013ULL)*amp;amp*=.5f;freq*=1.95f;} const float slope_noise=noise2(x*.01f,z*.01f,config_.seed+77)*.5f; return erode(h*80.0f,slope_noise,.5f,hash64(static_cast<std::uint64_t>(std::llround(x*8))+static_cast<std::uint64_t>(std::llround(z*17))),config_.terrain); }
BiomeSample HighFidelityWorld::sample_biome(float x,float z,float height) const noexcept { BiomeSample s; s.moisture=std::clamp(.5f+.5f*noise2(x*.0025f,z*.0025f,config_.seed+303),0.0f,1.0f); s.temperature=std::clamp(.6f-.004f*height+.25f*noise2(x*.0015f,z*.0015f,config_.seed+701),0.0f,1.0f); const float sx=terrain_height(x+2,z)-terrain_height(x-2,z),sz=terrain_height(x,z+2)-terrain_height(x,z-2); s.slope=std::clamp(std::sqrt(sx*sx+sz*sz)/8.0f,0.0f,1.0f); if(height>config_.terrain.snow_line)s.biome=Biome::Snow;else if(height>config_.terrain.rock_line||s.slope>.7f)s.biome=Biome::Rocky;else if(height<config_.water_level+2.0f&&s.moisture>.68f)s.biome=Biome::Wetland;else if(s.temperature<.28f)s.biome=Biome::Snow;else if(s.moisture>.65f)s.biome=Biome::Forest;else if(s.moisture<.25f&&s.temperature>.6f)s.biome=Biome::Desert;else if(height<config_.water_level+8.0f)s.biome=Biome::Beach;else s.biome=Biome::Plains; return s; }
bool HighFidelityWorld::has_water(float x,float z,float& depth) const noexcept { const float h=terrain_height(x,z),basin=noise2(x*.0018f,z*.0018f,config_.seed+5150)*10.0f; depth=std::max(0.0f,config_.water_level-h+basin-6.0f); return depth>0; }
WorldQueryResult HighFidelityWorld::query(Vec3 p) const noexcept { WorldQueryResult r;r.valid=true;r.height=terrain_height(p.x,p.z);r.biome=sample_biome(p.x,p.z,r.height);r.water=has_water(p.x,p.z,r.water_depth);return r; }
WorldRegion HighFidelityWorld::build_region(WorldChunkCoord c) const { WorldRegion r;r.coord=c;r.size=config_.chunk_size;r.origin={c.x*r.size,0,c.z*r.size};r.seed=region_seed(c);r.terrain_min=std::numeric_limits<float>::max();r.terrain_max=std::numeric_limits<float>::lowest();const auto n=config_.samples_per_axis;for(std::uint32_t z=0;z<n;++z)for(std::uint32_t x=0;x<n;++x){const float px=r.origin.x+r.size*(static_cast<float>(x)/(n-1)),pz=r.origin.z+r.size*(static_cast<float>(z)/(n-1));const auto q=query({px,0,pz});r.terrain_min=std::min(r.terrain_min,q.height);r.terrain_max=std::max(r.terrain_max,q.height);if(q.water)++r.water_count;}for(std::uint32_t i=0;i<config_.vegetation_instances;++i){const Vec3 p{r.origin.x+unit(r.seed+i*17ULL)*r.size,0,r.origin.z+unit(r.seed+i*29ULL)*r.size};const auto q=query(p);if(!q.water&&q.biome.biome!=Biome::Rocky&&q.biome.biome!=Biome::Snow&&q.biome.biome!=Biome::Desert)++r.vegetation_count;}r.structure_count=(r.terrain_max-r.terrain_min>250.0f)?std::min(config_.structure_budget,4u):config_.structure_budget;r.road_count=r.water_count>n?std::max(1u,config_.road_budget/2):config_.road_budget;r.interests.push_back({{r.origin.x+r.size*.5f,0,r.origin.z+r.size*.5f},r.size*.75f,1.0f});if(r.structure_count)r.interests.push_back({{r.origin.x+r.size*.62f,0,r.origin.z+r.size*.44f},r.size*.25f,1.5f});return r; }
std::vector<WorldChunkDetail> HighFidelityWorld::select_details(const std::vector<WorldInterestPoint>& interests,const std::vector<WorldChunkCoord>& candidates) const { std::vector<WorldChunkDetail> out;out.reserve(candidates.size());for(const auto& c:candidates){const Vec3 center{(c.x+.5f)*config_.chunk_size,0,(c.z+.5f)*config_.chunk_size};float best=std::numeric_limits<float>::max(),priority=1;for(const auto& i:interests){const float score=std::sqrt(dist_sq(center,i.position))/std::max(1.0f,i.priority);if(score<best){best=score;priority=i.priority;}}const float hero=128*priority,near=320*priority,mid=768*priority;WorldChunkDetail d;d.coord=c;d.detail=best<=hero?WorldDetailLevel::Hero:best<=near?WorldDetailLevel::Near:best<=mid?WorldDetailLevel::Mid:WorldDetailLevel::Far;d.terrain=true;d.water=d.detail>=WorldDetailLevel::Mid;d.vegetation=d.detail>=WorldDetailLevel::Mid;d.structures=d.detail>=WorldDetailLevel::Near;d.roads=d.detail>=WorldDetailLevel::Near;out.push_back(d);}std::stable_sort(out.begin(),out.end(),[](const WorldChunkDetail&a,const WorldChunkDetail&b){if(a.detail!=b.detail)return static_cast<int>(a.detail)>static_cast<int>(b.detail);if(a.coord.x!=b.coord.x)return a.coord.x<b.coord.x;return a.coord.z<b.coord.z;});return out; }
std::vector<WorldRegion> HighFidelityWorld::build_regions(const std::vector<WorldChunkCoord>& coords) const { std::vector<WorldRegion> out;out.reserve(coords.size());for(const auto& c:coords)out.push_back(build_region(c));return out; }
} // namespace exgine
